<font color='Maroon'><b>
My First ever EDA project. Thanks to many of wonderful Kagglers out here to serve me as inspiration. Referred to many notebooks and got an idea how to approach the problem. Its been years since i coded and i am new to Python. Please look into the code and provide me your comments.Thank you all
</font></b>

In [ ]:
#import different libraries required for analysis
import pandas as pd
import numpy as np
import seaborn as sns    
import matplotlib.pyplot as plt   
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.float_format', lambda x: '%.5f' % x)
sns.set(color_codes=True) 
%matplotlib inline

In [ ]:
#read the data
in_data = pd.read_csv('/kaggle/input/cardiogoodfitness/CardioGoodFitness.csv')

In [ ]:
#sample records to get the feel of data.Initial few records
in_data.head(7)

In [ ]:
#sample records from bottom
in_data.tail(7)

## Data Demographics

    
1.Structure of data


2.Shape of the data

3.Data types of various columns

4.Any null values in the data


In next few steps, lets try to get the demographics of the data

In [ ]:
#size of the data

pd.DataFrame(in_data.shape).rename(index={0: "Rows", 1: "Columns"},columns={0:"File Dimension"} )



<b>Observation:</b>

The data has 180 rows and 9 columns

In [ ]:
#datatypes of the columns
in_data.info()



<b>Observation:</b>

There are 6 numerical fields and 3 categorical columns

In [ ]:
#checking if there are any null values
in_data.columns.isnull().sum()



<b>Observation:</b>

None of the columns have null values.Data is populated for all records.

In [ ]:
#checking unique values in each column
in_data.nunique()

In [ ]:
#Statistics of all the numerical columns
in_data.describe().T


 
<b>Observation:</b>

1. Age range of customers using the product are 18-50 with mean being 28.8 and median being 26.
2. Customers who use the product have completed atleast 12 yrs of education. The max education of customers is 21 yrs.
3. All the users use the product atleast once per week. The Average usage of the product is 3 times per week. The max usage is all days per week.
4. Income range of customers are between 29K - 105K, average being about 53K
5. Customers plan to run atleast 21 miles/week and the maximum is 360 miles/week. Average is 103 miles per week.
6. The average fitness level of customers who use the product is 3.

# Univariate Analysis

We are clear on the Data demographics. All the data contains good data. We could now proceed with analysis of distribution of each column.

1.Customer Age

2.Education

3.Usage

4.Fitness

5.Income

6.Miles

7.Product

8.Gender

9.Marital Status

### PRODUCT

In [ ]:
##PRODUCT
#Using Piechart to display % of sales of each product
plt.figure(figsize=(10,5))

#Chart 1
plt.subplot(1, 2, 1)                   #setting up subplot - 1 row, 2 plots
pie_data=in_data.Product.value_counts()  #get the unique count of products
labl_text=in_data.Product.unique()  #get the unique product names
plt.title('Product Sales', fontweight='bold')         #Chart title
plt.pie(pie_data, labels=labl_text, autopct='%1.2f%%', shadow=True)  #plot chart

#Chart 2
plt.subplot(1, 2, 2)
sns.countplot(x=in_data.Product)
plt.title('Product Sales', fontweight='bold')         #Chart title
plt.tight_layout()


<b>Product</b>

<b>Observation:</b><br>

1.TM195 product is the King of market. It occupies 44.4% of total sales

2.The least popular product in market is TM798 which occupies 22.22% of sales

### AGE, MILES

In [ ]:
# Customer Age
plt.figure(figsize = (15,5))
plt.subplot(1, 2, 1)                          #setting up subplots
sns.histplot(x=in_data.Age, kde=False, color='c')   #Plot histogram
plt.axvline(in_data.Age.mean(), color='g', linewidth=2, label='Mean')      #draw mean
plt.axvline(in_data.Age.median(), color='b', linestyle='dashed', linewidth=2, label='Median')  #Median
plt.axvline(in_data.Age.mode()[0], color='y', linestyle='--', linewidth=2, label='Mode')     #Mode
plt.title('Age Distribution', fontweight='bold')         #Chart title
plt.legend()    #Display the legend on Plots

# Miles 
plt.subplot(1, 2, 2)
sns.histplot(x=in_data.Miles, kde=False, color='c')
plt.axvline(in_data.Miles.mean(), color='g', linewidth=2,label='Mean')
plt.axvline(in_data.Miles.median(), color='b', linestyle='dashed', linewidth=2, label='Median')
plt.axvline(in_data.Miles.mode()[0], color='y', linestyle='--', linewidth=2, label='Mode')
plt.title('Miles Distribution', fontweight='bold')         #Chart title
plt.legend()

plt.rcParams["axes.labelsize"] = 15
plt.tight_layout()
plt.show()


<b>Customer Age</b>
  
<b>Observation:</b><br>
1.Most of the customers who use any of the products are of younger age, typically between 25-28 years age.<br>
2.Customers with age less than 18 and older than 50 didn't buy any of the products. 

<b>Miles</b>

<b>Observation:</b><br>
1.Customers are expected to run average of 103 miles per week.<br>
2.Few outliers in data. Few of customers plan to run above 200 miles per week <br>

### EDUCATION, USAGE, FITNESS

In [ ]:
# Education,Usage,Fitness

plt.figure(figsize = (15,5))
plt.subplot(1, 3, 1)
sns.countplot(x=in_data.Education, color='c')    #Countplot 
plt.title('Education Distribution', fontweight='bold')         #Chart title

plt.subplot(1, 3, 2)
sns.countplot(x=in_data.Usage, color='c')
plt.title('Usage Distribution', fontweight='bold')         #Chart title

plt.subplot(1, 3, 3)
sns.countplot(x=in_data.Fitness, color='c')
plt.title('Fitness Distribution', fontweight='bold')         #Chart title

plt.tight_layout()
plt.rcParams["axes.labelsize"] = 15

plt.show()




<b>Education</b>


<b>Observation:</b><br>
Average eduction of customers using product is about 16 years of education  


<b>Usage</b>


<b>Observation:</b><br>
Average usage of threadmil by customers is 3 days per week


<b>Fitness</b>

<b>Observation:</b><br>
Self assessed customer fitness level is 3

### INCOME

In [ ]:
#Income
#histogram
plt.figure(figsize = (12,5))
plt.subplot(1, 2, 1)
sns.histplot(in_data.Income, color='c')
plt.title('Income Distribution - Histogram', fontweight='bold')         #Chart title
plt.axvline(in_data.Income.mean(), color='g', linewidth=2,label='Mean')
plt.axvline(in_data.Income.median(), color='b', linestyle='dashed', linewidth=2, label='Median')
plt.axvline(in_data.Income.mode()[0], color='y', linestyle='--', linewidth=2, label='Mode')
plt.legend()
#boxplot
plt.subplot(1, 2, 2)
sns.boxplot(x=in_data.Income, 
            color='c',
            showmeans=True,
            meanprops={"marker":"D",
                       "markerfacecolor":"blue", 
                       "markeredgecolor":"black",
                       "markersize":"7"
                      }
           )
plt.title('Income Distribution - Boxplot', fontweight='bold')         #Chart title
plt.rcParams["axes.labelsize"] = 15

plt.tight_layout()



<b>Income</b>

<b>Observation:</b><br>
1.Salary range of customers range from 30K through 105K.<br>
2.Average income of customers using product is 53K.<br>
3.Most of the customers using the product have salary less than 70K.<br>

### GENDER, MARITAL STATUS

In [ ]:
##Gender & Marital Status
#Using Piechart to display % 
plt.figure(figsize=(10,6))
#Chart 1
plt.subplot(1, 2, 1)
pie_data_g  = in_data.Gender.value_counts()  #get the unique count of Gender
labl_text_g = in_data.Gender.unique()  #get the unique Gender values in Dataframe
plt.title("Product Usage by Gender",fontweight="bold")
plt.pie(pie_data_g, labels=labl_text_g, autopct='%1.2f%%', shadow=True)   #Piechart

#Chart 2
plt.subplot(1, 2, 2)
pie_data_m  =in_data.MaritalStatus.value_counts()  #get the unique count of Marital Status
labl_text_m =in_data.MaritalStatus.unique()  #get the unique values of Marital Status
plt.title("Product Usage by Martial Status",fontweight="bold")
plt.pie(pie_data_m, labels=labl_text_m, autopct='%1.2f%%', shadow=True, colors=['lightblue','plum'])
plt.tight_layout()

<b>Gender</b>



<b>Observation:</b><br>
More male customers than female


<b>Marital Status</b>


<b>Observation:</b><br>
More Single customers than Partnered

## Relation between numerical variables

In [ ]:
#Pairplot to understand relation between numerica values
sns.pairplot(in_data, hue='Product')
plt.show()

In [ ]:
#Plotting heatmap to understand correlation between attributes
plt.figure(figsize = (12,6))
sns.heatmap(in_data.corr(), annot=True, cmap='OrRd', vmin=0, vmax=1)
plt.title('Heatmap', fontweight='bold')         #Chart title

#Correlation matrix
in_data.corr()

<b> Observation: </b>

Looking at above pairplot and heatmap, high correlation exists between:
    
1.Miles - Fitness<br>
2.Miles - Usage<br>
3.Income - Education<br>
4.Usage - Fitness

# Bivariate Analysis

## PRODUCT
## VS
## AGE, EDUCATION, USAGE, FITNESS, INCOME, MILES

In [ ]:
#Min, Max, Mean(Average) of all the numerical variables by Product

kj=pd.pivot_table(in_data, 
               values=['Age','Education','Usage','Fitness','Income','Miles'], 
               index=['Product'],
               aggfunc={
                        'Age': [min, max, np.mean, np.median],
                        'Education': [min, max, np.mean, np.median],
                        'Usage': [min, max, np.mean, np.median],
                        'Fitness': [min, max, np.mean, np.median],
                        'Income': [min, max, np.mean, np.median],
                        'Miles': [min, max, np.mean, np.median]
                       }
               )
kj.T

In [ ]:
########################################################################
#PLOTTING [PRODUCT] V/S [AGE, EDUCATION, USAGE, FITNESS, INCOME, MILES]
########################################################################

figure, axes = plt.subplots(3, 2, figsize=(20,25))    #3 rows and 2 subplots in each
figure.suptitle('Product and relation with other numerical variables',fontsize=16,fontweight='bold') #title of the chart
k=[(0,0),(0,1),(1,0),(1,1),(2,0),(2,1)]  #Setting up indices to access axes
cols=['Age','Education','Usage','Fitness','Income','Miles']   #different fields to plot against Product
for i in (enumerate(cols)):        #assigns count to each of value in cols 
    sns.boxplot(
                x='Product', 
                y=i[1], 
                data=in_data, 
                ax=axes[k[i[0]][0]][k[i[0]][1]], 
                palette='Blues_r',
                showmeans=True,
                meanprops={"marker":"D",
                           "markerfacecolor":"blue", 
                           "markeredgecolor":"black",
                           "markersize":"7"
                          }
               ).set(title='Product by ' + i[1])  #Boxplot to see the distribution
    
plt.rcParams["axes.labelsize"] = 15
plt.show()

In [ ]:
#Product by fitness plot above shows that for Product TM195 and TM498, the 25, 50 & 75 quartiles are same
#lets check that out.

print('Product: TM195')
display(pd.crosstab(in_data['Product'],in_data['Fitness']).query("Product=='TM195'").quantile([0.25, 0.5, 0.75]))
print('\nProduct: TM498')
display(pd.crosstab(in_data['Product'],in_data['Fitness']).query("Product=='TM498'").quantile([0.25, 0.5, 0.75]))

<b> Observation: </b>

1.TM195 is the most popular, economical product where as TM798 is premium product, caters to high income, super fit customers (may elite group of fitness/sports enthusiasts/athletes) <br>
2.Age range of customers is 15-50 yrs <br>
3.TM195 and TM498 is used on an average of 3 times per week where as TM798 is being used for about 5 times per week <br>
4.Users plan to run between 20-360 miles per week which is unrealistic <br> 
5.Average salary of customers using TM195 and TM498 is 45k-50k where as TM798 customers’ salary average to 75k <br>
6.All the customers have atleast basic education (12 yrs and above) <br>

In [ ]:
#Lets get more details on Products and Fitness of people using the product

plt.figure(figsize = (10,6))
sns.countplot(x=in_data['Fitness'],hue=in_data['Product'])
plt.title('Fitness of customers using the product',fontweight='bold')
plt.rcParams["axes.labelsize"] = 15

plt.show()

<b>Observation:</b>

1.Majority of People who use TM798 are super fit.<br>
2.Majority of people who use TM498 and TM798 are average fit.<br>
3.None of the people who use TM798 are poor fit.<br>
4.None of people who use TM498 are super fit.<br>

## GENDER
## VS
## AGE, EDUCATION, USAGE, FITNESS, INCOME, MILES

In [ ]:
#Min, Max, Mean of all the numerical variables by Gender

jk=pd.pivot_table(in_data, 
               values=['Age','Education','Usage','Fitness','Income','Miles'], 
               index=['Gender'],
               aggfunc={
                        'Age': [min, max, np.mean, np.median],
                        'Education': [min, max, np.mean, np.median],
                        'Usage': [min, max, np.mean, np.median],
                        'Fitness': [min, max, np.mean, np.median],
                        'Income': [min, max, np.mean, np.median],
                        'Miles': [min, max, np.mean, np.median]
                       }
               )

jk.T

In [ ]:
########################################################################
#PLOTTING [GENDER] V/S [AGE, EDUCATION, USAGE, FITNESS, INCOME, MILES]
########################################################################


figure, axes = plt.subplots(3, 2, figsize=(20,25))    #3 rows and 2 subplots in each
figure.suptitle('Gender and relation with other numerical variables',fontsize=16,fontweight='bold') #title of the chart
k=[(0,0),(0,1),(1,0),(1,1),(2,0),(2,1)]  #Setting up indices to access axes
cols=['Age','Education','Usage','Fitness','Income','Miles']   #different fields to plot against Product
for i in (enumerate(cols)):        #assigns count to each of value in cols 
    sns.boxplot(
                x='Gender', 
                y=i[1], 
                data=in_data, 
                ax=axes[k[i[0]][0]][k[i[0]][1]], 
                palette='PiYG_r',
                showmeans=True,
                meanprops={"marker":"D",
                           "markerfacecolor":"blue", 
                           "markeredgecolor":"black",
                           "markersize":"7"
                          }
               ).set(title='Gender with ' + i[1])   #boxplot    

plt.rcParams["axes.labelsize"] = 15
plt.show()

In [ ]:
#Gender by fitness plot above shows that 25, 50 & 75 quartiles are same for Female
#lets check that out.

print('Gender: Female')
display(pd.crosstab(in_data['Gender'],in_data['Fitness']).query("Gender=='Female'").quantile([0.25, 0.5, 0.75]))

<b> Observation: </b>
   

1.	Age of customers range from 18-50 yrs.<br> 
2.	Male customers are 57.8% and Female customers are 42.2%.<br>
3.	Average use of product : Male – 4 times/week, Female – 3 times/week<br>
4.	Males are slightly more fit than the female customers.<br>
5.	Males plan to run an average of 113 miles/week where as Females 90 miles/week.<br>
6.	Males earn slightly more salary than female.<br>
7.	Average number of years of education for both Male and Female customers is about 15 yrs.<br>

## MARITAL STATUS
## VS
## AGE, EDUCATION, USAGE, FITNESS, INCOME, MILES

In [ ]:
#Min, Max, Mean of all the numerical variables by Marital Status

mn=pd.pivot_table(in_data, 
               values=['Age','Education','Usage','Fitness','Income','Miles'], 
               index=['MaritalStatus'],
               aggfunc={
                        'Age': [min, max, np.mean, np.median],
                        'Education': [min, max, np.mean, np.median],
                        'Usage': [min, max, np.mean, np.median],
                        'Fitness': [min, max, np.mean, np.median],
                        'Income': [min, max, np.mean, np.median],
                        'Miles': [min, max, np.mean, np.median]
                       }
               )
mn.T

In [ ]:
##############################################################################
#PLOTTING [MARITAL STATUS] V/S [AGE, EDUCATION, USAGE, FITNESS, INCOME, MILES]
##############################################################################


figure, axes = plt.subplots(3, 2, figsize=(20,25))    #3 rows and 2 subplots in each
figure.suptitle('Marital Status and relation with other numerical variables',fontsize=16,fontweight='bold') #title of the chart
k=[(0,0),(0,1),(1,0),(1,1),(2,0),(2,1)]  #Setting up indices to access axes
cols=['Age','Education','Usage','Fitness','Income','Miles']   #different fields to plot against Product
for i in (enumerate(cols)):        #assigns count to each of value in cols 
    sns.boxplot(
                x='MaritalStatus', 
                y=i[1], 
                data=in_data, 
                ax=axes[k[i[0]][0]][k[i[0]][1]], 
                palette='Set2',
                showmeans=True,
                meanprops={"marker":"D",
                           "markerfacecolor":"blue", 
                           "markeredgecolor":"black",
                           "markersize":"7"
                          }
               ).set(title='MaritalStatus with ' + i[1])  #Boxplot     

plt.rcParams["axes.labelsize"] = 15
plt.show()




<b> Observation: </b>
    
1.	More Single status customers than partnered customers.<br>
2.	Average usage per week is 3 times and fitness self assessed rating is 3 for  both single and partnered customers.<br>
3.	Both single and partnered customers have an average of 15 yrs. of education.<br>
4.	Single customers earn slightly less than Partnered customers.<br>
5.	Average miles planned by both customers are almost same.<br>

# Multivariate Analysis

#### Which Product is popular among different Genders?

In [ ]:
#Number of customers using different Products split by Gender & Marital Status 

in_tab=pd.crosstab([in_data.Product,in_data.Gender],in_data.MaritalStatus)
display(in_tab)
in_tab.plot(kind="bar",figsize=(8,5),rot=45)
plt.title('Product and Gender by Marital Status', fontweight='bold')         #Chart title
plt.rcParams["axes.labelsize"] = 15



plt.show()


<b>Observation:</b>

1.TM195 - This is popular among both Male & Female. Most selling product.<br>
2.TM498 - This is least popular among males but second most popular among Females after TM195 <br>
3.TM798 - This is least popular among Females but is second most popular in males after TM195<br>

#### What is the Average Miles, Usage, Fitness level of customers using different products?

In [ ]:
in_df=pd.pivot_table(in_data, 
               values=['Usage','Miles','Fitness'], 
               index=['Gender','Product'],
               aggfunc={
                        'Usage': [np.mean],
                        'Fitness': [np.mean],
                        'Miles': [np.mean]
                        
                       }
              )

display(in_df)


<b>Observation:</b>

1.Females who bought TM798 product, use it an average of 5 miles per week to run about 180 miles and are super fit.<br>
2.Females who bought TM195 and TM498 products are of average fitness level of 3 even though they run between 76-87 miles and about 3 times per week.<br>
3.Males using TM798 enjoy the best of all.They are super fit, use it approx 5 times per week to run an average of 164 miles.Females run a bit more on this treadmill compared to Men.<br>
4.Males using TM195 and TM498 mostly maintain average fitness level of 3, run about 88 miles per week, 3 times per week. <br>

In [ ]:
#Income by Age, Product, Fitness using scatterplot

plt.figure(figsize=(10,8))
sns.scatterplot(x='Age', 
                y='Income',
                size='Fitness',
                sizes=(20,500),
                hue='Product',
                data=in_data,
                alpha=0.5
               )

plt.legend(bbox_to_anchor=(1.01, 1),borderaxespad=0)
plt.xlabel('Age')
plt.ylabel('Income')
plt.title('Income by Age, Product, Fitness',fontweight='bold',fontsize=15)
plt.rcParams["axes.labelsize"] = 15
plt.tight_layout()
plt.show()


<b>Observation:</b>

1.Customers using TM798 has the highest income and plan to use to it max. Most of them are superfit.<br>
2.Customers using TM498 and TM195 roughly fall in the same category, earn about 25K-70K, use 3-4 times per week, enjoy average fitness of rating 3.<br>

In [ ]:
#Income by Age, Fitness and Usage for each Product using relplot

sns.relplot(x='Age', 
            y='Income', 
            hue='Fitness', 
            size='Usage',
            sizes=(50,600),
            data=in_data,
            palette='prism',
            alpha=0.5,
            col='Product'
           )
plt.rcParams['axes.labelsize'] = 15
plt.show()


<b>Observation:</b>

1.TM195 - Most of Customers use it about 3-5 times per week and earn less than 70K per Annum. The age range of customers is 18-50, average fitness rating of 3 <br>
2.TM498 - Most customers use it about 3-5 times per week and earn less than 70K per Annum. The age range of customers is 18-42. Very few customers are of age greater than 42. They are of average fitness rating of 3 <br>
3.TM798 - Age range of customers using the product is 20 - 50. They earn high salary upto 105K and make the best use of the product. Many of them use on all 7 days per week and are superfit.

### Self assessed Fitness of customers using the product

In [ ]:
plt.figure(figsize=(15,7))
sns.countplot(in_data["Product"],hue=in_data["Fitness"],palette="plasma")
plt.legend(bbox_to_anchor=(1.00, 1))
plt.show()

# ============================================================
# Summary:
# ============================================================

    
### Data Demographics:
1.	The data received contains 180 records and 9 columns.
2.	There are no nulls/blanks in the data.
3.	There are 6 numerical fields and 3 categorical columns.
4.	Many columns are skewed.
5.	The data in Miles column is unrealistic. Should get a confirmation from company to ensure there are no issues in data extraction process.


### Insights:
1.	There are more male customers than female customers.
2.	Typical customer age range is 18-50
3.	TM195 is most popular and widely used and TM798 is least sold.
4.	TM798 is bought by customers having high salary.
5.	Most of the customers are having less salary. (less than 70K)
6.	Most of the customers plan to use minimum of 3 times per week and they consider themselves to be average fit (rating of 3)
7.	Most of customers have education of 16 yrs.
    
### Customer Profile:

#### TM195:
    
1.Most economical and widely popular between Male and Female. The King of all the Products.<br>
2.Popular among Partnered Female than Partnered male.<br>
3.Single male purchase this product more than Single Female.<br>
4.Attracts customers between age 18-28.5.<br>
5.Most of customers have 16 yrs. Of education.<br>
6.Most customers who use the treadmill plan to run an average of 83 miles, for about 3 days per week. The average self-assessed fitness rating is 3.<br>
7.Low income individual favorite treadmill.Average salary is 46K.Lowest salary compared to customers from other two products<br>

#### TM498:

1.Second most popular after TM195.<br>
2.Popular among Partnered Male than Partnered Female.Single Female purchase this product more than Single male<br>
3.Least popular among males but second most popular among Females after TM195.<br>
4.Attracts customers between age 19-29.<br>
5.Most of customers have 16 yrs. Of education.<br>
6.Most customers who use the treadmill plan to run an average of 88 miles, for about 3 days per week. The average self-assessed fitness rating is 3.<br>
7.Customers with average salary of 49K. Probably the ones who are slightly better off financially compared to customers of  TM195 product.<br>

#### TM798:

1.Premium elite treadmill.<br>
2.Customers who buy the treadmill are super fit. They make the best use of it. They use it average of 4-5 days per week.None of the customers using the product are poor fit.<br>
3.Average salary of customers who buy the treadmill is 75K and have about 17 yrs. Of education.<br>
4.Customers plan to run average of 167 miles per week which means the product is sturdy and of high quality. Hence, the price may be costly.<br>
5.Least popular among Female.Second most popular in Male after TM195<br>
6.Favorite product of partnered male than single male. Similar partnered female buy the product more than single female.<br>
7.Least sold product may be due to cost.<br>
    

### Recommendations:

1.None of the product is purchased by individuals older than 50 yrs. Company could offer incentives to senior citizens, interest free payments for few months, retired veterans.<br>
2.Company can also offer discount to big corporates and advertise health benefits for individuals older than 50 yrs.<br>
3.Maximum Salary of customers using product is 105K. Company can conduct research to understand the wellness routine of high salary individuals in the country and then take up necessary actions.<br>
4.Offer discounts to hotels and fitness centers.Most of 3 star hotels have gym these days.<br>
5.TM798 is not popular among female. Company can conduct research and understand the reason, then take necessary action steps.<br>
6.Special discounts on Mothers day, Valentines day, Womens day, Fathers day, Long weekend , half yearly sale may help to increase the business.<br>
7.Marketing campaign on Social media can also help. We do not have enough data to understand if that is done today.<br> 
8.Celebrity endorsement is another popular marketing campaign if not done today.<br>