In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [ ]:
data = pd.read_csv("/kaggle/input/pokemon-challenge/pokemon.csv")

In [ ]:
data.info()

In [ ]:
data.corr()

In [ ]:
#correlation map

f,ax = plt.subplots(figsize=(12,12))
sns.heatmap(data.corr(),annot=True,linewidths=0.5,fmt='.1f',ax=ax)
plt.show()

In [ ]:
data.head(10)

In [ ]:
data.columns

# **MATPLOTLİB**

In [ ]:
#line
data.Speed.plot(kind="line",color="g",label="Speed",linewidth=1,alpha=0.5,grid=True,linestyle=":")
data.Defense.plot(color="r",label="Defense",linewidth=1,alpha=0.5,grid=True,linestyle="-.")
plt.legend(loc="upper right")
plt.xlabel("x axis")
plt.ylabel("y axis")
plt.title("Line Plot")

In [ ]:
#scatter
data.plot(kind="scatter",x="Attack",y="Defense",alpha=0.5,color="red")
plt.xlabel("Attack")
plt.ylabel("Defense")
plt.title("Attack Defense Scatter Plot")

In [ ]:
#scatter with another coding style
plt.scatter(data.Attack,data.Defense,color="red",alpha=0.5)
plt.xlabel("Attack")
plt.ylabel("Defense")
plt.title("Attack Defense Scatter Plot")

In [ ]:
#histogram

data.Speed.plot(kind="hist",bins=50,figsize=(10,10))
plt.show()

#bin = barların sayısıdır.

In [ ]:
# clf() = cleans it up again you can start a fresh

data.Speed.plot(kind="hist",bins=50,figsize=(15,15))
plt.clf()

# **DICTIONARY**

In [ ]:
#dictionaries are faster than lists

In [ ]:
dictionary = {'spain':'madrid','usa':'vegas'}
print(dictionary.keys())
print(dictionary.values())

In [ ]:
dictionary['spain'] = "barcelona"
print(dictionary)
dictionary['france'] = "paris"
print(dictionary)

del dictionary['spain']
print(dictionary)

print('france' in dictionary)
dictionary.clear()
print(dictionary)

In [ ]:
del dictionary
print(dictionary)

# **PANDAS**

In [ ]:
data = pd.read_csv("/kaggle/input/pokemon-challenge/pokemon.csv")

In [ ]:
series = data.Defense
print(type(series))
data_frame = data[['Defense']]
print(type(data_frame))

In [ ]:
data[data.Defense > 200]

In [ ]:
#filtering pandas with logical and

data[np.logical_and(data.Defense>200,data.Attack>100)]

In [ ]:
#filtering pandas with another code style

data[(data.Defense>200) & (data.Attack>100)]

# **WHILE AND FOR LOOPS**

In [ ]:
i = 0
while i !=5:
    print("i is : ",i)
    i+=1
print(i," is equal to 5")

In [ ]:
lis = [1,2,3,4,5]

for i in lis:
    print("i is : ",i)
print("")

#enumerate index and value of list

for index,value in enumerate(lis):
    print(index," : ",value)
print("")


#for dictionaries

dictionary = {'spain':'madrid','france':'paris'}

for key,value in dictionary.items():
    print(key," : ",value)
print("")

#for pandas we can achieve index and value

for index,value in data[["Attack"]][0:1].iterrows():
    print(index, " : ",value)

# **2.PYTHON DATA SCIENCE TOOLBOX**

In [ ]:
def tuble_ex():
    """ return defined t tuble"""
    t= (1,2,3)
    return t

a,b,c = tuble_ex()
print(a,b,c)

# SCOPE

In [ ]:
#global , local , ....

# **NESTED FUNCTION**

In [ ]:
def square():
    
    def add():
        """add two local variable"""
        x=2
        y=3
        z=x+y
        return z
    return add()**2
print(square())

**DEFAULT AND FLEXIBLE ARGUMENTS**

In [ ]:
#default arguments example
def f(a,b=1,c=2):
    y = a+b+c
    return y
print(f(5))

print(f(5,4,3))

**ITERATORS AND LIST COMPREHENSION**

In [ ]:
#iteration example

name="ronaldo"
it=iter(name)
print(next(it))
print(*it)

# ***3.CLEANING DATA***

In [ ]:
data = pd.read_csv("/kaggle/input/pokemon-challenge/pokemon.csv")
data.head()

In [ ]:
data.tail()

In [ ]:
data.columns

In [ ]:
data.shape

In [ ]:
data.info()

# **EXPLOTARY DATA ANALYSIS(EDA)**

In [ ]:
print(data["Type 1"].value_counts(dropna=False))

In [ ]:
data.describe()

# **VISUAL EXPLORATORY DATA ANALYSIS**

In [ ]:
data.boxplot(column="Attack",by="Legendary")
plt.show()

# **TIDY AND PIVOTING DATA**

In [ ]:
data_new = data.head()
data_new

In [ ]:
#id_vars = what we do not want to melt
#value_vars = what we want to melt



melted = pd.melt(frame=data_new,id_vars="Name",value_vars=["Attack","Defense"])
melted

# **PIVOTING DATA**

In [ ]:
#reversal of melting

melted.pivot(index="Name",columns="variable",values="value")

# **CONCATENATING DATA AND DATA TYPES**

In [ ]:
data1 = data.head()
data2 = data.tail()

conc_data_row = pd.concat([data1,data2],axis=0,ignore_index=True)
conc_data_row

In [ ]:
data1 = data.Attack.head()
data2 = data.Defense.head()

conc_data_cols = pd.concat([data1,data2],axis=1)
conc_data_cols

DATA TYPES

In [ ]:
data.dtypes

In [ ]:
data["Type 1"] = data["Type 1"].astype("category")
data["Speed"] = data["Speed"].astype("float")

In [ ]:
data.dtypes

# **MISSING DATA AND TESTING WITH ASSERT**

In [ ]:
data.head()

#for example charmender has type1 but no type2. thats means missing data. 
#may be ıt has bu didnt written.!!!

In [ ]:
data.info()

In [ ]:
data["Type 2"].value_counts(dropna=False)

In [ ]:
data1=data
data1["Type 2"].dropna(inplace=True)

In [ ]:
data["Type 2"].value_counts(dropna=False)

In [ ]:
assert 1==1 #doğruysa birşey döndürmüyor!!

In [ ]:
assert 1==2

In [ ]:
assert data["Type 2"].notnull().all() #returns nothing because we drop nan values

In [ ]:
data["Type 2"].fillna("empty",inplace=True)

In [ ]:
assert data["Type 2"].notnull().all() # returns nothing because we do not have nan values

In [ ]:
assert data.columns[1] == "Name"

In [ ]:
assert data.Speed.dtypes == np.float

# **4.PANDAS FOUNDATION**

Review of Pandas

In [ ]:
data_dict = {"Country":["Spain","France"],"Population":[11,12]}
df = pd.DataFrame(data_dict)
df

In [ ]:
df["Capital"] = ["madrid","paris"]
df

In [ ]:
df["Income"] = 0
df

In [ ]:
data1 = data.loc[:,["Attack","Defense","Speed"]]
data1.plot()

In [ ]:
data1.plot(subplots=True)

In [ ]:
data1.plot(kind="scatter",x="Attack",y="Defense")

In [ ]:
data1.plot(kind="hist",y="Defense",bins=50,range=(0,250),normed=False)

# normed = normalize the data btwn 0-1

In [ ]:
# histogram subplot with non cumulative and cumulative
fig, axes = plt.subplots(nrows=2,ncols=1)
data1.plot(kind = "hist",y = "Defense",bins = 50,range= (0,250),normed = True,ax = axes[0])
data1.plot(kind = "hist",y = "Defense",bins = 50,range= (0,250),normed = True,ax = axes[1],cumulative = True)

**INDEXING PANDAS TIME SERIES**

In [ ]:
time_list = ["1992-03-08","1992-04-12"]
print(type(time_list[1])) # As you can see date is string
# however we want it to be datetime object
datetime_object = pd.to_datetime(time_list)
print(type(datetime_object))

In [ ]:
# close warning
import warnings
warnings.filterwarnings("ignore")
# In order to practice lets take head of pokemon data and add it a time list
data2 = data.head()
date_list = ["1992-01-10","1992-02-10","1992-03-10","1993-03-15","1993-03-16"]
datetime_object = pd.to_datetime(date_list)
data2["date"] = datetime_object
# lets make date as index
data2= data2.set_index("date")
data2

In [ ]:
print(data2.loc["1993-03-16"])
print(data2.loc["1992-03-10":"1993-03-16"])

**RESAMPLING PANDAS TIME SERIES**

Resampling: statistical method over different time intervals
Needs string to specify frequency like "M" = month or "A" = year
Downsampling: reduce date time rows to slower frequency like from daily to weekly
Upsampling: increase date time rows to faster frequency like from daily to hourly
Interpolate: Interpolate values according to different methods like ‘linear’, ‘time’ or index’
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.interpolate.html

In [ ]:
# We will use data2 that we create at previous part
data2.resample("A").mean()

In [ ]:
# Lets resample with month
data2.resample("M").mean()
# As you can see there are a lot of nan because data2 does not include all months

# **5. MANIPULATING DATAFRAMES WITH PANDAS**

In [ ]:
data.head()

In [ ]:
# read data
data = pd.read_csv("/kaggle/input/pokemon-challenge/pokemon.csv")
data= data.set_index("#")
data.head()

In [ ]:
data["HP"][1]

In [ ]:
data.loc[1,["HP"]]

In [ ]:
data[["HP","Attack"]]

SLICING DATA FRAME

In [ ]:
# Difference between selecting columns: series and dataframes
print(type(data["HP"]))     # series
print(type(data[["HP"]]))   # data frames

In [ ]:
# Slicing and indexing series
data.loc[1:10,"HP":"Defense"]   # 10 and "Defense" are inclusive

In [ ]:
# Reverse slicing 
data.loc[10:1:-1,"HP":"Defense"]

In [ ]:
# From something to end
data.loc[1:10,"Speed":]

FILTERING DATA FRAMES

In [ ]:
# Creating boolean series
boolean = data.HP > 200
data[boolean]

In [ ]:
# Combining filters
first_filter = data.HP > 150
second_filter = data.Speed > 35
data[first_filter & second_filter]

In [ ]:
data[data.Speed<15]

In [ ]:
# Filtering column based others
data.HP[data.Speed<15]

TRANSFORMING DATA

In [ ]:
# Plain python functions
def div(n):
    return n/2
data.HP.apply(div)

In [ ]:
# Or we can use lambda function
data.HP.apply(lambda n : n/2)

In [ ]:
# Defining column using other columns
data["total_power"] = data.Attack + data.Defense
data.head()

INDEX OBJECTS AND LABELED DATA

In [ ]:
# our index name is this:
print(data.index.name)
# lets change it
data.index.name = "index_name"
data.head()

In [ ]:
# Overwrite index
# if we want to modify index we need to change all of them.
data.head()
# first copy of our data to data3 then change index 
data3 = data.copy()
# lets make index start from 100. It is not remarkable change but it is just example
data3.index = range(100,900,1)
data3.head()

HIERARCHICAL INDEXING

In [ ]:
# lets read data frame one more time to start from beginning
data = pd.read_csv("/kaggle/input/pokemon-challenge/pokemon.csv")
data.head()
# As you can see there is index. However we want to set one or more column to be index

In [ ]:
# Setting index : type 1 is outer type 2 is inner index
data1 = data.set_index(["Type 1","Type 2"]) 
data1.head(50)
# data1.loc["Fire","Flying"] # howw to use indexes

PIVOTING DATA FRAMES,
pivoting: reshape tool

In [ ]:
dic = {"treatment":["A","A","B","B"],"gender":["F","M","F","M"],"response":[10,45,5,9],"age":[15,4,72,65]}
df = pd.DataFrame(dic)
df

In [ ]:
# pivoting
df.pivot(index="treatment",columns = "gender",values="response")

STACKING and UNSTACKING DATAFRAME

* deal with multi label indexes
* level: position of unstacked index
* swaplevel: change inner and outer level index position

In [ ]:
df1 = df.set_index(["treatment","gender"])
df1
# lets unstack it

In [ ]:
# level determines indexes
df1.unstack(level=0)

In [ ]:
df1.unstack(level=1)