 ## First Steps  
 
 ### * There is some basic features of pandas, numpy and matplot lib libraries. 
 ### * I tried to write code in a Cause and Effect Relationship 
 ### * First I wonder something in our data set, ( for example what is the best attack stat skilled pokemon in the data set?) and then I found it by code.
 ### * Thanks for efficient and instructive lessons to[ Kaan Can](https://www.kaggle.com/kanncaa1/)

Content
## [1.  Review of Pokemon Dataset](#1)
## [2. Scatter Plot](#2)
## [3. Relation Between Features By Correlation Method](#3)
## [4. Histogram Plot](#4)
## [5. Filtering Features With Numpy's Logical Method](#5)
## [6. For Loop](#6)
## [7.  Exploring And Cleaning Data](#7)
### * Box Plot
### * Melting Data   
### * Pivoting Data    (To Reverse  Melt Method)
### * Concatenating Data
### * Changing Data Type Of Variable
### * Exploring Null Data and Dropping them

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

<a id="1"></a> <br>
### 1. REVIEW OF POKEMON DATASET

In [ ]:

# Any results you write to the current directory are saved as output.
data=pd.read_csv('../input/Pokemon.csv')
data.info()

* We can see various type of informations about our dataset by  "describe method"

In [ ]:
data.describe()

*  How many samples in this dataset. We can see the last index number with listing last five samples by tail() method. We have 800 samples (first sample index number is "0")

In [ ]:
data.tail()

* Which features do we have in our great Pokemon data set ?

In [ ]:
data.columns

<a id="2"></a> <br>
### 2. SCATTER PLOT

* Plotting Attack and Defence in a table for understanding the relation between them.
* We intuitively understand that there is a lineer relation between them as seen plot below.

In [ ]:
data.plot(kind = "scatter",x="Attack",y="Defense",color = 'r',label = 'Attack',linewidth=1, alpha = 0.5,grid = True,linestyle = '-.')
plt.show()

* Now was the relation between Defence and Attack stats real?
* We can see that mathematically with correlation method. Let's try that.

<a id="3"></a> <br>
### 3. RELATION BETWEEN FEATURES BY CORRELATION METHOD

In [ ]:
data.corr()

* As we see attack and defence correlation coefficient is 0.43 almost best correlated stats in the data set.

<a id="4"></a> <br>
### 4. HISTOGRAM PLOT

* Now I wonder the frequencies of attack stats in dataframe.  I need to plot a histogram which has "attack parameter".

In [ ]:
data.Attack.plot(kind="hist",color="red",alpha=0.5)
plt.show()

As we see, the most common attack stats in pokemon world are between "40-60"

<a id="5"></a> <br>
### 5. FILTERING FEATURES WITH NUMPY'S LOGICAL METHOD

*  Let's see the pokemons which has attack stats between 40-60

In [ ]:
df_attack_logical = np.logical_and(data["Attack"] >40,data["Attack"]< 60)
data2=data[df_attack_logical]#"df_attack_logical" has boolean values (true or false) for each sample (pokemon) in data set.
                             # It's boolean values changes according to our (between 40-60) filter.
print(data2.head()["Name"])  # We need only names so I printed first five names coloumn (feature)

<a id="6"></a> <br>
### 6. FOR LOOP

* I want to list only first five index numbers and attack values in data2 dataframe.
* Then I used for loop.

In [ ]:
for index in data2.head()[['Attack']].iterrows():
    print(index)

<a id="7"></a> <br>
### 7. EXPLORING AND CLEANING DATA
* ### Box Plot
* ### Melting Data   
* ### Pivoting Data    (To Reverse  Melt Method)
* ### Concatenating Data
* ### Changing Data Type Of Variable
* ### Exploring Null Data and Dropping them

* Changing all column letters to lower
* Deleting spaces between letters in coloumn names

In [ ]:
data.columns = [each.lower() for each in data.columns] 
data.columns = [each.split()[0]+"_"+each.split()[1] if(len(each.split())>1) else each for each in data.columns]
data.head() # Listing first five samples in data set

* Changing the column name

In [ ]:
data.rename(columns = {'#':'number'}, inplace = True) #If we choose "inplace= true" it will change name permanently, else it will change for just one running of code
data.head()

 ### Box Plot
* What is the distrubition of attack stats according to the generation of Pokemons?
* We can see this by using box plot.

In [ ]:
data.boxplot(column="attack",by="generation")
plt.show()

### Melting Data

In [ ]:
data_first_five=data.head()
data_first_five
melted=pd.melt(frame=data_first_five,id_vars="name", value_vars=["attack","defense"])
melted

### Pivoting Data    (To Reverse  Melt Method)

In [ ]:
melted.pivot(index = 'name', columns = 'variable',values='value')

 ### Concatenating Data

*  I have two different datasets and they have same features so ı want to comnine them.
*  I should use the cons() method for this purposes

In [ ]:
data1 = data.head()
data2= data.tail()
conc_data_row = pd.concat([data1,data2],axis =0,ignore_index =True) # axis = 0 : adds dataframes in row, ignore_index =True means give  new index numbers for data2

conc_data_row

 ### Changing Data Type Of Variable
If we need to change the type of feature values we can use astype() method of numpy lib.

In [ ]:
data.dtypes

In [ ]:
data['attack'] = data['attack'].astype('object');
data.dtypes

 ### Exploring Null Data and Dropping them

* I have a huge dataset so that it is almost impossible all of features has all values.
* Before analysing data we need to make ready our dataset to analyse with some process
* It is called pre-processing
* First I need to see my data overview

In [ ]:
data.info()

* We have 414 non-null type_2 sample.
* If we have 800 sample dataset and there is 414 nonull values it means we have some null features (800-414=386)

In [ ]:
data["type_2"].value_counts() # It shows us the frequancies of type_2 values but there is no null values

In [ ]:
data["type_2"].value_counts(dropna =False) # Now we can see null values as we calculate there is 386 null values

* Our intention was dropping the non values in data set
* We saw that there is only one feature  has null values  which is type_2 feature
* Let's drop these bugs :)

In [ ]:
data["type_2"].dropna(inplace = True)
data["type_2"].value_counts(dropna=False)

* As we see there is no any null values after all 
* Let's test this with another way and finish this quest for now

In [ ]:
data["type_2"].notnull().all()