In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [ ]:
# importing Data
data=pd.read_csv("../input/students-performance-in-exams/StudentsPerformance.csv")
data.head()

In [ ]:
data.columns

In [ ]:
data.corr()

In [ ]:
# correlation Map

sns.heatmap(data.corr(),annot=True,Linewidth=1,fmt='.1f')

# Matplotlib

In [ ]:
data.head()

In [ ]:
# line Plot
plt.figure(figsize=(12,6))
data["math score"].plot(kind='line',label="math score",color="blue",alpha=0.5,grid=True)
data["reading score"].plot(color="red",label="reading score",alpha=0.5,grid=True)
data["writing score"].plot(color="green",label="writing score",alpha=0.5,grid=True)
plt.xlabel("number of person")
plt.ylabel("values")
plt.legend()

In [ ]:
# scatter Plot
plt.scatter(x=data["reading score"],y=data["math score"],color="green")
plt.show()

In [ ]:
# histogram Plot
plt.figure(figsize=(10,5))
data["reading score"].plot(kind="hist",bins=50)

In [ ]:
data.head()

# Dictionary

In [ ]:
dic={"Japan":"Tokyo","Turkey":"Ankara","Germany":"Berlin"}
dic.keys() # countries
dic.values() # capitals
dic

In [ ]:
# add
dic["USA"]="Washington"
#update
dic["Turkey"]="Ä°stanbul"
#delete
del dic["Turkey"]
#searching
print("Germany" in dic) #true or false
dic

# Filtering

In [ ]:
data.head()

In [ ]:
data[data["math score"]>95]
#filtering with two features
data[( data["parental level of education"]=="bachelor's degree")  &  (data["math score"]>95) ]
# another way
data[np.logical_and(data["parental level of education"]=="bachelor's degree" , data["math score"]>95)]

# For and While Loop

In [ ]:
liste=[1,2,3,4,5]
t=0
for i in liste:
    t=t+(i*i)
print(t)

In [ ]:
t=0
for i in range(1,6): 
    t=t+(i*i) 
print(t)

In [ ]:
i=0
t=0
while(i!=5):
    i=i+1
    t=t+(i*i)
   
    
print(t)

In [ ]:
liste=['USA',"China","Japan","Germany","UK"]
print("Biggest 5 Economy in the World")
for index,value in enumerate(liste):
    print(index+1,"",value)

In [ ]:
Dictionary={"USA":"328,2 million (2019)","China":"1,393 billion (2018)","Japan":"126,5 million (2018)"
            ,"Germany":"83,02 million (2019)","UK":"55,98 million (2018)"}
print("---Biggest 5 Economy and Their Population---")
for key,value in Dictionary.items():
    print(key,"", value)

# Python Data Science Toolbox

In [ ]:
# lambda function
area_triangle=lambda x,y:(x*y)/2
print("triangle's area :",area_triangle(5,4))

area_circle=lambda pi,r:pi*(r*r)
print("circle's area :",area_circle(3.14,10))

In [ ]:
# anonymous function
radius=[2.5,5,7.5,10]
areas=map(lambda r:3.14*(r*r),radius)
print(list(areas))

In [ ]:
# zip method
list1=[1,2,3,4,5,6,7]
list2=[ "Africa", "Antarctica", "Asia", "Australia", "Europe", "North America", "South America"]
zipped=zip(list1,list2)
listed=list(zipped)
listed

In [ ]:
# un-zip
un_zip=zip(*listed)
un_list1,un_list2=list(un_zip)
print(un_list1)
print(un_list2)

In [ ]:
# list comprehension
numbers1=[1,2,3,4,5]
numbers2=[i**2 for i in numbers1]
numbers2

In [ ]:
# conditional list comprehension
numbers3=[20,40,60,80,100]
numbers4=[i-i if i<50 else i+i for i in numbers3]
numbers4

In [ ]:
# adding new columns
data["avg_math"]=sum(data["math score"])/len(data["math score"])
data["math status"]=["above the average" if i>66 else "under the average" for i in data["math score"]]
data.head()

In [ ]:
data.head()
data.index.name="#"
data.loc[:,["parental level of education","math status"]]

In [ ]:
# graduation types of student
data["parental level of education"].value_counts(dropna=False)

In [ ]:
#data.drop(["avg_math","math status"],axis=1,inplace=True)
data.head()

# Exploratory Data Analysis

In [ ]:
#melting
data_exp=data.head(2)
melted=pd.melt(frame=data_exp,id_vars="race/ethnicity",value_vars=["parental level of education","writing score"])
melted

In [ ]:
#pivoting
pivot_data=melted.pivot(index="race/ethnicity",columns="variable",values="value")
pivot_data

In [ ]:
#concatenating Data
hdata=data.head()
tdata=data.tail()
concat_data=pd.concat([hdata,tdata],axis=0,ignore_index=True)
#ignore_index=generated new index
concat_data

In [ ]:
df1=data["parental level of education"].head(10)
df2=data["reading score"].head(10)
concat_data2=pd.concat([df1,df2],axis=1)
concat_data2

In [ ]:
#data types of columns
data.dtypes

In [ ]:
# changing types
data["gender"]=data["gender"].astype('category')
data["writing score"]=data["writing score"].astype('float')
data.dtypes

In [ ]:
data['gender'].value_counts(dropna=False)
# remove nan columns
#data["gender"].dropna(axis=0)
assert 1==1 #is there wrong ? if you don't see anything,everything is okey

In [ ]:
assert data["math score"].notnull().all()
#return nothing because we don't have a null values

In [ ]:
Country=["USA","Germany","Japan"]
GDP=["20,54 trilyon USD (2018)","3,948 trilyon USD (2018)","4,971 trilyon USD (2018)"]
list_label=["Country","GDP"]
list_col=[Country,GDP]
zipped=zip(list_label,list_col)
listed=list(zipped)
dictionary=dict(listed)
df=pd.DataFrame(dictionary)
df

In [ ]:
df["Population"]=["328,2 milyon (2019)","83,02 milyon (2019)","126,5 milyon (2018)"]
df

In [ ]:
df1=data.loc[:,["math score","math status"]]
df1

# Visualization Exploratory Data Analysis

In [ ]:


#data.drop("avg_math",axis=1,inplace=True)
data.plot(subplots=True)
plt.show()

In [ ]:
# time Series
date_time=["1990-05-20","1992-10-02","1994-05-08","1994-11-12"]
date_type=pd.to_datetime(date_time)
type(date_type) #DatetimeIndex

In [ ]:
import warnings
warnings.filterwarnings("ignore")
df2=data.head()
date_time=["1990-02-15","1978-10-11","1980-05-14","1994-04-30","1994-08-24"]
time_object=pd.to_datetime(date_time) # data type converting
df2["time"]=time_object # adding new columns
df2=df2.set_index("time") # new index
df2

In [ ]:
df2.loc["1990-02-15"]
# or
df2.loc["1980-01-01":"1994-04-30"]

In [ ]:
df2.resample("A").mean() # average of each year
df2.resample("M").mean() # average of each month

In [ ]:
df2.resample("A").mean().interpolate("linear") # filling null years with fit values

In [ ]:
data.loc[1:7,"math score":"writing score"]
data.loc[1:7,"math score"]
data.loc[10:1:-1,"gender":"parental level of education"]

In [ ]:
data.gender[data["reading score"]>90].value_counts()

In [ ]:
def div(n):
    return n/2
ws2=data["writing score"].apply(div)
ws2

In [ ]:
ms2=data["math score"].apply(lambda n:n/2)
ms2

In [ ]:
sum2var=data["math score"]+data["writing score"]
sum2var

In [ ]:
df=data.head()
df=df.set_index("math score") # just for available columns in data
df

In [ ]:
# print(data.index.name)

data.index.name="index" # you can define the index name whatever you want

In [ ]:
df2=data.head()
df2=df2.set_index(["gender","math score"]) #define two features as index
df2