## Your Turn!

## What's Love Got to do with it! Challenges with Answers

### import Libraries

In [ ]:
#import Libraries
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### import your data

In [ ]:
df = pd.read_csv('../input/speed-dating-experiment/Speed Dating Data.csv')

### Step 3: Exploratory Data Analysis - EDA 
#### Step 3a: Understand your data 
Let's see what we are working with.

In [ ]:
#Take a look at the first five rows of your dataset

In [ ]:
#The number of rows and columns in your dataset

In [ ]:
#Names of all the columns in your dataset

In [ ]:
#let's summarize your dataset

# What story do we want to tell?

### Who got the most and least dates?

* What is their income?
* What are their age?
* What is their Race?    
* What is their Gender?
* What  is their intended career?
* What  is their intended career?
* What field are they in?
* how often do they go on date?
* how often do they go out - social butterfly? 
* Did their goal influence their result?
* People who like what sport got the most or least dates.

In [ ]:
#create a sub dataset
df2 = df[["iid","id","gender","match","int_corr","samerace","age_o","race_o","dec_o","attr_o","age","field","race","imprace","imprelig","income","goal","date","go_out","sports","tvsports","exercise","dining","museums","art","hiking","gaming","clubbing","reading","tv","theater","movies","concerts","music","shopping","yoga","exphappy","expnum","attr3_1","sinc3_1","intel3_1","fun3_1","amb3_1","dec","attr","sinc","intel","fun","amb","met","match_es"]]
df2.head()

In [ ]:
#Take a look at the first five rows of your dataset

### Step 3b: Clean your data
Delete the null values

In [ ]:
#let's take out the null value
df2.isnull().sum()

In [ ]:
#drop rows with null values
df3 = df2.dropna()
df3.shape

In [ ]:
#Rename selected columns

df3.rename(columns={"gender": "Gender", 
                     "dec_o":"Decision",
                     "attr_o":"Attractive",
                     "sinc_o":"Sincere",
                     "intel_o":"Intelligent",
                     "fun_o":"Fun",
                     "amb_o":"Ambitious",
                     "shar_o":"Shared Interests",
                     "goal":"Why event?",
                     "date":"Dating frequency",
                     "go_out":"Social butterfly",
                     "exhappy":"Happy to meet people",
                     "expnum":"Expected dates",
                     "attr3_1":"MyAttractive",
                     "sinc3_1":"MySincere",
                     "intel3_1":"MyIntelligent",
                     "fun3_1":"MyFun",
                     "amb3_1":"MyAmbitious",
                    "match_es":"MyMatches"}, inplace=True)

#other cleaning tasks

df3.field=df3.field.str.upper()

df3.field.replace({"BUSINESS- MBA":"MBA","MASTERS OF SOCIAL WORK":"SOCIAL WORK"},inplace=True)


df3.columns

### Step 4:  Visualize your data
#### Who got the most dates?
Tell your stories visually!

In [ ]:
#What is the distribution/spread of the ages of all the students?

#create a figure object and set its size 

plt.figure(figsize=(20, 5))

#add plot title
plt.title('Student Age')

#add labels for the x and y axis
plt.xlabel('Ages')
plt.ylabel('Total Number of Students')

#set bin interval
bins = [18,20,22,24,26,28,30,32,34]

#set tick locations for y-axis
#ticks = [20,40,60,80,100,120,140,160, 180,200,220,240]
#plt.yticks(ticks)

#plot
plt.hist(df3.age,bins=bins,edgecolor='white')
plt.show()

In [ ]:
#what age got the most dates?

#create a figure object and set its size 
plt.figure(figsize=(20, 5))

#add plot title
plt.title('Ages of students who got the most dates')

#add labels for the x and y axis
plt.ylabel('Total Number of Students dates')
plt.xlabel('Ages')

#retrieve ages of students who got dates
rage=df3.groupby('age').Decision.sum()

#set ages as values for x-axis
index = ['18','19','20','21','22','23','24','25','26','27','28','29','30','34']
#plot
plt.bar(index,rage)
plt.show()

### What's gender got to do with it?

In [ ]:
#What is the proportion of male and female students?

#create a figure object and set its size 
plt.figure(figsize=(10, 30))

#add plot title
plt.title("Which Gender got more dates?")

#sum up the number of students for each gender 
rdates=df3.groupby('Gender').iid.sum()

#plot
plt.pie(rdates,labels=glabels,startangle=90,autopct='%.1f')
plt.legend()
plt.show()

In [ ]:
#Which gender got more dates?

#create a figure object and set its size 
plt.figure(figsize=(10, 30))

#add plot title
plt.title("Which Gender got more dates?")

#add labels
#glabels =["Female","Males"]

#sum up the number of dates for each gender 
gdates=df3.groupby('Gender').Decision.sum()


#plot
plt.pie(gdates,labels=glabels,startangle=90,autopct='%.1f')
plt.legend()
plt.show()