# Task assignment

#  **1. Load the data from the CSV files**

In [ ]:
import pandas as pd
df1 = pd.read_csv('../input/solar-power-generation-data/Plant_1_Generation_Data.csv')
df2 = pd.read_csv('../input/solar-power-generation-data/Plant_1_Weather_Sensor_Data.csv')
plant2_df1 = pd.read_csv('../input/solar-power-generation-data/Plant_2_Generation_Data.csv')
plant2_df2 = pd.read_csv('../input/solar-power-generation-data/Plant_2_Weather_Sensor_Data.csv')

# To display the Dataset of Generation data

In [ ]:
df1.head()#plant 1

In [ ]:
plant2_df1.head()#plant 2

# To display the Dataset of Weather Sensor Data

In [ ]:
df2.head()

In [ ]:
plant2_df2.head()

# **2. Explore each dataset - columns, counts, basic stats**

# To display columns of dataset 1 and dataset 2

In [ ]:
df1.columns

In [ ]:
df2.columns

In [ ]:
plant2_df1.columns

In [ ]:
plant2_df2.columns

# To display counts of datasets

In [ ]:
df1.nunique()

In [ ]:
df2.nunique()

In [ ]:
plant2_df1.nunique()

In [ ]:
plant2_df2.nunique()

# To display basic stats

In [ ]:
df1.describe()

In [ ]:
df2.describe()

In [ ]:
plant2_df1.describe()

In [ ]:
plant2_df2.describe()

# 3 . Understand the domain context and explore underlying patterns in the data
By evaluating the data without doing any calculations it is clear that daily yield has been dropped and the data is recorded continuosly. It seems that there are no null vaues but can not be determined without doing any calculations. Also it is seen that the number of invertors here are almost 22 but can not be determined without calculating.

# **4 . Explore the data and try to answer questions like -**

A.**What is the mean value of daily yield?**

In [ ]:
dy_mean = df1['DAILY_YIELD'].mean()

In [ ]:
print(f'The mean value of Daily Yield is {dy_mean}')

In [ ]:
dy_mean2 = plant2_df1['DAILY_YIELD'].mean()
print(f'The mean daily yield of plant 2 generation data is {dy_mean2}')

 **B.What is the total irradiation**

In [ ]:
irradiation_sum1 = df2['IRRADIATION'].sum()
print(f'The total irradiation in plant1 weather sensor data is {irradiation_sum1}' )

In [ ]:
irradiation_sum2 = plant2_df2['IRRADIATION'].sum()
print(f'The total irradiation in plant2 weather sensor data is {irradiation_sum2}' )

 **C.What is the max ambient and module temperature?**

In [ ]:

max_ambient_1 = df2['AMBIENT_TEMPERATURE'].max()
max_module_temp_1 = df2['MODULE_TEMPERATURE'].max()
print(f'The max ambient in plant 1 weather sensor data is {max_ambient_1}')
print(f'The max module temperature in plant 1 weather sensor data is {max_module_temp_1}')

In [ ]:
max_ambient_2 = plant2_df2['AMBIENT_TEMPERATURE'].max()
max_module_temp_2 = plant2_df2['MODULE_TEMPERATURE'].max()
print(f'The max ambient in plant 2 weather sensor data is {max_ambient_2}')
print(f'The max module temperature in plant 2 weather sensor data is {max_module_temp_2}')

 **D.How many inverters are there for each plant?**

In [ ]:
plant1_inverter1 = df1['SOURCE_KEY'].nunique()
plant1_inverter2 = df2['SOURCE_KEY'].nunique()
plant2_inverter1 = plant2_df1['SOURCE_KEY'].nunique()
plant2_inverter2 = plant2_df2['SOURCE_KEY'].nunique()
print(f'The number of inverters in plant 1 generation data is {plant1_inverter1}')
print(f'The number of inverters in plant 1 weather sensor data is {plant1_inverter2}')
print(f'The number of inverters in plant 2 generation data is {plant2_inverter1}')
print(f'The number of inverters in plant 2 weather sensor data is {plant2_inverter2}')

 **E.What is the maximum/minimum amount of DC/AC Power generated in a time interval/day?**

In [ ]:
df1['DC_POWER'].max()

In [ ]:
df1['DC_POWER'].min()

In [ ]:
print(df1.info())
print(plant2_df1.info())

In [ ]:

df1['DATE_TIME']=pd.to_datetime(df1['DATE_TIME'],format ='%d-%m-%Y %H:%M')
print(df1.info())
df1['DATE_TIME'] = pd.to_datetime(df1['DATE_TIME'],format = '%Y-%m-%d %H:%M:%S')
print(df1.info())

In [ ]:
df1['DATE'] = pd.to_datetime(df1['DATE_TIME'],format ='%d-%m-%Y %H:%M').dt.date
df1['DATE'] = pd.to_datetime(df1['DATE'])
df1

In [ ]:
df2['DATE'] = pd.to_datetime(df2['DATE_TIME'],format ='%Y-%m-%d %H:%M:%S').dt.date
df2['DATE'] = pd.to_datetime(df2['DATE'])

In [ ]:
plant2_df1['DATE'] = pd.to_datetime(plant2_df1['DATE_TIME'],format ='%Y-%m-%d %H:%M:%S').dt.date
plant2_df1['DATE'] = pd.to_datetime(plant2_df1['DATE'])
plant2_df1

In [ ]:
d1 = df1.groupby(['DATE']).sum()
d1

In [ ]:
plant2_df2['DATE'] = pd.to_datetime(plant2_df2['DATE_TIME'],format ='%Y-%m-%d %H:%M:%S').dt.date
plant2_df2['DATE'] = pd.to_datetime(plant2_df2['DATE'])

In [ ]:
d1 = df1.groupby(['DATE']).sum()
d1

In [ ]:
d2=df1.groupby(['DATE']).sum()
d2

In [ ]:
plant1_dc_max_power = (d1['DC_POWER'].max())
plant2_dc_max_power = (d2['DC_POWER'].max())
plant1_dc_min_power = (d1['DC_POWER'].min())
plant2_dc_min_power = (d2['DC_POWER'].min())

In [ ]:
print(f'The max dc power for plant 1 one table in a day is {plant1_dc_max_power}')
print(f'The min dc power for plant 1 other table in a day is {plant1_dc_min_power}')
print(f'The max dc power for plant 2 first table in a day is {plant2_dc_max_power}')
print(f'The min dc power for plant 2 second table in a day is {plant2_dc_min_power}')

In [ ]:
plant1_ac_max_power = (d1['AC_POWER'].max())
plant2_ac_max_power = (d2['AC_POWER'].max())
plant1_ac_min_power = (d1['AC_POWER'].min())
plant2_ac_min_power = (d2['AC_POWER'].min())

In [ ]:
print(f'The max ac power for plant 1 table 1 in a day is {plant1_ac_max_power}')
print(f'The min ac power for plant 1 table 2 in a day is {plant1_ac_min_power}')
print(f'The max ac power for plant 2 table 1 in a day is {plant2_ac_max_power}')
print(f'The min ac power for plant 2 table 2 in a day is {plant2_ac_min_power}')

 **F.Which inverter (source_key) has produced maximum DC/AC power?**

For DC_POWER

In [ ]:
df1['DC_POWER']

In [ ]:
df1['DC_POWER'].max()

In [ ]:
df1['DC_POWER']==df1['DC_POWER'].max()

In [ ]:
df1[df1['DC_POWER']==df1['DC_POWER'].max()]['SOURCE_KEY']

In [ ]:
plant2_df1['DC_POWER'].max()

In [ ]:
plant2_df1[plant2_df1['DC_POWER']==plant2_df1['DC_POWER'].max()]['SOURCE_KEY']

For AC_POWER

In [ ]:
df1['AC_POWER']

In [ ]:
df1['AC_POWER'].max()

In [ ]:
df1['AC_POWER']==df1['AC_POWER'].max()

In [ ]:
df1[df1['AC_POWER']==df1['AC_POWER'].max()]['SOURCE_KEY']

In [ ]:
plant2_df1['AC_POWER'].max()

In [ ]:
plant2_df1[plant2_df1['AC_POWER']==plant2_df1['AC_POWER'].max()]['SOURCE_KEY']

**G. Rank the inverters based on the DC/AC power they produce**

In [ ]:
#all invertors are ranked individually
df1["Rank"] = df1["AC_POWER"].rank(method ='first') 
df1

In [ ]:
df1["Rank"] = df1["DC_POWER"].rank(method ='first') 
df1

In [ ]:
plant2_df1["Rank"] = plant2_df1["AC_POWER"].rank(method ='first') 
plant2_df1

In [ ]:
plant2_df1["Rank"] = plant2_df1["DC_POWER"].rank(method ='first') 
plant2_df1

**H. Is there any missing data?**

In [ ]:
print(df1['SOURCE_KEY'].value_counts())
print(df1['DATE'].value_counts())

In [ ]:
print(df2['SOURCE_KEY'].value_counts())
print(df2['DATE'].value_counts())

In [ ]:
print(plant2_df1['SOURCE_KEY'].value_counts())
print(plant2_df1['DATE'].value_counts())

In [ ]:
plant2_df2['SOURCE_KEY'].value_counts()
plant2_df2['DATE'].value_counts()

This shows that there were many values which were null

Also the null values are needed to be checked

In [ ]:
df1.isnull().any().any()

here false means no value is missing

In [ ]:
df2.isnull().any().any()

In [ ]:
plant2_df1.isnull().any().any()

In [ ]:
plant2_df2.isnull().any().any()

since it shows there are no null values we can determine the columns having null values

In [ ]:
df1.loc[:, df1.isnull().any()].columns

In [ ]:
df1.dropna()

**Regards
Task Completed by-
ERICA SHARMA**