In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

from subprocess import check_output
print(check_output(["ls", "../input"]).decode("utf8"))

# Any results you write to the current directory are saved as output.

Import data, define a variable and a function - both of which will be used to get age

In [ ]:
import pandas as pd
import datetime as dt

end = pd.to_datetime('2016-08-21').date()
def correct_age(x):
    if  x < 0:
        x = x + 100
    return x

df = pd.read_csv('../input/athletes.csv', parse_dates=[4])

Add a column with total number of medals won; add a column with age

In [ ]:
df['medals'] = df['gold'] + df['silver'] + df['bronze']
df['age'] = end - pd.to_datetime(df.dob)
df['age'] = df['age'].astype('<m8[Y]')
df['age'] = df.age.apply(correct_age)

check new columns exist

In [ ]:
df.head()

create new dataframes for male and female  athletes who won at least one medal

In [ ]:
df_m = df.copy(deep=True)
df_m = df_m.drop(df_m[df_m.sex!='male'].index)
df_m_nz = df_m.copy(deep=True)
df_m_nz = df_m_nz.drop(df_m_nz[df_m_nz.medals==0].index) # male athletes who won at least one medal
df_m_z = df_m.copy(deep=True)
df_m_z = df_m_z.drop(df_m_z[df_m_z.medals!=0].index) # male athletes who did not win any medals

df_f = df.copy(deep=True)
df_f = df_f.drop(df_f[df_f.sex!='female'].index)
df_f_nz = df_f.copy(deep=True)
df_f_nz = df_f_nz.drop(df_f_nz[df_f_nz.medals==0].index) # female athletes who won at least one medal
df_f_z = df_f.copy(deep=True)
df_f_z = df_f_z.drop(df_f_z[df_f_z.medals!=0].index) # female athletes who did not win any medals

what percentage of male athletes won at least one medal?

In [ ]:
total_male_athletes = len(df_m.index)
num_male_medal = len(df_m_nz.index)
percent_m_winners = round((num_male_medal/total_male_athletes)*100,1)
percent_m_winners

what percentage of female athletes won at least one medal?

In [ ]:
total_female_athletes = len(df_f.index)
num_female_medal = len(df_f_nz.index)
percent_f_winners = round((num_female_medal/total_female_athletes)*100,1)
percent_f_winners

In [ ]:
How many athletes took part in the games?

In [ ]:
total_male_athletes

In [ ]:
How many female athletes took part?

In [ ]:
total_female_athletes

get the nationalities of all male athletes

In [ ]:
male_nationalities_list = df_m.nationality.unique()

get the nationalities of all female athletes

In [ ]:
female_nationalities_list = df_f.nationality.unique()

what countries sent all male teams?

In [ ]:
print(list(set(male_nationalities_list)-set(female_nationalities_list)))

In [ ]:
what countries sent all female teams?

In [ ]:
print(list(set(female_nationalities_list)-set(male_nationalities_list)))

To put the above in context, I don't believe the above countries were practising sexist selection policies, they are all small nations or in the case of Iraq a nation that has suffered from political instability and war.

if you are a male athlete what sports give you the best chance of winning multiple medals?

In [ ]:
top_m = df_m[df_m.medals>=3]
top_m_sports = top_m.groupby('sport').size()
print(top_m_sports.sort_values(ascending=False))

In [ ]:
if you are a female athlete what sports give you the best chance of winning multiple medals?

In [ ]:
top_f = df_f[df_f.medals>=3]
top_f_sports = top_f.groupby('sport').size()
print(top_f_sports.sort_values(ascending=False))

The above shows that for both male and female athletes, aquatics is the best sport to win 3 or more medals.

is there a difference in the mean age of male atheletes, competing in aquatics, who won
medals and those who did not win any medals

In [ ]:
sports_m_z_age = df_m_z['age'].groupby(df_m_z['sport'])
sports_m_nz_age = df_m_nz['age'].groupby(df_m_nz['sport'])
sports_m_z_age_mean = sports_m_z_age.mean()
sports_m_nz_age_mean = sports_m_nz_age.mean()
print(sports_m_z_age_mean['aquatics'])
print(sports_m_nz_age_mean['aquatics'])

For male athletes competing in aquatic sports it seems that experience slightly outperforms youth - so the average age of those who won medals is slightly higher than those who did not

Repeating the above for female athletes

In [ ]:
sports_f_z_age = df_f_z['age'].groupby(df_f_z['sport'])
sports_f_nz_age = df_f_nz['age'].groupby(df_f_nz['sport'])
sports_f_z_age_mean = sports_f_z_age.mean()
sports_f_nz_age_mean = sports_f_nz_age.mean()
print(sports_f_z_age_mean['aquatics'])
print(sports_f_nz_age_mean['aquatics'])

The same is true for female athletes, also the average age for female athletes in aquatics is 1 or 2 years less than for males.

Repeating the above for athletics, first men

In [ ]:
print(sports_m_z_age_mean['athletics'])
print(sports_m_nz_age_mean['athletics'])

The average age of male athletics medal winners is higher than for aquatics and there is no significant difference between the average age of medal winners and those who did not win any medals

Repeating for female athletes

In [ ]:
print(sports_f_z_age_mean['athletics'])
print(sports_f_nz_age_mean['athletics'])

The same is true for female athletes, also there is no significant difference between the average ages of female and male athletes competing in athletics

Lastly, the same for gymnastics, first males

In [ ]:
print(sports_m_z_age_mean['gymnastics'])
print(sports_m_nz_age_mean['gymnastics'])

Then females

In [ ]:
print(sports_f_z_age_mean['gymnastics'])
print(sports_f_nz_age_mean['gymnastics'])

Again there is a significant difference in average ages for females and males, in gymnastics the female medal winners are significantly younger than the male medal winners. But there is no significant difference in average ages between those who won medals and those who did not.