# ****Both a cultural hub and an economic powerhouse, Bangalore is one of the fastest-growing cities in India. Often referred to as the Silicon Valley of the country, the city is full of internationally renowned entrepreneurs who have moved to this buzzing metropolis from all corners of the globe, bringing with them a diversity thatâ€™s also culinary.

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current sessio

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("\Users\ANSHI RAJ\Documents\zomato.csv[1]")

In [ ]:
df.head()

****First we will know the dimensions of the zomato dataset:

In [ ]:
df.size

In [ ]:
df.shape

Describe the dataset

In [ ]:
df.describe

****Check the data information

In [ ]:
df.info

**Handling the missing values **

Check the number of nulls/missing values in the dataset

In [ ]:
df.isna().sum()

Making dish_liked null values to zero

In [ ]:
df = df[df.dish_liked.isna()==False]

In [ ]:
df.isna().sum()

**List the name of columns**

In [ ]:
df.columns

Deleting the rows that are not required

In [ ]:
df = df.drop(["url","votes","rest_type","listed_in(type)"],axis=1)

In [ ]:
df.head()

**Renaming Columns**

In [ ]:
df.rename(columns={'approx_cost(for two people)':'avg_cost','listed_in(type)':'listed type'},in place=True)

In [ ]:
df.columns

In [ ]:
df.head()

In [ ]:
df.info()

**Transformations**

Converting column avg_cost to float type

In [ ]:
df['avg_cost']=df['avg_cost'].astype(str)
df['avg_cost']=df['avg_cost'].apply(lambda x:x.replace('','') )
df['avg_cost']=df[avg_cost'].astype(float)
                  df.info()

**Taking the list of columns with rating >5**

In [ ]:
newdf_rate=df[['name','rate']].groupby(['rate'])
newdf_rate=newdf_rate.filter(lambda x:x.mean()>5)
newdf_rate=newdf_rate.sort_values(by=['rate'])
newdf_rate

**Visualisation & Exploratory data analysis**

In [ ]:
df.name.value_counts().head()

**Diametric Representation**

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
fig=plt.figure(figsize=(10,5))
ax=df.name.value_counts()[:20].plot(kind='bar')
plt.xlabel("Restaurant Name")
plt.ylabel("No. of Restaurants")
plt.title("Restaurant Names vs No. of Locations")

**Online vs Offline Orders**

In [ ]:
df.online_order.value_counts()

Plotting on graph Online vs Offline orders

In [ ]:
fig = plt.figure(figsize=(10,5))
ax = df.online_order.value_counts().plot(kind='bar')
plt.xlabel("Online/Offline Orders")
plt.ylabel("Count")
plt.title("Online/Offline Orders vs Count")

No. of restaurants that provide table booking

In [ ]:
df.book_table.value_counts()

* Plotting Book Table facility counts

In [ ]:
fig = plt.figure(figsize=(10,5))
ax = df.book_table.value_counts().plot(kind='bar')
plt.xlabel("Book Table facility")
plt.ylabel("Count")
plt.title("Book Table facility vs Count")

****Plot location with highest no. of restaurants

In [ ]:
df.location.value_counts()

In [ ]:
fig = plt.figure(figsize=(10,10))
ax = df.location.value_counts()[:15].plot(kind='pie')
plt.title("Location with highest no. of restaurants")
plt.legend()

In [ ]:
df.cuisines.value_counts()

In [ ]:
fig = plt.figure(figsize=(17,15))
ax = df.cuisines.value_counts().plot(kind='bar')
plt.xlabel("Cuisine types")
plt.ylabel("Count")
plt.title("Cuisine Types vs Count")

Showing in percentage Restaurants Types

In [ ]:
fig = plt.figure(figsize=(10,10))
axis = df.cuisines.value_counts()[:15].plot(kind='pie')
plt.title("Cuisine types")
plt.legend()

In [ ]:
df.cuisines.value_counts().head(5)

In [ ]:
newdf_rate = df[['name','rate']].groupby(['rate'])
newdf_rate = newdf_rate.sort_values(by = ['rate'])
newdf_rate.show

**We this I'm concluding the notebook.I tried to incorporate the various attributes of analysing the dataset of Zomato-Bangalore-Restaurants.Further suggestions/recommendations would be highly appreciated.Since I'm a learner and just stepped into this environment of data science so I would be highly obliged if the viewers find this useful.. **