In [ ]:
# Reference: DATAİ TEAM - https://www.dataiteam.com/ - https://www.kaggle.com/kanncaa1

# Language Python 3 
# Libraries
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # visualization tool
import seaborn as sns # visualization tool
import os             # System 

# Add data is in the upper right. Select " Pokemon- Weedle's Cave " dataset.
## Sağ üstte Add data bölümünden " Pokemon- Weedle's Cave " veri setini yüklüyoruz.


# This shows you that what datas there are in your directory,
## Klasörümüzde hangi veriset'leri yüklü olduğunu görüntüler.
for dirname, _, filenames in os.walk("/kaggle/input"):  
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Load Data

In [ ]:
# Read data, way is like this /kaggle/input/dataset name/data name
data = pd.read_csv('/kaggle/input/pokemon-challenge/pokemon.csv')
data.head()

In [ ]:
# Find missing and wrong data
data.info()

In [ ]:
data.corr()

In [ ]:
# Correlation map
# figsize x axis = 16 y axis = 16, data is data.corr(), annot is numbers in small square, linewidths is space between squares, fmt is length of decimal
f,ax = plt.subplots(figsize = (16,16))
sns.heatmap(data.corr(), annot = True, linewidths = .5, fmt= '.1g' )

In [ ]:
data.head(10)

In [ ]:
data.columns

# <font color ="blue">1. GENERAL PYTHON <font/>

<b> <font size="+2">DICTIONARY<font/>

*     Dictionary is easy and fast
*     Has two parameters key and value as dict = {'England' = 'London'}
    
 Lets Use Some Properties

In [ ]:
# Create dictionary, find keys and values.
dictionary = {'Turkey':'Ankara', 'Japan':'Tokyo', 'Canada':'Ottowa'}
print(dictionary.keys())
print(dictionary.values())

In [ ]:
# Update, Add, Remove, Check and Remove All
dictionary['Japan'] = 'New-Tokyo'            # Update
print(dictionary)
dictionary['Ukraine'] = 'Kiev'               # Add
print(dictionary)
del dictionary['Turkey']                     # Remove
print(dictionary)
print('Spain' in dictionary)                 # Check
dictionary.clear()                          # Remove All
print(dictionary)

# İf you run it again that you will have an error because dictionary is deleted. So Run All from Above

<b> <font size="+2">WHILE AND FOR LOOPS<font/>

In [ ]:
# İf i is bigger than 7, quit from loop.
i = 0
while i <=7 :
    print('i :', i)
    i += 1
print(i,'is bigger than 7 so Loop done ')

In [ ]:
# Write values of list
List = ['A','B','C','D','E','F','G']
for i in List:
    print('i is :', i)
    
# A's index is 0, B's index is 1, ..., G's index is 6
for index, value in enumerate(List):
    print(index, ':', value)

# Write key and values of dictionary
dictionary = {'Turkey':'Ankara', 'Japan':'Tokyo', 'Canada':'Ottowa'}
for key, value in dictionary.items():
    print(key, ":", value)

<b> <font size="+2">PANDAS<font/>
* Pandas is very powerful for tables.

In [ ]:
# Read CSV (Comma Seperated Values)
data = pd.read_csv('/kaggle/input/pokemon-challenge/pokemon.csv')

In [ ]:
# Find Type of Data
series = data['Attack']
print(type(series))
df = data[['Defense']]
print(type(df))

In [ ]:
# Find Pikachu values
for i, j in enumerate(data.Name): # i is index, j is values of Name column
    if j == 'Pikachu':
        print(i)                 # Found that Pikachu index is 30
# Get values of index 30
data.loc[30]                     # That gives us Pikachu values Pika Pika

**Filtering**

In [ ]:
#1# 3 pokemon has more than 200 defense
x = data['Defense']>200   
data[x]

In [ ]:
#2# 2 Pokemon has Defense more than 200 and attack more than 100
data[(data['Defense']>200) & (data['Attack']>100)]

In [ ]:
#3# Sum of Attack Column items
data['Attack'].count()

<b> <font size="+2">MATPLOTLIB<font/>

This is a library of Python that help us to plot data. Line, Scatter, Histogram and Boxplot are some basic plots.
* Line plot is better when x axis is time.
* Scatter is better when there is colleration between two variables
* Histogram is better when we need to see distribution of numerical data
* Boxplot is better when we need to see distribution of numerical data
* Customization: Colors, Labels, Thickness of Line, Opacity, Grid, Figsize, ticks of axis and Linestyle

In [ ]:
# Line Plot
# color = color, label = label, linewidth = width of line, alpha = opacity, grid = grid, linestyle = sytle of line
data.Speed.plot(kind = 'line', color = 'g', label = 'Speed', linewidth = 1, alpha = .5, grid = True, linestyle = ':')
data.Defense.plot( color = 'r', label = 'Defense', linewidth = 1, alpha = .5, grid = True, linestyle = '-.' )
plt.legend(loc = 'upper right')                                                                                             # legend = puts label into plot
plt.xlabel('x axis')                                                                                                        # label = name of label
plt.ylabel('y axis')
plt.title('Line Plot for Speed & Defense')                                                                                  # title = title of plot
plt.show()

In [ ]:
# Scatter Plot
# x = attack, y = defense
data.plot(kind = 'scatter', x = 'Attack', y = 'Defense', alpha = .5, color = 'red')
plt.xlabel('Attack')
plt.ylabel('Defense')
plt.title('Scatter Plot Attack & Defens')

In [ ]:
# Histogram
data.Speed.plot(kind = 'hist', bins = 50, figsize = (8,8))
plt.show()

In [ ]:
# clf() = cleans it up again you can start a fresh
data.Speed.plot(kind = 'hist', bins = 50)
plt.clf()

In [ ]:
# Boxplot 
data.plot(kind = 'box', figsize = (22,8))    # Good way to investigate Standard deviation, Median, Mean

# <font color ="blue">2. Python DataScince Tool Box <font/>

**User Defined Function**
* > Tuple : sequence of immutable python objects.
> cant modify values
> tuple uses paranthesis like tuble = (1,2,3)
> unpack tuple into several variables like a,b,c = tuple

In [ ]:
def tuple_ex():
    t = (1,2,3) # t is a tuple
    return t
a,b,c = tuple_ex()
print(a,b,c)

> Scope: 
* global: defined main body in script
* local: defined in a function
* built in scope: names in predefined built in scope module such as print, len

In [ ]:
x = 2               # global x variable
def f():
    x = 3         # local x variable
    return x
print(x)        # x = 2 global scope
print(f())     # x = 3 local scope

In [ ]:
# İf there is no local scope x
x = 5
def f():
    y = 2*x
    return y
print(f())
# Firstly local scope searched and then global searched.
# İf there are both, python choose local.

> Nested Function
* İt is located inside of Function

In [ ]:
def square():
    def add():
        x = 2
        y = 3
        z = x + y
        return z
    return add()**2
print(square())

> DEFAULT AND FLEXİBLE ARGUMENTS
* Default Example: def f(a,b=1):
* Flexible Example: def f(*args): and def f(**kwargs):

> DEFAULT

In [ ]:
# Default
def f(a, b = 1, c = 2):
    y = a + b + c
    return y
print(f(5))              # a = 5 b = default (1) c = default (2)
print(f(5,4,3))          # a = 5 b = 4 c = 3

> FLEXİBLE *ARGS

In [ ]:
# Flexible *args
def f(*args):
    for i in args:
        print(i)
f(1)
print("")
f(1,2,3,4)
# Flexible arguments **kwargs that is dictionary
def f (**kwargs):
    for key, value in kwargs.items():
        print(key, "", value)
f(country='spain', capital = 'madrid', population = 123456)

> LAMBDA

In [ ]:
# Lambda Function
square = lambda x: x**2   # we have x, result is x ** 2
print(square(3))
tot = lambda x,y,z:x+y+z  # we have x,y,z result is x+y+z
print(tot(1,2,3))

**ANONYMOUS FUNCTİON**

Smiliar to lambda, it can take more than one arguments
* map(func,seq): applies a function to all the items in a list

> MAP

In [ ]:
num_list = [1,2,3]
y = map(lambda x:x**2,num_list)
print(list(y))

**ITERATORS**

* You can use list, strings and dictionaries
* next() shows you that next item
* (*) shows you that remain items

> ITERATORS

In [ ]:
# Iteration Example
country = "canada"
it = iter(country)
print(next(it))       # Next iteration
print(*it)            # Remain iteration

> ZIP

In [ ]:
# zip():zip lists
list1 = [1,2,3,4]
list2 = [5,6,7,8]
z = zip(list1,list2)
z_list = list(z)           # Should make it list
print(z_list)

> UNZIP

In [ ]:
# unzip
un_zip = zip(*z_list)
un_list1, un_list2 = list(un_zip)
print(un_list1)
print(un_list2)
print(type(un_list1))

**LIST COMPREHENSİON**

*  One of the most important topic of Kernel

* We can make it one line coe that is list comprehension

In [ ]:
num1 = [1,2,3]
num2 = [i+1 for i in num1]
print(num2)

In [ ]:
num1 = [5,10,15]
num2 = [i**2 if i == 10 else i-5 if i<7 else i+5 for i in num1]
print(num2)

In [ ]:
# lets return pokemon csv and make one more list comprehension example
# lets classify pokemons whether they have high or low speed. Our threshold is average speed.
threshold = sum(data.Speed)/len(data.Speed)   # threshold founds 68.2775
data["speed_level"] = ["high" if i > threshold else "low" for i in data.Speed]
data.loc[:10,["speed_level","Speed"]]  # by loc you can choose what you need, will learn more deep

Up to Now, We have learned
* User defined function
* Scope
* Default and Flexible Arguments
* Lambda Function
* Anonymous Function
* Iterators
* List Comprehension

# <font color ="blue">3. CLEANING DATA <font/>

**DIAGNOSE DATA FOR CLEANING**

* Control the type of each column
* Control the column name inconsistency like upper-lower or space between words
* Control the missing data and manipulate or remove
* Control the language

We ll use head, tail, columns, shaper and info methods to diagnose data

In [ ]:
data = pd.read_csv('/kaggle/input/pokemon-challenge/pokemon.csv')
data.head()                 # shows first 5 rows

In [ ]:
# tail shows the last 5 rows
data.tail()

In [ ]:
# Shows columns name
data.columns

In [ ]:
# Shape gives number of rows and columns in a tuble
data.shape

In [ ]:
# Info gives data type, number of sample or row, number of feature or feature types and memory usage
data.info()

**EXPLORATORY DATA ANALYSIS**

value_counts(): Frequency counts
outliers: the value that is considerably higher or lower from rest of the data

* Q1 is %25 and Q3 is %75
* IQR is Q3 - Q1, We will use describe() method includes:
* count: number of entries
* mean: avarage of entries
* std: standard deviation
* min: minimum entry
* %25, %50, %75 first, second and third quantile
* max: maximum entry
* median: middle item of sorted sequence
* trim_mean: 10% is clipped from the beginning and end of the data then found mean.
* avarage: Weighted mean
* wquantiles.median: weighted median
* robust.scale.mad: median Absolute Deviation

What is quantile?

* 1,4,5,6,8,9,11,12,13,14,15,16,17
* The median is middle item that is 11.
* The lower quartile is between firt item and median ( 1,4,5,6,8,9,11) median of this is 6
* The upper quartile, median and biggest item (11,12,13,14,15,16,17) median of this is 14

In [ ]:
# For example lets look frequency of pokemom types
print(data['Type 1'].value_counts(dropna = False))    # if there are nan values that also be counted, Type 1 is a column name
# As it can be seen below there are 112 water pokemon or 70 grass pokemon

In [ ]:
# For example max HP is 255 or min defense is 5
data.describe() #ignore null entries

**VISUAL EXPLORATORY DATA ANALYSIS**

* Box plots: visualize basic statistics like outliers, min/max or quantiles

In [ ]:
# For example: compare attack of pokemons that are legendary  or not
# Black line at top & bottom are max & min
# Blue line at top & bottom is 75% & 25%
# Green line is median (50%)
# There are no outliers
data.boxplot(column = 'Attack', by = 'Legendary')

**TİDY DATA**

We tidy data with melt(). Describing melt is confusing. Therefore lets make example to understand it.

In [ ]:
# Firstly I create new data from pokemons data to explain melt nore easily.
data_new = data.head()    # I only take 5 rows into new data
data_new

In [ ]:
# id_vars = what we do not wish to melt
# value_vars = what we want to melt
# We can see columns and items by this method.
melted = pd.melt(frame = data_new, id_vars = 'Name', value_vars = ['Attack','Defense'])
melted

**PIVOTING DATA**

Reverse of Melting

In [ ]:
melted.pivot(index = 'Name', columns = 'variable', values = 'value')

**CONCATENATING DATA**

We can concatenate two dataframe

In [ ]:
# Firstly lets create 2 dataframe
data1 = data.head()
data2 = data.tail()
conc_data_row = pd.concat([data1,data2], axis = 0, ignore_index = True) # axis 0: adds df in rows,
conc_data_row

In [ ]:
data1 = data['Attack'].head()
data2 = data['Defense'].head()
conc_data_col = pd.concat([data1,data2],axis = 1) # axis 1: adds df in cols,
conc_data_col

**DATA TYPES**

There ara 5 basic data types: String(Object), Integer, Float, Categorical and Boolean
We can make conversion data types eachother

Why is Category important:
* Smaller in Memory
* Can be utilized for analysis especially for sklearn

In [ ]:
data.dtypes

In [ ]:
# Lets Convert Object(str) to categorical and int to float
data['Type 1'] = data['Type 1'].astype('category')
data['Speed'] = data['Speed'].astype('float')
data.dtypes

**MISSING DATA and TESTING WITH ASSERT**

What we can do for missing data:

* leave as is
* drop them with dropna()
* fill missing value with fillna()
* fill missing values with test statistics like mean
    
    Asser statement: check that you can turn on or turn off when you are done with yout testing  of the program

In [ ]:
# Lets look at does pokemon data have nan value
# As you can see there are 800 entries. However Type 2 has 414 non-null object so it has 386 null object
data.info()

In [ ]:
# Lets check Type 2
data['Type 2'].value_counts(dropna = False)
# As you can see, there are 386 NAN value

In [ ]:
# Lets drop nan values
data1=data   # also we will use data to fill missing value so I assign it to data1 variable
data1["Type 2"].dropna(inplace = True)  # inplace = True means we do not assign it to new variable. Changes automatically assigned to data
# So does it work ?

In [ ]:
#  Lets check with assert statement
# Assert statement:
assert 1==1 # return nothing because it is true

In [ ]:
# In order to run all code, we need to make this line comment
# assert 1==2 # return error because it is false

In [ ]:
data["Type 2"].fillna('empty',inplace = True)

In [ ]:
assert  data['Type 2'].notnull().all() # returns nothing because we do not have nan values

In [ ]:
# # With assert statement we can check a lot of thing. For example
# assert data.columns[1] == 'Name'
# assert data.Speed.dtypes == np.int

In this part, you learn:
* Diagnose data for cleaning
* Exploratory data analysis
* Visual exploratory data analysis
* Tidy data
* Pivoting data
* Concatenating data
* Data types
* Missing data and testing with assert

<a id="25"></a> <br>
# 4. PANDAS FOUNDATION

<a id="26"></a> <br>
### REVİEW of PANDAS
As you notice, I do not give all idea in a same time. Although, we learn some basics of pandas, we will go deeper in pandas.
* single column = series
* NaN = not a number
* dataframe.values = numpy

<a id="27"></a> <br>
### BUILDING DATA FRAMES FROM SCRATCH
* We can build data frames from csv as we did earlier.
* Also we can build dataframe from dictionaries
    * zip() method: This function returns a list of tuples, where the i-th tuple contains the i-th element from each of the argument sequences or iterables.
* Adding new column
* Broadcasting: Create new column and assign a value to entire column

In [ ]:
# Dataframes from dictionary
country = ['Spain', 'France']             # country is value of dictionary
population = ['11', '12']                 # population is value of dictionary
list_label = ['country', 'population']   # list_label is key of dictionary
list_col = [country, population]         # values put in a list
zipped = list(zip(list_label, list_col)) # this is obligation before convert to dictionary
data_dict = dict(zipped)                 # converted to dictionary
df = pd.DataFrame(data_dict)             
df

In [ ]:
# Add New Columns
df['capital'] = ['madrid', 'paris']
df

In [ ]:
# Broadcasting
df['income'] = 0 
df

**VISUAL EXPLORATORY DATA ANALYSIS**

* Plot
* Subplot
* Histogram:
    * bins: number of bins
    * range: min and max values of bins
    * normed(boolean): normalize or not
    * cumulative(boolean): compute cumulative distribution

In [ ]:
# Plotting all data
data1 = data.loc[:,['Attack','Defense','Speed']]
data1.plot()

In [ ]:
# Subplots, see all in different frame
data1.plot(subplots = True)
plt.show()

In [ ]:
# Scatter plot
data1.plot(kind = 'scatter', x = 'Attack', y = 'Defense')
plt.show()

In [ ]:
# hist plot
data1.plot(kind= 'hist', y = 'Defense', bins =50, range = (0,250))

In [ ]:
# histogram subplot with non cumulative and cumulative
fig, axes = plt.subplots(nrows=2,ncols=1)
data1.plot(kind = "hist",y = "Defense",bins = 50,range= (0,250),ax = axes[0])                                    
data1.plot(kind = "hist",y = "Defense",bins = 50,range= (0,250),ax = axes[1],cumulative = True)
plt.savefig('graph.png')
plt

**STATISTICAL EXPLORATORY DATA ANALYSIS**

I already explained it at previous parts. However lets look at one more times to learn better.

* count: number of entries
* mean:  average of entries
* std: standart deviation
* min: minimum entry
* 25%: first quantile
* 50%: median or second quantile
* 75%: third quantile
* max: maximum entry
* trim_mean: trimmered mean
* IQR: %75 - %25 ( 3. quantile - 1. quantile ) ~= median
* rsmad: Robust Scale Median Absolute Deviation

In [ ]:
data.describe()

In [ ]:
# trim_mean
from scipy.stats import trim_mean   # we should use this library
trim_mean = trim_mean(data['Attack'],0.1)  # Sorted Attack values, %10 first and last %10 values removed. Remove outliers
trim_mean            
# data['Attack'].mean()  is  79.00125

In [ ]:
# IQR and rsmad
from statsmodels import robust
std = data['Attack'].std()
IQR = data['Attack'].quantile(0.75) - data['Attack'].quantile(0.25)
rsmad = robust.scale.mad(data['Attack'])
print('IQR :', IQR)
print('RSMAD :', rsmad)

**INDEXING PANDAS TIME SERIES**

* datetime = object
* parse_dates(boolean): Transform date to ISO 8601 (yyyy--mm--dd hh:mm:ss) format

In [ ]:
time_list = ['1992-03-08', '1992-04-12']
print(type(time_list[1]))   # datetime is string however we want to make it datetime object
datetime_object = pd.to_datetime(time_list)
print(type(datetime_object))

In [ ]:
# close warning
import warnings
warnings.filterwarnings('ignore')
# Lets add a time list to Pokemon data
data2 = data.head()
date_list = ['1992-01-10', '1992-02-10','1992-03-10','1993-03-15','1993-03-16']
datetime_object = pd.to_datetime(date_list)
data2['date'] = datetime_object
# Lets set date as index
data2 = data2.set_index('date')
data2

In [ ]:
print(data2.loc['1993-03-16'])
print(data2.loc['1992-03-10':'1993-03-16'])

**RESAMPLİNG PANDAS TİME SERİES**

* Resampling: statistical method over different time intervals
    * Needs string to specify frequency lik 'M' = month or 'A'= year
* Downsampling: reduce date time rows to slower frequency like from daily to weekly
* Upsampling: şncrease date time rows to faster frequency like from daily to hourly
* Interpolate: Interpolate values according to different methods like 'linear', 'time, or 'index'
    * https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.interpolate.html

In [ ]:
# We will use data2 that we create at previous part
data2.resample('A').mean() # A is year

In [ ]:
# Lets resample with month
data2.resample('M').mean() # M is month
# There are lots of nan because data2 doesnt include all months

In [ ]:
# In real life(data is real. Not created from us like data2) we can solve this problem with interpolate
# We can interpolate from first value
data2.resample("M").first().interpolate("ffill")

In [ ]:
data2.resample('M').mean().interpolate('linear')

**MANIPULATING DATA FRAMES WITH PANDAS**

**INDEXING DATA FRAMES**

* Indexing using square brackets
* Using column attribute and row label
* Using loc accessor
* Selecting only some columns

In [ ]:
# read data
data = pd.read_csv('/kaggle/input/pokemon-challenge/pokemon.csv')
data = data.set_index('#')
data.head()

In [ ]:
# Indexing using square brackets
data['HP'][1]    # show first value of HP column values

In [ ]:
# Using column attribute and row label
data.HP[1]      # this is also shows same result

In [ ]:
# Using only loc
data.loc[1] # this shows first row

In [ ]:
# using loc accessor
data.loc[1,['HP']] # this shows first row's Hp value

In [ ]:
# Selecting only some columns
data[['HP', 'Attack']]

**SLICING DATA FRAME**

* Difference between selecting columns
    * Series and data frames
* Slicing and indexing series
* Reverse slicing
* From something to end

In [ ]:
# Difference between selecting columns: series and dataframes
print(type(data['HP']))      # Series
print(type(data[['HP']]))    # DataFrame

In [ ]:
# Slicing and indexing series
data.loc[1:10,"HP":"Defense"] # 10 and defense are inclusive

In [ ]:
# Reverse slicing
data.loc[10:1:-1,"HP":"Defense"]

In [ ]:
# From something to end
data.loc[1:10,"Speed":]

**FILTERING DATA FRAMES**

Creating boolean series to filtering columns

In [ ]:
# Creating boolean series
boolean = data.HP > 200
data[boolean]

In [ ]:
# Combining filters
first_filter = data.HP > 150
second_filter = data.Speed > 35
data[first_filter & second_filter]

In [ ]:
# Filtering column based others
data.HP[data.Speed < 15]

**TRANSFORMING DATA**

* Plain python functions
* Lambda function: to apply arbitrary python function to every element
* Defining column using other coolumns

In [ ]:
# Plain python functions
def div(n):
    return n/2
data.HP.apply(div)

In [ ]:
# Or we can use lambda function
data.HP.apply(lambda n : n/2)

In [ ]:
# Defining column using other columns
data["total_power"] = data.Attack + data.Defense
data.head()

**INDEX OBJECTS AND LABELED DATA**

index:squence of label

In [ ]:
# our index name is this:
print(data.index.name)
# lets change it
data.index.name = "index_name"
data.head()

In [ ]:
# Overwrite index
# if we want to modify index we need to change all of them.
data.head()
# first copy of our data to data3 then change index
data3 = data.copy()
# lets make index start from 100. It is not remarkable change but it is just an example
data3.index = range(100,900,1)
data3.head()

In [ ]:
# We can make one of the column as index. I actually did it at the beggining of manipulating data frames with pandas section
# It was like this
# data = data.set_index("#")
# data.index = data['#']

**HIERARCHICAL INDEXING**

* Setting indexing

In [ ]:
# lets read data frame one more time to start from beggining
data = pd.read_csv('/kaggle/input/pokemon-challenge/pokemon.csv')
data.head()
# As you can see there is index. However we want to ser one or more column to be index

In [ ]:
# Setting index : type 1 is outer type 2 is inner index
data1 = data.set_index(["Type 1", "Type 2"])
data1.head(100)
# data1.loc["Fire","Flying"] # how to use indexes

**PIVOTING DATAFRAMES**

* pivoting: reshape tool

In [ ]:
import pandas as pd
dic = {"treatment":["A","A","B","B"], "gender":["F","M","F","M"],"response":[10,45,5,9],"age":[15,4,72,65]}
df = pd.DataFrame(dic)
df

In [ ]:
# pivoting
df.pivot(index="treatment", columns = "gender", values = "response")

**STACKING and UNSTACKING DATAFRAME**

* deal with multi label indexes
* level: position of unstacked index
* swaplevel: change inner and outer level index position

In [ ]:
df1 = df.set_index(["treatment","gender"])
df1
# lets unstack it

In [ ]:
# level determines indexes
df1.unstack(level = 0)

In [ ]:
df1.unstack(level = 1)

In [ ]:
# change inner and outer level index position
df2 = df1.swaplevel(0,1)
df2

**MELTING DATA FRAMES**

* Reverse of pivoting

In [ ]:
df

In [ ]:
# df.pivot(index = "treatment", columns = "gender", values = "response")
pd.melt(df, id_vars = "treatment", value_vars = ["age","response"])

**CATEGORICALS AND GROUPBY**

In [ ]:
# We will use df
df

In [ ]:
# According to treatment take means of other features
df.groupby("treatment").mean()  # mean is aggregation / reduction method
# there are other methods like sum, std, max or min

In [ ]:
# We can only choose one of the feature
df.groupby("treatment").age.max()

In [ ]:
# Or we can choose multiple features
df.groupby("treatment")[["age","response"]].min()

In [ ]:
df.info()
# as you can see gender is object
# However if we use groupby, we can convert it categorical data.
# Because cetegorical data uses less memory, speed up operations like groupby
# df["gender"] = df["gender"].astype("category")
# df["treatment"] = df["treatment"].astype("category")
# df.info()

# CONCLUSION
Thank you for your votes and comments
<br> **MACHINE LEARNING ** https://www.kaggle.com/kanncaa1/machine-learning-tutorial-for-beginners/
<br> **DEEP LEARNING** https://www.kaggle.com/kanncaa1/deep-learning-tutorial-for-beginners
<br> **STATISTICAL LEARNING** https://www.kaggle.com/kanncaa1/statistical-learning-tutorial-for-beginners
<br>**If you have any question or suggest, I will be happy to hear it.**