In [ ]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

Importing Required Libraries

In [ ]:
df=pd.read_csv("../input/ipl-complete-dataset-20082020/IPL Ball-by-Ball 2008-2020.csv")

Importing the Dataset

In [ ]:
df.head()

Returns First Five Rows of a Dataset

In [ ]:
df.tail()

Returns Last Five Rows of a Dataset

In [ ]:
df.shape

Returns Number of Rows and Number of Columns

In [ ]:
df.columns

It returns the columns of the dataset.

In [ ]:
df.dtypes

3 of the columns are numeric while the other 5 are categorical which is seen by dtpes function.

In [ ]:
df.describe(include="all")

To Obtain Details like Mean,Frequency,Max etc....

In [ ]:
df.info()

Outputs the including index and column datatypes

In [ ]:
df.duplicated().sum()

It returns the number of duplicates

In [ ]:
df.isnull().sum()

Outputs the number of missing values of the datasets

In [ ]:
plt.subplot(221)

df['inning'].value_counts().plot(kind='bar', title='inning', figsize=(16,9))

plt.xticks(rotation=0)

plt.subplot(222)

df['over'].value_counts().plot(kind='bar', title='over')

plt.xticks(rotation=0)

plt.subplot(223)

df['ball'].value_counts().plot(kind='bar', title='ball')

plt.xticks(rotation=0)

plt.subplot(224)

df['batsman'].value_counts().plot(kind='bar', title='batsman')

plt.xticks(rotation=0)

plt.show()

**Observation :**  Review of IPL between inning ,over,ball,batsman . Here the subplot(221) means it consists of two Rows and two Columns.figsize returns the height and width of a figure.Title attribute returns the title of the figure.

In [ ]:
df.dropna(inplace=True)
df.head()

From this,we are getting the dataset by removing all the inconsistency present in it.

In [ ]:
df.iloc[:10,:3]

By using positional based indexing function iloc[:10,:3], we got the part of the dataset which is having 10 rows and 3 columns

In [ ]:
df.boxplot()

It outputs the distribution of a dataset on the basis of minimum ,maximum ,median,first quatrel,second quatrel

In [ ]:
sns.heatmap(df.isnull())

It plots the missing values and a heatmap using seaborn

In [ ]:
sns.distplot(df['extra_runs'])

Observation:Extra runs between 0 to 1.0 as highest density

In [ ]:
corr = df.corr()
sns.heatmap(corr, annot=True, square=True)
plt.yticks(rotation=2)
plt.show()

annot=True makes  Sure that the values of each cell appear on the chart and yticks sets the y-axis value

In [ ]:
df.hist(figsize=(10, 12), bins=50, xlabelsize=8, ylabelsize=8);

This plots a histogram with width as 10 and height as 12 bins represents the bars of histogram.bins can be changed as per our wish

In [ ]:
sns.relplot(x="extra_runs", y="batsman_runs", hue='batting_team', data=df)

**Observation:** The plot is more dense in range 0 to 1 below the batsman runs 0 to 1

In [ ]:
sns.factorplot("is_wicket",data=df,kind="count")

The is_wicket of 1 have highest count

In [ ]:
sns.set_palette("gist_rainbow_r")
sns.jointplot(x="extra_runs",y="total_runs",kind="hex",data=df)
plt.show

The highest extra_runs and between total_runs is 4

**Aim**:To explore the IPl complete Dataset in the years 2008 to 2020. 
**Conclusion:** 1.Finally this dataset tell us about the runs,batsman,wickets,extra runs,total runs etc..... 2.The IPl dataset can be analyzed using many more graph techniques and also for visualize than,as described in this notebook.