In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['kc_house_data.csv']

In [2]:
dataset = pd.read_csv("../input/kc_house_data.csv")

In [3]:
dataset.head()

           id             date     ...      sqft_living15  sqft_lot15
0  7129300520  20141013T000000     ...               1340        5650
1  6414100192  20141209T000000     ...               1690        7639
2  5631500400  20150225T000000     ...               2720        8062
3  2487200875  20141209T000000     ...               1360        5000
4  1954400510  20150218T000000     ...               1800        7503

[5 rows x 21 columns]

In [4]:
Y = dataset['price'].values
Y.shape
Y.shape[0]

21613

In [5]:
X = dataset.iloc[:,3:]
X.shape[1]

18

In [6]:
X.iloc[:,3:].values

array([[ 5.65000e+03,  1.00000e+00,  0.00000e+00, ..., -1.22257e+02,
         1.34000e+03,  5.65000e+03],
       [ 7.24200e+03,  2.00000e+00,  0.00000e+00, ..., -1.22319e+02,
         1.69000e+03,  7.63900e+03],
       [ 1.00000e+04,  1.00000e+00,  0.00000e+00, ..., -1.22233e+02,
         2.72000e+03,  8.06200e+03],
       ...,
       [ 1.35000e+03,  2.00000e+00,  0.00000e+00, ..., -1.22299e+02,
         1.02000e+03,  2.00700e+03],
       [ 2.38800e+03,  2.00000e+00,  0.00000e+00, ..., -1.22069e+02,
         1.41000e+03,  1.28700e+03],
       [ 1.07600e+03,  2.00000e+00,  0.00000e+00, ..., -1.22299e+02,
         1.02000e+03,  1.35700e+03]])

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [10]:
model = LinearRegression()

In [11]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [12]:
l = model.coef_
print(len(l))

18

In [13]:
model.intercept_

6643873.527913024

In [14]:
y_preds = model.predict(X_test)

In [15]:
acc = model.score(X_test,y_test)

In [18]:
print("Score :",round(acc*100,2))

Score : 70.12

In [19]:
from sklearn.metrics import r2_score

In [20]:
print(r2_score(y_test,y_preds))

0.7011904448878357