In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
data = pd.read_csv('/kaggle/input/pokemon-challenge/pokemon.csv')
data.head()

In [ ]:
data.info()

In [ ]:
data.corr()

In [ ]:

import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#correlation map
f,ax = plt.subplots(figsize=(10,10))
sns.heatmap(data.corr(), annot=True, linewidths=.5, fmt= '.1f',ax=ax)

In [ ]:
data.head()

In [ ]:
data.columns

In [ ]:
data.values[1]

In [ ]:
# Line Plot
# color = color, label = label, linewidth = width of line, alpha = opacity, grid = grid, linestyle = sytle of line
data.HP.plot(kind = 'line', color = 'g',label = 'HP',linewidth=1,alpha = 0.5,grid = True,linestyle = ':')
data.Attack.plot(color = 'r',label = 'Attack',linewidth=1, alpha = 0.5,grid = True,linestyle = '-')
plt.legend(loc='upper right')     # legend = puts label into plot
plt.xlabel('x axis')              # label = name of label
plt.ylabel('y axis')
plt.title('Line Plot')            # title = title of plot
plt.show()

In [ ]:
# Scatter Plot 
# x = attack, y = defense
data.plot(kind='scatter', x='Attack', y='Defense',alpha = 0.5,color = 'red')
plt.xlabel('Attack')              # label = name of label
plt.ylabel('Defence')
plt.title('Attack Defense Scatter Plot')

In [ ]:

# Histogram
# bins = number of bar in figure
data.Speed.plot(kind = 'hist',bins = 10,figsize = (5,5))
plt.show()

In [ ]:
# Histogram
# bins = number of bar in figure
data.Attack.plot(kind = 'hist',bins = 10,figsize = (5,5))
plt.show()

In [ ]:

#create dictionary and look its keys and values
dictionary = {'spain' : 'madrid','usa' : 'vegas'}
print(dictionary.keys())
print(dictionary.values())

In [ ]:

# Keys have to be immutable objects like string, boolean, float, integer or tubles
# List is not immutable
# Keys are unique
dictionary['spain'] = "barcelona"    # update existing entry
print(dictionary)
dictionary['france'] = "paris"       # Add new entry
print(dictionary)
del dictionary['spain']              # remove entry with key 'spain'
print(dictionary)
print('france' in dictionary)        # check include or not
dictionary.clear()                   # remove all entries in dict
print(dictionary)

In [ ]:

# In order to run all code you need to take comment this line
# del dictionary         # delete entire dictionary     
print(dictionary)

In [ ]:
####PANDAS

In [ ]:
series = data['Defense']        # data['Defense'] = series
print(type(series))
data_frame = data[['Defense']]  # data[['Defense']] = data frame
print(type(data_frame))

In [ ]:

# 1 - Filtering Pandas data frame
x = data['Defense']>200     # There are only 3 pokemons who have higher defense value than 200
data[x]

In [ ]:
data[data['HP']>50].head()

In [ ]:
# 2 - Filtering pandas with logical_and
# There are only 2 pokemons who have higher defence value than 2oo and higher attack value than 100
data[np.logical_and(data['Defense']>200, data['Attack']>100 )]

In [ ]:

# This is also same with previous code line. Therefore we can also use '&' for filtering.
data[(data['Defense']>200) & (data['Attack']>100)]

In [ ]:
# For pandas we can achieve index and value
for index,value in data[['Attack']].iterrows():
    print(index," : ",value)

In [ ]:
# lambda function
square = lambda x: x**2     # where x is name of argument
print(square(4))
tot = lambda x,y,z: x+y+z   # where x,y,z are names of arguments
print(tot(1,2,3))

In [ ]:
number_list = [1,2,3]
y = map(lambda x:x**2,number_list)
print(list(y))

In [ ]:

# iteration example
name = "ronaldo"
it = iter(name)
print(next(it))    # print next iteration
print(*it)

In [ ]:
# zip example
list1 = [1,2,3,4]
list2 = [5,6,7,8]
z = zip(list1,list2)
print(z)
z_list = list(z)
print(z_list)

In [ ]:
# Example of list comprehension
num1 = [1,2,3]
num2 = [i + 1 for i in num1 ]
print(num2)

In [ ]:
# Conditionals on iterable
num1 = [5,10,15]
num2 = [i**2 if i == 10 else i-5 if i < 7 else i+5 for i in num1]
print(num2)

In [ ]:
# lets return pokemon csv and make one more list comprehension example
# lets classify pokemons whether they have high or low speed. Our threshold is average speed.
threshold = sum(data.Speed)/len(data.Speed)
data["speed_level"] = ["high" if i > threshold else "low" for i in data.Speed]
data.loc[:10,["speed_level","Speed"]] # we will learn loc more detailed later

In [ ]:
### cleaning data

In [ ]:
data.shape

In [ ]:

# For example lets look frequency of pokemom types
print(data['Type 1'].value_counts(dropna =False))  # if there are nan values that also be counted
# As it can be seen below there are 112 water pokemon or 70 grass pokemon

In [ ]:
# For example max HP is 255 or min defense is 5
data.describe() #ignore null entries

In [ ]:

# For example: compare attack of pokemons that are legendary  or not
# Black line at top is max
# Blue line at top is 75%
# Red line is median (50%)
# Blue line at bottom is 25%
# Black line at bottom is min
# There are no outliers
data.boxplot(column='Attack',by = 'Legendary')

In [ ]:

# Firstly I create new data from pokemons data to explain melt nore easily.
data_new = data.head()    # I only take 5 rows into new data
data_new

In [ ]:
# lets melt
# id_vars = what we do not wish to melt
# value_vars = what we want to melt
melted = pd.melt(frame=data_new,id_vars = 'Name', value_vars= ['Attack','Defense'])
melted

In [ ]:

# Index is name
# I want to make that columns are variable
# Finally values in columns are value
melted.pivot(index = 'Name', columns = 'variable',values='value')

In [ ]:

# Firstly lets create 2 data frame
data1 = data.head()
data2= data.tail()
conc_data_row = pd.concat([data1,data2],axis =0,ignore_index =True) # axis = 0 : adds dataframes in row
conc_data_row

In [ ]:
# Firstly lets create 2 data frame
data1 = data.head()
data2= data.tail()
conc_data_row = pd.concat([data1,data2],axis =0,ignore_index =False) # axis = 0 : adds dataframes in row
conc_data_row

In [ ]:
data1 = data[(data['Attack']>0)&(data['Name'])]
data2= data['Defense'].head()
conc_data_col = pd.concat([data1,data2],axis =1) # axis = 0 : adds dataframes in row
conc_data_col
## birleştirme işlemi

In [ ]:

data.dtypes

In [ ]:
# lets convert object(str) to categorical and int to float.
data['Type 1'] = data['Type 1'].astype('category')
data['Speed'] = data['Speed'].astype('float')

In [ ]:
data.info()

In [ ]:
data["Type 2"].value_counts(dropna=False)

In [ ]:
data1=data   # also we will use data to fill missing value so I assign it to data1 variable
data["Type 2"].dropna(inplace = True)  # inplace = True means we do not assign it to new variable. Changes automatically assigned to data
# So does it work ?

In [ ]:
data.shape

In [ ]:

data["Type 2"].fillna('empty',inplace = True)

In [ ]:
data.shape

In [ ]:
data["Type 2"].value_counts(dropna=False)

In [ ]:

data["Type 2"].value_counts(dropna=False)

In [ ]:
# # With assert statement we can check a lot of thing. For example
# assert data.columns[1] == 'Name'
# assert data.Speed.dtypes == np.int

In [ ]:
# data frames from dictionary
country = ["Spain","France"]
population = ["11","12"]
list_label = ["country","population"]
list_col = [country,population]
zipped = list(zip(list_label,list_col))
data_dict = dict(zipped)
df = pd.DataFrame(data_dict)
df

In [ ]:
# Add new columns
df["capital"] = ["madrid","paris"]
df

In [ ]:
# Plotting all data 
data1 = data.loc[:,["Attack","Defense","Speed"]]
data1.plot()
# it is confusing

In [ ]:
data1.plot(subplots = True)
plt.show()

In [ ]:
# scatter plot  
data1.plot(kind = "scatter",x="Attack",y = "Defense")
plt.show()

In [ ]:

# hist plot  
data1.plot(kind = "hist",y = "Defense",bins = 50,range= (0,250),normed = True)

In [ ]:
# histogram subplot with non cumulative and cumulative
fig, axes = plt.subplots(nrows=2,ncols=1)
data1.plot(kind = "hist",y = "Defense",bins = 50,range= (0,250),normed = True,ax = axes[0])
data1.plot(kind = "hist",y = "Defense",bins = 50,range= (0,250),normed = True,ax = axes[1],cumulative = True)
plt.savefig('graph.png')
plt

In [ ]:
# histogram subplot with non cumulative and cumulative
fig, axes = plt.subplots(nrows=2,ncols=1)
data1.plot(kind = "hist",y = "Defense",bins = 50,range= (0,250),normed = True,ax = axes[0])
data1.plot(kind = "hist",y = "Defense",bins = 50,range= (0,250),normed = True,ax = axes[1],cumulative = True)
plt.savefig('graph.png')
plt

In [ ]:
###   INDEXING PANDAS TIME SERIES

In [ ]:

time_list = ["1992-03-08","1992-04-12"]
print(type(time_list[1])) # As you can see date is string
# however we want it to be datetime object
datetime_object = pd.to_datetime(time_list)
print(type(datetime_object))

In [ ]:

# close warning
import warnings
warnings.filterwarnings("ignore")
# In order to practice lets take head of pokemon data and add it a time list
data2 = data.head()
date_list = ["1992-01-10","1992-02-10","1992-03-10","1993-03-15","1993-03-16"]
datetime_object = pd.to_datetime(date_list)
data2["date"] = datetime_object
# lets make date as index
data2= data2.set_index("date")
data2

In [ ]:
# Now we can select according to our date index
print(data2.loc["1993-03-16"])
print(data2.loc["1992-03-10":"1993-03-16"])

In [ ]:
data2.resample("A").mean()

In [ ]:
data2.resample("M").mean()

In [ ]:
data2.resample("M").first().interpolate("linear")

In [ ]:
data2.resample("M").mean().interpolate("linear")

In [ ]:
### INDEXING DATA FRAMES

In [ ]:
# read data
data = pd.read_csv('../input/pokemon-challenge/pokemon.csv')
data= data.set_index("#")
data.head()

In [ ]:
# indexing using square brackets
data["HP"][1]

In [ ]:
# using column attribute and row label
data.HP[1]

In [ ]:

# using loc accessor
data.loc[1,["HP"]]

In [ ]:
# Selecting only some columns
data[["HP","Attack"]]

In [ ]:
### SLICING DATA FRAME

In [ ]:

# Difference between selecting columns: series and dataframes
print(type(data["HP"]))     # series
print(type(data[["HP"]]))   # data frames

In [ ]:
# Slicing and indexing series
data.loc[1:10,"HP":"Defense"]   # 10 and "Defense" are inclusive

In [ ]:
# Reverse slicing 
data.loc[10:1:-1,"HP":"Defense"]

In [ ]:

# From something to end
data.loc[1:10,"Speed":]

In [ ]:
### FILTERING DATA FRAMES

In [ ]:
# Creating boolean series
boolean = data.HP > 200
data[boolean]

In [ ]:
# Combining filters
first_filter = data.HP > 150
second_filter = data.Speed > 35
data[first_filter & second_filter]

In [ ]:
# Filtering column based others
data.HP[data.Speed<15]

In [ ]:
## TRANSFORMING DATA

In [ ]:

# Plain python functions
def div(n):
    return n/2
data.HP.apply(div)

In [ ]:

# Or we can use lambda function
data.HP.apply(lambda n : n/2)

In [ ]:
# Defining column using other columns
data["total_power"] = data.Attack + data.Defense
data.head()

In [ ]:
###  INDEX OBJECTS AND LABELED DATA