In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
# memuat dataset
df = pd.read_csv("../input/palmer-archipelago-antarctica-penguin-data/penguins_size.csv")
df.head(5)

In [ ]:
df.tail(5)

In [ ]:
# cek duplikat
df.duplicated().sum()

In [ ]:
# melihat isi kolom
df.columns

In [ ]:
# melihat informasi data
df.info()

In [ ]:
# meihat data yang kosong
df.isna().sum()

In [ ]:
# pengisian data kosong pada kolom dengan tipe float dengan rata-rata sesuai dengan speciesnya
def imputasi(df_input):
    col = df_input.select_dtypes(float).columns
    class_col = df_input.columns[0]

    # melakukan pengisian data kosong dengan mean
    for i in col:
        df_input[i].fillna(df_input.groupby(class_col)[i].transform("mean").round(1), inplace=True)

    return df_input

In [ ]:
imputasi(df)

In [ ]:
# melihat isi data pada kolom kategorikal
df["species"].value_counts()

In [ ]:
df["island"].value_counts()

In [ ]:
df["sex"].value_counts()

In [ ]:
# mengisi data yang salah dengan NaN
df["sex"].replace({
    ".": np.NaN
})

In [ ]:
# menghapus baris pada kolom "sex" yang berisi data NaN 
df.dropna(subset=["sex"], inplace=True)

In [ ]:
# melihat informasi data
df.info()

In [ ]:
# Encoding nominal data
df["species"].replace({
    'Adelie': 0, 
    'Gentoo': 1, 
    'Chinstrap': 2
}, inplace=True)

df["island"].replace({
    'Biscoe': 0, 
    'Dream': 1, 
    'Torgersen': 2
}, inplace=True)

df["sex"].replace({
    'MALE': 0, 
    'FEMALE': 1
}, inplace=True)

In [ ]:
df.head()

In [ ]:
# melihat rentang masing-masing fitur
def rentang_data(df_input):
    list_feature = df.select_dtypes(float)

    for i in list_feature:
        min = df_input[i].min()
        max = df_input[i].max()
        print("Rentang data {fitur} adalah {nilai}".format(fitur=i, nilai=(max-min)))

In [ ]:
rentang_data(df)

In [ ]:
# melakukan normalisasi data dengan metode MinMax
# melakukan normalisasi data dengan metode minmax
def minmax(df_input):
    list_feature = df.select_dtypes(float)

    for i in list_feature:
        min = df_input[i].min()
        max = df_input[i].max()
        df_input[i] = (df_input[i] - min) / (max - min)
    return df_input

In [ ]:
minmax(df)
df.head()

In [ ]:
# melihat rentang data setelah data telah dinormalisasi
rentang_data(df)

In [ ]:
# melihat distribusi data
df.describe()

In [ ]:
# melihat korelasi antar data
df.corr()

In [ ]:
# membuat data x dan y untuk melakukan klasifikasi species pinguin berdasarkan data yang ada
x = df.select_dtypes(float)
y = df["species"]

In [ ]:
# melakukan pembagian data menjadi data latih dan uji dengan perbandingan 70 30
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state=3, stratify=y)

In [ ]:
# melakukan klasifikasi dengan KNN
model_knn = KNeighborsClassifier().fit(x_train, y_train)
yPred_knn = model_knn.predict(x_test)
yPred_knn

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, yPred_knn))