In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
data= pd.read_csv('/kaggle/input/zomato-bangalore-restaurants/zomato.csv')

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data.head()

In [ ]:
data.info()

In [ ]:
data.columns

In [ ]:
data.describe()

In [ ]:
data.isnull().sum()

In [ ]:
data.shape

In [ ]:
data=data[data.cuisines.isna()==False]

In [ ]:
data.shape

In [ ]:
data.isnull().sum()

In [ ]:
data.drop(columns=["url","address","phone","listed_in(city)"],inplace=True)

In [ ]:
data.rename(columns={'approx_cost(for two people)': 'average_cost'}, inplace=True)

In [ ]:
data.name.value_counts().head()

In [ ]:
plt.figure(figsize=(12,6))
ax= data.name.value_counts()[:20].plot(kind='bar')
ax.legend(['*Restaurants'])
plt.xlabel("Name of Restaurant")
plt.ylabel("Count of Restaurants")
plt.title("Name vs Number of Restaurant",fontsize =20, weight = 'bold')

In [ ]:
data.online_order.value_counts()

In [ ]:
ax= sns.countplot(data['online_order'])
plt.title('Number of Restaurants accepting online orders', weight='bold')
plt.xlabel('online orders')

In [ ]:
data.book_table.value_counts()

In [ ]:
sns.countplot(data['book_table'])
plt.title("No of Restaurant with Book Table Facility", weight = 'bold')
plt.xlabel('Book table facility')
plt.ylabel('No of restaurants')

In [ ]:
data.location.value_counts()

In [ ]:
plt.figure(figsize=(12,10))
data['location'].value_counts()[:10].plot(kind='pie')
plt.title('Location', weight = 'bold')

In [ ]:
plt.figure(figsize=(12,10))
data.location.value_counts()[:10].plot(kind='bar')
plt.title("Location vs Count", weight = 'bold')

In [ ]:
data.location.nunique()

In [ ]:
data['rest_type'].value_counts().head()

In [ ]:
plt.figure(figsize=(14,8))
data.rest_type.value_counts()[:10].plot(kind='pie')
plt.title('Restaurent Type', weight = 'bold')
plt.show()

In [ ]:
data.average_cost.value_counts().head(20)

In [ ]:
plt.figure(figsize=(12,8))
data['average_cost'].value_counts()[:20].plot(kind='pie',autopct='%1.1f%%')
plt.title('Avg cost in Restaurent for 2 people', weight = 'bold')

In [ ]:
dishes_data = data[data.dish_liked.notnull()]
dishes_data.dish_liked = dishes_data.dish_liked.apply(lambda x:x.lower().strip())

In [ ]:
dishes_data.isnull().sum()

In [ ]:
dish_count = []
for i in dishes_data.dish_liked:
    for t in i.split(','):
        t = t.strip() # remove the white spaces to get accurate results
        dish_count.append(t)

In [ ]:
plt.figure(figsize=(12,6)) 
pd.Series(dish_count).value_counts()[:10].plot(kind='bar',color= 'c')
plt.title('Top 10 dished_liked in Bangalore',weight='bold')
plt.xlabel('Dish')
plt.ylabel('Count')

In [ ]:
cuisines_data = data[data.cuisines.notnull()]
cuisines_data.cuisines = cuisines_data.cuisines.apply(lambda x:x.lower().strip())

In [ ]:
cuisines_count= []

for i in cuisines_data.cuisines:
    for j in i.split(','):
        j = j.strip()
        cuisines_count.append(j)

In [ ]:
plt.figure(figsize=(12,6)) 
pd.Series(cuisines_count).value_counts()[:10].plot(kind='bar',color= 'r')
plt.title('Top 10 cuisines in Bangalore',weight='bold')
plt.xlabel('cuisines type')
plt.ylabel('No of restaurants')

In [ ]:
data['rate'] = data['rate'].replace('NEW',np.NaN)
data['rate'] = data['rate'].replace('-',np.NaN)
data.dropna(how = 'any', inplace = True)

In [ ]:
data['rate'] = data.loc[:,'rate'].replace('[ ]','',regex = True)
data['rate'] = data['rate'].astype(str)
data['rate'] = data['rate'].apply(lambda r: r.replace('/5',''))
data['rate'] = data['rate'].apply(lambda r: float(r))

In [ ]:
data.rate.hist(color='grey')
plt.axvline(x= data.rate.mean(),ls='--',color='yellow')
plt.title('Average Rating for Bangalore Restaurants',weight='bold')
plt.xlabel('Rating')
plt.ylabel('No of Restaurants')
print(data.rate.mean())

In [ ]:
data['online_order']= pd.get_dummies(data.online_order, drop_first=True)
data['book_table']= pd.get_dummies(data.book_table, drop_first=True)
data

In [ ]:
data.drop(columns=['dish_liked','reviews_list','menu_item','listed_in(type)'], inplace  =True)

In [ ]:
data['rest_type'] = data['rest_type'].str.replace(',' , '') 
data['rest_type'] = data['rest_type'].astype(str).apply(lambda x: ' '.join(sorted(x.split())))
data['rest_type'].value_counts().head()

In [ ]:
data['cuisines'] = data['cuisines'].str.replace(',' , '') 
data['cuisines'] = data['cuisines'].astype(str).apply(lambda x: ' '.join(sorted(x.split())))
data['cuisines'].value_counts().head()

In [ ]:
from sklearn.preprocessing import LabelEncoder
T = LabelEncoder()                 
data['location'] = T.fit_transform(data['location'])
data['rest_type'] = T.fit_transform(data['rest_type'])
data['cuisines'] = T.fit_transform(data['cuisines'])

In [ ]:
data["average_cost"] = data["average_cost"].str.replace(',' , '')

In [ ]:
data["average_cost"] = data["average_cost"].astype('float')

In [ ]:
x = data.drop(['rate','name'],axis = 1)

In [ ]:
y = data['rate']

In [ ]:
x.shape

In [ ]:
y.shape

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 33)

In [ ]:
from sklearn.preprocessing import StandardScaler
num_values1=data.select_dtypes(['float64','int64']).columns
scaler = StandardScaler()
scaler.fit(data[num_values1])
data[num_values1]=scaler.transform(data[num_values1])

In [ ]:
data.head()

In [ ]:
from sklearn import metrics
from sklearn.tree import DecisionTreeRegressor 
dc =  DecisionTreeRegressor()
dc.fit(X_train,y_train)
y_pred_rfr = dc.predict(X_test)

In [ ]:
dc.score(X_test,y_test)*100