In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
df = pd.read_csv("/kaggle/input/suicide-rates-overview-1985-to-2016/master.csv")
df

In [ ]:
df.info()

In [ ]:
df['age'].replace('5-14 years','05-14 years',inplace=True)
df

In [ ]:
Age_range = df.groupby('age').agg({'suicides_no':np.sum})
Age_range

In [ ]:
import matplotlib.pyplot as plt
plt.plot(Age_range,marker='o')
plt.ylim([10000,2500000])
plt.xticks(rotation=45)
plt.title('We can clearly see that no. of suicide cases are maximum in age range 35-54 years\n and they are 2452141',pad=50,fontsize=25)

In [ ]:
plt.pie(Age_range['suicides_no'],labels=Age_range.index)

In [ ]:
year_wise_df = df.groupby(['year','age']).agg({'suicides_no':np.sum})
year_wise_df.head(10)

In [ ]:
yr = pd.DataFrame(df['year'].value_counts()).sort_index()
yr.index

In [ ]:
yr.plot(kind ='bar')
plt.title('Suicides recorded per year',pad=25,fontsize=25)

# > ****We have 0 suicides for age_range 0-14 in the year 2016

In [ ]:
year_wise_df.loc[2016]

# > **We'll analyze data from year 2000 to year 2015**

In [ ]:
age_range_05to14 = year_wise_df.loc[[(2000,'05-14 years'), (2001,'05-14 years'), (2002,'05-14 years'), (2003,'05-14 years'),
                                    (2004,'05-14 years'), (2005,'05-14 years'), (2006,'05-14 years'), (2007,'05-14 years'), 
                                    (2008,'05-14 years'), (2009,'05-14 years'), (2010,'05-14 years'), (2011,'05-14 years'), 
                                    (2012,'05-14 years'), (2013,'05-14 years'), (2014,'05-14 years'), (2015,'05-14 years')]].reset_index()

In [ ]:
age_range_05to14

In [ ]:
age_range_05to14[age_range_05to14['suicides_no']==max(age_range_05to14['suicides_no'])]

In [ ]:
age_range_05to14[age_range_05to14['suicides_no']==min(age_range_05to14['suicides_no'])]

In [ ]:
plt.plot(age_range_05to14['year'],age_range_05to14['suicides_no'],marker='o')
ymax = 2095
xmax = 2001
plt.title('Number of Suicides commited by age_range: 5 to 14 years',pad=50,fontsize=25)
plt.gca().annotate('2095 is maximum no. of suicides in 2001 \n', xy=(xmax, ymax), xytext=(xmax, ymax+5),
            arrowprops=dict(facecolor='red', shrink=0.05) )
plt.ylim(0,2500)
ymin = 1640
xmin = 2008
plt.gca().annotate('  1640 is minimum no. of suicides in 2008', xy=(xmin, ymin), xytext=(xmin, ymin+30),
            arrowprops=dict(facecolor='red', shrink=0.05) )
plt.xlabel('Year')
plt.ylabel('Number of Suicides')

In [ ]:
age_range_15to24 = year_wise_df.loc[[ (2000,'15-24 years'), 
                 (2001,'15-24 years'), (2002,'15-24 years'), (2003,'15-24 years'), (2004,'15-24 years'), 
                 (2005,'15-24 years'), (2006,'15-24 years'), (2007,'15-24 years'), (2008,'15-24 years'), 
                 (2009,'15-24 years'), (2010,'15-24 years'), (2011,'15-24 years'), (2012,'15-24 years'), 
                 (2013,'15-24 years'), (2014,'15-24 years'), (2015,'15-24 years')]].reset_index()
age_range_15to24

In [ ]:
age_range_15to24[age_range_15to24['suicides_no']==max(age_range_15to24['suicides_no'])]

In [ ]:
age_range_15to24[age_range_15to24['suicides_no']==min(age_range_15to24['suicides_no'])]

In [ ]:
plt.plot(age_range_15to24['year'],age_range_15to24['suicides_no'],marker='o')
ymax = 31742
xmax = 2000
plt.title('Number of Suicides commited by age_range: 15 to 24 years',pad=50,fontsize=25)
plt.gca().annotate('31742 is maximum no. of suicides in 2000 \n', xy=(xmax, ymax), xytext=(xmax, ymax+5),
            arrowprops=dict(facecolor='red', shrink=0.05) )
plt.ylim(1000,35000)
ymin = 21841
xmin = 2015
plt.gca().annotate('  21841 is minimum no. of suicides in 2015', xy=(xmin, ymin), xytext=(xmin, ymin+30),
            arrowprops=dict(facecolor='red', shrink=0.05) )
plt.xlabel('Year')
plt.ylabel('Number of Suicides')

In [ ]:
age_range_25to34 = year_wise_df.loc[[ (2000,'25-34 years'), 
                 (2001,'25-34 years'), (2002,'25-34 years'), (2003,'25-34 years'), (2004,'25-34 years'), 
                 (2005,'25-34 years'), (2006,'25-34 years'), (2007,'25-34 years'), (2008,'25-34 years'), 
                 (2009,'25-34 years'), (2010,'25-34 years'), (2011,'25-34 years'), (2012,'25-34 years'), 
                 (2013,'25-34 years'), (2014,'25-34 years'), (2015,'25-34 years')]].reset_index()
age_range_25to34

In [ ]:
age_range_25to34[age_range_25to34['suicides_no']==max(age_range_25to34['suicides_no'])]

In [ ]:
age_range_25to34[age_range_25to34['suicides_no']==min(age_range_25to34['suicides_no'])]

In [ ]:
plt.plot(age_range_25to34['year'],age_range_25to34['suicides_no'],marker='o')
ymax = 41605
xmax = 2000
plt.title('Number of Suicides commited by age_range: 25 to 34 years',pad=50,fontsize=25)
plt.gca().annotate('41605 is maximum no. of suicides in 2000 \n', xy=(xmax, ymax), xytext=(xmax, ymax+5),
            arrowprops=dict(facecolor='red', shrink=0.05) )
plt.ylim(20000,55000)
ymin = 32118
xmin = 2015
plt.gca().annotate('  32118 is minimum no. of suicides in 2015', xy=(xmin, ymin), xytext=(xmin, ymin+30),
            arrowprops=dict(facecolor='red', shrink=0.05) )
plt.xlabel('Year')
plt.ylabel('Number of Suicides')

In [ ]:
age_range_35to54 = year_wise_df.loc[[ (2000,'35-54 years'), 
                 (2001,'35-54 years'), (2002,'35-54 years'), (2003,'35-54 years'), (2004,'35-54 years'), 
                 (2005,'35-54 years'), (2006,'35-54 years'), (2007,'35-54 years'), (2008,'35-54 years'), 
                 (2009,'35-54 years'), (2010,'35-54 years'), (2011,'35-54 years'), (2012,'35-54 years'), 
                 (2013,'35-54 years'), (2014,'35-54 years'), (2015,'35-54 years')]].reset_index()
age_range_35to54

In [ ]:
age_range_35to54[age_range_35to54['suicides_no']==max(age_range_35to54['suicides_no'])]

In [ ]:
age_range_35to54[age_range_35to54['suicides_no']==min(age_range_35to54['suicides_no'])]

In [ ]:
plt.plot(age_range_35to54['year'],age_range_35to54['suicides_no'],marker='o')
ymax = 98693
xmax = 2003
plt.title('Number of Suicides commited by age_range: 35 to 54 years',pad=50,fontsize=25)
plt.gca().annotate('98693 is maximum no. of suicides in 2003 \n', xy=(xmax, ymax), xytext=(xmax, ymax+5),
            arrowprops=dict(facecolor='red', shrink=0.05) )
plt.ylim(70000,100000)
ymin = 71298
xmin = 2015
plt.gca().annotate('  71298 is minimum no. of suicides in 2015', xy=(xmin, ymin), xytext=(xmin, ymin+30),
            arrowprops=dict(facecolor='red', shrink=0.05) )
plt.xlabel('Year')
plt.ylabel('Number of Suicides')

In [ ]:
age_range_55to74 = year_wise_df.loc[[ (2000,'55-74 years'), 
                 (2001,'55-74 years'), (2002,'55-74 years'), (2003,'55-74 years'), (2004,'55-74 years'), 
                 (2005,'55-74 years'), (2006,'55-74 years'), (2007,'55-74 years'), (2008,'55-74 years'), 
                 (2009,'55-74 years'), (2010,'55-74 years'), (2011,'55-74 years'), (2012,'55-74 years'), 
                 (2013,'55-74 years'), (2014,'55-74 years'), (2015,'55-74 years')]].reset_index()
age_range_55to74

In [ ]:
age_range_55to74[age_range_55to74['suicides_no']==max(age_range_55to74['suicides_no'])]

In [ ]:
age_range_55to74[age_range_55to74['suicides_no']==min(age_range_55to74['suicides_no'])]

In [ ]:
plt.plot(age_range_55to74['year'],age_range_55to74['suicides_no'],marker='o')
ymax = 60973
xmax = 2000
plt.title('Number of Suicides commited by age_range: 55 to 74 years',pad=50,fontsize=25)
plt.gca().annotate('60973 is maximum no. of suicides in 2000 \n', xy=(xmax, ymax), xytext=(xmax, ymax+5),
            arrowprops=dict(facecolor='red', shrink=0.05) )
plt.ylim(50000,70000)
ymin = 53588
xmin = 2015
plt.gca().annotate('  53588 is minimum no. of suicides in 2015', xy=(xmin, ymin), xytext=(xmin, ymin+30),
            arrowprops=dict(facecolor='red', shrink=0.05) )
plt.xlabel('Year')
plt.ylabel('Number of Suicides')

In [ ]:
age_range_75_and_above = year_wise_df.loc[[ (2000,'75+ years'), 
                 (2001,'75+ years'), (2002,'75+ years'), (2003,'75+ years'), (2004,'75+ years'), 
                 (2005,'75+ years'), (2006,'75+ years'), (2007,'75+ years'), (2008,'75+ years'), 
                 (2009,'75+ years'), (2010,'75+ years'), (2011,'75+ years'), (2012,'75+ years'), 
                 (2013,'75+ years'), (2014,'75+ years'), (2015,'75+ years')]].reset_index()
age_range_75_and_above

In [ ]:
age_range_75_and_above[age_range_75_and_above['suicides_no']==max(age_range_75_and_above['suicides_no'])]

In [ ]:
age_range_75_and_above[age_range_75_and_above['suicides_no']==min(age_range_75_and_above['suicides_no'])]

In [ ]:
plt.plot(age_range_75_and_above['year'],age_range_75_and_above['suicides_no'],marker='o')
ymax = 24865
xmax = 2014
plt.title('Number of Suicides commited by age_range: 75 and above years',pad=50,fontsize=25)
plt.gca().annotate('24865 is maximum no. of suicides in 2014 \n', xy=(xmax, ymax), xytext=(xmax, ymax+5),
            arrowprops=dict(facecolor='red', shrink=0.05) )
plt.ylim(20000,30000)
ymin = 21437
xmin = 2001
plt.gca().annotate('  21437 is minimum no. of suicides in 2001', xy=(xmin, ymin), xytext=(xmin, ymin+30),
            arrowprops=dict(facecolor='red', shrink=0.05) )
plt.xlabel('Year')
plt.ylabel('Number of Suicides')