#### Introduction 
In this notebook I will try to develop a multi-label genre classifier using given data of movie plots.

In [1]:
import pandas as pd

In [2]:
movie_plots = pd.read_csv('../input/wiki_movie_plots_deduped.csv')

In [3]:
movie_plots.head()

   Release Year                        ...                                                                       Plot
0          1901                        ...                          A bartender is working at a saloon, serving dr...
1          1901                        ...                          The moon, painted with a smiling face hangs ov...
2          1901                        ...                          The film, just over a minute long, is composed...
3          1901                        ...                          Lasting just 61 seconds and consisting of two ...
4          1902                        ...                          The earliest known adaptation of the classic f...

[5 rows x 8 columns]

#### Exploratory Data Analysis

In [4]:
movie_plots.shape

(34886, 8)

In [13]:
movie_plots.isnull().sum()

Release Year           0
Title                  0
Origin/Ethnicity       0
Director               0
Cast                1422
Genre                  0
Wiki Page              0
Plot                   0
dtype: int64

In [11]:
#Total unique combinations of genres

len(df['Genre'].unique())

2265

In [8]:
#Checking most popular genres

df = movie_plots.groupby(["Genre"]).size().reset_index(name='count')
df = df.sort_values(by=['count'], ascending=False)
df.head(n=50)

                 Genre  count
2169           unknown   6083
863              drama   5964
573             comedy   4379
1390            horror   1167
7               action   1098
2114          thriller    966
1726           romance    923
2210           western    865
753              crime    568
288          adventure    526
1553           musical    467
763        crime drama    464
1820   romantic comedy    461
1902   science fiction    418
1310         film noir    345
1590           mystery    310
2175               war    273
385          animation    264
644      comedy, drama    236
1865            sci-fi    221
1172            family    217
1228           fantasy    204
349           animated    195
1559    musical comedy    154
697       comedy-drama    137
491          biography    136
433              anime    112
2088          suspense    104
607       comedy drama    103
1831    romantic drama    103
361     animated short     91
1038    drama, romance     86
1974            social     82
1328        historical     77
104    action thriller     73
854        documentary     73
1941            serial     71
2233      world war ii     70
1179      family drama     66
2180         war drama     65
992       drama, crime     64
671    comedy, musical     63
714       comedy/drama     62
676    comedy, romance     60
1769    romance, drama     58
518             biopic     57
778     crime thriller     56
1343  historical drama     54
529       black comedy     52
84       action comedy     51

In [14]:
#Keeping only generes with 50+ instances

df = df[df['count']>=50]

In [15]:
df.shape

(51, 2)

In [18]:
genre_list = df['Genre'].tolist()
genre_list

['unknown',
 'drama',
 'comedy',
 'horror',
 'action',
 'thriller',
 'romance',
 'western',
 'crime',
 'adventure',
 'musical',
 'crime drama',
 'romantic comedy',
 'science fiction',
 'film noir',
 'mystery',
 'war',
 'animation',
 'comedy, drama',
 'sci-fi',
 'family',
 'fantasy',
 'animated',
 'musical comedy',
 'comedy-drama',
 'biography',
 'anime',
 'suspense',
 'comedy drama',
 'romantic drama',
 'animated short',
 'drama, romance',
 'social',
 'historical',
 'action thriller',
 'documentary',
 'serial',
 'world war ii',
 'family drama',
 'war drama',
 'drama, crime',
 'comedy, musical',
 'comedy/drama',
 'comedy, romance',
 'romance, drama',
 'biopic',
 'crime thriller',
 'historical drama',
 'black comedy',
 'action comedy',
 'comedy short']

In [21]:
#Removing genre 'unknown'

genre_list = genre_list[1:]

In [22]:
movie_plots_ = movie_plots[movie_plots['Genre'].isin(genre_list)]

#### Feature Analysis
Though I will be building classifier using movie plots only lets also alnalyse other features available in this dataset

In [25]:
len(movie_plots_['Origin/Ethnicity'].unique())

24

_Work in progress, will be adding further analysis soon_