In [17]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns  # visualization tool
data = pd.read_csv('../input/pokemon.csv')

In [18]:
def tuble_ex():
    t = (1,2,3)
    return t
a,b,c = tuble_ex()
print(a,b,c)

1 2 3

In [19]:
x = 2
def f():
    x = 3
    return x
print(x)      # global variable
print(f())    # function variable

2
3

In [20]:
data.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [21]:
def square():
    def add():
        
        x = 2
        y = 3
        z = x + y
        return z
    return add()**add()
print(square())

3125

In [22]:
def f(a, b = 1, c = 2):
    y = a + b + c
    return y
print(f(5))
print(f(5,4,3))

8
12

In [23]:
def f(*args):
    for i in args:
        print(i)
f(1)
print("")
f(1,2,3,4)
#Dictionary
def f(**kwargs):
    for key, value in kwargs.items():
        print(key, " ", value)
f(country = 'spain', capital = 'madrid', population = 123456)

1

1
2
3
4
country   spain
capital   madrid
population   123456

In [24]:
number_list = [1,2,3]
y=map(lambda x : x**2,number_list)
print(list(y))
##########
def dongu_yazma(*arg):
    return arg[0]**2

z=map(dongu_yazma,number_list)

print(list(z))
############
#pandas apply
import pandas as pd

dictionary = {"NAME":["ali","veli","kenan","hilal","ayse","evren"],
              "AGE":[15,16,17,33,45,66],
              "MAAS": [100,150,240,350,110,220]} 
dataFrame1 = pd.DataFrame(dictionary)
# apply()

def multiply(age):
    return age*2
    
dataFrame1["apply_metodu"] = dataFrame1.AGE.apply(multiply)
print(dataFrame1.apply_metodu)

[1, 4, 9]
[1, 4, 9]
0     30
1     32
2     34
3     66
4     90
5    132
Name: apply_metodu, dtype: int64

In [25]:
name = "Ayhan"
it = iter(name)
print(next(it))    # print next iteration
print(next(it))
print(*it)         # print remaining iteration

A
y
h a n

In [26]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
z = zip(list1,list2)
print(z)
z_list = list(z)
print(z_list)

<zip object at 0x7f188271fbc8>
[(1, 5), (2, 6), (3, 7), (4, 8)]

In [27]:
un_zip = zip(*z_list)
un_list1,un_list2 = list(un_zip) # unzip returns tuble
print(un_list1)
print(un_list2)
print(type(un_list2))

(1, 2, 3, 4)
(5, 6, 7, 8)
<class 'tuple'>

In [28]:
num1 = [1,2,3]
num2 = [i + 1 for i in num1 ]
print(num2)

[2, 3, 4]

In [29]:
num1 = [5,10,15]
num2 = [i**2 if i == 10 else i-5 if i < 7 else i+5 for i in num1]
print(num2)

[0, 100, 20]

In [30]:
threshold = sum(data.Speed)/len(data.Speed)
data["speed_level"] = ["high" if i > threshold else "low" for i in data.Speed]
data.loc[:10,["speed_level","Speed"]]

   speed_level  Speed
0          low     45
1          low     60
2         high     80
3         high     80
4          low     65
5         high     80
6         high    100
7         high    100
8         high    100
9          low     43
10         low     58