## دومین بوت کمپ هوش مصنوعی فیلاگر - تمرین جلسه ۲
Mahdi Ghaemi :)

#### 1- دیتاست را بخوانید

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
my_csv_file_location = '../input/hotel-booking/hotel_booking.csv'
df = pd.read_csv(my_csv_file_location)

#### 2 - اطلاعات پایه ای دیتاست را بررسی نمایید

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.describe()

#### 4- آیا داده گمشده (missing data) وجود دارد؟ اگر جواب مثبت است، کدام ستون بیشترین تعداد داده گمشده را دارد؟

In [ ]:
# way 1
missing_datas = df.isnull().sum()

print(missing_datas)

In [ ]:
# way 2
max_value = missing_datas.max()
max_value_title = missing_datas.idxmax()

print(f'column "{max_value_title}" with ({max_value}) have most missing values')

In [ ]:
# way 3
max_value = -1
max_value_title = '-1'

for title in missing_datas.index:
    value = missing_datas[title]
    if max_value < value:
        max_value = value
        max_value_title = title
        
print(f'column "{max_value_title}" with ({max_value}) have most missing values')

In [ ]:
# way 4
missing_datas_info = dict()

for column in df.columns:
    missing_data_count = 0
    
    for value in df[column]:
        
        if value is np.NaN :
            missing_data_count+=1
    
    missing_datas_info[column] = missing_data_count
    
print(missing_datas_info)
print(max(missing_datas_info.items(),key = lambda item:item[1]))

#### 5- ستون 'company' را از دیتافریم حذف کنید.

In [ ]:
# way 1
df.drop('company',axis=1,inplace=False)

In [ ]:
# way 2
del df['company']
df

#### 6- بیشترین مسافران از کدام کشورها هستند؟ 5 کشور نخست را مشخص کنید.

In [ ]:
# way 1 
df.groupby('country').size()

In [ ]:
# way 2
country_info = dict()

column = 'country'

for country in df[column]:
    if country not in country_info:
        country_info[country] = 0
        
    country_info[country] += 1
    
print(country_info)

In [ ]:
# way 3
from collections import Counter

Counter(df['country'])

#### 7- نام فردی که بیشترین پرداختی )ADR(Average Daily Rate را دارد مشخص کنید. مبلغ آن چقدر است؟

In [ ]:
# way 1
colume = 'adr'
max_value = df[colume].max()
index_max_value = df[colume].idxmax()
index_name = df['name'][index_max_value]

print(f'"{index_name}" with index({index_max_value}) have maximum value "{max_value}" in colume "{colume}"')

In [ ]:
# way 2
max_adr = 0
max_adr_index = -1
max_adr_person_name = '-1'
colume = 'adr'

for index,adr in enumerate(df[colume]):
    if adr > max_adr:
        max_adr = adr
        max_adr_index = index
        max_adr_person_name = df['name'][index]

print(f'"{max_adr_person_name}" with index({max_adr_index}) have maximum value "{max_adr}" in colume "{colume}"')

#### 8- میانگین کل ADR ها را مشخص کنید. (تا دور رقم اعشار)

In [ ]:
# way 1
mean = round(df['adr'].mean(),2)

print(mean)

In [ ]:
# way 2
mean = df.describe()['adr']['mean']
mean = int(mean * 100) / 100

print(mean)

In [ ]:
# way 3
mean = 0
total_count = 0

colume = 'adr'

for index,adr in enumerate(df[colume]):
    mean = (mean * total_count + adr) / (total_count + 1) 
    total_count += 1

mean = ("%.2f")  % (mean)
print(mean)

In [ ]:
# way 4
colume = 'adr'
total = 0

for adr in df[colume]:
    total += adr

mean = total / len(df[colume])
mean = round(mean,2)

print(mean)

#### 9 - میانگین تعداد شب های اقامت را مشخص نمایید (تا دو رقم اعشار)
(مشابه سوال قبلی)

In [ ]:
# way 1
total = df['stays_in_weekend_nights'] + df['stays_in_week_nights']

mean = total.mean()
mean = round(mean,2)

print(mean)

In [ ]:
# way 2
mean = 0
total_count=0

for index,name in enumerate(df['name']):
    new_value = df['stays_in_weekend_nights'][index] + df['stays_in_week_nights'][index]
    mean = (mean * total_count + new_value) / (total_count + 1) 
    total_count+=1

mean = round(mean,2)
print(mean)

#### 11- نام و آدرس ایمیل افرادی که 5 تا special request داشتند را مشخص نمایید.

In [ ]:
# way 1
target_indexes =  df['total_of_special_requests'] >= 5

for target_index,is_target in enumerate(target_indexes):

    if is_target:
        print(f"'{df['name'][target_index]}' have ({df['total_of_special_requests'][target_index]}) Special Requests")

In [ ]:
# way 2

for index,total_of_special_requests in enumerate(df['total_of_special_requests']):
    
    if total_of_special_requests >= 5:
        print(f"'{df['name'][index]}' have ({total_of_special_requests}) Special Requests")

#### 11 - بیشترین فراوانی نام خانوادگی مربوط به چه نام هایی هست؟ (5 فامیل پرتعداد را مشخص کنید)

In [ ]:
# way 1
df.groupby('name').size()

In [ ]:
# way 2
df.pivot_table(index=['name'], aggfunc='size')

In [ ]:
# way 3
from collections import Counter

name_with_count = Counter(df['name'])
# print(name_with_count)

In [ ]:
# way 4
name_with_count = dict()

for name in df['name']:
    if name not in name_with_count:
        name_with_count[name] = 0
        
    name_with_count[name] += 1
    
# print(name_with_count)

#### 12 - افرادی که همراه با بیشترین تعداد babies و children هتل رزرو کرده اند را مشخص کنید.

In [ ]:
# way 1
df['children'] = df['children'].fillna(0)
df['babies'] = df['babies'].fillna(0)

df['total_young_age'] = df['children'] + df['babies']

df.sort_values('total_young_age')[['name','total_young_age']]

In [ ]:
# way 2
total_young_age = dict()

for index,name in enumerate(df['name']):
    total_young_age[name] = df['children'][index] +df['babies'][index]
    
# print(total_young_age)

#### 13- کد تلفن مناطقی که بیشترین رزرو را داشته اند، مشخص کنید (3 کد پرتکرار)

In [ ]:
# way 1
df['phone-code'] = df['phone-number'].apply(lambda phone:phone.split('-')[0])

df.groupby('phone-code').size().sort_values(ascending=False)

In [ ]:
# way 2
phone_repeats = dict()

for phone in df['phone-number']:
    phone_code = phone.split('-')[0]
    
    if phone_code not in phone_repeats:
        phone_repeats[phone_code] = 0
        
    phone_repeats[phone_code] +=1
    
phone_repeats = sorted(phone_repeats.items(), key=lambda phone_repeat: phone_repeat[1])    
print(phone_repeats[:3])