<h1 align=center><font size="5"> Data Analysis with Python Assignment (Coursera)</font></h1>
<p><font size="4"> Name: Somsuvra Dutta</font>
<p ><font size="4"> Class: MBA TECH CS A</font></p>
<p><font size="4">Roll No: N217</font>
<p><font size="4"> SAP: 70471118019</font>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataframe=pd.read_csv('../input/employee/test.csv')

In [ ]:
dataframe.head()

In [ ]:
dataframe.describe()

### 3.	What are the different ways to create a data frame in Pandas?

In [ ]:
# method 0
# Initialize a blank dataframe and keep adding
df = pd.DataFrame(columns = ['year','make','model'])
# Add records to dataframe using the .loc function
df.loc[0] = [2014,"toyota","corolla"] 
df.loc[1] = [2018,"honda","civic"] 
df

In [ ]:
# Pass a 2D numpy array - each row is the corresponding row required in the dataframe

data = np.array([[2014,"toyota","corolla"], 
                 [2018,"honda","civic"], 
                 [2020,"hyndai","accent"], 
                 [2017,"nissan","sentra"]]) 

# pass column names in the columns parameter 
df = pd.DataFrame(data, columns = ['year', 'make','model'])
df

In [ ]:
data = {'year': [2014, 2018,2020,2017], 
        'make': ["toyota", "honda","hyndai","nissan"],
        'model':["corolla", "civic","accent","sentra"]
       }

# pass column names in the columns parameter 
df = pd.DataFrame(data)
df

In [ ]:
data = [{'year': 2014, 'make': "toyota", 'model':"corolla"}, 
        {'year': 2018, 'make': "honda", 'model':"civic"}, 
        {'year': 2020, 'make': "hyndai", 'model':"nissan"}, 
        {'year': 2017, 'make': "nissan" ,'model':"sentra"}
       ]
# pass column names in the columns parameter 
df = pd.DataFrame(data)
df

In [ ]:
data = {'year': [2014, 2018,2020,2017], 
        'make': ["toyota", "honda","hyndai","nissan"],
        'model':["corolla", "civic","accent","sentra"]
       }

# pass column names in the columns parameter 
df = pd.DataFrame.from_dict(data)
df

In [ ]:
from io import StringIO
# f is a file handle created from a csv like string
f = StringIO('year,make,model\n2014,toyota,corolla\n2018,honda,civic\n2020,hyndai,accent\n2017,nissan,sentra')
df = pd.read_csv(f)
df

In [ ]:
df = pd.read_json('../input/iris-dataset-json-version/iris.json')
df

In [ ]:
from io import StringIO
# f is a file handle created from json like string
f = StringIO('{"year": "2014", "make": "toyota", "model": "corolla"}\n{"year": "2018", "make": "honda", "model": "civic"}\n{"year": "2020", "make": "hyndai", "model": "accent"}\n{"year": "2017", "make": "nissan", "model": "sentra"}')
df = pd.read_json(f,lines=True)
df

In [ ]:
df_copy = df.copy()   # copy into a new dataframe object
df_copy = df          # make an alias of the dataframe(not creating 
                      # a new dataframe, just a pointer)

In [ ]:
data1 = [{'year': 2014, 'make': "toyota", 'model':"corolla"}, 
        {'year': 2018, 'make': "honda", 'model':"civic"}, 
        {'year': 2020, 'make': "hyndai", 'model':"nissan"}, 
        {'year': 2017, 'make': "nissan" ,'model':"sentra"}
       ]
df1 = pd.DataFrame(data1)
data2 = [{'year': 2019, 'make': "bmw", 'model':"x5"}]
df2 = pd.DataFrame(data2)
df3 = pd.concat([df1,df2], axis = 'index') 
df3

In [ ]:
data1 = [{'year': 2014, 'make': "toyota", 'model':"corolla"}, 
        {'year': 2018, 'make': "honda", 'model':"civic"}, 
        {'year': 2020, 'make': "hyndai", 'model':"nissan"}, 
        {'year': 2017, 'make': "nissan" ,'model':"sentra"}
       ]
df1 = pd.DataFrame(data1)
data2 = [{'year': 2019, 'make': "bmw", 'model':"x5"}]
df2 = pd.DataFrame(data2)
df3 = pd.concat([df1,df2], axis = 'columns')
df3

In [ ]:
data1 = [{'year': 2014, 'make': "toyota", 'model':"corolla"}, 
        {'year': 2018, 'make': "honda", 'model':"civic"}, 
        {'year': 2020, 'make': "hyndai", 'model':"nissan"}, 
        {'year': 2017, 'make': "nissan" ,'model':"sentra"}
       ]
df1 = pd.DataFrame(data1)
data2 = [{'make': 'honda', 'Monthly Sales': 114117}, 
        {'make': 'toyota', 'Monthly Sales': 172370}, 
        {'make': 'hyndai', 'Monthly Sales': 54790}
       ]
df2 = pd.DataFrame(data2)
# inner join on 'make'
# default is inner join
df3 = pd.merge(df1,df2,how = 'inner',on = ['make'])
df3 = pd.merge(df1,df2,on = ['make'])
df3

In [ ]:
# To transpose a dataframe - use .T method
df4 = df3.T
# To rename columns to anything else after the transpose
df4.columns = (['column1','column2','column3'])
df4

In [ ]:
data1 = [{ 'make': "toyota", 'model':"corolla", 'body':"sedan"}, 
        {'make': "honda", 'model':"crv", 'body':"suv"}, 
        {'make': "dodge", 'model':"caravan", 'body':"van"}, 
        {'make': "ford" ,'model':"f150", 'body':"truck"}
       ]
df1 = pd.DataFrame(data1) 

df2 = pd.get_dummies(df1,columns = ['body'])
df2