In [ ]:
# 786
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import plotly.express as px
import plotly.graph_objs as go

import plotly as py
from plotly import tools
from plotly.offline import iplot
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):

    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Data Loading & Preparation

In [ ]:
dt = pd.read_csv("../input/pakistans-largest-ecommerce-dataset/Pakistan Largest Ecommerce Dataset.csv", parse_dates=["created_at", "Working Date"], low_memory=False)
print("Data Dimensions are: ", dt.shape)
print("Columns: ", dt.columns)

In [ ]:
print(dt.info())

Data contains 1048574 rows but maximum columns contain 584524 records. 

Half of row are completely empty, so we will drop them. The tricky part is we can't drop all na rows as actual data set  also contain few NA entries. We need to keep them.
We will drop NA values where all entries are Null. 

Also, we will drop last 5 empty columns.

In [ ]:
data = dt[['sku','category_name_1']]

In [ ]:
data.head(20)

In [ ]:
data.category_name_1.value_counts()

As we can see above, few columns are not in correct data type. We need to perform casting.

In [ ]:
data.category_name_1.['Fashion'] = data.category_name_1.['Men's Fashion','Women's Fashion']

In [ ]:
dt.tail()

### Let's look into summary of data
Data Summary of non-numeric data

In [ ]:
data.describe()

Data Summary of non-numeric data

In [ ]:
p.head()

As we analysed above, we need to drop cancelled orders