For this capstone project we will be analyzing some 911 call data from Kaggle. The data contains the following fields:
lat : String variable, Latitude
lng: String variable, Longitude
desc: String variable, Description of the Emergency Call
zip: String variable, Zipcode
title: String variable, Title
timeStamp: String variable, YYYY-MM-DD HH:MM:SS
twp: String variable, Township
addr: String variable, Address
e: String variable, Dummy variable (always 1)
Just go along with this notebook and try to complete the instructions or answer the questions in bold using your Python and Data Science skills!

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
%matplotlib inline

**Read in the csv file as a dataframe called df**

In [5]:
df=pd.read_csv('../input/911.csv')

**What are the top 5 zipcodes for 911 calls?****

In [6]:
df['zip'].value_counts().head()

**What are the top 5 townships (twp) for 911 calls?**

In [7]:
df['twp'].value_counts().head()

**Take a look at the 'title' column, how many unique title codes are there?**

In [9]:
len(df['title'].unique())

**Creating new features
In the titles column there are "Reasons/Departments" specified before the title code. These are EMS, Fire, and Traffic. Use .apply() with a custom lambda expression to create a new column called "Reason" that contains this string value.
For example, if the title column value is EMS: BACK PAINS/INJURY , the Reason column value would be EMS.******

In [11]:
df['Reasons']=df['title'].apply(lambda x:x.split(':')[0])
df['Reasons'].head()

**What is the most common Reason for a 911 call based off of this new column?**

In [12]:
k=df.Reasons.value_counts().head(3)
k

**Now use seaborn to create a countplot of 911 calls by Reason.**

In [13]:
sns.countplot('Reasons',data=df,palette='viridis')

**Now let us begin to focus on time information. What is the data type of the objects in the timeStamp column?******

In [14]:
type(df['timeStamp'].iloc[0])

**you should have seen that these timestamps are still strings. Use pd.to_datetime to convert the column from strings to DateTime objects.**

In [15]:
df['timeStamp']=pd.to_datetime(df['timeStamp'])
df['timeStamp'].iloc[0]

**** You can now grab specific attributes from a Datetime object by calling them. For example:**

    time = df['timeStamp'].iloc[0]
    time.hour

 Now that the timestamp column are actually DateTime objects, use .apply() to create 3 new columns called Hour, Month, and Day of Week. **

In [16]:
df['Hour']=df.timeStamp.apply(lambda x:x.hour)
df['Month']=df.timeStamp.apply(lambda x:x.month)
df['day of week']=df.timeStamp.apply(lambda x:x.dayofweek)
df['day of week'].head()

****Notice how the Day of Week is an integer 0-6. Use the .map() with this dictionary to map the actual string names to the day of the week:
    dmap = {0:'Mon',1:'Tue',2:'Wed',3:'Thu',4:'Fri',5:'Sat',6:'Sun'}****

In [18]:
dmap = {0:'Mon',1:'Tue',2:'Wed',3:'Thu',4:'Fri',5:'Sat',6:'Sun'}
df['day of week']=df['day of week'].map(dmap)
df['day of week'].head()

In [19]:
sns.countplot(x='day of week',data=df,hue='Reasons',palette='viridis')
plt.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)

**Now let's move on to creating heatmaps with seaborn and our data. We'll first need to restructure the dataframe so that the columns become the Hours and the Index becomes the Day of the Week. There are lots of ways to do this, but I would recommend trying to combine groupby with an unstack method. **

In [20]:
piv=df.groupby(['day of week'])['Hour'].value_counts().unstack()
piv.head()

In [21]:
pivm=df.groupby(['day of week'])['Month'].value_counts().unstack()
pivm.head()
plt.figure(figsize=(12,6))
sns.heatmap(pivm,cmap='viridis')