In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
import seaborn as sns
import plotly.figure_factory as ff
import plotly.express as px
import plotly.graph_objs as go
from plotly.offline import iplot
import matplotlib.pyplot as plt

**IMPORTING DATASET**

In [ ]:
df=pd.read_csv('../input/amazon-top-rated-smartphones-accessories-2021/Amazon Top Rated Smartphones  Accessories 2021   - amazon_top_rated_smartphones.csv')

In [ ]:
df.head()

**CHECKING FOR NULL VALUES**

In [ ]:
df.isnull().sum()

In [ ]:
sns.heatmap(df.isnull())

In [ ]:
df.describe()

# FINDING TOP 10 COMAPNIES ACCORDING TO NUMBER OF MODELS

In [ ]:
names = df['Smartphone']
names=names.str.lower()
names.head()
from collections import Counter
lis = []
for i in names:
    for j in i.split():
        lis.append(j)
# Calculating frequency of all words
freq = Counter(lis)
     
most_occur = freq.most_common(100)
print(most_occur)

**FROM ABOVE LIST OF MOST OCCUCRING WORDS WE CAN GET ROUGH IDEA OF THE BRANDS THAT ARE IN THE TOP 10:**
*  apple
* samsung
* nillkin
* redmi
* vivo
* oppo
* mi
* realme
* lava
* oneplus

In [ ]:
top_companies=['apple','samsung','nillkin','redmi','vivo','oppo','mi','realme','lava','oneplus']
no_of_models=[]
for i in top_companies:
    no_of_models.append(freq[i])


fig = plt.figure(figsize = (15, 5))
plt.bar(top_companies, no_of_models)
plt.xlabel("Companies")
plt.ylabel("No. of models")
plt.title("Number of models of top companies")
plt.show()

# CALCULATING AVERAGE RATING PER MODEL OF EACH COMAPANY

In [ ]:
r_apple=0
n_apple=0
r_samsung=0
n_samsung=0
r_nillkin=0
n_nillkin=0
r_redmi=0
n_redmi=0
r_vivo=0
n_vivo=0
r_oppo=0
n_oppo=0
r_mi=0
n_mi=0
r_realme=0
n_realme=0
r_lava=0
n_lava=0
r_oneplus=0
n_oneplus=0
c=0
for i in names:
    for j in i.split():
        #if float(df['Rating'][c][0:3])<4.2:
           # print(i)
        if(j=='apple'):
            r_apple = r_apple +float(df['Rating'][c][0:3])
            n_apple=n_apple+1
            break
        if(j=='samsung'):
            r_samsung = r_samsung +float(df['Rating'][c][0:3])
            n_samsung=n_samsung+1
            break
        if(j=='nillkin'):
            r_nillkin = r_nillkin +float(df['Rating'][c][0:3])
            n_nillkin=n_nillkin+1
            break
        if(j=='redmi'):
            r_redmi = r_redmi +float(df['Rating'][c][0:3])
            n_redmi=n_redmi+1
            break
        if(j=='vivo'):
            r_vivo = r_vivo +float(df['Rating'][c][0:3])
            n_vivo=n_vivo+1
            break
        if(j=='oppo'):
            r_oppo = r_oppo +float(df['Rating'][c][0:3])
            n_oppo=n_oppo+1
            break
        if(j=='mi'):
            r_mi = r_mi +float(df['Rating'][c][0:3])
            n_mi=n_mi+1
            break
        if(j=='realme'):
            r_realme = r_realme +float(df['Rating'][c][0:3])
            n_realme=n_realme+1
            break
        if(j=='lava'):
            r_lava = r_lava +float(df['Rating'][c][0:3])
            n_lava=n_lava+1
            break
        if(j=='oneplus'):
            r_oneplus = r_oneplus +float(df['Rating'][c][0:3])
            n_oneplus=n_oneplus+1
            break
        
    c=c+1
avgr=[]
avgr_apple =r_apple/n_apple
avgr.append(avgr_apple)
avgr_samsung = r_samsung/n_samsung
avgr.append(avgr_samsung)
avgr_nillkin = r_nillkin/n_nillkin
avgr.append(avgr_nillkin)
avgr_redmi = r_redmi/n_redmi
avgr.append(avgr_redmi)
avgr_vivo = r_vivo/n_vivo
avgr.append(avgr_vivo)
avgr_oppo = r_oppo/n_oppo
avgr.append(avgr_oppo)
avgr_mi = r_mi/n_mi
avgr.append(avgr_mi)
avgr_realme = r_realme/n_realme
avgr.append(avgr_realme)
avgr_lava = r_lava/n_lava
avgr.append(avgr_lava)
avgr_oneplus = r_oneplus/n_oneplus
avgr.append(avgr_oneplus)
fig = plt.figure(figsize = (15, 5))
plt.bar(top_companies, avgr)
plt.xlabel("Companies")
plt.ylabel("Average Ratings")
plt.title("Average rating of top companies")
plt.show()

**HERE WE CAN SEE THAT AVERAGE RATING PER MODEL IS HIGHEST FOR NILLKIN AND IT IS LOWEST FOR SAMSUNG**

# FINDING PRICE RANGE HAVING HIGHEST NUMBER OF GOOD RATING

In [ ]:
n_1=0
n_2=0
n_3=0
n_4=0
n_5=0
n_6=0
n_7=0
n_8=0
n_9=0
n_10=0
r_1=0
r_2=0
r_3=0
r_4=0
r_5=0
r_6=0
r_7=0
r_8=0
r_9=0
r_10=0
for i in range(0,1368):
    if df['Offer price'][i] is not 'nan':
        df['Offer price'][i]=str(df['Offer price'][i]).replace(',','')
        df['Offer price'][i]=str(df['Offer price'][i]).replace('â‚¹','')
        df['Offer price'][i]=float(df['Offer price'][i])
        if 0<df['Offer price'][i] and df['Offer price'][i]<10000:
            n_1=n_1+1
            r_1=r_1+float(df['Rating'][i][0:3])
        if 10000<df['Offer price'][i] and df['Offer price'][i]<20000:
            n_2=n_2+1
            r_2=r_2+float(df['Rating'][i][0:3])
        if 20000<df['Offer price'][i] and df['Offer price'][i]<30000:
            n_3=n_3+1
            r_3=r_3+float(df['Rating'][i][0:3])
        if 30000<df['Offer price'][i] and df['Offer price'][i]<40000:
            n_4=n_4+1
            r_4=r_4+float(df['Rating'][i][0:3])
        if 40000<df['Offer price'][i] and df['Offer price'][i]<50000:
            n_5=n_5+1
            r_5=r_5+float(df['Rating'][i][0:3])
        if 50000<df['Offer price'][i] and df['Offer price'][i]<60000:
            n_6=n_6+1
            r_6=r_6+float(df['Rating'][i][0:3])
        if 60000<df['Offer price'][i] and df['Offer price'][i]<70000:
            n_7=n_7+1
            r_7=r_7+float(df['Rating'][i][0:3])
        if 70000<df['Offer price'][i] and df['Offer price'][i]<80000:
            n_8=n_8+1
            r_8=r_8+float(df['Rating'][i][0:3])
        if 80000<df['Offer price'][i] and df['Offer price'][i]<90000:
            n_9=n_9+1
            r_9=r_9+float(df['Rating'][i][0:3])
        if 90000<df['Offer price'][i] and df['Offer price'][i]<100000:
            n_10=n_10+1
            r_10=r_10+float(df['Rating'][i][0:3])
                
l=[r_1/n_1,r_2/n_2,r_3/n_3,r_4/n_4,r_5/n_5,r_6/n_6,r_7/n_7,r_8/n_8,r_9/n_9,r_10/n_10]
fig = plt.figure(figsize = (15, 5))
plt.bar(['0-10000','10000-20000','20000-30000','30000-40000','40000-50000','50000-60000','60000-70000','70000-80000','80000-90000','90000-100000'],l)
plt.xlabel("Range of Prices in rupees")
plt.ylabel('Average rating for the range')
plt.title("Averagee rating according to price range")
plt.show()

**HERE IT IS CLEAR THAT PRICE RANGE 90,000-1,00,000 HAS HIGHEST AVERAGE RATING AND PRICE RANGE 10,000-20,000 IS HAVING LOWEST**

**ANOTHER THING TO NOTE HERE IS AS PRICE IS INCREASED AVERAGE RATING IS SLIGHTLY INCREASING**

**COMMENT FOR ANY SUGGESTION AND
UPVOTE IF YOU LIKE IT!**