In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Content

List of 700+ Unicorn Companies across the globe.

Well, Unicorn company? A company which has a valuation of over $1 billion.

A unicorn company, or unicorn startup, is a private company with a valuation over $1 billion. As of June 2021, there are more than 700 unicorns around the world.

New subsets include a decacorn, companies which are valued at over $10 billion, and a hectocorn, companies which are valued at over $100 billion.

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings 
warnings.filterwarnings("ignore")

In [ ]:
df = pd.read_csv("../input/list-of-700-unicorn-companies-across-the-globe/List of 700 Unicorn Companies.csv")

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df["Valuation (in $B)"] = df["Valuation (in $B)"].apply(lambda x : x.replace("$",""))

In [ ]:
df["Valuation (in $B)"] = df["Valuation (in $B)"].astype("float")

In [ ]:
df["Valuation (in $B)"].describe()

# EDA

## Country of origin

### Counts of Country of origin

In [ ]:
df["Country of origin"].value_counts()

In [ ]:
# Top 10
plt.figure(figsize=(12,6))
sns.countplot(data=df,x="Country of origin", order = df["Country of origin"].value_counts().iloc[:10].index)
plt.show()

### Valuation of Country of origin

In [ ]:
top_10 = pd.DataFrame(df.groupby(['Country of origin'])['Valuation (in $B)'].sum().sort_values(ascending=False)[:10])
top_10

In [ ]:
plt.figure(figsize=(12,7))
sns.barplot(data=top_10, x=top_10.index, y="Valuation (in $B)")

plt.show()

## Industries

### Counts of Industries

In [ ]:
df["Industry"].value_counts()

In [ ]:
plt.figure(figsize=(20,10))
sns.countplot(data=df,y="Industry", order = df["Industry"].value_counts()[:10].index)
plt.show()

### Valuation of Industries

In [ ]:
top_10 = pd.DataFrame(df.groupby(['Industry'])['Valuation (in $B)'].sum().sort_values(ascending=False)[:10])
top_10

In [ ]:
plt.figure(figsize=(15,7))
sns.barplot(data=top_10, x="Valuation (in $B)", y=top_10.index)
plt.show()

## City

### Counts of City

In [ ]:
df["City"].value_counts()[:10]

In [ ]:
plt.figure(figsize=(12,8))
sns.countplot(data=df,x="City", order=df["City"].value_counts()[:10].index)
plt.grid(axis="y",color="r", linestyle="--")
plt.show()

### Valuation of City

In [ ]:
top_10 = pd.DataFrame(df.groupby(['City'])['Valuation (in $B)'].sum().sort_values(ascending=False)[:10])
top_10

In [ ]:
plt.figure(figsize=(12,7))
sns.barplot(data=top_10, x=top_10.index, y="Valuation (in $B)")

plt.show()