In [23]:
from nltk import pos_tag
import pandas as pd

In [24]:
dataset = pd.read_csv('../input/amazon-reviews-unlocked-mobile-phones/Amazon_Unlocked_Mobile.csv')
dataset['Reviews']=dataset['Reviews'].astype(str) #it is used to convert the type of Reviews from float to string

In [25]:
dataset.head()

                                        Product Name     ...      Review Votes
0  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...     ...               1.0
1  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...     ...               0.0
2  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...     ...               0.0
3  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...     ...               0.0
4  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...     ...               0.0

[5 rows x 6 columns]

In [ ]:
tagged_Reviews = dataset['Reviews'].str.split().map(pos_tag)
tagged_Reviews.head()
dataset['Tagged_Review'] = tagged_Reviews

*Download created csv*

In [ ]:
from IPython.display import HTML
import numpy as np

dataset.to_csv('submission.csv') #dataframe that will be downloaded as csv

def create_download_link(title = "Download CSV file", filename = "data.csv"):  
    html = '<a href={filename}>{title}</a>'
    html = html.format(title=title,filename=filename)
    return HTML(html)

# create a link to download the dataframe which was saved with .to_csv method
create_download_link(filename='submission.csv')

In [26]:
dataset = pd.read_csv('../input/tagged-amazon-reviews/Amazon_Unlocked_Mobile_Tagged.csv')

In [27]:
# selecting a part of the dataframe
sample_df = dataset[:10]
sample_df

   Unnamed: 0                        ...                                                              Tagged_Review
0           0                        ...                          [('I', 'PRP'), ('feel', 'VBP'), ('so', 'RB'), ...
1           1                        ...                          [('nice', 'JJ'), ('phone,', 'NN'), ('nice', 'J...
2           2                        ...                                        [('Very', 'RB'), ('pleased', 'JJ')]
3           3                        ...                          [('It', 'PRP'), ('works', 'VBZ'), ('good', 'JJ...
4           4                        ...                          [('Great', 'NNP'), ('phone', 'NN'), ('to', 'TO...
5           5                        ...                          [('I', 'PRP'), ('already', 'RB'), ('had', 'VBD...
6           6                        ...                          [('The', 'DT'), ('charging', 'VBG'), ('port', ...
7           7                        ...                          [('Phone', 'NNP'), ('looks', 'VBZ'), ('good', ...
8           8                        ...                          [('I', 'PRP'), ('originally', 'RB'), ('was', '...
9           9                        ...                          [("It's", 'NNP'), ('battery', 'NN'), ('life', ...

[10 rows x 8 columns]

In [28]:
import spacy
nlp = spacy.load('en')

dataset.review = sample_df.Reviews.str.lower()

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  after removing the cwd from sys.path.

In [29]:
aspect_terms = []
for review in nlp.pipe(dataset.review):
    chunks = [(chunk.root.text) for chunk in review.noun_chunks if chunk.root.pos_ == 'NOUN']
    aspect_terms.append(' '.join(chunks))

In [30]:
sample_df['aspect_terms'] = aspect_terms

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [31]:
sample_df

   Unnamed: 0                        ...                                                               aspect_terms
0           0                        ...                          phone phone line someone one son one years upg...
1           1                        ...                          phone grade revue phone size surfing media sam...
2           2                        ...
3           3                        ...
4           4                        ...                          phone phone thing volume button settings job p...
5           5                        ...                          phone problems comments item side goods money ...
6           6                        ...                               port battery cost purchase phone phone state
7           7                        ...                                                       phone battery person
8           8                        ...                          galaxy sprint epic g sprint keyboard size phon...
9           9                        ...                                            life issue screen button screen

[10 rows x 9 columns]