In [ ]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("Select specific columns and rows:")
print(df.iloc[[1, 3, 5, 6], [1, 3]])

In [ ]:
# Read a dataset with missing values
flights = pd.read_csv("../input/titanic/train_and_test2.csv")
  # Select the rows that have at least one missing value
flights[flights.isnull().any(axis=1)].head()

In [ ]:
import random 
import matplotlib.pyplot as plt

height = []
   
for i in range(50):
    height.append(random.randint(60, 80))
height[10] = 172
height[20] = 172
height[30] = 12
height[40] = 12
   
plt.boxplot(height)
plt.show()