In [ ]:
#IMPORT NECESSARY LIBRARIES

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
df = pd.read_csv('../input/cardiogoodfitness/CardioGoodFitness.csv')

In [ ]:
df.head()

In [ ]:
df['Product'].value_counts()

**We can see that there are only a few columns available in the data. We need to find out the type of Treadmill one would choose on the basis of his/her age, gender, education, marital status etc.**

In [ ]:
df.describe()

In [ ]:
df.info()

**We do not have any null values in our data set which makes it easier for us to conduct our data analysis.
**

In [ ]:
#changing it to  object dtype to category  to save memory
df.Product=df["Product"].astype("category")
df.Gender=df["Gender"].astype("category")
df.MaritalStatus=df["MaritalStatus"].astype("category")

In [ ]:
df[df['Product']=='TM195'].describe().T
#.T is used to transform the data.

**OBSERVATIONS**

Some of the important conclusions that can be drawn by looking at our results are:

* Exactly 80 customers purchased TM195 Model.
* The average age of customers who bought TM195 is 28.5, whereas the min and max age is 18 and 50 respectively.
* Average Education is 15 and median is 16.
* Expected usage is 3 day a week

In [ ]:
df[df['Product']=='TM498'].describe().T

**OBSERVATIONS
**
* There are 60 customers who purchased TM 498 Model
* Average age of customer who purchases TM498 is 28.9 , Median is 26 . Age is right skewed. Customer range is between 24-33.
* Average Education is 15 and median is 16.
* Expected usage is 3 day a week

In [ ]:
df[df['Product']=='TM798'].describe().T

**OBSERVATIONS**

* Average age of customer who purchases TM798 is 29 , Median is 27 .
* Average Education is 17 and median is 18.
* Expected usage is 4-5 day a week

In [ ]:
pd.crosstab(df['Gender'], df['Product'])

* Equal number of customers who purchased TM195 were Male as well as Female.
* Number of customers who purchased TM498 were more Males than Females.
* There are considerably more Males than there are Females who purchased TM798.

In [ ]:
pd.crosstab(df['Fitness'], df['Product'])

**Now lets try visualizing the data a little bit.**

In [ ]:
sns.countplot(x='Product', hue='Gender', data=df)

In [ ]:
sns.pairplot(df)

We can play around with pairplot by giving hue to the data i.e. in relation to which columm we want the plot.

In [ ]:
#For Example
sns.color_palette("hls", 8)
sns.pairplot(df, hue='Gender')

In [ ]:
df.corr()

In [ ]:
plt.figure(figsize=(12,6))
sns.heatmap(df.corr(), annot=True)

In [ ]:
#Univariate Analysis
#categorical variables 

df['Product'].value_counts().plot.pie(autopct='%1.1f%%',figsize=(6,6))
plt.title("Pie chart of Product Sales")
plt.show()

In [ ]:
sns.scatterplot(x='Age', y='Income', hue='Product', data=df)

We can conclude that people with income groups equal to or higher that 50,000 tend to buy TM798

In [ ]:
plt.figure(figsize=(7,7))
sns.countplot(df['Gender'],hue=df["MaritalStatus"]).set(title='MARTIAL STATUS BY GENDER')

In [ ]:
#scatter plot between income, age ,product and usage
sns.relplot(x="Age", y="Income", hue="Product", size="Usage",
            sizes=(40, 400), alpha=.5,
            height=6, data=df).set(title='INCOME BY AGE ,PRODUCT AND USAGE');

OBSERVATION

* Products TM195 and TM498 are bought by people with lower than 70K as income and age is concentrated more in range of 23-35
* Product TM798 is mainly bought by people with higher than 70K income and age falls in range of 23-30. 
* Majority of people who buys the TM798 expect that they will run more than consumers of the other two products, on average.