In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [ ]:
df=pd.read_csv('/kaggle/input/2018-chicago-employees-salaries/chicago_employees.csv')

We begin by explorung the data and see something interesting

In [ ]:
df.head()

In [ ]:
df.shape

In [ ]:
df.describe()

In [ ]:
df.info()

In [ ]:
df.isnull().sum()

We see that the column "Hourly Rate" has too many null values, and it's obvious that this variable is correlated with a linear function to annual salary, which is the part that we want to see details and relations about it. so we gonna remove this column anyway.

In [ ]:
df.drop('Hourly Rate',axis=1, inplace=True)

Now let's see the some descriptive statistics about annual salary

In [ ]:
#for i in df["Annual Salary"]:
    #print(type(i))

So we need to convert this attribute to integers.

Feature engineering

We first replace the $ sign from the each row that has the number and ve omit the .00 value of the cents( With respect to the median that we will see in the following, cents are neglectable in this model)

In [ ]:
for i in range(df["Annual Salary"].size):
    if(type(df["Annual Salary"][i])==str):
            df["Annual Salary"][i]=df["Annual Salary"][i].replace("$","")
            df["Annual Salary"][i]=df["Annual Salary"][i].replace(".00","")

In [ ]:
df["Annual Salary"].head(10)

In [ ]:
for i in range(df["Annual Salary"].size):
    if(type(df["Annual Salary"][i])==str):
        if(not df["Annual Salary"][i]==False):
            df["Annual Salary"][i]=float(df["Annual Salary"][i])

We see that some values have other cents amount.

In [ ]:
df["Annual Salary"].plot(kind='hist',title="Annual Salary Histogram with null values included")

In [ ]:
df["Annual Salary"].plot.kde()

In [ ]:
df["Annual Salary"].describe()

Now we replace the missing values for Annual Salary column with the median of the sample, and then we're gonna replace it with mean sample and see the differences.

In [ ]:
#median=df["Annual Salary"].median()
#value1={"Annual Salary": median}
#df2=df.fillna(value=value1)
mean=df["Annual Salary"].mean()
value2={"Annual Salary": mean}
df2=df.fillna(value=value2)

In [ ]:
#ALREADY RUNED AND COPPIED

df3["Annual Salary"].plot(kind='hist',title="Histogram of Annual Salary after filling nulls with mean")

Now we are done with this column and and we need to check the typical hour column

In [ ]:
df2["Typical Hours"].value_counts()

As we see, only near 8000 rows have non-null values and the 25% of the population has 20 hours for this column, we will need to do something about this problem, but first let make another data frame without this column and do some analysis

In [ ]:
df1= df2.drop("Typical Hours", axis=1, inplace=False)

In [ ]:
df1["Full or Part-Time"].value_counts()

So by this we can manage the Typical Hours Salary, since if someone is emplpyed as a full time position, they will have to work 40 hours per week.

Lets see what we can find from job titles column

In [ ]:
df["Department"].value_counts()

we see that we have 1111 unique values into the 33183 samples and Police Officer is the most job used with 9520 times used. So with having this in mind, spilit the dataset by jobs may sound interesting, lets see what we can get about pollice officers.

In [ ]:
df["Job Titles"]

In [ ]:
police=df1[df1["Department"]=="POLICE"]
#now lets see how much Finance people make
finance=df1[df1["Department"]=="FINANCE"]

In [ ]:
it=df1[df1["Department"]=="DoIT"]

In [ ]:
it["Annual Salary"].describe()

Lets see the distributions

In [ ]:
police["Annual Salary"].describe()

In [ ]:
finance["Annual Salary"].describe()

In [ ]:
df1["Annual Salary"].describe()

In [ ]:
police["Annual Salary"].mean()

In [ ]:
police["Annual Salary"].std()

Now lets fit a kernel density function to the distribution of policemen salaries:

In [ ]:
it["Annual Salary"].plot.kde(title="IT section KDE fitted plot / mean null values")

now lets see what other titles can say more

In [ ]:
finance["Annual Salary"].plot.kde(title="Finance section KDE fitted plot/ mean null values")

In [ ]:
police["Annual Salary"].plot.kde(title='Police section KDE fitted plots/ mean null values')

from this plot the first guess is that the group of policemen can be devided in two general part like part A and part B which part A represents the left peak and part B represent the right peak.
The very first other guess is that the part A is the entry level ones with less experience while the group B is the ones with higher experience

In [ ]:
df1["Annual Salary"].plot.kde(title='All salaries KDE fitted plots/ mean null values')

In [ ]:
police["Annual Salary"].plot.kde(bw_method=0.4)

In [ ]:
df["Annual Salary"].plot.kde(bw_method=0.2)

Now it's more reasonable since data now has more normal distribution, now lets see the outliers

In [ ]:
out1=df[df["Annual Salary"]>180000]
out2=df[df["Annual Salary"]<30000]

In [ ]:
out1.to_csv("best.csv")

In [ ]:
out2.to_csv("worst.csv")

This two list can say what are the best jobs and worst jobs in chicago according to this dataset.

In [ ]:
x=df[df["Department"]=="POLICE"]

In [ ]:
x

In [ ]:
x["Annual Salary"].plot.kde()

The distribution of salaries in the police department