In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
df = pd.read_csv('/kaggle/input/7k-indian-famous-women/data.csv')
df.head()

In [ ]:
df.shape

In [ ]:
df.isna().sum()  #we have quite a few null values to deal with

In [ ]:
df[['Description','Job']].sample(10)
#it seems like both the columns convey the same thing. It is safe to drop Description column
#actually no we can fill the missing values of job column with description since ** THEYRE MORE OR LESS THE SAME **

In [ ]:
df[df['Job'].isna()].head()  #observe 46th data

In [ ]:
df['Job'] = df['Job'].fillna(df['Description'])

In [ ]:
df.iloc[46]  # here we can see that our values have been updated, awesome

In [ ]:
df.isna().sum()  #the null values in Job column have dropped down drastically, yaaay

In [ ]:
df = df.drop(['Description'],axis=1)  #dropping the column we dont need

In [ ]:
df['Job'].value_counts()  # we have 423 job categories they all fall under

In [ ]:
plot1 = df['Job'].value_counts()[:10]

In [ ]:
px.bar(plot1,
      x='Job',
      text = 'Job',
      title = 'Top 10 professsions among popular ladies')

# It is clearly obvious about the impact of the film industry on this generation
# (Film Actor and Directors storm into the top 10 list)

In [ ]:
df['Country'].value_counts() # we have a bunch of settled foreigners in India

In [ ]:
#before we visualize, we can convert all the countries with values <= 5 to Others since they are significantly low compared to
#the others

In [ ]:
df['Country'] = df['Country'].replace(["Australia",                        
"Canada",                           
"Pakistan",                        
"Switzerland",                      
"Nigeria",                     
"Germany",                          
"Italy",                           
"Malaysia",                         
"Japan",                           
"France",                          
"Kuwait",                      
"South Africa",                     
"Bangladesh",              
"Kingdom Of The Netherlands",       
"Brazil",                           
"Portugal",                         
"Albania",                          
"New Zealand",                      
"Sweden",                           
"Czech Republic",                   
"Dominican Republic",               
"Nepal"],'Other')

In [ ]:
df.Country.value_counts()

In [ ]:
px.bar(df.Country.value_counts(),
      x='Country',
      text = 'Country',
      title = 'Having a look at the nationalities')

# Self explanatory , most of them are from India by a far distance, the closest to come is British India(makes sense, like theyre Indian :p

In [ ]:
df['Birth Place'].value_counts()[:5]  #most of them seem to be from North India

In [ ]:
px.bar(df['Birth Place'].value_counts()[:5],
      x='Birth Place',
      text = 'Birth Place',
      title = 'Top 10 Cities among these celebrities')

In [ ]:
df['Death Method'].value_counts()

In [ ]:
sns.countplot(data = df, x= df['Death Method'])

# MOST OF THE OTHER FEATURES HAVE A LOT OF MISSING VALUES .SO IT DIDNT MAKE SENSE TO USE THEM. THANKS FOR STOPPING BY :)