# Data Science Çalışma Notları 
**[Kaan Can Yılmaz](https://www.kaggle.com/kanncaa1)**'ın hazırlamış olduğu  [Data Science Sıfırdan Uzmanlğa Veri Bilimi](https://www.udemy.com/data-science-sfrdan-uzmanlga-veri-bilimi-2/learn/v4/overview) kursuna devam ederken kurstaki ödevlerimi yapmış olduğum çalışma notlarım.

#### Dataset Hakkında
Ödevlerde Car Sale Advertisement datasetini kullanmaya karar verdim .
 
 Car Sale Advertisement dataseti; Ukrayna'da özel araç satışı reklamlarından toplanan verilerden oluşmaktadır.
 
 İçerisindekiler;
 * car : araba ismi 
 * price : fiyatı
 * body : araba gövde tipi
 * mileage : kilometresi
 * engV : motor hacmi
 * engType : motor tipi
 * registration : kayıt 
 * year : yılı
 * drive :  sürücü

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import matplotlib.pyplot as plt
import seaborn as sns
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

**   Öncelikle csv dosyamızı okuyup içerisinde kaç satır, kaç sütun olduğuna bakıyoruz.**

  Datasetimiz 9576 satır ve 10 sütundan oluşuyor.

In [ ]:
data = pd.read_csv('../input/car_ad.csv',encoding ='iso-8859-9')
data.shape # kac satır kaç sütun var

 **Datasetimizim içerisindeki sütun isimlerine tekrar bakalım .**

In [ ]:
data.columns # sütun isimleri

**Datasetimiz hakkında genel  bir bilgi edinmemiz gerek.**

Aşağıda datasetimizin kaç satır satır ve sütundan oluştuğu, içerisindeği feature' ların tipleri ve kaç tane değer bulunduğunu görüyoruz.
Bazı feature'larda eksik değerler var gibi duruyor.

In [ ]:
data.info() # dataset hakkında genel bilgiler

**Feture'lardaki eksik değerleri kontrol ediyoruz.**

 Aşağıda engV ve drive feature'larında eksik değerler olduğunu görüyoruz.

In [ ]:
data.isnull().sum() # eksik verileri kontrol ediyoruz

**Datasetimizdeki int tipindeki değerler hakkında bilgi edinelim.**

Aşağıda genel olarak  int tipindeki tüm feature'ların maksimum - minimum değerlerini, ortalama olarak ne olduklarını ve kaç tane veri içerdikleini görüyoruz.

In [ ]:
data.describe() # datasetdeki sayısal değerler hakkında bilgiler
# ör. arabaların ortalama kilometresi, max kilometre, min kilometre

**Datasetimiz hakkında genel bir bilgi edindiğimize göre artık içerisindeki birkaç veriye bakıp üzerinde işlemler yapmaya başlayabiliriz.**

Aşağıda datasetimiz içerisindeki ilk beş veriyi listeliyoruz

In [ ]:
data.head() # ilk 5 veri

**Dataset içerisindeki feature'larda eşsiz olan kelimeleri görmek istiyoruz.**

Örneğin aşagıda Car sütununda kaç farklı değer olduğuna baktık; 87 tane farklı araba marksı bulunuyormuş. 
Diğer sütunlar için de aynı şey tekrarlanabilir.

In [ ]:
# sütunlarda ne kadar farklı değer var 
print(len(data.car.unique()))
data.car.unique() # (ör. kaç farklı araba markası var)
#data.engType.unique()
data.year.unique()
#data.model.unique()
#data.drive.unique()

**Dataset içerisindeği kolerasyonlara bakıyoruz.**

Aşağıda sayısal değerler arasındak kolerasyona baktığımızda çok fazla yüksek değerler göremiyoruz .

In [ ]:
data.corr()

**Scatter Plot ile değerler arasındaki kolerasyonları görselleştiriyoruz.**

Örneğin aşağıda yıl ve fiyat arasındaki kolerasyonuna görüyoruz. Yıllar arttıkça fiyatta artıyor gibi bir yorum yapamayız fakat genel olarak son yıllarda fiyatta bir artış gözlenmiş.

In [ ]:
# Scatter plot ile yıl-fiyat kolerasyonu 
data.plot(kind = 'scatter', x='year', y = 'price', alpha = 0.5, color = 'r')
plt.xlabel("year")
plt.ylabel("price")
plt.title("year - price Scatter Plot")
plt.show()

**Car sütununu veri sayılarına göre grupluyoruz**

Datasetimiz en çok  hangi araba markasında içeriyor ya da hangi markadan ne kadar var bakmak için grupluyor ve ilk 5 araba markasını yazdırıyoruz.

Sonuçlara baktığımızda en yüksek değer olarak Volkswagen ve Mercedes-Benz markalarını görüyoruz. İlerleyen adımlarda bu markalar üzerinden işlem yapabiliriz :)

In [ ]:
data_vc = data['car'].value_counts() # araba isimlerine göre grupluyor 
data_vc.head()

**Volkswagen arabaları  ayrı bir dataframe aktarıyoruz**

Üzerinde daha iyi işlem yapabilmek adına volkswagen adında ayı bir dataframe oluşturduk ve içerdiği ilk 10 veryi yazdırdık.
Görünüşe göre ayırma işlemimiz başarılı olmuş :)

In [ ]:
volkswagen = data[data.car == 'Volkswagen'] # Volkswagen olan arabaları ayrıyoruz
volkswagen.head(10) # 10 tanesini yazdırıyoruz

**Mercedes-Benz arabaları  ayrı bir dataframe aktarıyoruz**

Üzerinde daha iyi işlem yapabilmek adına mercedes_benz adında ayı bir dataframe oluşturduk ve içerdiği ilk 10 veryi yazdırdık.
Görünüşe göre ayırma işlemimiz başarılı olmuş :)

In [ ]:
mercedes_benz = data[data.car == 'Mercedes-Benz']# Mercedes-Benz olan arabaları ayrıyoruz
mercedes_benz.head(10) # 10 tanesini yazdırıyoruz

**Volkswagen ve Mercedes-Benz markası arabaların yıllara göre sayılarını Histogram ile görselleştiriyoruz.**

Aşağıdaki grafiklere göre  Volkswagen marka araba 2010-2015 yılları arasında  ve Mercedes-Benz marka arabaların 2000 yılından sonraki kısımda fazla sayıda olduğu gözüküyor.

In [ ]:
#Volkswagen yıllara göre sayılarını görselleştiriyoruz 
plt.hist(volkswagen.year, bins = 30)
plt.xlabel("year")
plt.ylabel("frekans")
plt.title("Volkswagen Hist")
plt.legend()
plt.show()
#Mercedes-Benz yıllara göre sayılarını görselleştiriyoruz 
plt.hist(mercedes_benz.year, bins = 30)
plt.xlabel("year")
plt.ylabel("frekans")
plt.title("Mercedes-Benz Hist")
plt.legend()
plt.show()

**2012 yılından sonraki arabaların listelenmesi**

2012 yılından sonra 1727  aracın bulunduğunu ve bunların listesini aşağıda görüyoruz.

In [ ]:
#yılı 2012 den büyük olanlar
x = data['year'] > 2012 
#x 
data[x]

**Yılı 2012 sonraki ve motor hacmi 3,00 den büyük araçların listesi**

2012 yılından sonra ve motor hacmi 3,00 den büyük 219 aracın bulunduğunu ve bunların listesini aşağıda görüyoruz.

In [ ]:
# yılı 2012 den , motor boyutu da 3,00 den büyük olanlar
#data[(data['year'] > 2012) & (data['engV'] > 3.00)] # bu şekilde de yapılabilir 
data[np.logical_and(data['year'] > 2012 , data['engV'] > 3.00)]

**Kendi istediğimiz araba markası ve modeline göre filtreleme**

Ford marka , Mustang model araba isteğimize göre bulunan arabalardan ilk sıradaki aracın özelliklerini aşağıda yazdırdık.

In [ ]:
#kendi isteğimize özel filtreleme yapıp ilk veriyi yazıdırdık
data_ozel = data[np.logical_and(data['car'] == 'Ford' , data['model'] == 'Mustang')]
for index, value in data_ozel[0:1].iterrows():
    print(index, ' : ', value)

**Fonksiyon ile isteklerimize göre Araba listeletme **

Aşağıda araba markası default olarak BMW verilmiş olan fonksiyonda model ve engV seçimimize göre arabaları listeletiyoruz.
İstediğimiz doğrultusunda  olan  arabalar  listenedi.

In [ ]:
engV = 5.0 # global
#user defined fonction
def Bmw(model, engV, car = 'BMW'):
    """BMW marka arabaların istenilen model ve motor hacmine göre listelenmesi"""
    data_ozel = data[(data['car'] == car) & ( data['model'] == model) & (data['engV'] == engV)]
    return data_ozel
data_ozel =Bmw('M5',engV)
data_ozel

**List Comprehension ile yeni sütun ekleme **

Kilometresi ortlama kilometreden daha yüksek olanlara 'high mileage', daha düşük olanlara da 'low mileage' yazdırdık.

In [ ]:
ort = sum(data['mileage']) / len(data['mileage'])
print("ortalama kilometre: ", ort)
data['mileage_level'] = ["high mileage" if i > ort else "low mileage" for i in data['mileage']]
data.loc[:10]

Yılı 2010'dan düşük olanlara 'eski model', 2010 - 2016 arasındakilere 'yeni model', diğer durumlar içinde 'son model' yazdırdık.

In [ ]:
data['year_model_level'] = ["eski model" if i<2010 else "yeni model" if(2016 > i) else "son model" for i in data['year']]
data.head(20)

**Anonymous Function ile Kapı sayısı arttırma**

Datasetimizdeki tüm arabaların kapı sayısını 2 kabul ederek 'kapi_sayisi' sütununu eklendik.

Daha sonra anonymous function kullanarak tüm arabaların kapı sayısını 2 daha arttırılıp 4 yaptık.

In [ ]:
data['kapi_sayisi'] = 2
data
data['kapi_sayisi'] =list(map(lambda  x: x + 2, data['kapi_sayisi']))
data