---

<h1 style="text-align: center;font-size: 40px;">Data Scientists Jobs </h1>

---

<center><img src="https://media.giphy.com/media/HUplkVCPY7jTW/giphy.gif"></center>

---

<h4>I was very curious to know about different job sectors of Data Science,about the salary,What are those industry which provides Data Science Jobs,Where are they Located,where's the Head Quarters of these Company,this Dataset really Help me to know all of these.. thanks to <a href = "http://https://www.kaggle.com/andrewmvd">andrewmvd </a> for providing this Dataset </h4>
<h4>This Dataset provides information,such as:</h4>
<h4>i.Salary Estimate</h4>
<h4>ii.Location</h4>
<h4>ii.Company Rating</h4>
<h4>iii.Job Description</h4>
<h4>iv.Company Name</h4>
<h4>v. Location</h4>
<h4>vi. Location of the Head uarters</h4>
<h4>vii. and more...</h4>

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [ ]:
df = pd.read_csv("/kaggle/input/data-scientist-jobs/DataScientist.csv")
df.head()

In [ ]:
df.info()

In [ ]:
df.describe()

<h4>There are some unnecessary columns,First drop these Columns</h4>

In [ ]:
df.drop(["Unnamed: 0","index"],axis=1,inplace=True)
df.head()

<h4>Let's split Salary Estimate into lower & upper bound</h4>
<h4>Let's assume Hours per week is 40 & Weeks per Year is 52</h4>

In [ ]:
hours_per_week = 40
weeks_per_year = 52

for i in range(df.shape[0]):
    salary_estimate = df.loc[i,"Salary Estimate"]
    salary_estimate = salary_estimate.replace("$", "")
    
    if "Per Hour" in salary_estimate:
        lower, upper = salary_estimate.split("-")
        upper, _ = upper.split("Per")
        upper= upper.strip()
        lower = int(lower) *hours_per_week*weeks_per_year*(1/1000)
        upper = int(upper) *hours_per_week*weeks_per_year*(1/1000)
        
    else:
        lower, upper = salary_estimate.split("-")
        lower = lower.replace("K", "")
        upper, _= upper.split("(")
        upper=upper.replace("K", "")
        upper = upper.strip()
    
        
    lower = int(lower)
    upper = int(upper)
    df.loc[i,"salary_estimate_lower_bound"] = lower
    df.loc[i,"salary_estimate_upper_bound"] = upper

<h4>Now let's split the "\n & rating" from company Name</h4>

In [ ]:
for i in range(df.shape[0]):
    name = df.loc[i,"Company Name"]
    if "\n" in name:
        name,_ = name.split("\n")
    df.loc[i,"Company Name"] = name

In [ ]:
df["Size"].value_counts()

<h4>Now let's splits the Size into lower & upper size</h4>

In [ ]:
for i in range(df.shape[0]):
    size = df.loc[i,"Size"]
    if "to" in  size:
        lower,upper = size.split("to")
        lower = lower.strip() 
        _, upper, _ = upper.split(" ")
        upper = upper.strip()
        lower = int(lower)
        upper = int(upper)
    elif "+" in size:
        lower,_ = size.split("+")
        lower = int(lower)
        upper = np.inf
    else:
        lower = np.nan
        upper = np.nan
    df.loc[i,"Minimum Size"] = lower
    df.loc[i,"Maximum Size"] = upper

In [ ]:
df.head()

In [ ]:
df.drop(["Salary Estimate","Size"],axis=1,inplace=True)
df.head()

In [ ]:
df["Minimum Size"].fillna(0,inplace=True)
df["Maximum Size"].fillna(0,inplace=True)

In [ ]:
df.isnull().sum()

<h3>Now let's visualize our Data</h3>
<h4>Let's see name of the Company Involved in Data Science </h4>

In [ ]:
plt.rcParams["figure.figsize"] = (12,9)
plt.style.use("classic")
color = plt.cm.PuRd(np.linspace(0,1,20))
df["Company Name"].value_counts().sort_values(ascending=False).head(20).plot.bar(color=color)
plt.title("Top 20 Company with Highest number of Jobs in Data Science",fontsize=20)
plt.xlabel("Company Name",fontsize=15)
plt.ylabel("Count",fontsize=15)
plt.show()

<h4> Let's see most Popular Data Science Job Title <h4>

In [ ]:
plt.rcParams['figure.figsize'] = (12,9)
color = plt.cm.BuPu(np.linspace(0,1,20))
df["Job Title"].value_counts().sort_values(ascending=False).head(20).plot.bar(color=color)
plt.title("Top 20 Data Science Job",fontsize=20)
plt.xlabel("Job Title",fontsize=15)
plt.ylabel("Count",fontsize=15)
plt.show()

<h4>Top 20 locations for Data Science Job</h4>

In [ ]:
plt.rcParams['figure.figsize'] = (12,9)
color = plt.cm.BuPu(np.linspace(0,1,20))
df["Location"].value_counts().sort_values(ascending=False).head(20).plot.bar(color=color)
plt.title("Top 20 locations for Data Science Job",fontsize=20)
plt.xlabel("Locations",fontsize=15)
plt.ylabel("Count",fontsize=15)
plt.show()

<h4>Top 20 Head Quarters of Data Science, Job Holder Company </h4>

In [ ]:
plt.rcParams['figure.figsize'] = (12,9)
color = plt.cm.BuPu(np.linspace(0,1,20))
df["Headquarters"].value_counts().sort_values(ascending=False).head(20).plot.bar(color=color)
plt.title("Top 20 Head Quarters of Data Science Job Holder Company",fontsize=20)
plt.xlabel("Head Quarters",fontsize=15)
plt.ylabel("Count",fontsize=15)
plt.show()

In [ ]:
color = plt.cm.PuRd(np.linspace(0,1,20))
df["Headquarters"].value_counts().sort_values(ascending=False).head(20).plot.pie(y="Headquarters",colors=color,autopct="%0.1f%%")
plt.title("Head Quarters according to Locations")
plt.axis("off")
plt.show()

<h4>So almost 15.6% Head Quarters are in New York</h4>
<h4> So most of the Head Quarters are in New York, & "-1" is the no. of  undeclared Head Quarters in the Dataset <h4>

In [ ]:
plt.rcParams['figure.figsize'] = (12,9)
color = plt.cm.PuRd(np.linspace(0,1,20))
df["Founded"].value_counts().sort_values(ascending=False)[1:21].plot.bar(color=color)
plt.title("Number of Company, Founded in a Year",fontsize=20)
plt.xlabel("Foundation Year",fontsize=15)
plt.ylabel("Count",fontsize=15)
plt.show()

<h4>So 1999 is the Year when almost 110 Company's with Data Science job has been Founded,then in the Year 2002 almost 100 company's with data science job has been Founded,so we can say that after 1999 ,demand of Data Science job has been Increased Rapidly</h4>

In [ ]:
plt.rcParams['figure.figsize'] = (12,9)
color = plt.cm.hsv(np.linspace(0,1,20))
df["Type of ownership"].value_counts().sort_values(ascending=False).plot.bar(color=color)
plt.title("Types of Ownership",fontsize=20)
plt.xlabel("Ownership",fontsize=15)
plt.ylabel("Count",fontsize=15)
plt.show()

<h4>A higher number of Data Science Company's are Private almost 1900 & then almost 1100 company's are Public & "-1" is the number of Undeclared Ownership of the Company</h4>

In [ ]:
plt.rcParams['figure.figsize'] = (12,9)
color = plt.cm.hsv(np.linspace(0,1,20))
df["Sector"].value_counts().sort_values(ascending=False).plot.bar(color=color)
plt.title("Different types of Sectors in DataScience",fontsize=20)
plt.xlabel("Sectors",fontsize=15)
plt.ylabel("Count",fontsize=15)
plt.show()

<h4>So most of the Data Science jobs are belongs to the sector of Information Technology</h4>
<h4> Top 10 Data Science job according to Salar.,Highest Salary of these Jobs are same,theye are 254k</h4>

In [ ]:
df[['Job Title','salary_estimate_upper_bound']].nlargest(10,"salary_estimate_upper_bound")

In [ ]:
plt.rcParams['figure.figsize'] = (12,9)
df[['Job Title','salary_estimate_upper_bound']].nlargest(10,"salary_estimate_upper_bound").plot.bar(x="Job Title",y="salary_estimate_upper_bound",color='cyan')
plt.title("Top 10 Jobs according to Salary",fontsize=20)
plt.xlabel("Job Title",fontsize=15)
plt.ylabel("Salary in 'k' ",fontsize=15)
plt.show()

In [ ]:
df["Maximum Size"].replace(np.inf,0,inplace=True)
df[['Company Name','Maximum Size']].nlargest(10,'Maximum Size')

<h4>Company's with Highest Number of Employees,all of these Company's has employees higher than 10000</h4>

In [ ]:
plt.rcParams['figure.figsize'] = (12,9)
df[['Company Name','Maximum Size']].nlargest(30,'Maximum Size').plot.bar(x="Company Name",y="Maximum Size",color='cyan')
plt.title("Company's with Highest Number of Employees",fontsize=20)
plt.xlabel("Company Name",fontsize=15)
plt.ylabel("No. of Employees",fontsize=15)
plt.show()

<h4>Let's make Word Cloud</h4>

<h4>1. Job Title </h4>

In [ ]:
from wordcloud import WordCloud
from wordcloud import STOPWORDS
stopwords = set(STOPWORDS)
wordcloud = WordCloud(background_color = 'yellow',
                      height =2000,
                      width = 2000
                     ).generate(str(df["Job Title"]))
plt.rcParams['figure.figsize'] = (12,12)
plt.axis("off")
plt.imshow(wordcloud)
plt.title("Most available Job Title")
plt.show()

<h4>So Data Scientist,Data Engineer,Data Analyst,Senior Data Scientist are the most available jobs. </h4>
<h4>2. Company Name</h4>

In [ ]:
from wordcloud import WordCloud
from wordcloud import STOPWORDS
stopwords = set(STOPWORDS)
wordcloud = WordCloud(background_color = 'lightgreen',
                      height =2000,
                      width = 2000
                     ).generate(str(df["Company Name"]))
plt.rcParams['figure.figsize'] = (12,12)
plt.axis("off")
plt.imshow(wordcloud)
plt.title("Most available Company")
plt.show()

<h4>3. Head Quarters</h4>

In [ ]:
from wordcloud import WordCloud
from wordcloud import STOPWORDS
stopwords = set(STOPWORDS)
wordcloud = WordCloud(background_color = 'lightpink',
                      height =2000,
                      width = 2000
                     ).generate(str(df["Headquarters"]))
plt.rcParams['figure.figsize'] = (12,12)
plt.axis("off")
plt.imshow(wordcloud)
plt.show()

In [ ]:
hq = pd.read_csv("../input/country/Country.csv")
hq.head()

<h4>Country's having Head quarters</h4>

In [ ]:
fig = px.choropleth(hq,   
    locationmode='country names',
    locations='Country',
    color="Country",
    featureidkey="Location",
    hover_name = "Country",
    labels=hq["No of HeadQuarters"],
    color_continuous_scale=px.colors.sequential.Plasma
)
fig.show()

<h4> Almost all of the Head Quarters are in United States </h4>

<div class="alert alert-block alert-info">
    <b></b><h3> ...........If the like this Notebook ,then Please Up Vote............👍</h3>
</div>