In [ ]:
41# This Python 3 environment comes with many helpful analytics libraries installed
# I0t is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
import pandas as pd

url ='/kaggle/input/test-file/tested.csv'

dataframe = pd.read_csv(url)
dataframe.head(6)

**describes the data******

In [ ]:
dataframe.shape

In [ ]:
dataframe.info()

In [ ]:
dataframe.info()

In [ ]:
dataframe['PassengerId']

In [ ]:
dataframe['PassengerId'].unique()

In [ ]:
dataframe['Embarked'].unique()

In [ ]:
dataframe['Sex'].value_counts()

In [ ]:
dataframe[dataframe['Age'].isnull()]

In [ ]:
dataframe.iloc[0]

In [ ]:
dataframe.iloc[6]

In [ ]:
df.iloc[400:]

In [ ]:
dataframe.iloc[0:10]

In [ ]:
df=dataframe
df.iloc[:7]

In [ ]:
df2=df.iloc[400:]

In [ ]:
df2

#select rows based condn.

In [ ]:
df[df['Sex']=='female']

In [ ]:
df[(df['Sex']=='female')&(df['Age']>65)]

In [ ]:
df[(df['Sex']=='female')&(df['Embarked']=='S')]

In [ ]:
df[(df['Sex']=='female')&(df['Age']>40)&(df['Survived']==1)]

**Replacing values**

In [ ]:
dataframe['Sex'].replace("female","Woman").head(2)

****Renaming column ****

In [ ]:
dataframe.rename(columns={'PClass':'Passenger Class','Sex':'Gender'}).head(2)

**Finding the Minimum,Maximum,Sum,Average,and Count**

In [ ]:
print('Maximum:',dataframe['Age'].max())
print('Mminimum:',dataframe['Age'].min())
print('Mean:',dataframe['Age'].mean())
print('Sum:',dataframe['Age'].sum())
print('Count:',dataframe['Age'].count())

**Finding the Unique value**

In [ ]:
dataframe['Sex'].unique ()

In [ ]:
dataframe['Sex'].value_counts ()

**Handing Missing File**

In [ ]:
dataframe[dataframe['Age'].isnull()].head(2)

In [ ]:
import numpy as np
dataframe['Sex']=dataframe['Sex'].replace('male',np.nan)

# **Deleting Column**

In [ ]:
dataframe.drop(['Age', 'Sex'], axis=1).head(2)

# **# Deleting Rows**

In [ ]:
dataframe[dataframe['Sex']!='male'].head(2)

# **Grouping Rows by Values**

In [ ]:
dataframe.groupby('Sex').mean()

In [ ]:
dataframe.groupby('Sex').count()

# **Grouping Rows by Time**

In [ ]:
import pandas as pd
import numpy as np
time_index = pd.date_range('06/06/2017',periods=100000, freq='30S')
dataframe=pd.DataFrame(index=time_index)
dataframe['Sale_Amount']=np.random.randint(1,10,100000)
dataframe.resample('W').sum()

# **Applying a Function over all element in a Column**

In [ ]:
def uppercase(x):
    return x.upper()

dataframe['Name'].apply(uppercase)[0:2]