In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [ ]:
data = pd.read_csv('../input/turkish-airlines-daily-stock-prices-since-2013/cleanThy.csv')

In [ ]:
#information of data
data.info()

In [ ]:
#the ration between data
data.corr()

In [ ]:
#correlation map #
f,ax = plt.subplots(figsize=(18, 18))
sns.heatmap(data.corr(), annot=True, linewidths=.5, fmt= '.1f',ax=ax)
plt.show()

In [ ]:
#top 10 data but ----- data.head() = top 5 data
data.head(10)

In [ ]:
#last 10 data
data.tail()

In [ ]:
data.columns

### MATPLOTLIB
Matplot is a python library that help us to plot data. The easiest and basic plots are line, scatter and histogram plots.
* Line plot is better when x axis is time.
* Scatter is better when there is correlation between two variables
* Histogram is better when we need to see distribution of numerical data.
* Customization: Colors,labels,thickness of line, title, opacity, grid, figsize, ticks of axis and linestyle

In [ ]:
# Line Plot
# color = color, label = label, linewidth = width of line, alpha = opacity, grid = grid, linestyle = sytle of line
data[' Lowest Price'].plot(kind = 'line', color = 'r',label = 'Lowest Price',linewidth=1,alpha = 0.5,grid = True,linestyle = ':',figsize = (15,15))
data[' Highest Price'].plot(kind = "line",color = 'b',label = 'Highest Price',linewidth=1, alpha = 0.5,grid = True,linestyle = '-.',figsize = (15,15))
plt.legend(loc='upper right')     # legend = puts label into plot
plt.xlabel('x axis')              # label = name of label
plt.ylabel('y axis')
plt.title('Price')            # title = title of plot
plt.show()

In [ ]:
# Scatter Plot =  correlation between two variables
# x = Lowest Price , y = Highest Price
data.plot(kind = 'scatter' , x=' Lowest Price', y=' Highest Price' , alpha = 0.5 , color = 'red', figsize = (12,12))
plt.xlabel('Lowest')
plt.ylabel('Highest')
plt.title('Price')
plt.show()

In [ ]:
#Alternative Code
plt.scatter(data[' Lowest Price'],data[' Highest Price'],alpha = 0.5,color='red')

In [ ]:
# Histogram
# bins = number of bar in figure
data[' Last Price'].plot(kind = 'hist',bins = 50 , figsize = (12,12))
plt.show()

In [ ]:
# clf() = cleans it up again you can start a fresh
data[' Last Price'].plot(kind = 'hist',bins = 50)
plt.clf()
# We cannot see plot due to clf()

### DICTIONARY
Why we need dictionary?
* It has 'key' and 'value'
* Faster than lists
<br>
What is key and value. Example:
* dictionary = {'game' : 'The Legend of Zelda'}
* Key is game.
* Values is The Legend of Zelda.
<br>
<br>**It's that easy.**
<br>Lets practice some other properties like keys(), values(), update, add, check, remove key, remove all entries and remove dicrionary.

In [ ]:
#create dictionary and look its keys and values
dic = {'Lowest Price' : '13.02','Highest Price' : '13.28'}
print(dic.values())
print(dic.keys())

In [ ]:
# Keys have to be immutable objects like string, boolean, float, integer or tubles
# List is not immutable
# Keys are unique
dic['Lowest Price'] = '13.10'  #update existing entry
print(dic)
dic['Last Price'] = '13.25'  #add new entry
print(dic)
del dic['Lowest Price']        #remove entry with key 'Lowest Price'
print(dic)
print('Last Price' in dic)
dic.clear()                   # remove all entries in dict.Delete entire dictionary from memories so it gives error because dictionary is deleted
print(dic)

### PANDAS
What we need to know about pandas?
* CSV: comma - separated values

In [ ]:
data = pd.read_csv('../input/turkish-airlines-daily-stock-prices-since-2013/cleanThy.csv')

In [ ]:
# 1 - Filtering Pandas data frame
filter1 = data[' Lowest Price']>10
data[filter1]

In [ ]:
# 2 - Filtering pandas - use '&' for filtering.
data[(data[' Lowest Price']>10) & (data[' Highest Price']<15)]

### WHILE and FOR LOOPS
We will learn most basic while and for loops

In [ ]:
# Stay in loop if condition( i is not equal 5) is true
i = 0
while i < 5 :
    print('i is: ',i)
    i = i + 1
print(i,' is not less than 5')

In [ ]:
# Stay in loop if condition( i is not equal 5) is true
liste = [12,13,14,15]
for i in liste:
    print('Price :',i )
    
# Enumerate index and value of list
# index : value = 0:1, 1:2, 2:3, 3:4, 4:5
for index,value in enumerate(liste):
    print(index ,":", value)
    
# For dictionaries
# We can use for loop to achive key and value of dictionary. We learnt key and value at dictionary part.
dic={'First Price ':'12','Second Price:':'13'}
for key,value in dic.items():
    print(key,":",value)

In [ ]:
# For pandas we can achieve index and value
for index,value in data[[' Lowest Price']][0:4].iterrows():
    print(index," : ",value)

# 2. PYTHON DATA SCIENCE TOOLBOX

### USER DEFINED FUNCTION
What we need to know about functions:
* docstrings: documentation for functions. Example:
<br>for f():
    <br>"""This is docstring for documentation of function f"""
* tuble: sequence of immutable python objects. 
<br>cant modify values
<br>tuble uses paranthesis like tuble = (1,2,3)
<br>unpack tuble into several variables like a,b,c = tuble

In [ ]:
# example of what we learn above
def tuble_ex():
    """ return defined t tuble"""
    t = (11,12,13)
    return t
Lowest,Highest,Last = tuble_ex()
print(Lowest,Highest,Last)

### SCOPE
What we need to know about scope:
* global: defined main body in script
* local: defined in a function
* built in scope: names in predefined built in scope module such as print, len
<br><br>Lets make some basic examples

In [ ]:
# guess print what
x = 12
def f():
    x = 13
    return x
print(x)      # x = 12 global scope
print(f())    # x = 13 local scope

In [ ]:
# What if there is no local scope
x = 10
def f():
    y = 4*x        # there is no local scope x
    return(y)      # it uses global scope x
print(f())    
# First local scopesearched, then global scope searched, if two of them cannot be found lastly built in scope searched.

In [ ]:
# How can we learn what is built in scope
import builtins
dir(builtins)

### NESTED FUNCTION
* function inside function.
* There is a LEGB rule that is search local scope, enclosing function, global and built in scopes, respectively.

In [ ]:
#nested function

def Square():
    """return square of value"""
    def add():
        """add three local variable"""
        x = 5
        y = 6
        z = 8
        w = x+y+z
        return w 
    return add()**2
print(Square())

### DEFAULT and FLEXIBLE ARGUMENTS
* Default argument example:
<br> def f(a,pi = 3.14):
        """ pi = 3.14 is default argument"""
* Flexible argument example:
<br> def f(*args):
       """ *args can be one or more"""
<br>def f(** kwargs)
       """ **kwargs is a dictionary"""

In [ ]:
#default arguments

def f(x , y =  5 , z = 10):
    w = x + y + z
    return w
print(f(20))
# what if we want to change default arguments
print(f(7,8,9))

In [ ]:
#flexible arguments *args

def f(*args):
    for i in args:
        return i
print(f('Lowest , Highest , Last'))

# flexible arguments **kwargs that is dictionary
def f(**kwargs):
    for key,value in kwargs.items():
        print(key, ':' ,value)
    
f(country = 'France', capital = 'Monaco', population = 123456)

### LAMBDA FUNCTION
Faster way of writing function

In [ ]:
#lambda function
square = lambda x : x**2    # where x is name of argument
print(square(5))
total = lambda x,y,z : x+y+z    # where x,y,z are names of arguments
print(total(5,6,7))

### ANONYMOUS FUNCTİON
Like lambda function but it can take more than one arguments.
* map(func,seq) : applies a function to all the items in a list

In [ ]:
lis1 = [1,2,3]
z = map(lambda x : x**2,lis1)
print(z)
print(list(z))

### ITERATORS
* iterable is an object that can return an iterator
* iterable: an object with an associated iter() method
<br> example: list, strings and dictionaries
* iterator: produces next value with next() method

In [ ]:
#iteration example
name = "Monaco"
it = iter(name)
print(next(it))
print(*it)

zip(): zip lists

In [ ]:
#zip example
lis1 = [1,2,3]
lis2 = [4,5,6]
z = zip(lis1,lis2)
print(z)
z_list = list(z)
print(z_list)

### LIST COMPREHENSİON
**One of the most important topic of this kernel**
<br>We use list comprehension for data analysis often. 
<br> list comprehension: collapse for loops for building lists into a single line
<br>Ex: num1 = [1,2,3] and we want to make it num2 = [2,3,4]. This can be done with for loop. However it is  unnecessarily long. We can make it one line code that is list comprehension.

In [ ]:
#example of list comprehension
lis1 = [10,15,20]
lis2 = [i + 5 for i in lis1]
print(lis2)

[i + 1 for i in num1 ]: list of comprehension
<br> i +1: list comprehension syntax
<br> for i in num1: for loop syntax
<br> i: iterator
<br> num1: iterable object

In [ ]:
# Conditionals on iterable
lis1 = [5,10,15]
lis2 = [i + 5 if i>10 else i + 10 if i == 10 else i-5 for i in lis1]
print(lis2)

In [ ]:
#comprehension example
#Our treshold is Highest Price
treshold = sum(data[' Last Price'])/len(' Last Price')
data['price_level'] = ['High' if i > treshold else 'Low' for i in data[' Last Price']]
data.loc[:10,['price_level',' Last Price']]

# 3.CLEANING DATA

### DIAGNOSE DATA for CLEANING
We need to diagnose and clean data before exploring.
<br>Unclean data:
* Column name inconsistency like upper-lower case letter or space between words
* missing data
* different language

<br> We will use head, tail, columns, shape and info methods to diagnose data

In [ ]:
data = pd.read_csv('../input/turkish-airlines-daily-stock-prices-since-2013/cleanThy.csv')

In [ ]:
data.head()  # head shows first 5 rows

In [ ]:
# tail shows last 5 rows
data.tail()

In [ ]:
# columns gives column names of features
data.columns

In [ ]:
# shape gives number of rows and columns in a tuble
data.shape

In [ ]:
#information of data
data.info()

### EXPLORATORY DATA ANALYSIS
value_counts(): Frequency counts
<br>outliers: the value that is considerably higher or lower from rest of the data
* Lets say value at 75% is Q3 and value at 25% is Q1. 
* Outlier are smaller than Q1 - 1.5(Q3-Q1) and bigger than Q3 + 1.5(Q3-Q1). (Q3-Q1) = IQR
<br>We will use describe() method. Describe method includes:
* count: number of entries
* mean: average of entries
* std: standart deviation
* min: minimum entry
* 25%: first quantile
* 50%: median or second quantile
* 75%: third quantile
* max: maximum entry

<br> What is quantile?

* 1,4,5,6,8,9,11,12,13,14,15,16,17
* The median is the number that is in **middle** of the sequence. In this case it would be 11.

* The lower quartile is the median in between the smallest number and the median i.e. in between 1 and 11, which is 6.
* The upper quartile, you find the median between the median and the largest number i.e. between 11 and 17, which will be 14 according to the question above.

In [ ]:
#for example
print(data[' Volume'].value_counts(dropna = True)) # if there are nan values that also be counted

In [ ]:
data.describe() #ignore null entries  #%25 Q1 quartile -- %50 Q2 median----%75 Q3 qurtile

### VISUAL EXPLORATORY DATA ANALYSIS
* Box plots: visualize basic statistics like outliers, min/max or quantiles

In [ ]:
# Black line at top is max
# Blue line at top is 75%
# Red line is median (50%)
# Blue line at bottom is 25%
# Black line at bottom is min
# There are no outliers
data.boxplot(column = ' Highest Price',by = 'price_level')

<a id="20"></a> <br>
### TIDY DATA
We tidy data with melt().
Describing melt is confusing. Therefore lets make example to understand it.

In [ ]:
#Firstly I create new data
data_new = data.head()
data_new

In [ ]:
# lets melt
# id_vars = what we do not wish to melt
# value_vars = what we want to melt
melted = pd.melt(frame = data_new,id_vars = 'Date',value_vars = [' Lowest Price',' Highest Price'])
melted

### PIVOTING DATA
Reverse of melting.

In [ ]:
#Index is Date
# I want to make that columns are variable
# Finally values in columns are value
melted.pivot(index = 'Date',columns = 'variable',values = 'value')

### CONCATENATING DATA
We can concatenate two dataframe

In [ ]:
#Firstly I creat two data frame
data1 = data.head()
data2 = data.tail()
concat_data_row = pd.concat([data1,data2],axis=0) #axis = 0 in row
concat_data_row

In [ ]:
data1 = data.head()
data2 = data.tail()
concat_data_column = pd.concat([data1,data2],axis=1) 
concat_data_column

### DATA TYPES
There are 5 basic data types: object(string),booleab,  integer, float and categorical.
<br> We can make conversion data types like from str to categorical or from int to float
<br> Why is category important: 
* make dataframe smaller in memory 
* can be utilized for anlaysis especially for sklear(we will learn later)

In [ ]:
# lets convert object(str) to categorical and int to float.
data[' Lowest Price'] = data[' Lowest Price'].astype('category')
data[' Highest Price'] = data[' Highest Price'].astype('float')

In [ ]:
data.dtypes

### MISSING DATA and TESTING WITH ASSERT
If we encounter with missing data, what we can do:
* leave as is
* drop them with dropna()
* fill missing value with fillna()
* fill missing values with test statistics like mean
<br>Assert statement: check that you can turn on or turn off when you are done with your testing of the program

In [ ]:
# Lets look at does THY Price data have nan value
data.info()

In [ ]:
#Lets check type 2
data[' Highest Price'].value_counts(dropna = False)
#As you can see,there is no NaN value

In [ ]:
#Lets assume that our data have NaN value
#Lets drop NaN value
data[' Highest Price'].dropna(inplace = 1)  # inplace = True means we do not assign it to new variable. Changes automatically assigned to data
data[' Highest Price'].value_counts(dropna = False)

In [ ]:
#  Lets check with assert statement
# Assert statement:
assert 1==1 # return nothing because it is true

In [ ]:
# In order to run all code, we need to make this line comment
# assert 1==2 # return error because it is false

In [ ]:
assert  data[' Highest Price'].notnull().all() # returns nothing because we drop nan values

In [ ]:
# replacing NaN values in data with empty 
data[' Highest Price'].fillna('empty',inplace = True)

In [ ]:
assert  data[' Highest Price'].notnull().all() # returns nothing because we drop nan values

In [ ]:
# # With assert statement we can check a lot of thing. For example
assert data.columns[1] == ' Highest Price'
#returns error because first column's name is 'Date'

In this part, you learn:
* Diagnose data for cleaning
* Exploratory data analysis
* Visual exploratory data analysis
* Tidy data
* Pivoting data
* Concatenating data
* Data types
* Missing data and testing with assert