1.Go through the concept in pandas
2.Create our own data frame
3.Numpy and matplotlib

In [ ]:
#pandas
#dataframe is standard structure object of pandas to represent data in rows and column format
#2dimensional data structure

In [ ]:

import pandas as pd

In [ ]:
#read csv file and convert it into dataframe
df = pd.read_csv('../input/solar-power-generation-data/Plant_1_Generation_Data.csv')

In [ ]:
df

In [ ]:
df.info()   #summary of the data

In [ ]:
type(df)

In [ ]:
#display first 10 rows
df.head(10)

In [ ]:
#display last 10 rows
df.tail(10)

In [ ]:
#Pandas describe() is used to view some basic statistical details like percentile, mean, std etc. of a data frame or a series of numeric values. 
df.describe()

In [ ]:
#While analyzing the data, many times we wants to see the unique values in a particular column, which can be done using Pandas unique() function.
df['SOURCE_KEY'].unique()

In [ ]:
len(df['SOURCE_KEY'].unique())

In [ ]:
df['SOURCE_KEY'].nunique()

AC_Power ,DC_power

68878

In [ ]:
#no of times unique values are repeated in that column
df['SOURCE_KEY'].value_counts()

In [ ]:
?pd.unique

Statistical methods: min,max ,mean

In [ ]:
df['DC_POWER'].max()    # to get max value in DC Power

In [ ]:
df['DC_POWER'].min()   # to get min value in DC Power

In [ ]:
df['DC_POWER'].mean()  # to get mean

In [ ]:
df['AC_POWER']      #to display one column

In [ ]:
df['AC_POWER'].to_frame()   #To display one column with tag

In [ ]:
df[['AC_POWER','DC_POWER','DATE_TIME']]

In [ ]:
df.nunique()

LOC and ILOC
LOC : Location of index (fancy indexing)
ILOC : index of location

In [ ]:
power = df.iloc[:,4]    # Display the 4th column
power

In [ ]:
power = df.iloc[:,4].values    # Display the 4th column in array
power

In [ ]:
power = df.iloc[20:30,4]
power

In [ ]:
df['AC_POWER'][30000:60116]

In [ ]:
df['AC_POWER'].sort_values()

In [ ]:
df

In [ ]:
df.sort_values(by = 'SOURCE_KEY')

In [ ]:
df['SOURCE_KEY']== '1BY6WEcLGh8j5v7'

In [ ]:
df[df['SOURCE_KEY']== '1BY6WEcLGh8j5v7'].sum()

In [ ]:
df[df['SOURCE_KEY']== '1BY6WEcLGh8j5v7'].sum()['DAILY_YIELD']

Creation dataframe with list

In [ ]:
list = [[2,3,'a'],[34,67]]

In [ ]:
var = pd.DataFrame(list)
var

In [ ]:
type(var)

In [ ]:
var.info()

In [ ]:
#Attribute
var.ndim    #ndimension

In [ ]:
#to know the range of rows
var.index

In [ ]:
#to know the range of columns
var.columns

In [ ]:
var.columns = ['apple','banana','mango']

In [ ]:
var

In [ ]:
var.index = ['count','value']

In [ ]:
var

Creation dataframe with dictionary

In [ ]:
d ={"name":['Ami','Anu'],"age":[25,32]}
d

In [ ]:
type(d)

In [ ]:
var1 = pd.DataFrame(d)
var1

In [ ]:
type(var1)