## TecNM Campus Colima           Ingeniería en Sistemas Computacionales
### Herramientas para la ciencia de datos   U3
Hector Barbosa León
__________________________________________________________________________________________________________
### 3b Descriptive data extraction

Alejandra Centeno Alcaraz     17460100

__________________________________________________________________________________________________________________________________

In [ ]:
from mpl_toolkits.mplot3d import Axes3D

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt #data visualization
import plotly.express as px 



#get the dataset of students performance
dfStudents = pd.read_csv('../input/students-performance-in-exams/StudentsPerformance.csv')
dfStudents.dataframeName = 'StudentsPerformance.csv'

# Dataset presentation

#### Observe the dimensions and describe the information

In [ ]:
rows, cols = dfStudents.shape
print(f'{rows} rows and {cols} columns')
dfStudents.describe()

#### Present some elements of the dataset

In [ ]:
dfStudents.head(10)

#### Clean the dataset in case there is missing data (nan)

In [ ]:
#Count nulls
print(dfStudents.isnull().sum())

#Delete nulls
dfStudents = dfStudents.dropna()
print('---')
dfStudents.shape

*There is no missing data*

*********************************************************************************************************

## 1.1 Creat a new column with the mean score for each student

In [ ]:
dfStudents['total score'] = round((dfStudents['math score'] + dfStudents['reading score'] + dfStudents['writing score']) / 3, 2 )
dfStudents.head(10)

## 1.2 Group mean scores

*Ranks -> 60-70, 70-80,  80-90,  90-100*

In [ ]:
groupRank = pd.cut(dfStudents['total score'], [60, 70, 80, 90, 100], right=False)
groupRank = groupRank.dropna()
groupRank = groupRank.value_counts()
dfgroupRank = pd.DataFrame({'Students': [groupRank[0], groupRank[1], groupRank[2], groupRank[3]]}, index= groupRank.index)  
dfgroupRank

## 1.3 Graph the results

In [ ]:
fig1 = px.bar(dfgroupRank, x= dfgroupRank.index.astype(str), y= 'Students', width=800, height=400, 
              title="Number of Students in different mean ranges")
fig1.show()

*********************************************************************************************************

## 2.1 Obtain the total of students on each parental level of education and then their mean score

In [ ]:
group = dfStudents.groupby('parental level of education')

groupHS = group.get_group('high school')
groupHs_mean = round(groupHS['total score'].sum() / len(groupHS), 2 )
print("Students in High School: ", len(groupHS), 
      "mean of total score: ", groupHs_mean)

groupBD = group.get_group("bachelor's degree")
groupBD_mean = round(groupBD['total score'].sum() / len(groupBD), 2 )
print("Students in bachelor's degree: ", len(groupBD),
     "mean of total score: ", groupBD_mean)

groupMD = group.get_group("master's degree")
groupMD_mean = round(groupMD['total score'].sum() / len(groupMD), 2 )
print("Students in master's degree: ", len(groupMD),
     "mean of total score: ", groupMD_mean)

groupSC = group.get_group('some college')
groupSC_mean = round(groupSC['total score'].sum() / len(groupSC), 2 )
print("Students in some college: ", len(groupSC), 
     "mean of total score: ", groupSC_mean)

groupAD = group.get_group("associate's degree")
groupAD_mean = round(groupAD['total score'].sum() / len(groupAD), 2 )
print("Students in associate's degree: ", len(groupAD), 
     "mean of total score: ", groupAD_mean)

print("************************************************")

dfGroupScores = pd.DataFrame({'Total Students': [len(groupHS), len(groupBD), len(groupMD), len(groupSC), len(groupAD) ], 
                              'Mean Score': [groupHs_mean, groupBD_mean, groupMD_mean, groupSC_mean, groupAD_mean]}, 
                             index =['High School', "Bachelor's degree", "Master's degree", "Some college", "Associate's degree"])  
dfGroupScores

## 2.2 Graph the results

*********************************************************************************************************

In [ ]:
px.pie(dfGroupScores, names= dfGroupScores.index, values= "Total Students", title= "% STUDENTS ON EACH PARENTAL EDUCATION LEVEL")

In [ ]:
fig2 = px.bar(dfGroupScores, x= dfGroupScores.index, y='Mean Score', width=800, height=400, 
              title="Mean Scores on each parental education level")
fig2.show()

## 3.1 Maximum / minimum mean score for female and male of the group "High school" (parental level of education)

In [ ]:
#Create a group of only females of High school
female = groupHS.groupby('gender').get_group('female')
#Obtain the total
print("Female Students: ", len(female))
#get the maximum total score
female_max = female['total score'].max()
female_min = female['total score'].min()
print("Highest score of female: ", female_max)
print("Lowest score of female: ", female_min)

print("************************************************")

#Do the same to males
male = groupHS.groupby('gender').get_group('male')
print("Male Students: ", len(male))
male_max = male['total score'].max()
male_min = male['total score'].min()
print("Highest score of male: ", male_max)
print("Lowest score of male: ", male_min)

print("************************************************")

# Create a new dataframe of these calculations 
dfHSMaxMin = pd.DataFrame({'Max Score': [female_max, male_max], 
                           'Min Score': [female_min, male_min]}, index =['Female', 'Male'])  
dfHSMaxMin

## 3.2 Graph the results

In [ ]:
dfHSMaxMin.plot(kind="bar")
plt.title(label= "Maximum and Minimum Scores by gender with a parental level of High School" , fontsize= 18, pad='40')
plt.show()