## Disney Plus Movies and TV Shows - EDA

* Source: https://www.kaggle.com/unanimad/disney-plus-shows

In [ ]:
# open libraries
import pandas as pd
import seaborn as sns
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [ ]:
#to get the kaggle path
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [ ]:
# open df
df = pd.read_csv('/kaggle/input/disney-plus-shows/disney_plus_shows.csv', encoding = 'latin1', engine = 'python', delimiter = ',')

In [ ]:
# print 4 first rows 
df.head().T

In [ ]:
# print info about 
df.info()

#### imdb_id

Internet Movie Database ID

895 non-null    object

In [ ]:
# check if there's repetead values
## as expected, there aren't repetead values.

df.imdb_id.value_counts()

#### title

Show's title

895 non-null    object

In [ ]:
df.title.value_counts()

#### plot

Show's plot

866 non-null    object

In [ ]:
#filter to only movies
df_disney = df[(df.type == "movie")]

In [ ]:
df_disney['plot']

In [ ]:
# plot the most frequent words in the movies
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

# combine multiple rows into one object
text = df_disney['plot'].str.cat(sep='/ ')

# Create stopword list:
stopwords = set(STOPWORDS)

# Create and generate a word cloud image:
wc= WordCloud(stopwords = stopwords, background_color="white").generate(text)

# Display the generated image:
plt.imshow(wc, interpolation='bilinear')
plt.axis("off")
plt.show()

#wc.to_file("disney.png")
#adapted code from: https://www.datacamp.com/community/tutorials/wordcloud-python

#### type 

Show's type

895 non-null object

In [ ]:
# show's type percentage
df.type.value_counts()/len(df)*100

There are 3 show's type. 68.93% are movies, 19.33% are series and 2.33% are episodes.

In [ ]:
ax = sns.countplot(y = df.type, palette = 'colorblind')
ax.set(xlabel = 'Frequency', ylabel= 'Type')
plt.title("Disney Show's Type")

#### rated 

Rated

739 non-null object

In [ ]:
df_disney.rated.value_counts()/len(df_disney)*100

In [ ]:
# set order by value_counts
ax = sns.countplot(y = df_disney.rated, palette = 'colorblind', order = df_disney.rated.value_counts().index)
ax.set(xlabel = 'Frequency', ylabel= 'Rate')
plt.title("Disney Rate")

#### year         

895 non-null    object

In [ ]:
df_disney.year.value_counts()/len(df_disney)*100
# this column need to be treated

#### released_at  

875 non-null    object

In [ ]:
df_disney.released_at.value_counts()/len(df_disney)*100

In [ ]:
## tranform in date
df_disney['released']= df_disney.released_at.astype('datetime64') 

## get only the year
df_disney['released_year'] = df_disney.released.dt.year

## get only the month
df_disney['released_month'] = df_disney.released.dt.month

In [ ]:
## plot a graph line
sns.distplot(df_disney.released_year)
plt.title('Released Year')
plt.xlabel("Year")

In [ ]:
# plot released_month
sns.countplot(y = df_disney.released_month, palette = 'colorblind')
plt.title('Disney Shows Released Month')
plt.xlabel('Frequency')
plt.ylabel('Month')

Disney Plus Tv Shows are more released in November, June and March.

#### added_at     

When the title was added in platform

988 non-null    object

In [ ]:
## tranform in date
df_disney['added'] = df_disney.added_at.astype('datetime64')

## get only the year
df_disney['added_year'] = df_disney.added.dt.year
df_disney['added_month'] = df_disney.added.dt.month

In [ ]:
# explore added_year
df_disney.added_year.value_counts()/len(df_disney) * 100

In [ ]:
# plot added_month
df_disney.added_month.value_counts()/len(df_disney)*100

In [ ]:
# plot added_month
sns.countplot(y = df_disney.added_month, palette = 'colorblind')
plt.title('Disney Shows Added Month')
plt.xlabel('Frequency')
plt.ylabel('Month')

#### runtime     

837 non-null    object

In [ ]:
## convert to a float
df_disney['runtime'] = df_disney.runtime.str.rstrip('min')
df_disney['runtime'] = df_disney.runtime.str.rstrip('h').astype(float)

In [ ]:
df_disney.runtime.describe()

In [ ]:
sns.distplot(df_disney.runtime)
plt.title('Runtime')

In [ ]:
sns.boxplot(df_disney.runtime)

#### genre 

886 non-null    object

In [ ]:
df_disney.genre.value_counts()/len(df_disney)*100

#### director     

689 non-null    object

In [ ]:
#create a df that split the director column
df_director = df_disney.assign(var1 = df_disney.director.str.split(',')).explode('var1').reset_index(drop = True)

#To remove white space at the beginning of string:
df_director['var1'] = df_director.var1.str.lstrip()

In [ ]:
sns.countplot(y = df_director.var1, order=df_director.var1.value_counts().iloc[:15].index, palette = 'colorblind')
plt.title('Top 15 Directors')
plt.xlabel('')
plt.ylabel('')

####  writer       

742 non-null    object

In [ ]:
#create a df that split the writer column
df_writer = df_disney.assign(var1 = df_disney.writer.str.split(',')).explode('var1').reset_index(drop = True)

#To remove white space at the beginning of string:
df_writer['var1'] = df_writer.var1.str.lstrip()

In [ ]:
#plot top 15 writers with the most movies produced
sns.countplot(y = df_writer.var1, order=df_writer.var1.value_counts().iloc[:15].index, palette = 'colorblind')
plt.title('Top 15 Writers')
plt.xlabel('')
plt.ylabel('')

####  actors      

871 non-null    object

In [ ]:
#create a df that split the writer column
df_actors = df_disney.assign(var1 = df_disney.actors.str.split(',')).explode('var1').reset_index(drop = True)

#To remove white space at the beginning of string:
df_actors['var1'] = df_actors.var1.str.lstrip()

In [ ]:
#plot top 15 actors with the most movies produced
sns.countplot(y = df_actors.var1, order=df_actors.var1.value_counts().iloc[:15].index, palette = 'colorblind')
plt.title('Top 15 Actors')
plt.xlabel('')
plt.ylabel('')

#### language    

Languages available

866 non-null    object

In [ ]:
#create a df that split the writer column
df_lang= df_disney.assign(var1 = df_disney.language.str.split(',')).explode('var1').reset_index(drop = True)

#To remove white space at the beginning of string:
df_lang['var1'] = df_lang.var1.str.lstrip()

In [ ]:
#plot top 15 actors with the most movies produced
sns.countplot(y = df_lang.var1, order=df_lang.var1.value_counts().iloc[:15].index, palette = 'colorblind')
plt.title('Top 15 Languages')
plt.xlabel('')
plt.ylabel('')

#### country      
Country available

870 non-null    object

In [ ]:
#create a df that split the writer column
df_countries= df_disney.assign(var1 = df_disney.country.str.split(',')).explode('var1').reset_index(drop = True)

#To remove white space at the beginning of string:
df_countries['var1'] = df_countries.var1.str.lstrip()

In [ ]:
#plot top 15 actors with the most movies produced
sns.countplot(y = df_countries.var1, order=df_countries.var1.value_counts().iloc[:5].index, palette = 'colorblind')
plt.title('Top 5 Countries')
plt.xlabel('')
plt.ylabel('')

####  awards       

555 non-null    object

In [ ]:
df_disney.awards.value_counts()/len(df_disney)*100

In [ ]:
df_disney.awards.describe()

#### metascore    

291 non-null    float64

In [ ]:
df_disney.metascore.describe()

In [ ]:
# metascore density plot
sns.distplot(df_disney.metascore)

#### imdb_rating 

879 non-null    float64

In [ ]:
df_disney.imdb_rating.describe()

In [ ]:
sns.distplot(df_disney.imdb_rating)

#### imdb_votes   

Internet Movie Database votes

879 non-null    object

In [ ]:
# replace ',' with ''
df_disney['imdb_votes'] = df_disney.imdb_votes.str.replace(',', '').astype(float)

In [ ]:
df_disney.imdb_votes.describe()

In [ ]:
sns.distplot(df_disney.imdb_votes)