## I2DS - Midterm Project (Questions)

Nov. 26, 2020

#### Import the necessary libraries

In [ ]:
pip install pandas

In [ ]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### PART-1 (60 points)

Download "DM_student_dataset_2019.csv" file from the Canvas Files section and apply following tasks.

#### 1) (5 points) Import the dataset into Jupyter Notebook.

In [ ]:
student=pd.read_csv("../input/student-data/DM_student_dataset_2019.csv")

#### 2) (5 points) Dataset information
* Show the size of the dataset. 
* Print the # of attributes and # of tuples.
* Print the attribute names.
* Show the first 4 rows of the dataset. 
* Show the last 4 rows of the dataset.

In [ ]:
# Shape
print(student.shape)

In [ ]:
#Size
print(student.size)

In [ ]:
# Attributes & Tuples
print("# of Attributes:",len(student.keys()))
print("# of Tuples:",len(student))

In [ ]:
print(student.keys())

In [ ]:
print(student.head(4))

In [ ]:
print(student.tail(4))

#### 3) (5 points) Generate descriptive statistics that summarize the central tendency, dispersion and shape of a dataset's distribution (for Age, Weight and Height). Use only one line statement!

In [ ]:
student.describe()

#### 4) (5 points) Show only "Age", "Weight", "Height" and "Gender" columns of this dataset (Drop the "Education" column).

In [ ]:
student=student.drop(columns="Education")
print(student)

#### 5) (10 points) Show dataset separately for Female and Male students.

In [ ]:
#Female
female = student[(student.Gender == "Female")]
print(female)

In [ ]:
#Male

male = student[(student.Gender == "Male")]
print(male)

#### 6) (10 points) Print average values for Female and Male students separately.

In [ ]:


fage=female.Age.mean()
mage=male.Age.mean()
fw=female.Weight.mean()
mw=male.Weight.mean()
fh=female.Height.mean()
mh=male.Height.mean()


print("Average age of female students:",fage)
print("Average age of male students:",mage)
print("Average weight of female students:",fw)
print("Average weight of male students:",mw)
print("Average height of female students:",fh)
print("Average height of male students:",mh)

#### 7) (10 points) Draw the scatter plot of the dataset using attributes *Weight* and *Height* according to class label *Gender*. Use different colors for *Gender* on the plot.

In [ ]:
plt.scatter(x=male['Weight'],y=male['Height'],color="blue", label='male')
plt.scatter(x=female['Weight'],y=female['Height'],color="red", label='female')
plt.legend()
plt.xlabel("Weight")
plt.ylabel("Height")
plt.show()

#### 8) (10 points) Draw the boxplot of the dataset using attributes "Age", "Weight" and "Height" for Female and Male students separately.

In [ ]:
plt.subplot(2,2,1) 
plt.boxplot([female.Age,female.Weight, female.Height],labels=('Age','Weight','Height'))
plt.grid()
plt.title("Box Plot of Female Student")


plt.subplot(2,2,2) 
plt.boxplot([male.Age,male.Weight, male.Height],labels=('Age','Weight','Height'))
plt.grid()
plt.title("Box Plot of Male Student")
plt.show()

### PART-2 (40 points)

#### Find any dataset that contains both numerical and nominal attributes from the web (i.e. Kaggle).

Dataset name:Titanic: Machine Learning from Disaster

Dataset web link:https://www.kaggle.com/shuofxz/titanic-machine-learning-from-disaster

In [ ]:
titanic=pd.read_csv("../input/titanic-machine-learning-from-disaster/test.csv")

#### 1) (5 points) Dataset information

* Show the size of the dataset. 
* Print the # of attributes and # of tuples.
* Print the names of numerical and nominal attributes separately.
* Show the first 10 rows of the dataset.

In [ ]:
print("Size of the dataset:",titanic.size)

In [ ]:
print("# of Attributes:",len(titanic.keys()))
print("# of Tuples:",len(titanic))

In [ ]:

print(titanic.dtypes)

In [ ]:
Nominal = titanic.dtypes[titanic.dtypes == np.object]
Numeric_i = titanic.dtypes[titanic.dtypes == np.int64]
Numeric_f = titanic.dtypes[titanic.dtypes == np.float64]

print('Nominal attributes:\n',Nominal)

print('Numerical attributes:\n',Numeric_i,'\n',Numeric_f)

In [ ]:
print("First 10 row:\n",titanic.head(10))

#### 2) (5 points) Compute the central tendency of any variable (mean, median, mode, range, and midrange).

In [ ]:
import statistics

#Nan's dropped for compute reals values.
Fare=titanic.Fare
Age_drop=titanic.Age.dropna(axis="rows")
Fare_drop=Fare.dropna(axis="rows")


print("Mean of Fare     :", np.mean(Fare_drop))
print("Median of Fare   :", np.median(Fare_drop))
print("Mode of Fare     :", statistics.mode(Fare_drop))
 
minval=min(Fare_drop)
maxval=max(Fare_drop)
print("Range of Fare    :", maxval-minval)
print("Mid-Range of Fare:", (maxval+minval)/2)

#### 3) (5 points) Compute the dispersion of data (standard deviation and variance).

In [ ]:
print("Standart Deviation of Fare:", statistics.stdev(Fare_drop) )
print("Variance of Fare          :", statistics.variance(Fare_drop) )

#### 4) (5 points) Compute 5-number summary of a distribution.

In [ ]:
quartiles = np.percentile(Fare_drop, [25, 50, 75])
print('Min   : %.3f' % minval)
print('Q1    : %.3f' % quartiles[0])
print('Median: %.3f' % quartiles[1])
print('Q3    : %.3f' % quartiles[2])
print('Max   : %.3f' % maxval)

#### 5) (20 points) Visualize the data
* Box plot
* Histogram
* 2-D Scatter plot
* 3-D Scatter plot

In [ ]:
plt.boxplot([Age_drop,Fare_drop],labels=('Age','Fare',))

plt.grid()
plt.title("Box Plot of Titanic Passangers")
plt.show()

In [ ]:
plt.hist(Age_drop)
plt.title("Histogram Graph of Passengers' Age")
plt.show()

In [ ]:
plt.scatter(x=titanic["PassengerId"],y=titanic['Age'],color="green",label="Age")
plt.scatter(x=titanic["PassengerId"],y=titanic['Fare'],color="red",label="Fare")
plt.title("2D - Scatter of Passengers' Age & Fare")
plt.legend()
plt.show()

In [ ]:
from mpl_toolkits.mplot3d import Axes3D

d = plt.figure()
ax = Axes3D(d)

ax.scatter(titanic["PassengerId"],titanic["Age"],titanic["Fare"])
plt.title("3D Scatter")
plt.show()