# RAINFALL DATA

This notebook is exclusively for people for wanted to learn seaborn (beginner level). I tried to use all plots and charts. 

Upvote if you find this useful. Thanks :)

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns


import warnings
warnings.simplefilter('ignore')

In [ ]:
df = pd.read_csv('/kaggle/input/rainfall-data-from-1901-to-2017-for-india/Rainfall_Data_LL.csv')
df

In [ ]:
df.drop(columns = ['Name'],inplace = True)

In [ ]:
df.SUBDIVISION.unique()

In [ ]:
df.info()

In [ ]:
#we will use subdivision, year, annual, jan-feb, mar-may, june-sept, oct-Dec columns alone 


df = df[['SUBDIVISION','YEAR','ANNUAL','Jan-Feb' , 'Mar-May', 'June-September' ,'Oct-Dec' ]]
df

In [ ]:
df.describe()

In [ ]:

conditions = [
    (df['ANNUAL'] <= 800),
    (df['ANNUAL'] > 800) & (df['ANNUAL'] <= 2000),
    (df['ANNUAL'] > 2000) & (df['ANNUAL'] <= 4500),
    (df['ANNUAL'] > 4500)
    ]


values = ['low', 'medium', 'high', 'very_high']

df['status'] = np.select(conditions, values)
df

In [ ]:
#scatter plot

plt.figure(figsize = (15,5))
sns.scatterplot(x ='YEAR' , y='ANNUAL', data = df)

plt.show()

In [ ]:
#scatter plot wit hue

plt.figure(figsize = (15,5))
sns.scatterplot(x ='YEAR' , y='ANNUAL', data = df ,hue = 'status' )

plt.show()

In [ ]:
sns.set_style("whitegrid")

sns.catplot(x='status', y ='SUBDIVISION', data =df , height = 10)
plt.show()

In [ ]:
plt.figure(figsize = (15,10))
chart = sns.boxplot(x ='SUBDIVISION' , y ='Jan-Feb' , data = df)
chart.set_xticklabels(chart.get_xticklabels(), rotation = 90)
plt.show()

We will try to group by year and see how the rainfall is all over INDIA from 1901 to 2017

In [ ]:
grouped_df = df.groupby('YEAR').sum()
grouped_df

In [ ]:
x = grouped_df[grouped_df['ANNUAL']>50000]
plt.figure(figsize = (15,10))
chart2 = sns.barplot(x = x.index , y = 'ANNUAL' , data =x)
chart2.set_xticklabels(chart2.get_xticklabels(), rotation = 90)
plt.show()

In [ ]:
sns.regplot(x=grouped_df.index, y="ANNUAL", data=grouped_df);

In [ ]:
sns.scatterplot(x = grouped_df.index , y = 'June-September' , data = grouped_df)

In [ ]:
sns.regplot(x = grouped_df.index , y = 'June-September' , data = grouped_df)

In [ ]:
sns.displot(grouped_df , x = 'YEAR' , stat = 'probability')

In [ ]:
sns.displot(grouped_df['ANNUAL'] , x = 'YEAR' ,kind = 'kde', bw_adjust = 0.1)

In [ ]:
chart3 = sns.catplot(
    data=df[df['YEAR'].isin([1910,1940,1970,2000,2015])],
    x='YEAR',
    kind ='count',
    palette='Set1',
    row='status',
    aspect=3,
    height=3
)

In [ ]:
sns.displot(grouped_df, x=grouped_df.index, y="ANNUAL")

In [ ]:
sns.displot(grouped_df, x=grouped_df.index, y="ANNUAL" , kind ='kde')