In [ ]:
# Nabil FATTOUCH 
# Date : 31/08/2021 
# Data source: "/kaggle/input/salaries/Salaries.csv"

In [ ]:
# Answer questions asked by  client who is a  human resources   and management control department
# The client located in San Francisco, wants to know its data. 
# This department asks a set of questions to evaluate the salaries attributed to their employees which are the following:





# variable target :  TotalPayBenefits

# Analysis of the data form :

# Rows and columns : (148654, 13)
# Analysis of NaN 
 # • Elimination of useless columns (Ratio Sum NaN/ Total ( shape ! ) < 70 %
 # • Many NaN for columns "Notes"and "Statuts"(half of the variables > 70% of NaN)
 
# In-depth analysis : 
 # • Visualization of the target 
 # • Average 
 # • The highest salary in the company, the name of the person and the position held?
 # • Positions have the lowest salaries and for which people in the company ?
 # •The number of job titles were represented by only one person in 2014
 # • Top 07 persons works the most overtime ? 
 # • Relationship between the position held and the amount of overtime worked?
 # • Rbetween OvertimePay and TotalPayBenefits?
# Exploratory of others  variables :
 # • The highest amount of OvertimePay in the dataset 
 # • The number of people having the word captain in their job title
 # • Top-07 jobs in which there are majority of the people ( in %) ?
 # • The average ( mean) TotalPayBenefit of all employees per year ( 2011-2014)

In [ ]:
## Import packages 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
pd.set_option('display.max_row', 111)              # If we want to display the result in full 
pd.set_option('display.max_column', 111)

In [ ]:
filename = "/kaggle/input/salaries/Salaries.csv"
df = pd.read_csv(filename)

In [ ]:
df.head()

In [ ]:
df1= df.copy()
df1.head(7)

In [ ]:
pd.show_versions()

# Analysis of the data form

In [ ]:
                                      # number of columns and rows 

df1.shape

In [ ]:
df1.columns                            # Columns names

In [ ]:
print("Number of rows in dataset: ",df1.shape[0])
print("Number of columns in dataset: ",df1.shape[1])

In [ ]:
#df1.dtypes()
df1.dtypes.value_counts()              #  Data types

In [ ]:
df1.dtypes.value_counts().plot.pie()   # Data types visualization

In [ ]:
df1.isnull().sum(axis=0)                # Checking the NaN  in the dataset

In [ ]:
df1.head()

# Analysis of NaN :

In [ ]:

                                      # Visualization of NaN 

plt.figure(figsize=(20,10))           # To create a figure of dimensions 20, 10 
sns.heatmap(df1.isna(), cbar=False)    # cbar = False to eliminate the colored bar

In [ ]:
df.isna().sum()

In [ ]:
(df1.isna().sum()/df1.shape[0]).sort_values( ascending = True)

In [ ]:
# • Elimination of useless columns (Ratio Sum NaN/ Total ( shape ! ) > 70 %
 # • Many NaN for columns "Notes"and "Statuts"(more than half of the variables > 70% of NaN)

 ## sns.heatmap(df1.isna() )

In [ ]:
df2= df1[df1.columns[df1.isna().sum()/df1.shape[0] < 0.7] ]
    
    # 1/ df.isna().sum()/df.shape[0] >0.7     2/df.columns[df.isna().sum()/df.shape[0] > 0.7]

    # What we do here is boolean indexing, i.e. I take the table of columns df.columns[df.isna().sum()/df.shape[0] < 0.7] 
    # and I inject it in our new dataframe df and we save

In [ ]:
df2.head(7)

In [ ]:
# elimination of rows
# In the data frame above, it is visible that there are some rows in which no values is entered, 
# which is equal to NaN . So we need to delete these rows.

df2 = df2[df2['EmployeeName'] != 'Not provided']
df2 = df2[df2['JobTitle'] != 'Not provided']
df2.reset_index(inplace = True, drop = True)
df2

In [ ]:
                                     # Unique values in dataset
    
print('Number of unique values in Job-Title column are:',df['JobTitle'].nunique())
print('Number of unique values in Agency column are:',df['Agency'].nunique())
print('Number of unique values in Year column are:',df['Year'].nunique())

In [ ]:
print("Job-Title:",df['JobTitle'].unique())

print("Agency:",df['Agency'].unique())
print("Year:",df['Year'].unique())

# Visualization of the target

In [ ]:
# Examination of the Target column : TotalPayBenefits

In [ ]:
df2['TotalPayBenefits'].value_counts()  # if you want to display the result in %. , value_counts(normalize=True)

In [ ]:
df2['TotalPayBenefits'].value_counts(normalize=True)

In [ ]:
# meaning of variables (continuous!) ( Histogram of continuous variables )

for col in df2.select_dtypes('float'): print(col)  
                                                 # We check what we have as columns 
                                                 # then we will create histograms,
                                                 # we will observe the distribution, 
                                                 # the distribution of data for each of its columns. 
                                                 # For that, we can use Matplotlib or seaborn

In [ ]:
for col in df2.select_dtypes('float'): 
                                                 # displot: a distribution curve and we will pass through it
                                                 # each time the column (variable) of our df 
    plt.figure()
    sns.displot(df[col])          
                                                
                                                 # and they appear to have a standard deviation = 1. 
                                                 # This immediately suggests that these data 
                                                 # have been standardized 
                                               
                                                 #  A perfect positive relationship between the two variables.

In [ ]:
df2[['TotalPay', 'TotalPayBenefits']].corr()

In [ ]:

df2[['OvertimePay','TotalPayBenefits']].corr()

In [ ]:
df2.info()

In [ ]:
# The highest salary in the company, the name of the Employee and the JobTitle?

df2[df2['TotalPayBenefits'] == df2['TotalPayBenefits'].max()]

In [ ]:
df2[df2['TotalPayBenefits'] == df2['TotalPayBenefits'].max()]['EmployeeName']

In [ ]:
df2[df2['TotalPayBenefits'] == df2['TotalPayBenefits'].max()]['TotalPayBenefits']

In [ ]:
df2['TotalPayBenefits'].value_counts().head(15)

In [ ]:
df2['Year']== 2014

In [ ]:
df2[df2['Year']== 2014]['JobTitle']

In [ ]:
df2[df2['Year']== 2014]['JobTitle'].value_counts()

In [ ]:
(df2[df2['Year']== 2014]['JobTitle'].value_counts() ==1).sum()

In [ ]:
df2['TotalPayBenefits'].mean()

## The highest amount of OvertimePay in the dataset

In [ ]:
df2['EmployeeName']== 'PATRICK GARDNER'

In [ ]:
df2[df1['EmployeeName']=='GARY JIMENEZ']['JobTitle']

In [ ]:
df2[df2['EmployeeName']=='GARY JIMENEZ']['TotalPayBenefits']

In [ ]:
## the average ( mean) TotalPayBenefits of all employees per year ( 2011-2014)

In [ ]:
df2_by_year=df2.groupby('Year').mean()['TotalPayBenefits']
df2_by_year

In [ ]:
ax = df2_by_year.plot(kind='bar', title ="Average ( mean) TotalPayBenefits of all employees per year", figsize=(16, 10), legend=True, fontsize=10)
ax.set_xlabel("TotalPayBenefits", fontsize=12)
ax.set_ylabel("Year", fontsize=12)
plt.show()

## The top 07  most popular jobs

In [ ]:
df2['JobTitle'].value_counts()

In [ ]:
df3= df2['JobTitle'].value_counts().head(7)
df3

In [ ]:

ax = df3.plot(kind='bar', title ="The top 07  most popular jobs", figsize=(15, 10), legend=True, fontsize=12)
ax.set_xlabel("JobTitle", fontsize=12)
ax.set_ylabel("Year", fontsize=12)
plt.show()

## The number of job titles were represented by only one person in 2014

In [ ]:
df2['Year']== 2014

In [ ]:
df2[df2['Year']== 2014]['JobTitle']

In [ ]:
df2[df2['Year']== 2014]['JobTitle'].value_counts()

In [ ]:
(df2[df2['Year']== 2014]['JobTitle'].value_counts() ==1).sum()

## The number of people having the word captain in their job title

In [ ]:
def captain(string):
    if 'captain' in (string.lower()):
        return True
    else:
        return False

In [ ]:
 captain('CAPTAIN SERVICE') # test of function

In [ ]:
(df2['JobTitle'].apply(lambda x: captain(x)))

In [ ]:
(df2['JobTitle'].apply(lambda x: captain(x))).sum()