In [ ]:
import pandas as pd

In [ ]:
laptops = pd.read_csv("/kaggle/input/laptop-details/laptops.csv", encoding = "Latin-1")

In [ ]:
laptops.head()

In [ ]:
laptops.info()

In [ ]:
laptops.shape

In [ ]:
1303-1133

In [ ]:
laptops.columns

In [ ]:
laptops.index

In [ ]:
# laptops.columns = []

In [ ]:
col = []

for i in laptops.columns:
    # print(i)
    i = i.lower()
    i = i.strip()
    i = i.replace(" ","_")
    i = i.replace("(", "").replace(")","")
    i = i.replace("operating_system","os")
    col.append(i)
# 1st method to change the column name.

In [ ]:
col

#### i am not updated from this method because one more way to change the column name and remove special character.

In [ ]:
# laptops.columns = col

In [ ]:
laptops.columns

#### 2nd method

In [ ]:
laptops.columns = laptops.columns.str.lower().str.strip().str.replace(" ","_").str.replace("(","").str.replace(")","")

In [ ]:
laptops.columns

In [ ]:
laptops.columns = laptops.columns.str.replace('operating_system', "os")

#### Column names are changed now.

In [ ]:
laptops.head(2)

### removing " character from column.

In [ ]:
laptops["screen_size"] # Series

In [ ]:
# float('15.6"'.strip('"'))

In [ ]:
laptops["screen_size"] = laptops["screen_size"].str.strip('"').astype(float)

### screen_size column is cleaned now.

In [ ]:
laptops["screen_size"]

In [ ]:
laptops.head(2)

#### Rename screen size col.

In [ ]:
# laptops = laptops.rename({"screen_size", "screen_size_inches"}, axis = 1)
laptops.rename({"screen_size":"screen_size_inches"}, axis = 1, inplace = True) ##1st method

In [ ]:
laptops.head(2)

In [ ]:
# laptops.columns = laptops.columns .str.replace("screen_size","screen_size_inches") ### 2nd method

#### remove GB from column.

In [ ]:
laptops["ram"]

In [ ]:
laptops["ram"] = laptops["ram"].str.replace("GB" , "").astype(int)

####  remove kg from column.

In [ ]:
laptops["weight"]

In [ ]:
laptops["weight"] = laptops["weight"].str.replace("kg" , "")

In [ ]:
laptops["cpu"]

### make one more column with the help of cpu column..

#### 1st  method

In [ ]:
# laptops["cpu_manufacturer"] = laptops["cpu"]

laptops["cpu"].str.split().str[0]

#### 2nd method

In [ ]:
laptops["cpu"].str.split(n = 1, expand = True)[0]

In [ ]:
laptops["cpu_manufacturer"] = laptops["cpu"].str.split(n = 1, expand = True)[0]

#### new column is created

In [ ]:
laptops.head(2)

In [ ]:
laptops["gpu"]

In [ ]:
laptops["price_euros"].head()

In [ ]:
laptops["price_euros"] = laptops["price_euros"].str.replace("," , "").astype(int)

In [ ]:
laptops["os"].unique()

#### there is 2 os names which is actually one name changed into single name.

In [ ]:
laptops["os"].value_counts()

#### manual function of value_counts() if you apply this the answer will be same.

In [ ]:
# count = {}

# for i in laptops["os"]:
#     if i not in count:
#         count[i] = 1
#     else:
#         count[i] += 1

In [ ]:
# count

#### 1st method

In [ ]:
# laptops["os"] = laptops["os"].str.replace("Mac OS","macOS")

#### 2nd method

In [ ]:
change = {'macOS':'macOS', 'No OS':'No OS', 'Windows':'Windows', 
           'Mac OS':'macOS', 'Linux':'Linux', 'Android':'Android',
       'Chrome OS':'Chrome OS'}

laptops["os"] = laptops["os"].map(change)

#### now os column is look good.

In [ ]:
laptops["os"].value_counts()

In [ ]:
laptops.isnull()

#### there is 170 null values in the os_version column.

In [ ]:
laptops.isnull().sum()

In [ ]:
laptops["os_version"].isnull().sum()

In [ ]:
boolean = laptops["os_version"].isnull()      ### this is called boolean indexing

boolean

#### these row have null values which is shown with the help of boolean indexing.

In [ ]:
laptops[boolean]

In [ ]:
laptops.loc[boolean, "os"]

In [ ]:
laptops.loc[boolean, "os"].value_counts()

In [ ]:
laptops["os"] == "macOS"

#### search from internet 
#### what is os_version of macos , the answer is x that'why i am filled 'X' in the os_version column.

In [ ]:
laptops.loc[laptops["os"] == "macOS","os_version"] = "X"

#### No OS are not existing in any os_version that why i am replace it with unknown vesion.

In [ ]:
laptops.loc[laptops["os"] == "No OS","os_version"] = "unknown version"

#### reduce null value from 170 to 91

In [ ]:
laptops.isnull().sum()

In [ ]:
170-79

In [ ]:
laptops.head()

In [ ]:
laptops["price_euros"].max()

In [ ]:
laptops["price_euros"].min()

In [ ]:
laptops["manufacturer"].value_counts()

#### Most expensive laptop of apple is MacBook Air.

In [ ]:
laptops[laptops["manufacturer"] == "Apple"].sort_values("price_euros" , ascending = False).head(1)

#### cheap laptop of apply is also MacBook Air but there is a big differnce in the ram section .

In [ ]:
laptops[laptops["manufacturer"] == "Apple"].sort_values("price_euros" , ascending = True).head(1)

#### Most expensive laptop of Dell is Inspiron 7773.

In [ ]:
laptops[laptops["manufacturer"] == "Dell"].sort_values("price_euros" , ascending = False).head(1)

#### cheap laptop of Dell is Latitude 5580.

In [ ]:
laptops[laptops["manufacturer"] == "Dell"].sort_values("price_euros" , ascending = True).head(1)

In [ ]:
laptops[laptops["manufacturer"] == "Dell"]["price_euros"].min()

#### Most expensive laptop of  Lenovo is Legion Y520-15IKBN.

In [ ]:
laptops[laptops["manufacturer"] == "Lenovo"].sort_values("price_euros" , ascending = False).head(1)

#### cheapest laptop of Lenovo is ThinkPad T460	.

In [ ]:
laptops[laptops["manufacturer"] == "Lenovo"].sort_values("price_euros" , ascending = True).head(1)

In [ ]:
laptops[laptops["manufacturer"] == "Lenovo"]["price_euros"].min()

#### Most expensive laptop of HP is Probook 440.

In [ ]:
laptops[laptops["manufacturer"] == "HP"].sort_values("price_euros" , ascending = False).head(1)

#### cheapest laptop of HP is EliteBook 840.

In [ ]:
laptops[laptops["manufacturer"] == "HP"].sort_values("price_euros" , ascending = True).head(1)

In [ ]:
laptops[laptops["manufacturer"] == "HP"]["price_euros"].min()

#### Most expensive laptop of Asus is FX553VD-FY647T (i7-7700HQ/8GB/256GB/GeForce.

In [ ]:
laptops[laptops["manufacturer"] == "Asus"].sort_values("price_euros" , ascending = False).head(1)

#### cheapest laptop of Asus is ZenBook UX310UQ-GL026T.

In [ ]:
laptops[laptops["manufacturer"] == "Asus"].sort_values("price_euros" , ascending = True).head(1)

In [ ]:
laptops[laptops["manufacturer"] == "Asus"]["price_euros"].min()

#### Most expensive laptop of Acer is Spin 5.

In [ ]:
laptops[laptops["manufacturer"] == "Acer"].sort_values("price_euros" , ascending = False).head(1)

#### cheapest laptop of acer is Aspire F5-573G-510L

In [ ]:
laptops[laptops["manufacturer"] == "Acer"].sort_values("price_euros" , ascending = True).head(1)

In [ ]:
laptops[laptops["manufacturer"] == "Acer"]["price_euros"].min()

#### Most expensive laptop of Toshiba is Satellite Pro.

In [ ]:
laptops[laptops["manufacturer"] == "Toshiba"].sort_values("price_euros" , ascending = False).head(1)

#### cheapest laptop of Toshiba is Tecra A40-C-1E5.

In [ ]:
laptops[laptops["manufacturer"] == "Toshiba"].sort_values("price_euros").head(1)

In [ ]:
laptops[laptops["manufacturer"] == "Toshiba"]["price_euros"].min()

#### Most expensive laptop of Samsung is Chromebook Plus.

In [ ]:
laptops[laptops["manufacturer"] == "Samsung"].sort_values("price_euros" , ascending = False).head(1)

#### cheapest laptpop of Samsung is Notebook 9.

In [ ]:
laptops[laptops["manufacturer"] == "Samsung"].sort_values("price_euros").head(1)

#### Completed.