In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Import Libraries

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Read data

In [ ]:
df = pd.read_csv('../input/bachelor-degree-majors-by-age-sex-and-state/Bachelor_Degree_Majors.csv')

In [ ]:
df.head()

In [ ]:
df.info()

In [ ]:
df.isnull().sum()

# Data cleaning

**The ````"Age Group"```` column has a value `"25 and older"`. This value also includes the values present for "25 to 39", "50 to 64" and "65 and older". Hence I have removed the rows that contain "25 and older" as a value for "Age Group**

**Also, in the "Sex" column, "Total" value includes both Male and Female. Hence it is of not much use to us.**

In [ ]:
df = df[df["Age Group"] != "25 and older"]

In [ ]:
df = df[df["Sex"] != "Total"]

In [ ]:
df.head()

**Right now, the value of the columns `"Bachelor's Degree Holders"`, `"Science and Engineering"`, `"Science and Engineering Related "`, `"Business"`,`"Education"` ,"	Arts, Humanities and Others" are `strings`** 

Hence we need to convert the strings into integers for better analysis.

In [ ]:
# function to convert the data into integer types
def process_data(data):
    data = data.split(",")
#     print(data)
    data = "".join(data)
    return int(data)

In [ ]:
columns = df.columns

In [ ]:
columns = columns[3:]

In [ ]:
columns

In [ ]:
for col in columns:
    df[col] = df[col].apply(process_data)

In [ ]:
df.head()

In [ ]:
sns.countplot(x="Age Group", data=df)

We have equal number of candidates in all the three age groups

In [ ]:
sns.countplot(y="Sex", hue="Age Group", data=df)

We have equal number of male and female candidates in the three age groups

We will look at the data, State wise, grouped by age and sex in that order.

In [ ]:
df.groupby(['State']).sum().style.background_gradient(cmap='Blues').set_table_styles([{'selector' : '',
                            'props' : [('border',
                                        '2px solid darkblue')]}])

**From the above table, we can see that, most of the degree holders are concentrated in the states of California, Florida, New York, Texas**

**Next, we will look at the data state wise , grouped by age groups and sex, in that order.**

In [ ]:
df.groupby(['State','Age Group', "Sex"]).sum().style.background_gradient(cmap='Blues').set_table_styles([{'selector' : '',
                            'props' : [('border',
                                        '2px solid darkblue')]}])

In [ ]:
# g = sns.catplot(x="Age Group", y="Bachelor's Degree Holders",

#                 hue="Sex", col="State",col_wrap=4,

#                 data=df, kind="bar");

In [ ]:
i=1
plt.figure(figsize=(15,10))
for col in columns:
    
    plt.subplot(2,3,i)
    sns.barplot(x="Age Group", y=col, hue="Sex", data=df, ci=False);
    plt.title(col)
    i+=1
plt.subplots_adjust(left=0.1,
                    bottom=0.1, 
                    right=0.9, 
                    top=0.9, 
                    wspace=0.4, 
                    hspace=0.4)
plt.show()

* We can see that more females are bachelor's degree holder than male students.
* More Male students majored in Science and Engineering and Business than female students.
* More Female students majored in science and engineering related fields, Education and Arts, Humanities and other fields than male students.

In [ ]:
# for col in columns:
#     sns.catplot(x="Age Group", y=col,

#                 hue="Sex", col="State",col_wrap=4,

#                 data=df, kind="bar");

# All open to suggestions and feedbacks
# If you liked this presentation of data, please do consider upvoting