## Introduction

In R, `data.table` is the go-to package for manipulating any large tabular datasets. It is widely used for fast aggregation of large datasets, low latency add/update/remove of columns, quicker ordered joins, and a fast file reader.

[Python datatable](https://github.com/h2oai/datatable) is closely related to R's `data.table` and attempts to mimic its core algorithms and API.  It is close in spirit to pandas or SFrame; however we put specific emphasis of the package is on speed and big data support. 

In this notebook, let us explore the functions present in the `datatable` module and also see how it fares in speed with other modules.

### References : 
1. https://cran.r-project.org/web/packages/data.table/index.html
2. https://www.dezyre.com/data-science-in-r-programming-tutorial/r-data-table-tutorial
3. https://datatable.readthedocs.io/en/latest/
4. https://github.com/vopani/datatableton

Python datatable is not natively present in the Kaggle environment. So let us install the module first as per the instructions in the [github page](https://github.com/h2oai/datatable).

In [ ]:
!pip install https://s3.amazonaws.com/h2o-release/datatable/stable/datatable-0.8.0/datatable-0.8.0-cp36-cp36m-linux_x86_64.whl

Now let us import the necessary modules.

In [ ]:
import time
import numpy as np
import pandas as pd
import datatable as dt
print(dt.__version__)

## Reading Data

Let us first start with reading the input data from csv file. `loan.csv` file has about 2.26 million rows and 145 columns.

`fread` is the fucntion to read the files in datatable module. From the documentation,fread provides fast and convenient parsing of text (csv) files.
* Automatically detects separators, headers, column types, quoting rules, etc.
* Reads from file, URL, shell, raw text, archives, glob
* Provides multi-threaded file reading for maximum speed
* Includes a progress indicator when reading large files
* Reads both RFC4180-compliant and non-compliant files

In [ ]:
## Data Table Reading
start = time.time()
input_file_name = "../input/lending-club-loan-data-csv/loan.csv"
dt_df = dt.fread(input_file_name)
end = time.time()
print(end - start)

This took about ~12 seconds to read the data and create a `Frame` object. The fundamental unit of analysis in datatable is a data `Frame`. It is the same notion as a pandas DataFrame or SQL table: data arranged in a two-dimensional array with rows and columns.

Now let us read the same file in pandas as see the time difference.

In [ ]:
import time

start = time.time()
pd_df= pd.read_csv(input_file_name)
end = time.time()
print(end - start)

Pandas takes more than ~50 seconds to read the same file and create a dataframe from it. I think this will be a good value add when we deal with large datasets. 

We also have options in datatable to convert the frame to pandas dataframe object. Let us do that.

In [ ]:
start = time.time()
dt_df.to_pandas()
end = time.time()
print(end - start)

Looks like this takes ~15 seconds. So reading a file as datable frame and converting that to pandas dataframe is faster than reading through pandas directly ;)

## Frame Properties

Similar to pandas, we can get the 

* top few rows by `head` command, 
* size of the frame by `shape` command and 
* column names by `names` command

In [ ]:
dt_df.head()

In [ ]:
# number of rows and columns
dt_df.shape

In [ ]:
# To get the column names
dt_df.names[:10]

## Summary Statistics

We can also get the summary statistics like sum, mean, max, min, sd etc.

Let us get the mean of the columns using both datatable and pandas

In [ ]:
dt_df.mean()

When I ran the below one, I got memory error and so commenting it out.

In [ ]:
## pd_df.mean()

## Sorting the frame

Now let us sort the dataframe by loan_amnt column.

In [ ]:
start = time.time()
dt_df.sort("loan_amnt")
end = time.time()
print(end - start)

In [ ]:
start = time.time()
pd_df.sort_values(by="loan_amnt")
end = time.time()
print(end - start)

Wow! This is super fast. 

## GroupBy Operations

Let us get the mean loan amount for each grades. 

In datatable, almost all operations with a Frame can be expressed as

`DT[ i, j, ...]`

where 

`i` is the row selector

`j` is the column selector and 

`...` represents additional modifiers might be added

In [ ]:
start = time.time()
for i in range(100):
    dt_df[:, dt.sum(dt.f.loan_amnt), dt.by(dt.f.grade)]
end = time.time()
print(end - start)

In this case `i` is all the rows, `j` is loan_amnt and `...` is grouping by grade

We have also used `dt.f` in the code - what does it mean? It is a "frame proxy", as it becomes a simple way to refer to the Frame that we currently operate on. In this example, `dt.f` represents the frame `dt_df`

In [ ]:
start = time.time()
for i in range(100):
    pd_df.groupby("grade")["loan_amnt"].sum()
end = time.time()
print(end - start)

## Filtering rows

Filtering also follows the same syntax as that of groupby

Let us filter those rows which has loan_amnt greater than the mean loan_amnt.

In [ ]:
start = time.time()
for i in range(100):
    dt_df[dt.f.loan_amnt>dt.mean(dt.f.loan_amnt), "loan_amnt"]
end = time.time()
print(end - start)

In [ ]:
start = time.time()
for i in range(100):
    pd_df["loan_amnt"][pd_df["loan_amnt"] > pd_df["loan_amnt"].mean()]
end = time.time()
print(end - start)

## Model Building

We can also build models using the dataframe as such. 

Let us try to build a linear regression model to predict the "interest rate" from "loan amount" and "installment". We can also build other models but let us build this one is for simplicity.

Thanks Mike for the question on the comments section.

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(dt_df[:,["loan_amnt", "installment"]], dt_df[:,"int_rate"])
model.coef_

## Saving the Frame

Now let us look at the ways to save the frame so as to load back when needed. `datatable` has to_csv function similar to pandas.

In [ ]:
gdf = dt_df[:, dt.sum(dt.f.loan_amnt), dt.by(dt.f.grade)]
gdf.to_csv("temp.csv")

Overall, the `datatable` module seems to be much faster compared to the pandas dataframe operations. This will be very handy when we deal with bigger datasets.

One drawback is that `datatable` does not have all the functionalities that are there in pandas.

Please do let me know your thoughts in the comments if you get a chance to try out python `datatable`

P.S : I worked for H2O.ai where python data.table is getting created. The views in this article are my own.