In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

**Hello Folks**,

If you are new to pandas, feel free to walk through this notebook. 
You can  **copy and edit**, if you like the content and feel like practicing.

To use pandas we need to **import pandas library**

In [ ]:
import pandas as pd

**Creating DataFrame**

A DataFrame is a table. It contains an array of individual entries, each of which has a certain value. Each entry corresponds to a row (or record) and a column

**pd.DataFrame()** = constructor to generate DataFrame objects. The syntax for declaring a new one  is similar to a dictionary whose keys are the column names , and whose values are a list of entries.

In [ ]:
pd.DataFrame({'CLASS':[1,2,3,4,5], 'No. of Students':[23,28,45,34,21]})


DataFrame entries are not limited to integers. For example, here's a DataFrame whose values are strings:-

In [ ]:
pd.DataFrame({'Customer_name':['Jyoti','Alice','Bob'],'Feedback':['I like the content','content is ok','Insightful content']})

Let's assign our own values for index

In [ ]:
pd.DataFrame({'Customer_name':['Jyoti','Alice','Bob'],'Feedback':['I like the content','content is ok','Insightful content'] }, index=['Notebook1','Notebook2','Notebook3'])

Lets create a DataFrame which is more similar to real world data i.e. contains various datatypes such as integer, string, float etc.

In [ ]:
pd.DataFrame({'Items':['Milk','Bread','Butter'],'Quantity':[1.5,2,1], 'Amount':[4,5,6]}, index=['Customer A','Customer B','Customer C'])

**Series**
A Series, by contrast, is a sequence of data values. If a DataFrame is a table, a Series is a list.

In [ ]:
pd.Series([1,2,3,4,5])

A Series is, in  layman terms is a single column of a DataFrame. We can assign column values to the Series the same way as before, using an index parameter. However, a Series does not have a column name, it only has one overall name:

In [ ]:
pd.Series([30, 35, 40], index=['2019 Sales', '2020 Sales', '2021 Sales'], name='Notebook A')

It's helpful to think of a DataFrame as actually being just a bunch of Series **"glued together".**

Lets **create** a variable ingredients with a Series that looks like:

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [ ]:
quantities = ['4 cups', '1 cup', '2 large', '1 can']
items = ['Flour', 'Milk', 'Eggs', 'Spam']

ingridients = pd.Series(quantities, index=items, name='Dinner')
ingridients

In the above code snippet, **we used one list as an index to the other list**.

**Reading data files**
use the **pd.read_csv()** function to read the data into a DataFrame.

In [ ]:
student_performance = pd.read_csv("../input/students-performance-in-exams/StudentsPerformance.csv")

Lets check if CSV got read or not . Type the name of dataframe created, here, student_performance, data will be dispalyed.

In [ ]:
student_performance

Read first few lines of data

In [ ]:
student_performance.head(10)

For reading last few lines from the dataframe use tail.

In [ ]:
student_performance.tail(15)

Check how many Rows, Columns our CSV file had using shape

In [ ]:
student_performance.shape

 The autogenerated index in pandas starts from 0. But there is in  reality a student having number/roll no zero. Lets fix that using a simple option in pandas. Lets try reading it again with the index value fixed. Set the index values using np.arange

In [ ]:
student_performance.index = np.arange(1, (len(student_performance)+1))

In [ ]:

student_performance.head(5)

Now, lets  save this DataFrame to disk as a csv file

In [ ]:
student_performance.to_csv("Record.csv")

This Record.csv file can be found in the output folder, which is in the right side of the window.