In [94]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from datetime import datetime
from ast import literal_eval

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['TTX-0013_DataDictionary_registered-businesses.xlsx', 'socrata_metadata.json', 'registered-business-locations-san-francisco.csv']

In [95]:
data = pd.read_csv('../input/registered-business-locations-san-francisco.csv')

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [96]:
data.head()

      Location Id                        ...                                                          Business Location
0  0000071-03-001                        ...                          {'latitude': '37.804759', 'longitude': '-122.4...
1  0000028-02-001                        ...                          {'latitude': '37.799823', 'longitude': '-122.4...
2  0000052-01-001                        ...                          {'latitude': '37.748926', 'longitude': '-122.4...
3  0000071-01-001                        ...                          {'latitude': '37.804734', 'longitude': '-122.4...
4  0000071-02-001                        ...                          {'latitude': '37.800876', 'longitude': '-122.4...

[5 rows x 26 columns]

## Getting Years from Datetime

In [97]:
# Takes in a list of datetimes and returns a list of years
def get_business_year(arr):
    years = []
    for d in arr:
        if str(d) == 'nan':
            years.append("NaN")
        else:
            years.append(datetime.strptime(str(d).split('T')[0], '%Y-%m-%d').year)
    
    return years

In [98]:
years = get_business_year(data['Business Start Date'])
data['Business Year'] = years
data[['Business Start Date', 'Business Year']]

        Business Start Date Business Year
0       1968-10-01T00:00:00          1968
1       1993-09-30T00:00:00          1993
2       1968-10-01T00:00:00          1968
3       1968-10-01T00:00:00          1968
4       1968-10-01T00:00:00          1968
5       1968-10-01T00:00:00          1968
6       1968-10-01T00:00:00          1968
7       1968-10-01T00:00:00          1968
8       1968-10-01T00:00:00          1968
9       2003-01-01T00:00:00          2003
10      1968-10-01T00:00:00          1968
11      1968-10-01T00:00:00          1968
12      1968-10-01T00:00:00          1968
13      1968-10-01T00:00:00          1968
14      1968-10-01T00:00:00          1968
15      1968-10-01T00:00:00          1968
16      1968-10-01T00:00:00          1968
17      1968-10-01T00:00:00          1968
18      1968-10-01T00:00:00          1968
19      1968-10-01T00:00:00          1968
20      1968-10-01T00:00:00          1968
21      1968-10-01T00:00:00          1968
22      1968-10-01T00:00:00          1968
23      1968-10-01T00:00:00          1968
24      1968-10-01T00:00:00          1968
25      1968-10-01T00:00:00          1968
26      1968-10-01T00:00:00          1968
27      1968-10-01T00:00:00          1968
28      1968-10-01T00:00:00          1968
29      1968-10-01T00:00:00          1968
...                     ...           ...
235553  2019-03-25T00:00:00          2019
235554  2019-03-25T00:00:00          2019
235555  2019-03-23T00:00:00          2019
235556  2019-03-15T00:00:00          2019
235557  2019-03-07T00:00:00          2019
235558  2005-01-01T00:00:00          2005
235559  2019-01-01T00:00:00          2019
235560  2019-03-22T00:00:00          2019
235561  2019-03-16T00:00:00          2019
235562  2005-01-01T00:00:00          2005
235563  2008-12-12T00:00:00          2008
235564  2019-02-06T00:00:00          2019
235565  2019-03-19T00:00:00          2019
235566  2017-09-28T00:00:00          2017
235567  2018-04-06T00:00:00          2018
235568  2018-03-01T00:00:00          2018
235569  2017-11-14T00:00:00          2017
235570  2018-10-19T00:00:00          2018
235571  2018-10-19T00:00:00          2018
235572  2018-10-19T00:00:00          2018
235573  2018-10-19T00:00:00          2018
235574  2019-03-15T00:00:00          2019
235575  2018-06-01T00:00:00          2018
235576  2012-01-04T00:00:00          2012
235577  2011-05-18T00:00:00          2011
235578  2011-02-24T00:00:00          2011
235579  2012-08-03T00:00:00          2012
235580  2016-03-15T00:00:00          2016
235581  2016-03-15T00:00:00          2016
235582  2019-03-25T00:00:00          2019

[235583 rows x 2 columns]

## Latitude/Longitude and Other Geodata

In [99]:
def get_dict(my_dict, val, default='NaN'):
    if val in my_dict:
        return my_dict[val]
    else:
        return default

In [100]:
# Takes a list of dictionary strings with geographic data and returns the latitude and longitude in separate lists
def get_geo_data(arr):
    lat = []
    long = []
    for geo_str in arr:
        if str(geo_str) == 'nan':
            lat.append("NaN")
            long.append("NaN")
        else:
            geo_dict = literal_eval(geo_str)
#             print(geo_dict)
            lat.append(get_dict(geo_dict,'latitude'))
            long.append(get_dict(geo_dict,'longitude'))
    return lat, long

In [101]:
lat, long = get_geo_data(data['Business Location'])
data['Latitude'] = lat
data['Longitude'] = long

In [102]:
data[['Business Location', 'Latitude', 'Longitude']]

                                        Business Location     ...         Longitude
0       {'latitude': '37.804759', 'longitude': '-122.4...     ...       -122.442794
1       {'latitude': '37.799823', 'longitude': '-122.4...     ...       -122.430996
2       {'latitude': '37.748926', 'longitude': '-122.4...     ...       -122.465074
3       {'latitude': '37.804734', 'longitude': '-122.4...     ...       -122.442997
4       {'latitude': '37.800876', 'longitude': '-122.4...     ...       -122.444757
5       {'latitude': '37.800876', 'longitude': '-122.4...     ...       -122.444757
6       {'latitude': '37.801724', 'longitude': '-122.4...     ...       -122.407812
7       {'latitude': '37.801724', 'longitude': '-122.4...     ...       -122.407812
8       {'latitude': '37.76378', 'longitude': '-122.41...     ...       -122.410307
9       {'latitude': '43.161276', 'longitude': '-77.61...     ...        -77.619386
10      {'latitude': '37.782133', 'longitude': '-122.4...     ...       -122.450433
11      {'latitude': '37.782133', 'longitude': '-122.4...     ...       -122.450433
12      {'latitude': '37.746192', 'longitude': '-122.3...     ...       -122.392421
13      {'latitude': '37.736139', 'longitude': '-122.3...     ...       -122.393059
14      {'latitude': '37.736139', 'longitude': '-122.3...     ...       -122.393059
15      {'latitude': '37.75034', 'longitude': '-122.38...     ...       -122.386099
16      {'latitude': '37.780746', 'longitude': '-122.4...     ...       -122.402797
17      {'latitude': '37.780746', 'longitude': '-122.4...     ...       -122.402797
18      {'latitude': '37.7877', 'longitude': '-122.400...     ...       -122.400776
19      {'latitude': '37.7877', 'longitude': '-122.400...     ...       -122.400776
20      {'latitude': '37.790697', 'longitude': '-122.4...     ...       -122.404484
21      {'latitude': '37.74525', 'longitude': '-122.40...     ...       -122.400812
22      {'latitude': '37.786634', 'longitude': '-122.3...     ...       -122.399502
23      {'latitude': '37.789736', 'longitude': '-122.4...     ...       -122.408673
24      {'latitude': '37.774234', 'longitude': '-122.3...     ...       -122.398633
25      {'latitude': '37.792972', 'longitude': '-122.4...     ...       -122.422943
26      {'latitude': '37.788972', 'longitude': '-122.4...     ...       -122.410677
27      {'latitude': '37.788919', 'longitude': '-122.4...     ...        -122.41109
28      {'latitude': '37.790564', 'longitude': '-122.4...     ...       -122.413156
29      {'latitude': '37.765733', 'longitude': '-122.3...     ...        -122.39975
...                                                   ...     ...               ...
235553                                                NaN     ...               NaN
235554                                                NaN     ...               NaN
235555                                                NaN     ...               NaN
235556                                                NaN     ...               NaN
235557                                                NaN     ...               NaN
235558                                                NaN     ...               NaN
235559                                                NaN     ...               NaN
235560                                                NaN     ...               NaN
235561                                                NaN     ...               NaN
235562                                                NaN     ...               NaN
235563                                                NaN     ...               NaN
235564                                                NaN     ...               NaN
235565                                                NaN     ...               NaN
235566                                                NaN     ...               NaN
235567                                                NaN     ...               NaN
235568                                                NaN     ...               NaN
235569                                                NaN     ...               NaN
235570                                                NaN     ...               NaN
235571                                                NaN     ...               NaN
235572                                                NaN     ...               NaN
235573                                                NaN     ...               NaN
235574                                                NaN     ...               NaN
235575                                                NaN     ...               NaN
235576                                                NaN     ...               NaN
235577                                                NaN     ...               NaN
235578                                                NaN     ...               NaN
235579                                                NaN     ...               NaN
235580                                                NaN     ...               NaN
235581                                                NaN     ...               NaN
235582                                                NaN     ...               NaN

[235583 rows x 3 columns]

In [103]:
## There are a number of NaN (null) values. So don't be worried from ouptut above
data.loc[data['Business Location'].isnull()]

           Location Id  Business Account Number    ...    Latitude Longitude
140     0001746-01-999                     1746    ...         NaN       NaN
329     0005995-01-001                     5995    ...         NaN       NaN
1436    0023047-01-999                    23047    ...         NaN       NaN
1524    0024864-01-999                    24864    ...         NaN       NaN
1813    0029094-01-999                    29094    ...         NaN       NaN
4347    0053813-01-001                    53813    ...         NaN       NaN
4369    0054273-01-999                    54273    ...         NaN       NaN
4372    0054358-01-999                    54358    ...         NaN       NaN
4379    0054495-01-999                    54495    ...         NaN       NaN
4695    0059322-01-999                    59322    ...         NaN       NaN
4709    0059484-01-999                    59484    ...         NaN       NaN
4738    0059845-01-999                    59845    ...         NaN       NaN
4974    0062168-01-999                    62168    ...         NaN       NaN
5171    0064007-01-999                    64007    ...         NaN       NaN
5231    0064530-01-999                    64530    ...         NaN       NaN
5260    0064932-01-999                    64932    ...         NaN       NaN
5299    0065495-02-999                    65495    ...         NaN       NaN
5354    0066317-01-001                    66317    ...         NaN       NaN
5378    0066906-01-999                    66906    ...         NaN       NaN
6100    0077865-01-999                    77865    ...         NaN       NaN
6172    0079484-01-001                    79484    ...         NaN       NaN
8221    0110841-01-999                   110841    ...         NaN       NaN
8378    0113606-01-001                   113606    ...         NaN       NaN
8453    0115138-01-999                   115138    ...         NaN       NaN
9575    0129902-01-999                   129902    ...         NaN       NaN
9613    0130387-01-999                   130387    ...         NaN       NaN
9839    0133836-01-999                   133836    ...         NaN       NaN
10182   0139571-01-001                   139571    ...         NaN       NaN
10388   0142166-01-999                   142166    ...         NaN       NaN
10561   0144837-03-999                   144837    ...         NaN       NaN
...                ...                      ...    ...         ...       ...
235553  1216934-03-191                  1099979    ...         NaN       NaN
235554  1216938-03-191                  1099981    ...         NaN       NaN
235555  1216940-03-191                  1099984    ...         NaN       NaN
235556  1216942-03-191                  1099985    ...         NaN       NaN
235557  1216944-03-191                  1099986    ...         NaN       NaN
235558  1216946-03-191                   390658    ...         NaN       NaN
235559  1216947-03-191                  1099987    ...         NaN       NaN
235560  1216948-03-191                  1099902    ...         NaN       NaN
235561  1216949-03-191                  1099651    ...         NaN       NaN
235562  1216950-03-191                   390658    ...         NaN       NaN
235563  1216951-03-191                  1040517    ...         NaN       NaN
235564  1216952-03-191                  1098908    ...         NaN       NaN
235565  1216953-03-191                  1099751    ...         NaN       NaN
235566  1216954-03-191                  1085097    ...         NaN       NaN
235567  1216955-03-191                  1086034    ...         NaN       NaN
235568  1216956-03-191                  1099473    ...         NaN       NaN
235569  1216957-03-191                  1079556    ...         NaN       NaN
235570  1216958-03-191                  1094278    ...         NaN       NaN
235571  1216959-03-191                  1094278    ...         NaN       NaN
235572  1216960-03-191                  1094278    ...         NaN       NaN
235573  1216961-03-191                  1094278    ...         NaN       NaN
235574  1216962-03-191                  1099907    ...         NaN       NaN
235575  1216963-03-191                  1088601    ...         NaN       NaN
235576  1216964-03-191                   465586    ...         NaN       NaN
235577  1216965-03-191                   459223    ...         NaN       NaN
235578  1216966-03-191                   456644    ...         NaN       NaN
235579  1216967-03-191                   471622    ...         NaN       NaN
235580  1216968-03-191                  1028880    ...         NaN       NaN
235581  1216969-03-191                  1028880    ...         NaN       NaN
235582  1216971-03-191                  1099988    ...         NaN       NaN

[64691 rows x 29 columns]

In [106]:
data.loc[data['Business Location'].notnull(), ['Business Location', 'Latitude', 'Longitude']]

                                        Business Location     ...         Longitude
0       {'latitude': '37.804759', 'longitude': '-122.4...     ...       -122.442794
1       {'latitude': '37.799823', 'longitude': '-122.4...     ...       -122.430996
2       {'latitude': '37.748926', 'longitude': '-122.4...     ...       -122.465074
3       {'latitude': '37.804734', 'longitude': '-122.4...     ...       -122.442997
4       {'latitude': '37.800876', 'longitude': '-122.4...     ...       -122.444757
5       {'latitude': '37.800876', 'longitude': '-122.4...     ...       -122.444757
6       {'latitude': '37.801724', 'longitude': '-122.4...     ...       -122.407812
7       {'latitude': '37.801724', 'longitude': '-122.4...     ...       -122.407812
8       {'latitude': '37.76378', 'longitude': '-122.41...     ...       -122.410307
9       {'latitude': '43.161276', 'longitude': '-77.61...     ...        -77.619386
10      {'latitude': '37.782133', 'longitude': '-122.4...     ...       -122.450433
11      {'latitude': '37.782133', 'longitude': '-122.4...     ...       -122.450433
12      {'latitude': '37.746192', 'longitude': '-122.3...     ...       -122.392421
13      {'latitude': '37.736139', 'longitude': '-122.3...     ...       -122.393059
14      {'latitude': '37.736139', 'longitude': '-122.3...     ...       -122.393059
15      {'latitude': '37.75034', 'longitude': '-122.38...     ...       -122.386099
16      {'latitude': '37.780746', 'longitude': '-122.4...     ...       -122.402797
17      {'latitude': '37.780746', 'longitude': '-122.4...     ...       -122.402797
18      {'latitude': '37.7877', 'longitude': '-122.400...     ...       -122.400776
19      {'latitude': '37.7877', 'longitude': '-122.400...     ...       -122.400776
20      {'latitude': '37.790697', 'longitude': '-122.4...     ...       -122.404484
21      {'latitude': '37.74525', 'longitude': '-122.40...     ...       -122.400812
22      {'latitude': '37.786634', 'longitude': '-122.3...     ...       -122.399502
23      {'latitude': '37.789736', 'longitude': '-122.4...     ...       -122.408673
24      {'latitude': '37.774234', 'longitude': '-122.3...     ...       -122.398633
25      {'latitude': '37.792972', 'longitude': '-122.4...     ...       -122.422943
26      {'latitude': '37.788972', 'longitude': '-122.4...     ...       -122.410677
27      {'latitude': '37.788919', 'longitude': '-122.4...     ...        -122.41109
28      {'latitude': '37.790564', 'longitude': '-122.4...     ...       -122.413156
29      {'latitude': '37.765733', 'longitude': '-122.3...     ...        -122.39975
...                                                   ...     ...               ...
171321  {'latitude': '37.762125', 'longitude': '-122.4...     ...       -122.492066
171322  {'latitude': '40.760674', 'longitude': '-73.97...     ...        -73.979869
171323  {'latitude': '37.782701', 'longitude': '-122.4...     ...       -122.473028
171324  {'latitude': '37.373158', 'longitude': '-122.0...     ...       -122.073764
171325  {'latitude': '37.734748', 'longitude': '-122.4...     ...       -122.427924
171326  {'latitude': '37.782979', 'longitude': '-122.4...     ...       -122.415788
171327  {'latitude': '37.360799', 'longitude': '-121.9...     ...       -121.956638
171328  {'latitude': '37.736833', 'longitude': '-122.4...     ...       -122.467301
171329  {'latitude': '37.75113', 'longitude': '-122.39...     ...       -122.396417
171330  {'latitude': '37.75113', 'longitude': '-122.39...     ...       -122.396417
171331  {'latitude': '32.629574', 'longitude': '-117.1...     ...       -117.132929
171332  {'latitude': '37.763332', 'longitude': '-122.3...     ...       -122.397559
171333  {'latitude': '37.763506', 'longitude': '-122.4...     ...       -122.478728
171334  {'latitude': '37.758', 'longitude': '-122.1680...     ...        -122.16802
171335  {'latitude': '37.679992', 'longitude': '-122.1...     ...       -122.160054
171336  {'latitude': '34.059486', 'longitude': '-84.31...     ...         -84.31055
171337  {'latitude': '37.76152', 'longitude': '-122.38...     ...       -122.388576
171338  {'latitude': '37.791977', 'longitude': '-122.4...     ...        -122.40093
171339  {'latitude': '37.781611', 'longitude': '-122.3...     ...        -122.39547
171340  {'latitude': '37.56103', 'longitude': '-122.31...     ...       -122.314703
171341  {'latitude': '37.734017', 'longitude': '-122.4...     ...        -122.48963
171342  {'latitude': '37.792481', 'longitude': '-122.4...     ...       -122.401034
171343  {'latitude': '37.75904', 'longitude': '-122.48...     ...       -122.485415
171344  {'latitude': '37.731625', 'longitude': '-122.3...     ...       -122.397482
171345  {'latitude': '37.787005', 'longitude': '-122.4...     ...        -122.40107
171346  {'latitude': '37.762784', 'longitude': '-122.5...     ...       -122.507169
171347  {'latitude': '37.771702', 'longitude': '-122.4...     ...       -122.427003
171348  {'latitude': '37.729619', 'longitude': '-122.4...     ...       -122.446578
171349  {'latitude': '37.777426', 'longitude': '-122.4...     ...       -122.422363
171350  {'latitude': '37.780016', 'longitude': '-122.4...     ...       -122.491191

[170892 rows x 3 columns]