In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
df=pd.read_csv('https://data.wra.gov.tw/Service/OpenData.aspx?format=csv&id=C79B9CF3-122E-43B6-A436-D7F6B40C0D3A')
df

In [ ]:
#改column名稱
df.columns=['年平均水位','年最高日水位','瞬間最高水位','年最低日水位','瞬間最低水位','年最高日水位發生日','年最低日水位發生日','瞬間最高水位發生日時','瞬間最低水位發生日時','井號','西元年']
df

In [ ]:
#將年水位差(年最高日水位-年最低日水位)加入欄位
df['年水位差']=df.年最高日水位 - df.年最低日水位
df

In [ ]:
#將年水位差從高到低排列
df_sort=df.sort_values(by='年水位差',ascending=False)
df_sort.loc[:,['井號','西元年','年水位差']]

In [ ]:
#年平均水位至少3.5的資料內容
year_ave = df.loc[df.年平均水位 >= 3.5]
year_ave

In [ ]:
#依'西元年'做分組並計算出現多少次
year_count=df.groupby('西元年').西元年.count()
year_count

In [ ]:
#依'西元年'分組後，取得2000年的內容
y2000 = df.groupby('西元年').get_group(2000)
y2000

In [ ]:
#將'井號'進行分組，計算出現次數並排序
number_count = df.groupby('井號').井號.count().sort_values()
number_count