filoger..Boot camp AI...
Exercise 2...
**Hotel-Booking dataset**

**Dataset:**
This data set contains booking information for a city hotel and a resort hotel and includes information such as when the booking was made, length of stay, the number of adults, children, and/or babies, and the number of available parking spaces, among other things. All personally identifying information has from the data.
We will perform exploratory data analysis with python to get insight from the data.

In [ ]:
#1 import libraries:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# read dataset:
df = pd.read_csv("../input/hotel-booking/hotel_booking.csv")

In [ ]:
#2 Information of dataset:

df.info()

In [ ]:
#3 Number of rows:

pd.DataFrame([df.shape],columns= ['rows','columns'],index= ['number'])

We have 119390 rows and 36 columns.

In [ ]:
#4 Check if our data contains any missing values: The column with most missing data?

df.isnull().sum().sort_values(ascending=False)[:5]

We have 4 features with missing values.In the company column, we have the most missing values.

In [ ]:
#5 Delete company column:

df = df.drop("company" , axis=1)
df.info()

In [ ]:
#6 Which countries have the most passengers? (5 country)

df["country"].value_counts().head()

Portugal,the United Kingdom,France,Spain and Germany have the most passengers.

In [ ]:
#7 Who has the maximum average daily rate (ADR)? How much?

df.loc[df["adr"].argmax()]
Name = df.loc[48515,"name"]
Price = df["adr"].max()
D= pd.DataFrame( [Name,Price] , ["Name","Price"] )
D.head()

Daniel Walter with $5400 has the maximum average daily rate.

In [ ]:
#8 Average of total ADRs with 2 decimals:

round(df["adr"].mean() , 2)

In [ ]:
#9 Average of stays in nights:

round((df["stays_in_weekend_nights"].mean()) + (df["stays_in_week_nights"].mean()) , 2)

In [ ]:
#10 Names and Emails who have 5 special request:

df[df["total_of_special_requests"]==5][["name",'email']]

In [ ]:
#11 The most frequent last name:

def family(name:str):
    return name.split()[1]
df["family"]= df["name"].apply(family)
df["family"].value_counts()[:5]

Smith with 2510 frequent has the most last name.

In [ ]:

#12 People whith the most children and babies:

df["kids"]= df["children"]+df["babies"]
df.groupby("name").sum()["kids"].sort_values(ascending=False).head()

Nicholas Parker and Jamie Ramirez with 10 number of children and babies have the most kids.

In [ ]:
#13 The most number of local calling codes:

df["local_code"] = df["phone-number"].apply(lambda code:code[:3])
df["local_code"].value_counts()[:3].reset_index()

168 , 167 and 166 have the most number of local calling codes.

****Exploratory Data Analysis****

In [ ]:
# What is the booking ratio between Resort Hotel and City Hotel?
sns.countplot(data=df , x="hotel")

The costumers prefer City Hotel to Resort Hotel.

In [ ]:
# What is the state for each year?
sns.countplot(data=df , x="arrival_date_year" )

More than double bookings were made in 2016, compared to the previous year. But the bookings decreased by almost 15000 the next year.

In [ ]:
# Year-wise and Hotel-wise (side-by-side) comparison:
sns.countplot(data=df , x="arrival_date_year" , hue="hotel" )
plt.legend()

In every years, City Hotel had the most booking.

In [ ]:
# Which is the busiest month for hotels?
plt.figure(figsize=(12,6))
sns.countplot(data=df ,x="arrival_date_month")

As we can see most bookings were made from July to August. And the least bookings were made at the start and end of the year.

In [ ]:
# How Long People Stay in the hotel?
plt.figure(figsize=(12,6),dpi=120)
df["stays_in_nights"]= df["stays_in_weekend_nights"]+ df["stays_in_week_nights"]
sns.countplot(data=df, x="stays_in_nights" , palette="hsv")

Most people stay for one, two, or three.