In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['salary_grid.csv', 'recruiting_costs.csv', 'HRDataset_v9.csv', 'production_staff.csv', 'core_dataset.csv']

In [2]:
import sklearn
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn.metrics import precision_recall_fscore_support as score

from sklearn.metrics import explained_variance_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

from time import time

from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, RANSACRegressor
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.svm import SVR
from sklearn.svm import LinearSVR
from sklearn.linear_model import Lasso, Ridge


from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR


import matplotlib.pyplot as plt
from pylab import rcParams
import seaborn as sb

In [9]:
hr = pd.read_csv("../input/core_dataset.csv")
hr

             Employee Name            ...                    Performance Score
0               Brown, Mia            ...                          Fully Meets
1     LaRotonda, William              ...                          Fully Meets
2         Steans, Tyrone              ...                          Fully Meets
3          Howard, Estelle            ...             N/A- too early to review
4              Singh, Nan             ...             N/A- too early to review
5         Smith, Leigh Ann            ...                          Fully Meets
6      LeBlanc, Brandon  R            ...                          Fully Meets
7              Quinn, Sean            ...                          Fully Meets
8        Boutwell, Bonalyn            ...                         90-day meets
9        Foster-Baker, Amy            ...                          Fully Meets
10             King, Janet            ...                          Fully Meets
11        Zamora, Jennifer            ...                          Exceptional
12           Becker, Renee            ...                          Fully Meets
13           Goble, Taisha            ...                          Fully Meets
14       Hernandez, Daniff            ...             N/A- too early to review
15           Horton, Jayne            ...             N/A- too early to review
16        Johnson, Noelle             ...                         90-day meets
17          Murray, Thomas            ...                          Exceptional
18        Pearson, Randall            ...                          Fully Meets
19       Petrowsky, Thelma            ...                          Exceptional
20             Roby, Lori             ...                          Fully Meets
21            Rogers, Ivan            ...             N/A- too early to review
22           Salter, Jason            ...                         90-day meets
23          Simard, Kramer            ...                         90-day meets
24             Zhou, Julia            ...                         90-day meets
25             Foss, Jason            ...                          Exceptional
26              Roup,Simon            ...                          Fully Meets
27           Ruiz, Ricardo            ...                          Fully Meets
28           Monroe, Peter            ...                    Needs Improvement
29           Dougall, Eric            ...                              Exceeds
..                     ...            ...                                  ...
272          Jeremy Prater            ...                                  PIP
273  Khemmich, Bartholemew            ...                          Fully Meets
274       Leruth, Giovanni            ...                          Fully Meets
275        Martins, Joseph            ...                          Fully Meets
276          McKinzie, Jac            ...             N/A- too early to review
277       Mullaney, Howard            ...                    Needs Improvement
278         Nguyen, Dheepa            ...                          Fully Meets
279         Onque, Jasmine            ...                          Fully Meets
280          Ozark, Travis            ...                         90-day meets
281            Potts, Xana            ...                          Fully Meets
282       Riordan, Michael            ...                              Exceeds
283        Strong, Caitrin            ...                          Fully Meets
284       Terry, Sharlene             ...                          Fully Meets
285        Valentin,Jackie            ...                          Fully Meets
286       Villanueva, Noah            ...                          Fully Meets
287        Houlihan, Debra            ...                          Fully Meets
288         Daneault, Lynn            ...                          Fully Meets
289    Kampew, Donysha                ...                          Fully Meets
290            Smith, John            ...                    Needs Improvement
291        Andreola, Colby            ...                          Fully Meets
292       Carabbio, Judith            ...                         90-day meets
293      Del Bosque, Keyla            ...                         90-day meets
294         Exantus, Susan            ...                    Needs Improvement
295         Martin, Sandra            ...                          Fully Meets
296        Patronick, Luke            ...                              Exceeds
297           Saada, Adell            ...                          Fully Meets
298          Szabo, Andrew            ...                          Exceptional
299           True, Edward            ...                          Fully Meets
300       Sweetwater, Alex            ...                          Fully Meets
301                    NaN            ...                                  NaN

[302 rows x 21 columns]

In [10]:
hr.columns = ['Name','EmpNum','State','Zip','Date_of_birth','Age','Sex','MaritalDesc','CitizenDesc','Hispanic/Latino','RaceDesc','Date_of_Hire','Date_of_Termination','Reason_For_Termination','Employment_Status','Department','Position','Pay_Rate','Manager_Name','Employment_Source','Performance_Score']
hr = hr.drop(hr.index[301])
print(hr)

                      Name            ...                    Performance_Score
0               Brown, Mia            ...                          Fully Meets
1     LaRotonda, William              ...                          Fully Meets
2         Steans, Tyrone              ...                          Fully Meets
3          Howard, Estelle            ...             N/A- too early to review
4              Singh, Nan             ...             N/A- too early to review
5         Smith, Leigh Ann            ...                          Fully Meets
6      LeBlanc, Brandon  R            ...                          Fully Meets
7              Quinn, Sean            ...                          Fully Meets
8        Boutwell, Bonalyn            ...                         90-day meets
9        Foster-Baker, Amy            ...                          Fully Meets
10             King, Janet            ...                          Fully Meets
11        Zamora, Jennifer            ...                          Exceptional
12           Becker, Renee            ...                          Fully Meets
13           Goble, Taisha            ...                          Fully Meets
14       Hernandez, Daniff            ...             N/A- too early to review
15           Horton, Jayne            ...             N/A- too early to review
16        Johnson, Noelle             ...                         90-day meets
17          Murray, Thomas            ...                          Exceptional
18        Pearson, Randall            ...                          Fully Meets
19       Petrowsky, Thelma            ...                          Exceptional
20             Roby, Lori             ...                          Fully Meets
21            Rogers, Ivan            ...             N/A- too early to review
22           Salter, Jason            ...                         90-day meets
23          Simard, Kramer            ...                         90-day meets
24             Zhou, Julia            ...                         90-day meets
25             Foss, Jason            ...                          Exceptional
26              Roup,Simon            ...                          Fully Meets
27           Ruiz, Ricardo            ...                          Fully Meets
28           Monroe, Peter            ...                    Needs Improvement
29           Dougall, Eric            ...                              Exceeds
..                     ...            ...                                  ...
271        Guilianno, Mike            ...                          Fully Meets
272          Jeremy Prater            ...                                  PIP
273  Khemmich, Bartholemew            ...                          Fully Meets
274       Leruth, Giovanni            ...                          Fully Meets
275        Martins, Joseph            ...                          Fully Meets
276          McKinzie, Jac            ...             N/A- too early to review
277       Mullaney, Howard            ...                    Needs Improvement
278         Nguyen, Dheepa            ...                          Fully Meets
279         Onque, Jasmine            ...                          Fully Meets
280          Ozark, Travis            ...                         90-day meets
281            Potts, Xana            ...                          Fully Meets
282       Riordan, Michael            ...                              Exceeds
283        Strong, Caitrin            ...                          Fully Meets
284       Terry, Sharlene             ...                          Fully Meets
285        Valentin,Jackie            ...                          Fully Meets
286       Villanueva, Noah            ...                          Fully Meets
287        Houlihan, Debra            ...                          Fully Meets
288         Daneault, Lynn            ...                          Fully Meets
289    Kampew, Donysha                ...                          Fully Meets
290            Smith, John            ...                    Needs Improvement
291        Andreola, Colby            ...                          Fully Meets
292       Carabbio, Judith            ...                         90-day meets
293      Del Bosque, Keyla            ...                         90-day meets
294         Exantus, Susan            ...                    Needs Improvement
295         Martin, Sandra            ...                          Fully Meets
296        Patronick, Luke            ...                              Exceeds
297           Saada, Adell            ...                          Fully Meets
298          Szabo, Andrew            ...                          Exceptional
299           True, Edward            ...                          Fully Meets
300       Sweetwater, Alex            ...                          Fully Meets

[301 rows x 21 columns]

In [11]:
hr_no_dot = hr.drop('Date_of_Termination',axis=1)

In [12]:
le = preprocessing.LabelEncoder()
hr_no_dot = hr_no_dot.apply(le.fit_transform)
hr_no_dot

     Name  EmpNum        ...          Employment_Source  Performance_Score
0      28      82        ...                          3                  3
1     149     102        ...                         20                  3
2     262     182        ...                          7                  3
3     126     168        ...                         15                  4
4     249     200        ...                         20                  4
5     253       4        ...                          3                  3
6     155      76        ...                          9                  3
7     221     158        ...                          3                  3
8      24     206        ...                          3                  0
9      88     138        ...                         13                  3
10    144      24        ...                         15                  3
11    298     133        ...                          4                  2
12     17      73        ...                         17                  3
13    101      11        ...                          5                  3
14    121     272        ...                          4                  4
15    124      96        ...                          5                  4
16    138      34        ...                          5                  0
17    190     254        ...                          3                  2
18    206      72        ...                          4                  3
19    214     112        ...                          4                  2
20    231     255        ...                          4                  3
21    233     146        ...                         15                  4
22    242     128        ...                         19                  0
23    248       7        ...                          4                  0
24    299     124        ...                          4                  0
25     87     135        ...                         16                  2
26    236     105        ...                         16                  3
27    237      20        ...                          3                  3
28    183      49        ...                          3                  5
29     69      70        ...                         16                  1
..    ...     ...        ...                        ...                ...
271   113      19        ...                         10                  3
272   135      15        ...                         20                  6
273   143      88        ...                         15                  3
274   157     282        ...                         20                  3
275   172     165        ...                          4                  3
276   175     167        ...                         20                  4
277   189     196        ...                          7                  5
278   195     132        ...                         15                  3
279   200     290        ...                         15                  3
280   203       8        ...                         20                  0
281   217      75        ...                         20                  3
282   224     294        ...                          0                  1
283   264     274        ...                         16                  3
284   272     224        ...                          9                  3
285   282     221        ...                         13                  3
286   284     131        ...                         20                  3
287   125      42        ...                          8                  3
288    55     227        ...                         15                  3
289   141     119        ...                         18                  3
290   252     285        ...                          3                  5
291     7     107        ...                         19                  3
292    36      66        ...                         15                  0
293    60     149        ...                          9                  0
294    77     225        ...                          0                  5
295   171     187        ...                         17                  3
296   205     134        ...                          3                  1
297   238      58        ...                         15                  3
298   269     140        ...                          8                  2
299   279      74        ...                          3                  3
300   268      27        ...                         17                  3

[301 rows x 20 columns]

In [13]:
corr = hr_no_dot.corr()
print(corr)

                            Name        ...          Performance_Score
Name                    1.000000        ...                   0.050567
EmpNum                 -0.062629        ...                   0.116753
State                  -0.068161        ...                   0.083885
Zip                     0.063956        ...                  -0.035418
Date_of_birth          -0.021010        ...                   0.058144
Age                     0.013301        ...                  -0.050695
Sex                     0.030142        ...                   0.020414
MaritalDesc            -0.043863        ...                   0.045112
CitizenDesc            -0.082492        ...                  -0.059613
Hispanic/Latino        -0.042185        ...                  -0.031689
RaceDesc               -0.058819        ...                  -0.045488
Date_of_Hire           -0.011273        ...                   0.173837
Reason_For_Termination  0.045477        ...                   0.007913
Employment_Status       0.100452        ...                   0.028353
Department             -0.024105        ...                   0.019003
Position               -0.051566        ...                  -0.010440
Pay_Rate               -0.021441        ...                  -0.041875
Manager_Name            0.001220        ...                  -0.033310
Employment_Source       0.002775        ...                   0.008829
Performance_Score       0.050567        ...                   1.000000

[20 rows x 20 columns]

In [14]:
hr_no_dot.columns

Index(['Name', 'EmpNum', 'State', 'Zip', 'Date_of_birth', 'Age', 'Sex',
       'MaritalDesc', 'CitizenDesc', 'Hispanic/Latino', 'RaceDesc',
       'Date_of_Hire', 'Reason_For_Termination', 'Employment_Status',
       'Department', 'Position', 'Pay_Rate', 'Manager_Name',
       'Employment_Source', 'Performance_Score'],
      dtype='object')

In [15]:
X = hr_no_dot.loc[:,['State', 'Zip', 'Date_of_birth', 'Age', 'Sex',
       'MaritalDesc', 'CitizenDesc', 'Hispanic/Latino', 'RaceDesc',
       'Date_of_Hire', 'Reason_For_Termination', 'Employment_Status',
       'Department', 'Position', 'Manager_Name',
       'Employment_Source', 'Performance_Score']]
y = hr_no_dot.loc[:,['Pay_Rate']]

print(X)
print(y)

     State  Zip        ...          Employment_Source  Performance_Score
0       10    3        ...                          3                  3
1       10    4        ...                         20                  3
2       10  119        ...                          7                  3
3       10   86        ...                         15                  4
4       10   98        ...                         20                  4
5       10   25        ...                          3                  3
6       10    4        ...                          9                  3
7       10   47        ...                          3                  3
8       10  112        ...                          3                  0
9       10   49        ...                         13                  3
10      10   35        ...                         15                  3
11      10   53        ...                          4                  2
12      10   41        ...                         17                  3
13      10   67        ...                          5                  3
14      10   39        ...                          4                  4
15      10  118        ...                          5                  4
16      10   95        ...                          5                  0
17      23  147        ...                          3                  2
18      10  121        ...                          4                  3
19      10   31        ...                          4                  2
20      10   31        ...                          4                  3
21      10   22        ...                         15                  4
22      10  108        ...                         19                  0
23      10   60        ...                          4                  0
24      10   80        ...                          4                  0
25      10    4        ...                         16                  2
26      10  116        ...                         16                  3
27      10   37        ...                          3                  3
28      10   73        ...                          3                  5
29      10   31        ...                         16                  1
..     ...  ...        ...                        ...                ...
271     22  140        ...                         10                  3
272     16  153        ...                         20                  6
273      3  149        ...                         15                  3
274     24  151        ...                         20                  3
275     23  146        ...                          4                  3
276     23  148        ...                         20                  4
277      0  139        ...                          7                  5
278      6  137        ...                         15                  3
279      5  138        ...                         15                  3
280     13  136        ...                         20                  0
281      9  141        ...                         20                  3
282     14  144        ...                          0                  1
283     12  145        ...                         16                  3
284     19  155        ...                          9                  3
285      1  152        ...                         13                  3
286     11  125        ...                         20                  3
287     21  123        ...                          8                  3
288     26  126        ...                         15                  3
289     20  134        ...                         18                  3
290     10   31        ...                          3                  5
291     10   60        ...                         19                  3
292     10   71        ...                         15                  0
293     10   88        ...                          9                  0
294     10   12        ...                          0                  5
295     10   74        ...                         17                  3
296     10   25        ...                          3                  1
297     10   71        ...                         15                  3
298     10   77        ...                          8                  2
299     10  107        ...                          3                  3
300     10   90        ...                         17                  3

[301 rows x 17 columns]
     Pay_Rate
0          35
1          22
2          38
3          19
4           6
5          16
6          73
7          73
8          43
9          43
10         90
11         89
12         55
13         61
14         50
15         42
16         49
17         44
18         51
19         54
20         48
21         53
22         56
23         39
24         40
25         89
26         86
27         17
28         87
29         88
..        ...
271        73
272        77
273        73
274        73
275        77
276        73
277        73
278        73
279        79
280        73
281        73
282        73
283        70
284        73
285        73
286        77
287        83
288        70
289        84
290        77
291        59
292        77
293        80
294        61
295        76
296        67
297        63
298        60
299        57
300        32

[301 rows x 1 columns]

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.1, random_state=17)

In [17]:
regressors = [
    LinearRegression(), 
    RANSACRegressor(), 
    KNeighborsRegressor(),
    KNeighborsRegressor(n_neighbors=9, metric='manhattan'),
    SVR(),
    LinearSVR(),
    GaussianProcessRegressor(),
    SVR(kernel='linear'), # Cf. LinearSVR: much slower, might be better or worse: 
]

In [18]:
head = 6
for model in regressors[:head]:
    start = time()
    model.fit(X_train, y_train)
    train_time = time() - start
    start = time()
    predictions = model.predict(X_test)
    predict_time = time()-start    
    print(model)
    print("\tTraining time: %0.3fs)" % train_time)
    print("\tPrediction time: %0.3fs" % predict_time)
    print("\tExplained variance:", explained_variance_score(y_test, predictions))
    print("\tMean absolute error:", mean_absolute_error(y_test, predictions))
    print("\tR2 score:", r2_score(y_test, predictions))
    print()

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)
	Training time: 0.162s)
	Prediction time: 0.001s
	Explained variance: 0.2617233150129802
	Mean absolute error: 21.053629248570044
	R2 score: 0.2588572686093086

RANSACRegressor(base_estimator=None, is_data_valid=None, is_model_valid=None,
        loss='absolute_loss', max_skips=inf, max_trials=100,
        min_samples=None, random_state=None, residual_threshold=None,
        stop_n_inliers=inf, stop_probability=0.99, stop_score=inf)
	Training time: 0.105s)
	Prediction time: 0.001s
	Explained variance: -2.6448236155568234
	Mean absolute error: 42.36766136907169
	R2 score: -3.2812530949153738

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=5, p=2,
          weights='uniform')
	Training time: 0.002s)
	Prediction time: 0.002s
	Explained variance: 0.23876125635750223
	Mean absolute error: 21.819354838709682
	R2 score: 0.2223020825943256

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='manhattan',
          metric_params=None, n_jobs=None, n_neighbors=9, p=2,
          weights='uniform')
	Training time: 0.001s)
	Prediction time: 0.002s
	Explained variance: 0.24280198822788857
	Mean absolute error: 22.60931899641577
	R2 score: 0.2192066037236945

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
  tol=0.001, verbose=False)
	Training time: 0.011s)
	Prediction time: 0.002s
	Explained variance: 5.422845560376643e-07
	Mean absolute error: 26.575799342270624
	R2 score: -0.20828354557488282

LinearSVR(C=1.0, dual=True, epsilon=0.0, fit_intercept=True,
     intercept_scaling=1.0, loss='epsilon_insensitive', max_iter=1000,
     random_state=None, tol=0.0001, verbose=0)
	Training time: 0.035s)
	Prediction time: 0.001s
	Explained variance: 0.2931740733239738
	Mean absolute error: 19.989640471534926
	R2 score: 0.214794476214607

/opt/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/opt/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

In [19]:
lr = LinearRegression()
lasso = Lasso()
ridge = Ridge()

for model in [lr, lasso, ridge]:
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    print(model)
    print("\tExplained variance:", explained_variance_score(y_test, predictions))
    print("\tMean absolute error:", mean_absolute_error(y_test, predictions))
    print("\tR2 score:", r2_score(y_test, predictions))
    print()

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)
	Explained variance: 0.2617233150129802
	Mean absolute error: 21.053629248570044
	R2 score: 0.2588572686093086

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)
	Explained variance: 0.2670900679656003
	Mean absolute error: 21.60418641465566
	R2 score: 0.26279836839698656

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)
	Explained variance: 0.26235856258562507
	Mean absolute error: 21.055164798726356
	R2 score: 0.2595085723662669

In [20]:
regressors = [LinearRegression(),
              DecisionTreeRegressor(max_depth=5),
              DecisionTreeRegressor(max_depth=10),
              DecisionTreeRegressor(max_depth=20),
              RandomForestRegressor(max_depth=10),
              SVR(),]

for model in regressors:
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    print(model)
    print("\tExplained variance:", explained_variance_score(y_test, predictions))
    print("\tMean absolute error:", mean_absolute_error(y_test, predictions))
    print("\tR2 score:", r2_score(y_test, predictions))
    print()

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)
	Explained variance: 0.2617233150129802
	Mean absolute error: 21.053629248570044
	R2 score: 0.2588572686093086

DecisionTreeRegressor(criterion='mse', max_depth=5, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')
	Explained variance: 0.8395094363040299
	Mean absolute error: 7.9409531894251755
	R2 score: 0.8368040970971553

DecisionTreeRegressor(criterion='mse', max_depth=10, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')
	Explained variance: 0.7614763397099285
	Mean absolute error: 10.279320276497696
	R2 score: 0.7570521435593195

DecisionTreeRegressor(criterion='mse', max_depth=20, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')
	Explained variance: 0.7509351247281472
	Mean absolute error: 10.064516129032258
	R2 score: 0.7489780291558312

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=10,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)
	Explained variance: 0.8782908389962826
	Mean absolute error: 7.977474156432138
	R2 score: 0.8745067402024784

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
  tol=0.001, verbose=False)
	Explained variance: 5.422845560376643e-07
	Mean absolute error: 26.575799342270624
	R2 score: -0.20828354557488282

/opt/conda/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:9: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  if __name__ == '__main__':
/opt/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)