## The link of the data set:
https://www.kaggle.com/tanuprabhu/hyper-cars-2019

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Reading the data

In [ ]:
df = pd.read_csv('../input/hyper-cars-2019/Hyper Cars 2019.csv')

### Showing the data

In [ ]:
df

### Explore the data

In [ ]:
f'The data has {df.shape[0]} Rows, and {df.shape[1]} Columns'

### Fix Column names

In [ ]:
df.rename(columns={'    Toppp-speeed':'Top speed'}, inplace=True) # Toppp-speeed
df.rename(columns={'Enginee':'Engine'}, inplace=True) # Enginee
df.rename(columns={'          hp':'Horsepower (hp)'}, inplace=True) # hp
df.rename(columns={'           Cost':'Price'}, inplace=True) # Cost
df.rename(columns={'     Car Name':'Car Name'}, inplace=True) # Car Name

## Cleaning the data

### Changing the misspelled car names

In [ ]:
df.iloc[3,0] = 'McLaren Senna Aaa'
df.iloc[4,0] = 'Koenigsegg Agera'
df.iloc[7,0] = 'Pagani Huayra BC'
df.iloc[9,0] = 'Bugatti Veyron'

### Round the floating points to a fixed number (2)

In [ ]:
# Convert hello (row 6 column Displacement) to the mean of the column
# Replace hello with 0
df.iloc[5,1] = 0
# Convert the column data tpe from str to float with round 2
df.iloc[:,1] = pd.to_numeric(df.iloc[:,1], downcast="float").round(2)
# Replace 0 with the mean of the column
df.iloc[5,1] = round(np.mean(df.iloc[:,1]), 2)

### Cleaning the garbage values in Engine column

In [ ]:
df.iloc[3,2] = 'V8' # From V8987654
df.iloc[7,2] = 'V12' # From _

### Replace the NaN values with the mean of the column

In [ ]:
df = df.fillna(df.mean())

### Reorder the columns

In [ ]:
df = df[['Car Name', 'Engine', 'Horsepower (hp)',
       '   Transmission', 'Top speed', 'Displacement ', 'Price']]

### Show the Result

In [ ]:
df

### Saving the data frame to a csv file

In [ ]:
df.to_csv('Result.csv', index=False)

### Plot the Price column

In [ ]:
# Define the figure
plt.figure(figsize=(10,6))

# Define x and y
x = df.iloc[:,0]
y = df.iloc[:,-1]

# Plot x and y
plt.scatter(x, y, color='b')

# Rotate the xticks
plt.xticks(rotation=45)

# Define title
plt.title('Price column', size=15, color='r')

# Show the figure
plt.show()

## Plot the Engine column

In [ ]:
# Define the figure
plt.figure(figsize=(10,6))

# Define x and y
x = df.iloc[:,0]
y = df.iloc[:,1]

# Plot x and y
plt.scatter(x, y, color='b')

# Rotate the xticks
plt.xticks(rotation=45)

# Define title
plt.title('Engine column', size=15, color='r')

# Show the figure
plt.show()