In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
data = pd.read_csv("../input/zomato-restaurants-in-india/zomato_restaurants_in_India.csv")

In [ ]:
data

In [ ]:
print("number of rows",data.shape[0])

Now, Lets see if the number of rows matches the number of unique items in the Data

In [ ]:
len(data.res_id)

### Data seems to be proper and clear. We will now proceed with further pre processing.
### Also, let us change the setting so that we can see all the columns in the data at once.

In [ ]:
pd.set_option('max_columns', None)

In [ ]:
data

### In the column 'Establishment we have a miscreant value with object '[ ]'. This is insignificant in our data and we will remove it.

In [ ]:
index_list = list(data[data['establishment']=='[]'].index)
data.drop(index_list, inplace = True)

In [ ]:
data.establishment.value_counts()

In [ ]:
data.establishment = data.establishment.apply(lambda x:x[2:-2])

In [ ]:
data.head()

In [ ]:
data.city.value_counts()

#### The city with maximum Restaurat savailble is Chennai with a count of 11406. The city with less restaurants are Nayagaon with 17 restaurants.