# 使用线性相关和逻辑回归来判断是否推荐该服装

In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
data = pd.read_csv("../input/Womens Clothing E-Commerce Reviews.csv")
data.shape

(23486, 11)

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
Unnamed: 0                 23486 non-null int64
Clothing ID                23486 non-null int64
Age                        23486 non-null int64
Title                      19676 non-null object
Review Text                22641 non-null object
Rating                     23486 non-null int64
Recommended IND            23486 non-null int64
Positive Feedback Count    23486 non-null int64
Division Name              23472 non-null object
Department Name            23472 non-null object
Class Name                 23472 non-null object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB

In [4]:
data.head()

   Unnamed: 0  Clothing ID    ...      Department Name Class Name
0           0          767    ...             Intimate  Intimates
1           1         1080    ...              Dresses    Dresses
2           2         1077    ...              Dresses    Dresses
3           3         1049    ...              Bottoms      Pants
4           4          847    ...                 Tops    Blouses

[5 rows x 11 columns]

In [5]:
#将title，text填充为空，len（）=0
data['Title']=data['Title'].fillna('')
data['Review Text']=data['Review Text'].fillna('')

In [6]:
data.head()

   Unnamed: 0  Clothing ID    ...      Department Name Class Name
0           0          767    ...             Intimate  Intimates
1           1         1080    ...              Dresses    Dresses
2           2         1077    ...              Dresses    Dresses
3           3         1049    ...              Bottoms      Pants
4           4          847    ...                 Tops    Blouses

[5 rows x 11 columns]

In [7]:
#因确实数据较少，将其替换为各类中最多的数据
data['Division Name']=data['Division Name'].fillna('General')
data['Department Name']=data['Department Name'].fillna('Tops')
data['Class Name']=data['Class Name'].fillna('Dresses')
data.head()

   Unnamed: 0  Clothing ID    ...      Department Name Class Name
0           0          767    ...             Intimate  Intimates
1           1         1080    ...              Dresses    Dresses
2           2         1077    ...              Dresses    Dresses
3           3         1049    ...              Bottoms      Pants
4           4          847    ...                 Tops    Blouses

[5 rows x 11 columns]

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
Unnamed: 0                 23486 non-null int64
Clothing ID                23486 non-null int64
Age                        23486 non-null int64
Title                      23486 non-null object
Review Text                23486 non-null object
Rating                     23486 non-null int64
Recommended IND            23486 non-null int64
Positive Feedback Count    23486 non-null int64
Division Name              23486 non-null object
Department Name            23486 non-null object
Class Name                 23486 non-null object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB

In [9]:
def get_lenth(x):
    if type(x)==str:
        
        return math.ceil(len(x)/10)
#get_lenth('qweddff df')

In [10]:
# title_df=pd.DataFrame()
# title_df=data['Title'].map(get_lenth)
# title_df.head()

In [11]:
data['Title']=data['Title'].map(get_lenth)
data['Title']

0        0
1        0
2        3
3        2
4        2
5        3
6        2
7        4
8        1
9        2
10       5
11       0
12       1
13       1
14       4
15       3
16       5
17       3
18       2
19       3
20       2
21       1
22       3
23       3
24       1
25       1
26       2
27       2
28       2
29       2
        ..
23456    4
23457    1
23458    0
23459    2
23460    2
23461    5
23462    1
23463    2
23464    2
23465    2
23466    2
23467    2
23468    2
23469    2
23470    0
23471    2
23472    2
23473    2
23474    3
23475    1
23476    1
23477    1
23478    2
23479    2
23480    0
23481    3
23482    3
23483    3
23484    5
23485    4
Name: Title, Length: 23486, dtype: int64

In [12]:
def get_text(x):
    if type(x)==str:
        return math.ceil(len(x)/50)

In [13]:
data['Review Text']=data['Review Text'].map(get_text)
data['Review Text']

0         2
1         7
2        10
3         3
4         4
5        10
6        10
7        10
8         4
9         8
10        7
11        2
12       11
13        8
14       10
15       10
16        8
17        6
18        4
19        6
20        6
21       10
22        9
23        5
24        9
25        7
26       10
27        5
28        4
29        9
         ..
23456     8
23457     4
23458     3
23459     5
23460    10
23461     8
23462     4
23463     8
23464     5
23465     5
23466     6
23467    10
23468    10
23469     7
23470     0
23471     3
23472     7
23473    10
23474    10
23475     4
23476     3
23477    10
23478     5
23479    10
23480     0
23481     3
23482     5
23483     5
23484     9
23485     3
Name: Review Text, Length: 23486, dtype: int64

In [14]:
DN_Df = pd.DataFrame()
DN_Df = pd.get_dummies(data['Division Name'] , prefix='DN' )
DN_Df.head()

   DN_General  DN_General Petite  DN_Initmates
0           0                  0             1
1           1                  0             0
2           1                  0             0
3           0                  1             0
4           1                  0             0

In [15]:
data = pd.concat([data,DN_Df],axis=1)
data.drop('Division Name',axis=1,inplace=True)
data.head()

   Unnamed: 0  Clothing ID      ...       DN_General Petite  DN_Initmates
0           0          767      ...                       0             1
1           1         1080      ...                       0             0
2           2         1077      ...                       0             0
3           3         1049      ...                       1             0
4           4          847      ...                       0             0

[5 rows x 13 columns]

In [16]:
Dep_Df = pd.DataFrame()
Dep_Df = pd.get_dummies(data['Department Name'] , prefix='Dep' )
DN_Df.head()

   DN_General  DN_General Petite  DN_Initmates
0           0                  0             1
1           1                  0             0
2           1                  0             0
3           0                  1             0
4           1                  0             0

In [17]:
data = pd.concat([data,Dep_Df],axis=1)
data.drop('Department Name',axis=1,inplace=True)
data.head()

   Unnamed: 0  Clothing ID  Age    ...      Dep_Jackets  Dep_Tops  Dep_Trend
0           0          767   33    ...                0         0          0
1           1         1080   34    ...                0         0          0
2           2         1077   60    ...                0         0          0
3           3         1049   50    ...                0         0          0
4           4          847   47    ...                0         1          0

[5 rows x 18 columns]

In [18]:
CN_Df = pd.DataFrame()
CN_Df = pd.get_dummies(data['Class Name'] , prefix='CN' )
CN_Df.head()

   CN_Blouses  CN_Casual bottoms    ...     CN_Swim  CN_Trend
0           0                  0    ...           0         0
1           0                  0    ...           0         0
2           0                  0    ...           0         0
3           0                  0    ...           0         0
4           1                  0    ...           0         0

[5 rows x 20 columns]

In [19]:
data = pd.concat([data,CN_Df],axis=1)
data.drop('Class Name',axis=1,inplace=True)
data.head()

   Unnamed: 0  Clothing ID  Age    ...     CN_Sweaters  CN_Swim  CN_Trend
0           0          767   33    ...               0        0         0
1           1         1080   34    ...               0        0         0
2           2         1077   60    ...               0        0         0
3           3         1049   50    ...               0        0         0
4           4          847   47    ...               0        0         0

[5 rows x 37 columns]

In [20]:
data.shape

(23486, 37)

In [21]:
#相关性矩阵
corrDf = data.corr() 
corrDf

                         Unnamed: 0  Clothing ID    ...      CN_Swim  CN_Trend
Unnamed: 0                 1.000000    -0.006072    ...     0.021585 -0.013001
Clothing ID               -0.006072     1.000000    ...    -0.304220 -0.010921
Age                       -0.007749     0.017972    ...    -0.051585  0.005000
Title                      0.007327     0.032894    ...     0.021288  0.010564
Review Text                0.009608     0.095459    ...     0.007060  0.023571
Rating                    -0.002568    -0.018879    ...     0.000123 -0.024489
Recommended IND           -0.003887    -0.016206    ...    -0.005357 -0.015472
Positive Feedback Count   -0.002907     0.046356    ...    -0.008479  0.010435
DN_General                -0.006665     0.194137    ...    -0.147639  0.031404
DN_General Petite          0.000985     0.136970    ...    -0.089410 -0.022876
DN_Initmates               0.011483    -0.656462    ...     0.470553 -0.018653
Dep_Bottoms                0.012386     0.126384    ...    -0.054030 -0.031349
Dep_Dresses                0.010343     0.505385    ...    -0.074622 -0.043296
Dep_Intimate               0.015766    -0.701850    ...     0.435492 -0.020155
Dep_Jackets               -0.000967     0.106044    ...    -0.026368 -0.015299
Dep_Tops                  -0.024441    -0.217337    ...    -0.110427 -0.064070
Dep_Trend                 -0.013001    -0.010921    ...    -0.008777  1.000000
CN_Blouses                -0.014415    -0.165042    ...    -0.047936 -0.027813
CN_Casual bottoms         -0.004407    -0.039430    ...    -0.001135 -0.000659
CN_Chemises                0.001624    -0.029149    ...    -0.000803 -0.000466
CN_Dresses                 0.011509     0.500956    ...    -0.074735 -0.043362
CN_Fine gauge             -0.010659    -0.018245    ...    -0.027265 -0.015819
CN_Intimates              -0.012696    -0.212843    ...    -0.009993 -0.005798
CN_Jackets                -0.021323     0.049378    ...    -0.021621 -0.012545
CN_Jeans                   0.004141     0.123073    ...    -0.027870 -0.016170
CN_Knits                  -0.008076    -0.127088    ...    -0.062689 -0.036372
CN_Layering                0.031793    -0.190217    ...    -0.009728 -0.005644
CN_Legwear                 0.022098    -0.290121    ...    -0.010346 -0.006003
CN_Lounge                  0.001595    -0.362887    ...    -0.021415 -0.012425
CN_Outerwear               0.029296     0.113468    ...    -0.014638 -0.008493
CN_Pants                   0.002367     0.148849    ...    -0.030825 -0.017885
CN_Shorts                  0.020665    -0.278286    ...    -0.014387 -0.008347
CN_Skirts                  0.003900     0.088482    ...    -0.025184 -0.014612
CN_Sleep                  -0.021331    -0.294192    ...    -0.012178 -0.007066
CN_Sweaters               -0.009516     0.020430    ...    -0.031295 -0.018157
CN_Swim                    0.021585    -0.304220    ...     1.000000 -0.008777
CN_Trend                  -0.013001    -0.010921    ...    -0.008777  1.000000

[37 rows x 37 columns]

In [22]:
corrDf['Recommended IND'].sort_values(ascending =False)

Recommended IND            1.000000
Rating                     0.792336
CN_Jeans                   0.035019
Dep_Bottoms                0.033232
Age                        0.030622
Dep_Intimate               0.020529
DN_Initmates               0.020404
CN_Lounge                  0.016974
CN_Layering                0.012664
CN_Skirts                  0.012397
CN_Jackets                 0.010490
CN_Fine gauge              0.008648
CN_Sleep                   0.008523
CN_Legwear                 0.008416
Dep_Jackets                0.007784
CN_Intimates               0.007393
DN_General Petite          0.006891
CN_Pants                   0.006879
CN_Shorts                  0.005128
CN_Casual bottoms          0.004289
CN_Chemises                0.003033
CN_Outerwear              -0.001647
Unnamed: 0                -0.003887
CN_Swim                   -0.005357
CN_Knits                  -0.006251
CN_Blouses                -0.012464
CN_Sweaters               -0.014607
Dep_Trend                 -0.015472
CN_Trend                  -0.015472
Clothing ID               -0.016206
Dep_Tops                  -0.016360
DN_General                -0.016815
CN_Dresses                -0.021845
Dep_Dresses               -0.022485
Review Text               -0.048461
Title                     -0.056166
Positive Feedback Count   -0.069045
Name: Recommended IND, dtype: float64

In [23]:
full_X = pd.concat([data['Rating']],axis=1)
full_X.head()

   Rating
0       4
1       5
2       3
3       5
4       5

In [24]:
source_X=data.loc[:,'Rating']

source_y=data.loc[:,'Recommended IND']
source_X,source_y

(0        4
 1        5
 2        3
 3        5
 4        5
 5        2
 6        5
 7        4
 8        5
 9        5
 10       3
 11       5
 12       5
 13       5
 14       3
 15       4
 16       3
 17       5
 18       5
 19       5
 20       4
 21       4
 22       2
 23       3
 24       5
 25       3
 26       2
 27       4
 28       5
 29       5
         ..
 23456    5
 23457    5
 23458    5
 23459    4
 23460    3
 23461    4
 23462    3
 23463    4
 23464    5
 23465    5
 23466    4
 23467    5
 23468    5
 23469    4
 23470    5
 23471    4
 23472    5
 23473    5
 23474    5
 23475    3
 23476    4
 23477    4
 23478    1
 23479    5
 23480    5
 23481    5
 23482    3
 23483    3
 23484    3
 23485    5
 Name: Rating, Length: 23486, dtype: int64, 0        1
 1        1
 2        0
 3        1
 4        1
 5        0
 6        1
 7        1
 8        1
 9        1
 10       0
 11       1
 12       1
 13       1
 14       1
 15       1
 16       1
 17       1
 18       1
 19       1
 20       1
 21       1
 22       0
 23       1
 24       1
 25       0
 26       0
 27       1
 28       1
 29       1
         ..
 23456    1
 23457    1
 23458    1
 23459    1
 23460    0
 23461    1
 23462    1
 23463    1
 23464    1
 23465    1
 23466    1
 23467    1
 23468    1
 23469    1
 23470    1
 23471    1
 23472    1
 23473    1
 23474    1
 23475    1
 23476    1
 23477    1
 23478    0
 23479    1
 23480    1
 23481    1
 23482    1
 23483    0
 23484    1
 23485    1
 Name: Recommended IND, Length: 23486, dtype: int64)

In [25]:
from sklearn.model_selection import train_test_split 

#建立模型用的训练数据集和测试数据集
train_X, test_X, train_y, test_y = train_test_split(source_X ,
                                                    source_y,
                                                    train_size=.8)

#输出数据集大小
print ('原始数据集特征：',source_X.shape, 
       '训练数据集特征：',train_X.shape ,
      '测试数据集特征：',test_X.shape)

print ('原始数据集标签：',source_y.shape, 
       '训练数据集标签：',train_y.shape ,
      '测试数据集标签：',test_y.shape)

原始数据集特征： (23486,) 训练数据集特征： (18788,) 测试数据集特征： (4698,)
原始数据集标签： (23486,) 训练数据集标签： (18788,) 测试数据集标签： (4698,)

/opt/conda/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [26]:
train_X=train_X.values.reshape(-1,1)
train_y=train_y.values.reshape(-1,1)
train_X,train_y

(array([[3],
        [5],
        [5],
        ...,
        [5],
        [2],
        [4]]), array([[0],
        [1],
        [1],
        ...,
        [1],
        [0],
        [1]]))

In [27]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(train_X,train_y)

/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/opt/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [28]:
test_X=test_X.values.reshape(-1,1)
test_y=test_y.values.reshape(-1,1)
test_X,test_y

(array([[4],
        [5],
        [5],
        ...,
        [5],
        [5],
        [5]]), array([[1],
        [1],
        [1],
        ...,
        [1],
        [1],
        [1]]))

In [29]:
model.score(test_X,test_y)

0.9357173265219242