# 대한민국 자살률 분석
대한민국 자살률이 헝가리와 1위를 두고 경쟁중이라는 기사가 떠올라 대한민국을 집중적으로 살펴보았습니다.  
본 노트북은 비슷한 사례인 헝가리의 자살률을 다룬 저널을 참고했습니다.  
[[헝가리에서의 자살-역학적 및 임상적 관점]-Zoltan Rihmer, Xenia Gonda, Balazs Kapitany, Peter Dome]((https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3698008/)

In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly as py

import plotly.graph_objs as go
import cufflinks as cf

In [5]:
py.offline.init_notebook_mode(connected=True)
pd.set_option('float_format', '{:.4f}'.format)

cf.set_config_file(offline=True, world_readable=True, theme='ggplot')

In [6]:
data = pd.read_csv('../input/master.csv')

In [15]:
data.head()

   country  year       ...        gdp_per_capita ($)       generation
0  Albania  1987       ...                       796     Generation X
1  Albania  1987       ...                       796           Silent
2  Albania  1987       ...                       796     Generation X
3  Albania  1987       ...                       796  G.I. Generation
4  Albania  1987       ...                       796          Boomers

[5 rows x 12 columns]

In [8]:
south_korea = data[data.country == 'Republic of Korea']

## 1985-2015 대한민국 자살률
### 성별에 따른 자살률

In [68]:
year = south_korea.groupby('year').sum().index.tolist()

In [69]:
f = go.Scatter(
    x = year,
    y = south_korea[south_korea.sex == 'female'].groupby('year').sum()['suicides/100k pop'],
    mode = 'lines+markers',
    name = 'female'
)
m = go.Scatter(
    x = year,
    y = south_korea[south_korea.sex == 'male'].groupby('year').sum()['suicides/100k pop'],
    mode = 'lines+markers',
    name = 'male'
)
t = go.Scatter(
    x = year,
    y = south_korea.groupby('year').sum()['suicides/100k pop'],
    mode = 'lines+markers',
    name = 'total'
)
data = [f, m, t]

py.offline.iplot(data)

### 사망원인