1- Load the Titanic Dataset in Kaggle notebook from given link below:
 https://www.kaggle.com/hesh97/titanicdataset-traincsv
Use the bar plot to show following plots:
 Plot the Number of people survived and did not survive. Hint: Plot the counts values of
“Survived” column of dataset.
 Also plot survived comparison by class and by gender
 Use the “groupby” function of Pandas to group the mean values (of all features) of
passengers’’ gender and class.

In [ ]:
import pandas as pd #impport pandas lin=brary as pd
import seaborn as sns #import seaborn library as sns to mini plot diffrent colums with FaceGrtid
import numpy as np
data=pd.read_csv('../input/titanicdataset-traincsv/train.csv')# importing file kaggle file

In [ ]:
data

Plot the Number of people survived and did not survive. Hint: Plot the counts values of “Survived” column of dataset

In [ ]:
total = len(data.Survived)# total lenght of colum servived
ones=data['Survived'].sum() #sum for colum servived as it gives number of people servived as servived =1,unservived=0
zeros=total-ones #finding number remaing which will be unservived
print('servived',ones,'unsurvived',zeros)

In [ ]:
import matplotlib.pyplot as plt #import matplot lib for plots
y=[zeros,ones] #y give us total value number
x=["unsurvived","unsurvvied"]
plt.bar(x,y) #ploting the bars

In [ ]:
g = sns.FacetGrid(data, col='Survived')#using facegrid we will do mini plot of colum survived
g.map(plt.hist, 'Pclass', bins=20) #ploting the Pclass in term of Servived

In [ ]:
g = sns.FacetGrid(data, col='Survived') #ploting Sex in term of Servived
g.map(plt.hist, 'Sex', bins=20)

In [ ]:
data.groupby('Survived').mean() #mean of all values in term of Survived using group by

Explore how to add and delete column from a data frame, explain and illustrate with an
example. Also define concept of axis in pandas.

*

In [ ]:
set={'rolnumber':[101,102,103,104,105,106] ,'English':[23,65,76,23,23,43],"Math":[76,46,54,34,23,32]}
set=pd.DataFrame(set)#creating data frames

In [ ]:
set#getting output

In [ ]:
set['total']=set['English']+set['Math']#adding coloum totol to data frame

In [ ]:
set.drop(['total'],axis=1)#deleting the coloums

Generate a random data frame of 20 rows and 04 columns and change their columns names.

In [ ]:
ran=pd.DataFrame(np.random.rand(20,4)) #genrating  data frame of random numbers

In [ ]:
ran#displaying the data

In [ ]:
ran.columns=['a','b','c','d'] #changing colums names

In [ ]:
ran

Apply logical conditions to print values greater than 0.5 in any one column.

In [ ]:

ran['a']>0.5 #printing values greater than 0.5

Explore sort function in Pandas, apply ascending and descending sorting according.

In [ ]:

#Ascending Sort
set.sort_values

# Loc and iloc are two functions of pandas for accessing the data from the dataframe. Define the difference between them

* loc get rows wirh particular labels from the index
* iloc get rowa with particular positions in index
* if label is present ix behave like iloc otherwise it behave like loc