# Student Alcohol Consumption

### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd
import numpy as np

### Step 2. Import the datasets *student-mat* and *student-por* and merge them.

In [ ]:
ms = pd.read_csv("../input/alc-consumption-and-higher-education/student-mat.csv")
ps =pd.read_csv("../input/alc-consumption-and-higher-education/student-por.csv")
df = pd.concat([ms,ps]).reset_index(drop=True)

### Step 3. Assign it to a variable called df.

In [ ]:
df.info()

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [ ]:
df = df.loc[:,:"guardian"]
df.head()

### Step 5. Create a lambda function that capitalize strings.

In [ ]:
def Capital():
    return lambda x: x.capitalize()

### Step 6. Capitalize both Mjob and Fjob

In [ ]:
df.Mjob = df.Mjob.apply(Capital())
df.Fjob = df.Fjob.apply(Capital())
df.head()

### Step 7. Print the last elements of the data set.

In [ ]:
df.tail(1)

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and captalize Mjob and Fjob.

In [ ]:
# Already done in Question 6

### Step 9. Create a function called majority that return a boolean value to a new column called legal_drinker

In [ ]:
def majority(x):
    if x == 1:
        return True
    else:
        return False
df["legal_drinker"] = [majority(1) if x>=18 else majority(0) for x in df["age"]]

In [ ]:
df.head()

### Step 10. Multiply every number of the dataset by 10.

In [ ]:
temp = df.apply(lambda x: x*10 if x.name in ['Medu', 'Fedu'] else x)

In [ ]:
temp