**Dictionary**

A dictionary consists of keys and values

my_dict = {
   "key1":"value1",
   "key2":"value2",
}

In [ ]:
# Definition of dictionary
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# Print out the keys in europe
print(europe.keys())

# Print out value that belongs to key 'norway'
print(europe['norway'])

# Add italy to europe
europe['italy'] = 'rome'

# Remove australia
del(europe['spain'])

print(europe)

Dictionaries of dictionaries

In [ ]:
# Dictionary of dictionaries
europe = { 'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } }


# Print out the capital of France
print(europe['france']['capital'])

# Create sub-dictionary data
data = {'capital':'rome', 'population': 59.83}

# Add data to europe under key 'italy'
europe['italy'] = data

# Print europe
print(europe)

**Pandas **

Pandas is an open source library which provides data structures and data analysis tools for Python. The DataFrame is one of Pandas' most important data structures. It's basically a way to store data where you can label the rows and the columns. One way to build a DataFrame is from a dictionary.

In [ ]:
# Pre-defined lists
names = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
dr =  [True, False, False, False, True, True, True]
cpc = [809, 731, 588, 18, 200, 70, 45]

# Import pandas as pd
import pandas as pd

# Create dictionary my_dict with three key:value pairs: my_dict
my_dict = {'country':names, 'drives_right':dr, 'cars_per_cap':cpc}

# Build a DataFrame cars from my_dict: cars
cars = pd.DataFrame(my_dict)

# Print cars
print(cars)

# Definition of row_labels
row_labels = ['US', 'AUS', 'JAP', 'IN', 'RU', 'MOR', 'EG']

# Specify row labels of cars
cars.index = row_labels

# Print cars again
print(cars)

Putting data in a dictionary and then building a DataFrame works, but it's not very efficient. What if you're dealing with millions of observations? In those cases, the data is typically available as files with a regular structure. One of those file types is the CSV file, which is short for "comma-separated values".

To import CSV data into Python as a Pandas DataFrame you can use read_csv().

In [ ]:
#import pandas as pd
import pandas as pd

#import the train.csv data: titanic
titanic = pd.read_csv('../input/train.csv', index_col = 0)

#print out titanic
print(titanic)

**Data selection**

(1) Square Brackets

In [ ]:
import pandas as pd
titanic = pd.read_csv('../input/train.csv', index_col=0)

# Print out Name column as Pandas series
print(titanic['Name'])

# Print out DataFrame with Name and Sex columns
print(titanic[['Name', 'Sex']])

# Print out first 2 observations
print(titanic[0:2])

(2) loc and iloc

loc is label-based, which means that you have to specify rows and columns based on their row and column labels. iloc is integer index based, so you have to specify rows and columns by their integer index.

In [ ]:
import pandas as pd
titanic = pd.read_csv('../input/train.csv', index_col = 0)

#Print out passengerID 2's every information
print(titanic.iloc[1])
print(titanic.loc[[2],:])

# Print out passengerID 3's Age
print(titanic.loc[3, 'Age'])
print(titanic.loc[[3],['Age']])

# Print out passengerID 1 and 2's Name, Sex, and Age
print(titanic.loc[[1,2],['Name','Sex','Age']])

**Comparision Operators**
: <, >, <=, >=, ==, !=



**Boolean Operators**
: and, or, not

To use Boolean Operators with Numpy, you will need 
np.logical_and(), np.logical_or() and np.logical_not().

In [ ]:
# Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

# my_house greater than 18.5 or smaller than 10
print(np.logical_or(my_house>18.5,my_house<10 ))

# Both my_house and your_house smaller than 11
print(np.logical_and(my_house<11, your_house<11))

**Comparison Operators**
: if, elif, else

if condition:
    expression
 elif condition:
     expression
 else : 
     expression

In [ ]:
# Define variables
room = "bed"
area = 14.0

# if-elif-else construct for room
if room == "kit" :
    print("looking around in the kitchen.")
elif room == "bed":
    print("looking around in the bedroom.")
else :
    print("looking around elsewhere.")

# if-elif-else construct for area
if area > 15 :
    print("big place!")
elif area > 10:
    print("medium size, nice!")
else :
    print("pretty small.")

**Filtering Pandas Data Frame
**

Goal: select passengers with age under 30

In [ ]:
# Import cars data
import pandas as pd
titanic = pd.read_csv('../input/train.csv', index_col = 0)

# select the age column
age = titanic.loc[:,'Age']

# Do comparison on age column
youth = age<30

# Use result to select passengers
print(titanic[age<30]) # print(titanic[youth]) would work the same

**While loop**


While loop = repeated if statement



while conditon:
    expression

In [ ]:
# Initialize offset
offset = 8

# Code the while loop
while offset !=0 :
    print("correcting...")
    offset = offset - 1
    print(offset)

**for loop**

for var in seq : 
    expression
for each var in seq, execute expression

In [ ]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Code the for loop
for a in areas :
    print(a)

In [ ]:
# house list of lists
house = [["hallway", 11.25], 
         ["kitchen", 18.0], 
         ["living room", 20.0], 
         ["bedroom", 10.75], 
         ["bathroom", 9.50]]
         
# Build a for loop from scratch
for h in house :
    print("the " + h[0] + " is "+ str(h[1]) + " sqm")

**Indexes and values**

Using a for loop to iterate over a list only gives you access to every list element in each run, one after the other. If you also want to access the index information, so where the list element you're iterating over is located, you can use enumerate().

In [ ]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Change for loop to use enumerate()
for index, a in enumerate(areas) :
    print("room " + str(index) + ": " + str(a))

**Looping Data Structures**

Dictionary

for key, val in my_dict.items() :

In [ ]:
# Definition of dictionary
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn', 
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw', 'australia':'vienna' }
          
# Iterate over europe
for x, y in europe.items() :
    print("the capital of " + x + " is " + y)

Numpy array

1D Numpy array

for x in my_array : 

2D Numpy array

for val in np.nditer(my_array) :

In [ ]:
# Import numpy as np
import numpy as np
np_height = [65, 75,65,78,98]
np_student = [[65,78],
              [75,63],
              [65,77],
              [78,86],
              [98,95]]

# For loop over np_height
for height in np_height: 
    print(str(height) + " inches")

# For loop over np_student
for all in np.nditer(np_student): 
    print(all)