# MEI Introduction to Data Science
# Lesson 4 - Activity 2

This activity uses Python code create times series plots. The activity uses the data from the MEI large data set 2 which gives information about different boroughs of London and regions of England. 

The basic `plot()` command in pandas can be used to create a time series graph.

## Problem: 
> *Have the changes in life expectancy since 1991 been similar for different regions of England and different boroughs of London?*

To answer this question you could explore time series graphs for life expectancy for different regions/boroughs.

## Getting the data

In [ ]:
# import pandas
import pandas as pd

# import matplotlib
import matplotlib.pyplot as plt

#import the data and check by viewing the top rows
male_le_data = pd.read_csv('../input/meilds2/male-life-expectancy.csv')
male_le_data.head()

You can check the data types and get the field names by running the code in the box below.

In [ ]:
male_le_data.dtypes

## Exploring the data
The `describe` command can be used on some of the columns to get a sense of the values in the dataset. 
* Run the code below to explore the data for the *North East* region
* Change and run the code to explore the data for other regions

In [ ]:
male_le_data['North East'].describe()

## Analysing the data
The basic `plot()` command for a data set can be used to create a time series. In the example below the *Years* field is used for the x-axis and the different regions are plotted by listing them for the parameter y.
* Run the code in the box below to plot the time series

In [ ]:
# create a plot with Years on the x axis and the regions on the y axis 
male_le_data.plot(x='Years',y=['North East',
                               'North West',
                               'Yorkshire and The Humber', 
                               'East Midlands','West Midlands',
                               'East of England',
                               'London',
                               'South East',
                               'South West' ],
                  figsize=(10, 10))
plt.show()

The above plot starts at about 72 on the y-axis, Is this misleading?

* Change the values in the `yticks` the parameter below so that it shows 0 on the y-axis.
* Is a plot with 0 on the y-axis preferable?

In [ ]:
# create a plot with Years on the x axis and the regions on the y axis 
male_le_data.plot(x='Years',y=['North East',
                               'North West',
                               'Yorkshire and The Humber', 
                               'East Midlands','West Midlands',
                               'East of England',
                               'London',
                               'South East',
                               'South West' ],
                  figsize=(10, 10), yticks=(70,72,74,76,78,80))
plt.show()

The fields to be plotted can be listed in the y parameter.
* Edit and run the code below so that it plots the times series for male life expectancy for Bexley, Camden, Croydon, Haringey and Islington

In [ ]:
# create a plot with Years on the x axis and the regions on the y axis 
male_le_data.plot(x='Years',y=['North East',
                               'North West',
                               'Yorkshire and The Humber', 
                               'East Midlands','West Midlands',
                               'East of England',
                               'London',
                               'South East',
                               'South West' ],
                  figsize=(10, 10))
plt.show()

* Edit and run the code in the boxes below so that it imports the data for female life expectancy and plots the times series for female life expectancy for Bexley, Camden, Croydon, Haringey and Islington

In [ ]:
#import the data and check by viewing the top rows
male_le_data = pd.read_csv('../input/meilds2/male-life-expectancy.csv')
male_le_data.head()

In [ ]:
# create a plot with Years on the x axis and the regions on the y axis 
male_le_data.plot(x='Years',y=['North East',
                               'North West',
                               'Yorkshire and The Humber', 
                               'East Midlands','West Midlands',
                               'East of England',
                               'London',
                               'South East',
                               'South West' ],
                  figsize=(10, 10))
plt.show()

## Communicating the results
Use the charts above to answer the initial problem: 
> *Have the changes in life expectancy since 1991 been similar for different regions of England and different boroughs of London?*

**Checkpoint**
> * Have the changes in life expectancy since 1991 been similar for different regions of England?
> * Which of the five London boroughs listed (Bexley, Camden, Croydon, Haringey and Islington) demonstrated the biggest change in life expectancy?
> * Was the change in life expectancy in these boroughs similar for males and females?