# Multvariate Analysis - Exercise Questions

The following notebook is created with empty questions for learners to perform multivariate tasks using the titanic dataset. Answers will be provided upon request in comments. Please upvote, follow and comment if you find my notebooks helpful.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data_df = pd.read_csv('../input/titanic/titanic1.csv')

In [ ]:
data_df.head()

In [ ]:
data_df.shape

In [ ]:
data_df.dtypes

#### 1) Change/Replace the values of Survived Column from 1 and 0 to 'Survived' and 'Not Survived' 
#### (Like we did in univariate_analysis Assignment)

#### 2) Apply Pandas' crosstab on both the categorical variables 'Survived' and 'Pclass' and store the result in a dataframe for further processing (Refer Multivariate analysis discussed in class)

#### 3)Plot a bar chart from the above formed crosstab dataframe. (You may use iloc to fetch data from crosstab dataframe)(HINT: Refer Multivariate analysis discussed in class)

#### 4) Plot a scatter plot between Age and Fare (HINT: Refer multivariate 'Continous vs Continous' Variables)

#### 5) Plot a boxplot between 'Survived' and 'Age' Columns

#### 6) Plot a boxplot between 'Survived' and 'Fare' Columns

#### 7) Filter the dataframe to remove the values of 'Fare' which are greater than 300

#### 8) Plot a box plot of the dataframe above namely "fare_filter_df" and choose 'Fare' and 'Survived' for plotting a boxplot