In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # visualization with graphics
import seaborn as sns # visualization
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

In [ ]:
data = pd.read_csv("../input/vgsales.csv")

In [ ]:
data.info()

In [ ]:
data.head()

In [ ]:
data.tail()

In [ ]:
data.columns

****DATA CLEANING****

**isna() function used to find missing value and that counts by sum() function.**

In [ ]:
data.isna().sum() #Found missing values in datasets and that count by sum() function.

In [ ]:
data.dropna(inplace=True,axis=0) #inplace -> Bool value. Default False. 
                                 #If True, do operation inplace and return None.
                                 #axis=0 drop rows which contain missing values. 
                                 #axis=1 drop columns which contain missing values.

In [ ]:
data.isna().sum()

In [ ]:
data.info()

**Let's do Correlation map!**

In [ ]:
size=[15,15]
plt.figure(figsize=size)
plt.title('Correlation Map')
sns.heatmap(data.corr(),annot=True,linewidths=.5,fmt='.2f',linecolor='black', cmap='Blues')
plt.show()

**Let's use 'Bar plot' to graphics global sales by genre.**

In [ ]:
plt.figure(figsize=(15,15))
plt.bar(data.Genre,data.Global_Sales,alpha=0.1)
plt.title('Bar Plot')
plt.xlabel("Genres")
plt.ylabel("Global Sales")
plt.show()

**Let's use 'Scatter plot' to graphics global sales by year.**

In [ ]:
plt.figure(figsize=(10,5))
plt.scatter(data.Global_Sales,data.Year,color="r",alpha=0.1)
plt.title('Scatter Plot')
plt.xlabel("Global Sales")
plt.ylabel("Years")
plt.show()

**Concatenate pandas objects with concat() functions. **

In [ ]:
# axis=0 --> for line
# axis=1 --> for column 
dataGenre1=data.groupby("Genre")[['Global_Sales']].mean()
dataGenre2=data.groupby("Genre")[['NA_Sales']].mean()
dataGenre3=data.groupby("Genre")[['EU_Sales']].mean()
dataGenre4=data.groupby("Genre")[['JP_Sales']].mean()

dataGenre = pd.concat([dataGenre1,dataGenre2,dataGenre3,dataGenre4],axis=1)
dataGenre.info()

In [ ]:
dataGenre

**Add a new column. This column indicates that the sales status is successful or unsuccessful.**

In [ ]:
dataGenre['Sales_Status']=['Successful' if(i>0.5) else 'Unsuccessful' for i in dataGenre['Global_Sales']]
dataGenre

**How many games were produced for each platform?**

In [ ]:
dataPlatform=data.groupby("Platform")[['Platform']].count()
dataPlatform.rename(columns={'Platform':'Counted'})

In [ ]:
print(data['Genre'].value_counts(dropna=False)) #value_counts() -> Boolean, default True.
                                                #Don't include counts of NaN

In [ ]:
data.describe()

In [ ]:
data['Sales_Status']=['Successful' if(i>0.5) else 'Unsuccessful' for i in data['Global_Sales']]
data.head()

In [ ]:
data.boxplot(column='Year',by='Sales_Status')

In [ ]:
data.head()

**TIDY DATA**

In [ ]:
data_new = data.head()
data_new

In [ ]:
melted = pd.melt(frame= data_new, id_vars='Name', value_vars=['Genre','Publisher'])
melted

PIVOTING DATA (Reverse of melting)

In [ ]:
melted.pivot(index='Name', columns='variable',values='value')

**CONCATENATING DATA**

In [ ]:
data1 = data.head()
data2 = data.tail()
concat_data_row = pd.concat([data1,data2], axis=0, ignore_index=True)
concat_data_row

In [ ]:
data1=data['Genre'].head()
data2=data['Sales_Status'].head()
concat_data_column = pd.concat([data1,data2], axis=1, ignore_index=True)
concat_data_column

**DATA TYPES**

In [ ]:
data['Year'] = data['Year'].astype('int') #convert float to int

**MISSING DATA AND TESTING WÄ°TH ASSERT**

In [ ]:
data['Genre'].value_counts(dropna = False)

In [ ]:
#assert 1==1 # return nothing because it is true
#assert 1==2 # return error because it is false

In [ ]:
assert data['Genre'].notnull().all() #returns nothing because we drop missing values
assert data.columns[1] == 'Name'

**---> zip() Function**

In [ ]:
country = ['Greece', 'Italy']
city = ['Athen', 'Milano']
title = ['country', 'city']
list_col = [country,city]
zipped = list(zip(title, list_col))
data_dict = dict(zipped)
df = pd.DataFrame(data_dict)
df

In [ ]:
#broadcasting
df['income']=1000
df

**VISUAL EXPLORATORY DATA ANALYSIS**

In [ ]:
data.plot(kind='hist', y='Global_Sales', bins=50, range=(0,1), normed=True)
plt

In [ ]:
data.plot(kind='hist', y='Global_Sales', bins=50, range=(0,1), normed=True, cumulative=True) # cumulative=True -> 
plt

In [ ]:
data.head()

**INDEXING PANDAS TIME SERIES**

In [ ]:
import warnings
warnings.filterwarnings('ignore')

data_indexing = data.head()
date_list=['1997-01-02', '1997-05-12', '1997-09-23', '1997-10-12', '1997-12-27']
date_object = pd.to_datetime(date_list)
data_indexing['date']=date_object

data_indexing = data_indexing.set_index('date')
data_indexing

In [ ]:
print(data_indexing.loc['1997-01-02'])

In [ ]:
print(data_indexing.loc['1997-01-02':'1997-12-27'])

**RESAMPLING PANDAS TIME SERIES**

In [ ]:
data_indexing.head()

In [ ]:
data_indexing.resample("M").mean()

In [ ]:
data_indexing.resample("M").mean().interpolate("linear")