**Using basic data science tools on the dataset. Preparing the dataset to the machine learning or deep learning. So we have to fix the unclean datas to clean datas.**
**Unclean data contains followings: **
* upper-lowercase, whitespace between the words or letters
* missing datas like NaN values.
* different language or alphabets/characters

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

# Input data files are available in the "../input/" directory.

import os
print(os.listdir("../input"))

In [ ]:
data = pd.read_csv("../input/countries of the world.csv")

In [ ]:
data.info() # shows some information about the dataset.

data.columns # shows dataset columns/features

In [ ]:
data.head() # shows first 5 rows.

In [ ]:
data.tail() # shows last 5 rows.

In [ ]:
data.shape # shows # of samples and # of features/columns.

In [ ]:
print(data['Region'].value_counts(dropna=True)) #dropna defines don't include Not A Number(NaN) values.
#Here we ignore them.

* **count defines an amount of the specified data feature**
* **mean defines a mean of the specified data feature**
* **std defines a standard deviation of the specified data feature**
* **min defines a minimum value of the specified data feature**
* **25% defines a first quartile (Q1) of the specified data feature**
* **50% defines a second quartile (Q2) of the specified data feature**
* **75% defines a third quartile (Q3) of the specified data feature**
* **max defines a maximum value of the specified data feature**

In [ ]:
data.describe()

**.boxplot() plotting a box. The box shows Q3(upper border of the box), Q2(middle line of the box), Q1(lower border of the box), min value(bottom line), max value(top line)**

In [ ]:
data.boxplot(column = 'GDP ($ per capita)', figsize =(28,15), by = 'Region') # column is showed data feature.
# Datas received from by = '....'

**.melt() tidies unclean datas.**

In [ ]:
data_new = data.head()
data_new

**frame = source data frame, id_vars= no melted feature, value_vars= melted features**

In [ ]:
melted = pd.melt(frame = data_new, id_vars = 'Country', value_vars = ['Population', 'GDP ($ per capita)','Birthrate'])
melted

**Pivoting is reverse of the melting.**
* Index is assigned what we want to replace the index.
* columns like a keys in dictionary.
* values like a values in dictionary.

In [ ]:
melted.pivot(index = 'Country', columns = 'variable', values = 'value')

**Concatenating the two datas with pd.concat() method.**

In [ ]:
data1 = data.head()
data2 = data.tail()

data_conc_row = pd.concat([data1,data2], axis = 0, ignore_index = True) # axis = 0 concatenates dataframes in row.
data_conc_row

In [ ]:
data1 = data['Population'].head()
data2 = data['Birthrate'].head()

data_conc_column = pd.concat([data1,data2], axis = 1) # axis = 1 concatenates dataframes in column.
data_conc_column

In [ ]:
data.dtypes

In [ ]:
data['Country'] = data['Country'].astype('category') # Data type of the Country feature is changed object to category
data['Population'] = data['Population'].astype('float') # Data type of the Population feature is changed integer to float

In [ ]:
data.dtypes

In [ ]:
data['Country'] = data['Country'].astype('object') # Converted default type
data['Population'] = data['Population'].astype('int') # Converted default type

In [ ]:
data.dtypes

In [ ]:
data['Literacy (%)'].value_counts(dropna = False) # dropna = False shows frequency of NaN

In [ ]:
data1 = data
data1['Literacy (%)'].dropna(inplace = True)

In [ ]:
assert 1==1 # returns nothing because it's true

In [ ]:
assert data1['Literacy (%)'].notnull().all() # we drop NaN values, so it returns nothing

In [ ]:
data1['Literacy (%)'].fillna('empty', inplace = True)

In [ ]:
assert data1['Literacy (%)'].notnull().all() # we do not have NaN values,thus returns nothing

**My third homework is ready.**