In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/drug-classification/drug200.csv

In [1]:
%matplotlib notebook
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [3]:
data = pd.read_csv('/kaggle/input/drug-classification/drug200.csv')
data.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [4]:
data['Sex'] = data['Sex'].replace('F', 0)
data['Sex'] = data['Sex'].replace('M', 1)
data['BP'] = data['BP'].replace('LOW', 1)
data['BP'] = data['BP'].replace('NORMAL', 2)
data['BP'] = data['BP'].replace('HIGH', 3)
data['Cholesterol'] = data['Cholesterol'].replace('NORMAL', 0)
data['Cholesterol'] = data['Cholesterol'].replace('HIGH', 1)
data.head()

   Age  Sex  BP  Cholesterol  Na_to_K   Drug
0   23    0   3            1   25.355  DrugY
1   47    1   1            1   13.093  drugC
2   47    1   1            1   10.114  drugC
3   28    0   2            1    7.798  drugX
4   61    0   1            1   18.043  DrugY

In [5]:
X = data[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']]
y = data['Drug']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [6]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 5)

In [7]:
knn.fit(X_train, y_train)
knn.score(X_test, y_test)

0.72

In [8]:
new = knn.predict([[47, 1, 3, 1, 10.114]])
new

array(['drugA'], dtype=object)