****dataset:Telco Customer Churn,****
link:https://www.kaggle.com/blastchar/telco-customer-churn

In [ ]:
import numpy as np
import pandas as pd

**part1: preparatory exercises**

In [ ]:
#rename columns
df = pd.read_csv("../input/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv" )
df.head()

In [ ]:
ndf = df.rename(columns={"tenure":'months'})
ndf.head(5)

In [ ]:
#change casing
# Suppress trailing spaces
ndf["InternetService"].str.strip()

In [ ]:
#normalize data types
print(ndf)
ndf.dtypes

In [ ]:
#ndf['TotalCharges'].type: object  --- float
# 将TotalCharges列中的空值全部替换为nan
ndf['TotalCharges'] = ndf['TotalCharges'].replace(' ', np.nan)

# 将值转变为浮点型
ndf['TotalCharges'] = ndf['TotalCharges'].astype(float)
print(ndf['TotalCharges'])

****part2: Handle missing values ****

In [ ]:
#是否为空值
ndf.isnull()

In [ ]:
ndf.isna().sum()

In [ ]:
ndf.isnull().sum()

In [ ]:
#处理缺失数据：Get rid of (delete) the rows that have missing data
ndf.dropna(axis=1)

****part3:Parsing dates****