# DC Superheroes

**author - komal gupta**

# Aim :-
* there are many superheroes so we will find when did the first superhero appeared in this dataset. 
* When there was an increase in superheroes. 
* How much bad and good superheroes are present. 
* How many male and female superheroes are present

In [ ]:
# importing numpy be used as an efficient multi-dimensional container of generic data.
import numpy as np 

#importing pandas it allows you to perform data manipulation create, manipulate and wrangle the data in python.
import pandas as pd 

# Import Libraries for plotting 

#Matplotlib is a Python 2D plotting library
import matplotlib.pyplot as plt 

# Seaborn is high-level interface for drawing attractive and informative statistical graphics.
import seaborn as sns 

import plotly.offline as pyo
import plotly.graph_objs as go
import plotly.express as px

In [ ]:
df = pd.read_csv("../input/dcwikia-datacsv/dc-wikia-data.csv" , header = 0)
df.head()

In [ ]:
df.shape

In [ ]:
# dropping page_id column
df = df.drop('page_id',axis = 1)
df.head()

In [ ]:
# whether a dc character is a homosexual or bisexual
df['GSM'].value_counts()

In [ ]:
# replacing the blank spaces by straight characters in GSM
df = df.fillna(value = 'No value')
df = df.replace({'GSM' : {'No value': 'straight character'}})
df.head()

In [ ]:
# cleaning up the name column as it has both real name and superhero name 
df['superhero_name'] = df['name'].str.split('(').str[0]
df.head()

In [ ]:
df.head()

In [ ]:
df['Real_name'] = df['name'].str.split('(').str[1]
df.head()

In [ ]:
# replacing the value "new earth" with no value
df = df.replace({'Real_name':{'New Earth)':'No value'}})
df.head()

**now we have the superhero name and real name as both the different columns so we can drop the name column.**

In [ ]:
#dropping name column
df = df.drop('name',axis = 1)
df.head()

**as we can see in the first appearance column we have both the year and month so we need to seperate them**

In [ ]:
df['appearance_month'] = df['FIRST APPEARANCE'].str.split(',').str[1]
df.head()

In [ ]:
df['first_appearance_year'] = df['FIRST APPEARANCE'].str.split().str[0]
df.head()

In [ ]:
# dropping first appearance column
df = df.drop('FIRST APPEARANCE' , axis = 1)
df.head()

# exploratory analysis

In [ ]:
df['SEX'].value_counts()

In [ ]:
plt.subplots(figsize=(10,10))
sns.countplot(x='SEX',data = df)
plt.title('count of superheroes by gender',fontweight = 'bold',fontsize = 30)
plt.ylabel("number of superheroes",fontweight = 'bold')
plt.xlabel("align",fontweight='bold')
sns.set()

In [ ]:
df['ALIGN'].value_counts()

In [ ]:
plt.subplots(figsize=(10,10))
sns.countplot(x='ALIGN',data = df)
plt.title('superheroes alignment',fontweight = 'bold',fontsize = 30)
plt.ylabel("number of superheroes",fontweight = 'bold')
plt.xlabel("align",fontweight='bold')
sns.set()

* **there is a slightly more bad characters than good characters**

In [ ]:
plt.subplots(figsize=(10,10))
sns.countplot(x='ALIGN',hue = 'SEX',data = df)
sns.set()
plt.title('superheroes alignment by gender',fontweight = 'bold',fontsize = 30)
plt.ylabel("number of superheroes",fontweight = 'bold')
plt.xlabel("align",fontweight='bold')

In [ ]:
plt.subplots(figsize=(10,10))
sns.countplot(x='ALIGN',hue = 'ID',data = df)
sns.set()
plt.title('superheroes alignment by identity',fontweight = 'bold',fontsize = 30)
plt.ylabel("count",fontweight = 'bold')
plt.xlabel("align",fontweight='bold')
sns.set()

In [ ]:
plt.subplots(figsize=(10,10))
sns.countplot(x='ALIVE',hue = 'ALIGN',data = df)
sns.set()
plt.title('superheroes alignment by alive or not alive',fontweight = 'bold',fontsize = 30)
plt.ylabel("count",fontweight = 'bold')
plt.xlabel("align",fontweight='bold')
sns.set()

* **bad superheroes have higher rates of death**

In [ ]:
fig = px.histogram(df,x='YEAR')
fig.update_layout(height=800,title_text="count of superheroes appearance")
fig.show()

In [ ]:
df

# CONCLUSION
* **The first superhero appeared in the year 1935 and the latest was in 2013**
* **The increase of superheroes are in the year 2006 with count = 303**
* **Good superheroes = 2895 and bad superheroes = 2832**
* **male superheroes = 4783 and female superheroes = 1967**