In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
import pandas as pd
url='/kaggle/input/test-file/tested.csv'
dataframe=pd.read_csv(url)

dataframe.head(6)

In [ ]:
dataframe.shape

dataframe.describe()

In [ ]:
dataframe.iloc[0]

In [ ]:
dataframe.iloc[1:4]

In [ ]:
dataframe.iloc[:4]

In [ ]:
dataframe[dataframe['Sex'] == 'female'].head(2)

In [ ]:
dataframe[(dataframe['Sex'] == 'female') & (dataframe['Age'] >= 65)]

In [ ]:
dataframe['Sex'].replace("female", "Woman").head(3)

In [ ]:
dataframe['Sex'].replace(["female", "male"], ["Woman", "Man"]).head(5)

In [ ]:
dataframe.replace(1, "One").head(2)

In [ ]:
dataframe.replace(r"1st", "First", regex=True).head(2)

In [ ]:
dataframe.rename(columns={'Pclass':'Passenger Class'}).head(2)

In [ ]:
dataframe.rename(columns={'Pclass': 'Passenger Class', 'Sex': 'Gender'}).head(2)

In [ ]:
import collections
column_names = collections.defaultdict(str)

for name in dataframe.columns:    
    column_names[name]
    
column_names

In [ ]:
print('Maximum:', dataframe['Age'].max())
print('Minimum:', dataframe['Age'].min())
print('Mean:', dataframe['Age'].mean())
print('Sum:', dataframe['Age'].sum())
print('Count:', dataframe['Age'].count())

In [ ]:
dataframe.count()

In [ ]:
dataframe['Sex'].unique()

In [ ]:
dataframe['Sex'].value_counts()

In [ ]:
dataframe['Pclass'].value_counts()

In [ ]:
dataframe['Pclass'].nunique()

In [ ]:
dataframe[dataframe['Age'].isnull()].head(2)

In [ ]:
dataframe['Sex'] = dataframe['Sex'].replace('male', np.nan)

In [ ]:
dataframe = pd.read_csv(url, na_values=[np.nan, 'NONE', -999])

In [ ]:
dataframe.drop('Age', axis=1).head(2)

In [ ]:
dataframe.drop(['Age', 'Sex'], axis=1).head(2)

In [ ]:
dataframe.drop(dataframe.columns[1], axis=1).head(2)

In [ ]:
dataframe[dataframe['Sex'] != 'male'].head(2)

In [ ]:
dataframe[dataframe['Name'] != 'Allison, Miss Helen Loraine'].head(2)

In [ ]:
dataframe[dataframe.index != 0].head(2)

In [ ]:
dataframe.drop_duplicates().head(2)

In [ ]:
print("Number Of Rows In The Original DataFrame:", len(dataframe))
print("Number Of Rows After Deduping:", len(dataframe.drop_duplicates()))

In [ ]:
dataframe.drop_duplicates(subset=['Sex'])

In [ ]:
dataframe.drop_duplicates(subset=['Sex'], keep='last')

In [ ]:
dataframe.groupby('Sex').mean()

In [ ]:
dataframe.groupby('Sex')

In [ ]:
dataframe.groupby('Survived')['Name'].count()

In [ ]:
dataframe.groupby(['Sex','Survived'])['Age'].mean()

In [ ]:
import pandas as pd 
import numpy as np

time_index = pd.date_range('06/06/2017', periods=100000, freq='30S')
dataframe = pd.DataFrame(index=time_index)
dataframe['Sale_Amount'] = np.random.randint(1, 10, 100000)
dataframe.resample('W').sum()

In [ ]:
dataframe.head(3)

In [ ]:
dataframe.resample('2W').mean()

In [ ]:
dataframe.resample('2W').mean()

In [ ]:
dataframe.resample('M', label='left').count()

In [ ]:
dataframe = pd.read_csv(url)
for name in dataframe['Name'][0:2]:
    print(name.upper())

In [ ]:
def uppercase(x):
    return x.upper()

In [ ]:
dataframe = pd.read_csv(url)
dataframe['Name'].apply(uppercase)[0:2]

In [ ]:
dataframe.groupby('Sex').apply(lambda x: x.count())

In [ ]:
data_a = {'id': ['1', '2', '3'],
          'first': ['Alex', 'Amy', 'Allen'],
          'last': ['Anderson', 'Ackerman', 'Ali']}
dataframe_a = pd.DataFrame(data_a, columns = ['id', 'first', 'last'])

In [ ]:
data_b = {'id': ['4', '5', '6'],
          'first': ['Billy', 'Brian', 'Bran'],
          'last': ['Bonder', 'Black', 'Balwner']}
dataframe_b = pd.DataFrame(data_b, columns = ['id', 'first', 'last'])

In [ ]:
pd.concat([dataframe_a, dataframe_b], axis=0)

In [ ]:
row = pd.Series([10, 'Chris', 'Chillon'], index=['id', 'first', 'last'])

In [ ]:
dataframe_a.append(row, ignore_index=True)

In [ ]:
employee_data = {'employee_id': ['1', '2', '3', '4'],'name': ['Amy Jones', 'Allen Keys', 'Alice Bees','Tim Horton']}
dataframe_employees = pd.DataFrame(employee_data, columns = ['employee_id','name'])

In [ ]:
sales_data = {'employee_id': ['3', '4', '5', '6'],'total_sales': [23456, 2512, 2345, 1455]}
dataframe_sales = pd.DataFrame(sales_data, columns = ['employee_id','total_sales'])

In [ ]:
pd.merge(dataframe_employees, dataframe_sales, on='employee_id')

In [ ]:
pd.merge(dataframe_employees, dataframe_sales, on='employee_id', how='outer')

In [ ]:
pd.merge(dataframe_employees, dataframe_sales, on='employee_id', how='left')

In [ ]:
pd.merge(dataframe_employees,dataframe_sales,left_on='employee_id',right_on='employee_id')