# Labor market analysis 2014-2016

* An in-depth analysis of the labor market and its requirments in the field ofsoftware development and engineering

## Description
- This research is about the availability of employment and labour, in terms of supply and demand in software devoelopment and engineering in 2014-2016 Egypt

## The golden question
- what  courses should the company provide  ?
### Sub questions
- what is the proportion of career level ?
- what is the comparison of career level vs average salary vs exp. years? 
- what is the comparison of job_category vs average salary vs exp. years?
- what is the most offering years?
- what is most offer?
    - in general
    - in 2014
    - in 2015
    - in 2016
- what is most Location?
    - in general
    - in 2014
    - in 2015
    - in 2016 
    
 - what is the most offering month
    - in 2014
    - in 2015
    - in 2016
    
 -  what is the top 10 rare jobs that have very high salary?

## Gathering

In [ ]:
import pandas as pd 
import plotly.express as px
df1=pd.read_csv("../input/labor-market/Wuzzuf14-16.csv")

## Assessing

In [ ]:
df1.head(17)

## Assessing results
-  (id,post_date,views,job_description,job_requirements) columns will not help us in  our analysis
- ("city "& "num_vacancies")columns have not readable names

## Cleaning

In [ ]:
df=df1.copy()

## define
- dropping missing value

### Code

In [ ]:
df.isnull().sum()

In [ ]:
df.dropna(inplace= True)

### Test

In [ ]:
df.isnull().sum()

### define
- grouping start of experience level

### code

In [ ]:
x=df.experience_years.str.extract('(\d+)')
x

In [ ]:
x.value_counts()

In [ ]:
df['exp.years']=x
df.head()

In [ ]:
av_column = x.mean(axis=0)

av_column

### Define
- dropping (id,post_date,views,job_description,job_requirements)

### code

In [ ]:
df=df.drop(['id','views','job_description','job_requirements','job_category2','job_category3','job_industry2','job_industry3','experience_years'],axis=1)

### Test

In [ ]:
df.head()

### Define
- rename "city" to "location" & "num_vacancies" to "vacant places"

 ### code

In [ ]:
df=df.rename(columns={'city':'Location','num_vacancies':'Vacant places'})

### Test

In [ ]:
df.head()

In [ ]:
df['year'] = pd.DatetimeIndex(df['post_date']).year
df['month'] = pd.DatetimeIndex(df['post_date']).month

In [ ]:
df.head()

## define
- Dividing to 4 data sets

In [ ]:
is_2014 =df[df['year']==2014]
is_2014.head()

In [ ]:
is_2015 =df[df['year']==2015]
is_2015.head()

In [ ]:
is_2016 =df[df['year']==2016]
is_2016.head()

In [ ]:
df['average salary']=(df['salary_minimum']+df['salary_maximum'])/2

In [ ]:
df.head()

### Define
- saving data sets

In [ ]:
is_2014.to_csv("2014.csv",index=False)
is_2015.to_csv("2015.csv",index=False)
is_2016.to_csv("2016.csv",index=False)

### This pie chart represent the proportion between career levels

In [ ]:
pie_df = df.career_level.value_counts().reset_index()
pie_df.columns = ['career_level','count']
fig = px.pie(pie_df, values='count', names='career_level', title='Proportion of career_level',
             color_discrete_sequence=['#34568B', '#FFA500','#CD212A','#FA7A35',"#6A2E2A"])
fig.show()

### chart results
-  The most level that is requirded isExperienced

### Box plot that present career level vs average salary vs exp. years

In [ ]:
fig = px.box(df, x="career_level", y="average salary",color="exp.years")
fig.update_traces(quartilemethod="exclusive")
fig.show()

In [ ]:
fig = px.box(df, x="job_category1", y="average salary",color="exp.years")
fig.update_traces(quartilemethod="exclusive")
fig.show()

### chart results
- The least salary for a student with no experience is 3000 L.E
- The maximum salary for a 10 experience manager is 140,000

In [ ]:
title=df['year'].value_counts()[:10]
title.plot(kind='barh',title="years proportion" ,color="#A2242F")

In [ ]:
df.year.value_counts()

In [ ]:
title=df['job_title'].value_counts()[:10]
title.plot(kind='barh',title="Most ten offers in general")

In [ ]:
title=df['Location'].value_counts()[:10]
title.plot(kind='barh',title="Most ten locations in general")

## Analysis of 2014

In [ ]:
title=is_2014['job_title'].value_counts()[:10]
title.plot(kind='barh',title="Most ten offers in 2014")

In [ ]:
title=is_2014['Location'].value_counts()[:10]
title.plot(kind='barh',title="Most ten Locations in 2014")

In [ ]:
title=is_2014["month"].value_counts()[:10]
title.plot(kind='barh',title="month proportion in 2014" ,color="#A2242F")

In [ ]:
is_2014.month.value_counts()

## Analysis of 2015

In [ ]:
title=is_2015['job_title'].value_counts()[:10]
title.plot(kind='barh',title="Most ten offers in 2015")

In [ ]:
title=is_2015['Location'].value_counts()[:10]
title.plot(kind='barh',title="Most ten Locations in 2015")

In [ ]:
title=is_2015["month"].value_counts()[:10]
title.plot(kind='barh',title="month proportion 2015" ,color="#A2242F")

In [ ]:
is_2015.month.value_counts()

## Analysis of 2016

In [ ]:
title=is_2016['job_title'].value_counts()[:10]
title.plot(kind='barh',title="Most ten offers in 2016")

In [ ]:
title=is_2016['Location'].value_counts()[:10]
title.plot(kind='barh',title="Most ten Locations in 2016")

In [ ]:
title=is_2016["month"].value_counts()[:10]
title.plot(kind='barh',title="month proportion 2016" ,color="#A2242F")

In [ ]:
is_2016.month.value_counts()[:12]

In [ ]:
x=df[["job_title","average salary","salary_maximum"]].sort_values(by="average salary",ascending= False)
x.head(10)

In [ ]:
df.info()