In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
df=pd.read_csv('/kaggle/input/paralmpic-2020/Paralympic_Medal_Count.csv')

## First Steps in DATA ANALYST

From here I would like to start off with the characteristics of the Dataframes (eg: shapes, variables, info, etc)

Showing the first top 5 data in dataframe

In [ ]:
df.head()

showing the last 5 data in dataframe

In [ ]:
df.tail()

Let's see how many column and rows in this dataframe.

In [ ]:
df.shape

Check for variables in dataframes. What are the type of variables in the dataframe. 
we can use pd.info() or pd.dtypes

In [ ]:
df.info()

In [ ]:
df.dtypes

from this, we can see that only Team/Npc variable/column is a string type wheres other variables/columns are an intergers.

## Let's do some data cleaning
does this dataframe need cleaning or not? Does the data have null value? Does it have duplication? so let's do it here.

In [ ]:
# df.duplicated().any()
# false will tell us that the data does not have any duplication in the dataframe.
# However, I would like to print this value into a more understanding output. let's use IF ELSE method
chkdup = df.duplicated().any() 

if chkdup == False:
    print('There is no duplication of data in the DF')
else:
    print('There is duplication of data in the DF')

In [ ]:
# Now we would like to check is there any null value in the data through each columns
df.isna().any()
# note that if the value is False, that means there is no null value in the column.

In [ ]:
# Here I want to check what are the values in the series dataframe of Team/NPC, maybe I could add some more column from this.

df["Team/Npc"].unique()

In [ ]:
## lets classify these teams into a continent for further analysis purpose
conti={"People's Republic of China":"Asia", 'Great Britain':'Europe',
       'United States of America':'North America', 'RPC':'Europe and Asia', 'Netherlands':'Europe', 'Ukraine':'Europe',
       'Brazil':'South America', 'Australia':'Oceania', 'Italy':'Europe', 'Azerbaijan':'Europe and Asia', 'Japan':'Asia', 'Germany':'Europe',
       'Islamic Republic of Iran':'Asia', 'France':'Europe', 'Spain':'Europe', 'Uzbekistan':'Asia',
       'Poland':'Europe', 'Hungary':'Europe', 'Switzerland':'Europe', 'Mexico':'North America', 'New Zealand':'Oceania',
       'Israel':'Asia', 'Canada':'North America', 'India':'Asia', 'Thailand':'Asia', 'Slovakia':'Europe', 'Belarus':'Europe',
       'Tunisia':'Africa', 'Algeria':'Africa', 'Morocco':'Africa', 'Belgium':'Europe', 'Ireland':'Europe', 'Nigeria':'Africa',
       'South Africa':'Africa', 'Cuba':'North America', 'Jordan':'Asia', 'Colombia':'South America', 'Venezuela':'South America',
       'Malaysia':'Asia', 'Denmark':'Europe', 'Republic of Korea':'Asia', 'Turkey':'Europe and Asia', 'Indonesia':'Asia',
       'Czech Republic':'Europe', 'Chile':'South America', 'Serbia':'Europe', 'Norway':'Europe', 'Singapore':'Asia',
       'Austria':'Europe', 'Sweden':'Europe', 'Greece':'Europe', 'Finland':'Europe', 'Kazakhstan':'Europe and Asia',
       'United Arab Emirates':'Asia', 'Costa Rica':'North America', 'Ecuador':'South America', 'Cyprus':'Europe',
       'Sri Lanka':'Asia', 'Ethiopia':'Africa', 'Mongolia':'Asia', 'Pakistan':'Asia', 'Peru':'South America',
       'Argentina':'South America', 'Egypt':'Africa and Asia', 'Croatia':'Europe', 'Latvia':'Europe', 'Georgia':'Europe and Asia',
       'Hong Kong, China':'Asia', 'Bulgaria':'Europe', 'Iraq':'Asia', 'Kuwait':'Asia', 'Namibia':'Africa',
       'Romania':'Europe', 'Slovenia':'Europe', 'Vietnam':'Asia', 'Lithuania':'Europe', 'Portugal':'Europe',
       'Bosnia and Herzegovina':'Europe', 'El Salvador':'North America', 'Kenya':'Africa', 'Saudi Arabia':'Asia',
       'Montenegro':'Europe', 'Oman':'Asia', 'Qatar':'Asia', 'Chinese Taipei':'Asia', 'Uganda':'Africa'}
## put this dictionary into another column (creating new column named; Continent)
df['Continent']=df["Team/Npc"].replace(conti)
df.head(3)

In [ ]:
#just to rename column to look better.
df1=df.rename(columns={'silver':'Silver','bronze':'Bronze','total medals':'Total Medals','rank by total':'Rank by total medals'}, inplace = False)
df1.head(3)

#from now on, I have to use df1 for updated dataframe

## Data Analysis

Now that our data is clean, we can start do analysis with the data provided in the data frame.

It is time to import some packages provided by python.

In [ ]:
## import packages that can be use for data analysis and visualization
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

Here I want to analyse the ranking of team in paralympics 2021.

In [ ]:
rank=df1.sort_values(by='Rank by total medals',ascending=True)
rank.head(20)

let's see how many countries/team from each continent

we can also see the total of gold, silver & bronze medals obtained during the paralympic 2021

In [ ]:
count = df1[['Gold','Silver','Bronze']].sum().reset_index().rename(columns={'index':'Medal',0:'Total obtained'})
print(count)

It is time to plot some data visualization to do further analysis.

In [ ]:
vari=['Team/Npc','Rank by total medals','Total Medals']
byRank=df1.sort_values('Rank by total medals', ascending=True).reset_index().head(20)
byRank=byRank[vari].head(20)

plt.figure(figsize = (15,8))
bar2=sns.barplot(y='Team/Npc',x='Total Medals', data=byRank)
bar2.set_title('Team/Npc against Total Medals')

In [ ]:
df1['Continent'].value_counts()

In [ ]:
plt.figure(figsize = (10,8))
bar1=sns.countplot(x='Continent', data=df1,palette=['#6F8FAF'])
bar1.set_title('Figure 2: Number of Team/NPC in Continent',fontsize=15)
bar1.set_xlabel('Continent',fontsize=12)
bar1.set_ylabel('Number of Team/Npc')
bar1.tick_params(axis='x', rotation=45)

In [ ]:
dfcont=df1.groupby('Continent', as_index=False).agg({"Total Medals": "sum","Gold":"sum","Silver":"sum","Bronze":"sum"})
dfcont

In [ ]:
plt.figure(figsize = (10,8))
bar3=sns.barplot(x='Continent',y='Total Medals',data=dfcont,palette=['#6F8FAF'])
bar3.set_title('Figure 3: Total medals obtained by each Continents',fontsize=15)
bar3.tick_params(axis='x', rotation=45)

Based on both Figure 2 and Figure 3, we can see Europe continent has the highest value in both; team and total medal obtained. As Europe Team has the largest number of team, that would tell us that Europe will obtained highest TOTAL number of medals. eventhough People's Republic of China has ranked as no 1 in the list. However comparing with the continent, Europe still obtained highest number of medals.

In [ ]:
plt.figure(figsize=(16,7))
xpos = np.arange(len(dfcont['Continent']))
plt.xticks(xpos,dfcont['Continent'],rotation=90,fontweight='bold',fontsize=13)
plt.bar(xpos-0.3,'Gold',data=dfcont,color='gold',width=0.3)
plt.bar(xpos,'Silver',data=dfcont,color='#C0C0C0',width=0.3,label='Silver')
plt.bar(xpos+0.3,'Bronze',data=dfcont,color='#C39B77',width=0.3,label='Bronze')
plt.yticks(fontsize=12,color='black',fontweight='bold')
plt.legend(labels=["Gold","Silver","Bronze"])
plt.show()

In [ ]:
df1.corr()

In [ ]:
df1.describe()