In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')

## Exploring the Titanic Dataset using Pandas in Python

In [ ]:
df = pd.read_csv('../input/d/rahulsah06/titanic/train.csv')
df.head()

In [ ]:
df.drop(['PassengerId','Ticket','Name'],inplace=True,axis=1)

# Building a Pivot Table using Pandas

### single index

In [ ]:
#a single index
table = pd.pivot_table(data=df,index=['Sex'])
table

In [ ]:
table.plot(kind='bar');

### multi index

In [ ]:
#multiple indexes
table = pd.pivot_table(df,index=['Sex','Pclass'])
table

In [ ]:
#different aggregate functions
table = pd.pivot_table(df,index=['Sex','Pclass'],aggfunc={'Age':np.mean,'Survived':np.sum})
table

In [ ]:
table = pd.pivot_table(df,index=['Sex','Pclass'],values=['Survived'], aggfunc=np.mean)
table

In [ ]:
table.plot(kind='bar');

###  relationship between features with columns parameter

In [ ]:
#columns
table = pd.pivot_table(df,index=['Sex'],columns=['Pclass'],values=['Survived'],aggfunc=np.sum)
table

In [ ]:
table.plot(kind='bar');

### Handling missing data

In [ ]:
#display null values
table = pd.pivot_table(df,index=['Sex','Survived','Pclass'],columns=['Embarked'],values=['Age'],aggfunc=np.mean)
table

In [ ]:
#handling null values
table = pd.pivot_table(df,index=['Sex','Survived','Pclass'],columns=['Embarked'],values=['Age'],aggfunc=np.mean,fill_value=np.mean(df['Age']))
table