In [ ]:
import pandas as pd
import numpy as np
import holoviews as hv
import seaborn as sns
import matplotlib.pyplot as plt
hv.extension('bokeh')

In [ ]:
data=pd.read_csv("/kaggle/input/okcupid-profiles/okcupid_profiles.csv")
data.head()

In [ ]:
data.dtypes

In [ ]:
data["sex"].unique()

In [ ]:
## Make a category of Status
data["sex"]=data["sex"].astype("category")
data["sex"].cat.set_categories(["m","f"], inplace=True)

In [ ]:
pd.pivot_table(data=data, index=data.sex, values="income", aggfunc=np.mean)

on average, the average age for both men and women is 32, men are taller than women and receive on average a twice higher salary

In [ ]:
pd.pivot_table(data=data, index=data.education, values=["age", "income"],aggfunc=np.mean)

In [ ]:
pd.pivot_table(data=data, index=["education", "sex"],aggfunc=np.mean)

In [ ]:
pd.pivot_table(data=data, index=["smokes", "drinks"], values="income")

In [ ]:
pd.pivot_table(data=data, index=["smokes", "drinks"], values=["income"])

In [ ]:
pd.pivot_table(data=data, index="education", values=["income"], aggfunc=[np.mean,len], fill_value=0)

In [ ]:
pd.pivot_table(data=data, 
               index=["status", "sex"], 
               values=["income", "age"],
               aggfunc=np.mean, 
               fill_value=0, 
               margins=True)

on Average the age is 32y.o and the average income is around 20 000â‚¬

In [ ]:
pd.pivot_table(data=data, 
               index=["status", "sex"], 
               values=["income", "age"],
               aggfunc={"income": np.mean, "age": np.median}, 
               fill_value=0, 
               margins=True)

In [ ]:
table=pd.pivot_table(data=data, 
               index=["status", "sex"], 
               values=["income", "age"],
               columns="orientation",
               aggfunc={"income": np.mean, "age": np.median}, 
               fill_value=0, 
               margins=True)
table

In [ ]:
table=pd.pivot_table(data=data, 
               index=["status", "sex"], 
               values=["income", "age"],
               columns="orientation",
               aggfunc=[len, np.mean],
               fill_value=0, 
               margins=True)
table

In [ ]:
table.query('status==["available"]')

In [ ]:
table.query('status==["available", "married"]')

In [ ]:
data.head()

In [ ]:
pd.set_option('display.max_rows', None) 
pd.pivot_table(data,
               index=["drugs", "drinks", "smokes"], 
               values=["age", "income"], 
               aggfunc=[np.mean, len],
               margins=True)

In [ ]:
pd.set_option('display.max_rows', None) 
bad_habit=pd.pivot_table(data,
               index=["drugs", "drinks", "smokes"], 
               values="income", 
               aggfunc=[np.mean, len],
               margins=True)
bad_habit

In [ ]:
bad_habit.query('smokes=="yes" and drugs=="never"', inplace=True)
bad_habit

In [ ]:
pd.set_option('display.max_rows', None) 
bad_habit=pd.pivot_table(data,
               index=["drugs", "drinks", "smokes"], 
               values="income", 
               aggfunc=[np.mean, len],
               margins=True)
bad_habit

In [ ]:
bad_habit.xs(("never", "not at all", "no")) ## Never use Drugs, no drinking but no smoking

In [ ]:
bad_habit.xs(("sometimes", "very often", "yes")) ## Sometimes use Drugs, very often drinking but smoking

In [ ]:
bad_habit.dtypes

In [ ]:
bad_habit.query('drugs=="never"')

In [ ]:
bad_habit.query('drugs=="never" & drinks==["desperately","not at all"] & smokes=="no"')