In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input/revenue-generated-by-advertisements/'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
root = '/kaggle/input/revenue-generated-by-advertisements/'

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
df = pd.read_csv(
    os.path.join(root, 'Test_Data.csv'))
#df.isnull().any()[df.isnull().any()>0]
#df = df.fillna(df.mean)
df

In [ ]:
#Checking null values
df.isnull().sum()
#No null in the dataset

In [ ]:
#Checking if datasets have duplicates values
df2 = df.drop_duplicates()
print("Dataset before duplicates {} and after duplicate deletion {}".format(df.shape, df2.shape))
#No duplicates

In [ ]:
#Checking all unique elements
df2['campaign'].unique()
df2['adgroup'].unique()
#Campaign has 1 dataset and adgroup has 4 dataset, Campaign could be dropped
df2.drop(['campaign'], axis = 'columns')

In [ ]:
#Convert adgroup and ad string into integer
df2['adgroup'] = df2['adgroup'].apply(lambda x : int(x.split(' ')[1]))
df2['ad'] = df2['ad'].apply(lambda x : int(x.split(' ')[1]))
df2['ad']

In [ ]:
#Preliminary analysis, understanding data
df_group = df2.groupby(['adgroup', 'ad']).sum().sort_values(by ='conversions', ascending = False).sort_index()
df_group = df_group['conversions']
df_group

In [ ]:
#Generating barplot for the above data
import matplotlib.pyplot as plt 
import seaborn as sns
df_group.unstack().plot(kind = 'bar', stacked = True)
#sns.barplot(df_group.index,df_group['cost'])