# Reading the Data

In [ ]:
import pandas as pd
DataFrame = pd.read_csv('../input/buylab/buys_labtop.csv')
DataFrame

**1. We can use the shape attribute to check how large the resulting DataFrame is:

In [ ]:
DataFrame.shape

2. We can examine the contents of the resultant DataFrame using the head() command, which grabs the first five rows:

In [ ]:
DataFrame.head()

grabs the first 20 rows:

In [ ]:
DataFrame.head(20)

# Indexing, Selecting & Assigning

acess column gender by two ways:
1st method using (dataframe.nameofcolumn)

In [ ]:
DataFrame.gender

2nd method using (dataframe['Label of column'])

In [ ]:
DataFrame['gender']

you can save the selected column in a serie
Create a serie in which you select only colum gender

In [ ]:
serie=DataFrame['gender']
serie

select data in row 6, column gender (**column-first, row-second**)

In [ ]:
DataFrame['gender'][6]

# Indexing in pandas

To select the first row of data in a DataFrame, we may use the

# iloc: 
**row-first, column-second**

In [ ]:
DataFrame.iloc[0]

To get a column with iloc, we can do the following

In [ ]:
DataFrame.iloc[:, 2]

to select the gender column from just the third, fourth, and fifth row, we would do:

In [ ]:
DataFrame.iloc[2:5, 0]

It's also possible to pass a list: (elements at row 0, 4 and 7 of colum number 2: gender)

In [ ]:
DataFrame.iloc[[0, 4, 7], 2]

to select the 6 last genders we do:
1st method : using iloc

In [ ]:
DataFrame.iloc[-6:]

to select the 6 last genders we do:
2nd method : using tail

In [ ]:
DataFrame.tail(6)

Label-based selection
# using loc

to get the first entry in DataFrame,from column gender, we would now do the following:

In [ ]:
DataFrame.loc[0, 'gender']

to select columns gender, education and	buys_labtop

In [ ]:
DataFrame.loc[:, ['gender', 'education', 'buys_labtop']]

to select 2nd fourth and sixth values from columns gender, education and buys_labtop

In [ ]:
DataFrame.loc[[1, 3, 5], ['gender', 'education', 'buys_labtop']]

# Manipulating the index
Label-based selection derives its power from the labels in the index. Critically, the index we use is not immutable.

In [ ]:
DataFrame.set_index("gender")

# Conditional selection
To do interesting things with the data, we often need to ask questions based on conditions.

We start by  start by checking if   buys_labtop=yes in DataFrame

In [ ]:
DataFrame.buys_labtop=='yes'

This operation produced a Series of True/False booleans based on the buy_labtop of each record. This result can then be used inside of loc to select the relevant data:

In [ ]:
DataFrame.loc[DataFrame.buys_labtop=='yes']

We can use the ampersand (&) and (|) for complex condition

In [ ]:
DataFrame.loc[((DataFrame.buys_labtop=='yes')& (DataFrame.education=='bachelor'))|((DataFrame.buys_labtop=='no')& (DataFrame.education=='H-school'))]

**isin**  lets you select data whose value "is in" a list of values.

In [ ]:
DataFrame.loc[DataFrame.age.isin(['young', 'mid-age'])]

isnull  (and its companion notnull) lets you highlight values which are (or are not)   empty (NaN)

to select non null values from column gender

In [ ]:
DataFrame.loc[DataFrame.gender.notnull()]

to select null values from column gender

In [ ]:
DataFrame.loc[DataFrame.gender.isnull()]

# Assigning data

Add column Computer science and assign it a constant value yes

In [ ]:
DataFrame['Computer Scinece']='yes'
DataFrame

create a new column and assign  it iterable of values:

In [ ]:
DataFrame['iterable'] = range(len(DataFrame)*2, 0, -2)
DataFrame

# Summary Functions and Maps

If you want to get some particular simple summary statistic about a column in a DataFrame or a Series, there is usually a helpful pandas function that makes it happen

# #1 Summary functions

# Describe
This method generates a high-level summary of the attributes of the given column. It is type-aware, meaning that its output changes based on the data type of the input. 

For string data here's what we get:

summary of column gender

In [ ]:
DataFrame.gender.describe()

For numeric data

In [ ]:
DataFrame.iterable.describe()

To see a list of unique values we can use the unique()

In [ ]:
DataFrame.iterable.unique()

To see a list of unique values and how often they occur in the dataset, we can use the value_counts() method:

In [ ]:
DataFrame.iterable.value_counts()

# DESCRIPTIVE STATISTICS

# measures of central tendency

Measured in a given data using 3 M’s
•
Mean
•
Median
•
Mode

In [ ]:
DataFrame.iterable.mean()

In [ ]:
DataFrame.iterable.median()

In [ ]:
DataFrame.iterable.mode()

# measures of variability

Range
•
Variance and standard deviation.
•
Quartiles and the interquartile range

Extract outliers

In [ ]:
import matplotlib.pyplot as plt
desc = DataFrame.iterable.describe()
Q1 = desc[4]
Q2 = desc[5]
Q3 = desc[6]
print('Q1=', Q1, 'Q2=', Q2,'Q3=', Q3)
IQR = Q3-Q1
lower_bound = Q1 - 1.5*IQR
upper_bound = Q3 + 1.5*IQR
print("Anything outside this range is an outlier: (", lower_bound ,",", upper_bound,")")
DataFrame[DataFrame.iterable < lower_bound].iterable
print("Outliers: ",DataFrame[(DataFrame.iterable < lower_bound) | (DataFrame.iterable > upper_bound)].iterable.values)
boxplot=DataFrame.boxplot(column='iterable')
plt.show()

# Grouping and Sorting

# Groupwise analysis

In [ ]:
DataFrame.groupby('gender').gender.count()

We can use any of the summary functions we've used before

In [ ]:
DataFrame.groupby('gender').iterable.min()

Another groupby() method worth mentioning is agg(), which lets you run a bunch of different functions on your DataFrame simultaneously. For example, we can generate a simple statistical summary of the dataset as follows:

In [ ]:
DataFrame.groupby(['gender']).iterable.agg([len, min, max])

# Multi-indexes

A multi-index differs from a regular index in that it has multiple levels. For example:

In [ ]:
DataFrame_reviewed = DataFrame.groupby(['gender', 'age']).iterable.agg([len])
DataFrame_reviewed

# Sorting

In [ ]:
DataFrame.sort_values(by='iterable')

sort_values() defaults to an ascending sort, where the lowest values go first. However, most of the time we want a descending sort, where the higher numbers go first. That goes thusly:

In [ ]:
DataFrame.sort_values(by='iterable', ascending=False)

We can sort by more than one column at a time:

First, we add a new numeric column

In [ ]:
DataFrame['last']=DataFrame['iterable']+DataFrame['iterable']*3
DataFrame

We sort DataFrame by iterable and last

In [ ]:
DataFrame.sort_values(by=['iterable','last'], ascending=False)

# Data Types and Missing Values

# Dtypes

In [ ]:
DataFrame.iterable.dtype

Alternatively, the dtypes property returns the dtype of every column in the DataFrame:

In [ ]:
DataFrame.dtypes

It's possible to convert a column of one type into another

In [ ]:
DataFrame.iterable.astype('float64')

# Missing data

Pandas provides some methods specific to missing data. To select NaN entries you can use pd.isnull() (or its companion pd.notnull())

In [ ]:
DataFrame[pd.isnull(DataFrame.gender)]

Replacing missing values is a common operation. Pandas provides a really handy method for this problem: **fillna()**.

In [ ]:
DataFrame.gender.fillna(0)

# Renaming and Combining

# Renaming

In [ ]:
DataFrame.rename(columns={'last': 'score'},inplace=True)

# Combining

In [ ]:
DataFrame['result']=DataFrame['iterable']+DataFrame['score']
DataFrame

# Data Visualization

# A-Univariate plotting

Draw frequency of age

In [ ]:
import matplotlib.pyplot as plt
DataFrame.age.value_counts().plot.bar()
plt.show()

# bivariate plot

Scatter plot for age and income: Scatter for numerical data

Convert Categorical data to numerical data

In [ ]:
# create new feature mapping each category value to number as shown below
DataFrame['age_n'] = DataFrame.age.map({'young': 1, 'mid-age': 2,'old': 3 })
DataFrame['income_n'] = DataFrame.income.map ({'low': 1, 'medium': 2,'high': 3 })
DataFrame

In [ ]:
import matplotlib.pyplot as plt
DataFrame.plot.scatter(x='age_n' , y='income_n' )
plt.show()

# To overcome problem of over-plotting****

In [ ]:
import matplotlib.pyplot as plt
DataFrame.plot.hexbin(x='age_n' , y='income_n' , gridsize=10)
plt.show()

In [ ]:
import seaborn as sns 
sns.lmplot(x='age_n' , y='income_n' , hue='buys_labtop', data=DataFrame)
plt.show()

# Linear Regression

Predict income based on feature age

In [ ]:
#import library required for linear regression
from sklearn.linear_model import LinearRegression
#import library required for data visualization
import matplotlib.pyplot as plt
_,ax = plt.subplots(figsize=(5,5))
#select model
model = LinearRegression()
#select feature (predictor =age_n) 
x = DataFrame.age_n.values.reshape(-1,1)
#target ( response variable=income_n) 
y = DataFrame.income_n.values.reshape(-1,1)
model.fit(x,y)

ax.scatter(x, y, color = "red")
y_pred= model.predict(x).reshape(-1,1)

ax.scatter(x,y_pred, color = "blue")
plt.show()

In [ ]:
_, ax=plt.subplots(figsize=(15,5))

n_samples=50 #Y.shape[0]
n_samples=y.shape[0]
ax.scatter(x=range(0, n_samples),y=y[0:n_samples],c= 'blue',label='Actual')
ax.scatter(x=range(0, n_samples),y=y_pred.T[0:n_samples],c= 'red',label='predicted')

plt.title('Actual and predicted values')
plt.xlabel('Samples')
plt.ylabel('value')
plt.legend()
plt.show()