# NOTE:
Refer to the below notebook first:
1. **Salaries w.r.t Majors:** https://www.kaggle.com/harshdatadivecha/analysing-salaries-w-r-t-majors

In [ ]:
%matplotlib inline

import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv("../input/salaries-by-college-type.csv")


**Lets first get familiar with the dataset provided to us:**

In [ ]:
dataset.head(5)

<font size =4>
We can see Dollar signs in our data, so we will solve this problem just as we did previously in Exploring salaries w.r.t majors kernel. (link has been provided at the top)<br><br>
But there's one difference from last time... there are NaN values to be dealth with along with formatting of data types.
</font>

<font size =3>
Lets first formulate questions now and also look at the types of features we have at our hand:
</font>
### Questions:
- which are the top salary grossing colleges ?
- Which are the top salary grossing degree types ?

### Feature types:
- **Categorical:**
    - Degree types
- **Continuous:**
    - All other columns

# 1. Data Cleaning:

In [ ]:
cols = list(dataset)
cols.insert(5,cols.pop(cols.index('Mid-Career Median Salary')))

cols

In [ ]:
dataset=dataset.loc[:,cols]
dataset.columns = cols=["School_name",'College_type','Start','Mid_10th','Mid_25th','Mid_50th','Mid_75th','Mid_90th']
dataset.head(3)

In [ ]:
df = dataset

In [ ]:
print ( type(df.Mid_10th[0]),type(df.Mid_10th[1]))

### This time we have added an if-else statement to check the nan values and preserve them

In [ ]:

def convert(col):
#for col in columns:
    df[col] = df[col].map(
        lambda x : x.split('$')[1] if not pd.isnull(x) else None).map(
        lambda x: float(x.split(',')[0]+x.split(',')[1]) if not pd.isnull(x) else np.nan)

In [ ]:
for col in df.columns[2:]:
    convert(col)

In [ ]:
df.info()

<br><br>
<font size=3>
We can see that there are 38 null values in Mid_10th and Mid_90th columns... so lets deal with them before moving on.
</font>

In [ ]:


def fill_nas(cols):
    for col in cols:
        df[col]=df.groupby("College_type")[col].apply(lambda x: x.fillna(x.mean()))

In [ ]:
cols = df.columns[2:]
fill_nas(cols)

In [ ]:
df.info()

In [ ]:
df.head(4)


# 2. EDA:
lets take a look at mean values for different colleges:

In [ ]:
grouped_df = df.groupby("College_type").mean().sort_values(by="Start",ascending=False)
grouped_df

In [ ]:
grouped_df=grouped_df.transpose()

In [ ]:
f,ax = plt.subplots(figsize=(8,7))
grouped_df.plot(ax=ax)
ax.set_ylabel("Salary")
ax.set_xlabel("Career")

<br>
This graph shows the power of visualization. Here we can see that two college types (Ivy League and Engineering) and rest of the three college types start with almost same starting salaries, but the Ivy League takes the lead from engineering at about Mid_25th percentile and grows rapidly and exponentialy.<br><br>
One intresting thing we notice is that Engineering starts falling behind Liberal Arts at Mid_75

In [ ]:
df_melt = df.drop("School_name",axis=1)
df_melt=df_melt.melt(id_vars="College_type",var_name="Career",value_name="Salary")

In [ ]:
df_melt.head(6)

In [ ]:
f,ax= plt.subplots(figsize=(8,6))

sns.boxplot(data=df_melt,x="Career",y="Salary",ax=ax)

In [ ]:
f,ax = plt.subplots(figsize=(8,6))
sns.swarmplot(ax=ax,x=df_melt.College_type,y=df_melt.Salary)
ax.set_title("Salaries acc to college type")

In [ ]:
f,ax = plt.subplots(figsize=(8,6))
sns.swarmplot(ax=ax,x=df_melt.Career,y=df_melt.Salary,hue=df_melt.College_type)
ax.set_title("Salaries acc to Career")

In [ ]:
df_melt.College_type.value_counts()

<br>

### These swarm plots reveal that:<br>
- There are too many students who go for the **"STATE" College** in comparison to other colleges and on calculating the values we see there are 1050 students going to the State college.
- The Ivy League colleges such as Harvard,Cornell,etc have few students as it is really tough to get into and really costly, but we also see that students belonging to these colleges also get higher salaries than other colleges.
- We also observe that students belonging to the "STATE" college are the ones with the lowest salaries.


At first the values of Ivy League Colleges seemed like outliers but, they are required as they reflect real life. 

<br><br>
** GIVE me suggestions w.r.t what should i do next ?**<br>
Obviously, next plan is to perfrom cleaning and EDA on region data but what should i do after that ?<br>
Also please comment with suggestions for improvements and how was the work.<br>