# This is a Short Introduction to pandas and Visualization libraries.
**You can Learn how to read Data and elemantry exploratry Data Analysis by this Notebook.**

For this purpose, I select a real dataset about the Salary of employee in San Francisco ( a city in USA).

This Dataset contains more than 300k employee records found from 2011 to 2018.

Salary analysis help government to increase public understanding in order to make a better decison.



## About the Dataset:
This Dataset Contains 9 row and 312882 rows showing the lots of information about the emoloyee's salary in San Francisco during 2011 to 2018 as below:

**EmployeeName**:Shows each Employee Name

**JobTitle**:Shows the job title of each Employee

**BasePay**:Base Pay Salary for each Employee

**OvertimePay**:The overtime Pay Salary for each Employee

**OtherPay**:if the Employees have any other Salary

**Benefits**:indicate any Benefits

**TotalPay**:Sum of BasePay, OverTimePay and OtherPay

**TotalPayBenefits**:Sum of TotalPay and Benefits

**Year**:2011 to 2018

### Step1: Import all necessary Libraries as follow

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### Step2: Import the Data

In [ ]:
#Read the Data and make a DataFrame
df=pd.read_csv('../input/20112018-salaries-for-san-francisco/Total.csv')

### Stpe3: DataFrame Overview

In [ ]:
df.head()

In [ ]:
#Check the Shape of the DataFrame

print('This Dataset countains {} Rows and {} Columns'.format(df.shape[0], df.shape[1]))

In [ ]:
#Check other information about the dataset
df.info()

**The above window shows that:**

1- All columns have 312882 records (We don't have any missing data)

2- Columns (BasPay, OvertimePay, OtherPay and Benefits) are in object format. Therefore, for analyzing these columns, we must change their type to float64. So,..

In [ ]:
series_list = ['BasePay', 'OvertimePay', 'OtherPay', 'Benefits']
for series in series_list:
    df[series] = pd.to_numeric(df[series], errors='coerce')

In [ ]:
#Check the dataset information again
df.info()

### Step3: Descriptive Statistical Analysis

**Q1: What is the average of BasePay?**

In [ ]:
df['BasePay'].mean()

**Q2: What is the maximum of BasePay?**

In [ ]:
df['BasePay'].max()

**We can calculate all the basic statistical details for one (or more) column(s) as below:**

In [ ]:
df['BasePay'].describe()

### Exercise1: Apply the above analysis for other columns

**We can calculate basic statistical details for all the numerical columns as below:**

In [ ]:
df.describe()

**Like me, you may be curious about this negative BasePay**

**So, let me check who have negetaive BasePay?**

In [ ]:
df[df['BasePay']<0]

**The above table shows that 13 employee get negetavie BasePay. It needs to be check.**

### Step4: Elementary EDA

**Q3: We have an Employee Name:"Ricardo Jimenez"**

**lets explore some insights about "Ricardo Jimenez"?**

In [ ]:
df[df['EmployeeName']=='Ricardo Jimenez']

### Exercise2: Plot RicardoJimenez TotalPayBenefits VS Year

**Q4: How much is the "BasePay" of "RicardoJimenez"?**

In [ ]:
df[df['EmployeeName']=='Ricardo Jimenez'][['BasePay', 'Year']]

**Q5:The information of how many years are available in this dataset?**

In [ ]:
A=df['Year'].nunique()
B=df['Year'].unique()
print('The information of {} Years are available in this data set: {}'.format(A,B))

**Q6: What is the average BasePay in each Year?**

In [ ]:
df.groupby('Year').mean()['BasePay']

**Q7: Visualize the mean of BasePay in each year**

In [ ]:
sns.barplot(data=df,x='Year', y='BasePay')

### Exercise3: Which year has the maximum mean of BasePay?

**Q8: What is the 5 most popular JobTitle?**

In [ ]:
df['JobTitle'].value_counts().head(5)

**Q9: How many unique JobTitle are in each year?**

In [ ]:
df.groupby('Year').nunique()['JobTitle']

**Q10: How many unique JobTitle are in 2013?**

In [ ]:
df[df['Year']==2013]['JobTitle'].nunique()

**Q11: In 2013, how many JobTitle belong just to one employee?**

In [ ]:
sum(df[df['Year']==2013]['JobTitle'].value_counts()==1)

**Q12: How many employee have JobTitle with the word 'chief'?**

In [ ]:
def chief_string(title):
    if 'chief' in title.lower():
        return True
    else:
        return False

sum(df['JobTitle'].apply(lambda x: chief_string(x)))