In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
import pandas as pd
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import lightgbm as lgb
import plotly.express as px

In [ ]:
rainfall=pd.read_csv("../input/rainfall-in-pakistan/Rainfall_1901_2016_PAK.csv")

Basic Analysis

In [ ]:
rainfall.head()

In [ ]:
rainfall.shape

In [ ]:
rainfall.info()

Renaming columns

In [ ]:
rainfall.rename(columns ={' Year':'year'}, inplace=True)
rainfall.rename(columns ={"Month":'month'}, inplace=True)
rainfall.rename(columns ={"Rainfall - (MM)":'rainfall-mm'}, inplace=True)

In [ ]:
rainfall.head()

Rainfall(mm) in January from year 2000 to 2016

In [ ]:
plt.figure(figsize=(10,6))
sns.barplot(x=rainfall["year"].loc[(rainfall.year >=2000)].loc[(rainfall.month =="January")],y=rainfall["rainfall-mm"]).set_title("Rainfall(mm) in January from year 2000 to 2016")

Rainfall(mm) in Feburary from year 2000 to 2016

In [ ]:
plt.figure(figsize=(10,6))
sns.barplot(x=rainfall["year"].loc[(rainfall.year >=2000)].loc[(rainfall.month =="February")],y=rainfall["rainfall-mm"]).set_title("Rainfall(mm) in Feburary from year 2000 to 2016")

Rainfall(mm) in March from year 2000 to 2016

In [ ]:
plt.figure(figsize=(10,6))
sns.barplot(x=rainfall["year"].loc[(rainfall.year >=2000)].loc[(rainfall.month =="March")],y=rainfall["rainfall-mm"]).set_title("Rainfall(mm) in March from year 2000 to 2016")

Rainfall(mm) in April from year 2000 to 2016

In [ ]:
plt.figure(figsize=(10,6))
sns.barplot(x=rainfall["year"].loc[(rainfall.year >=2000)].loc[(rainfall.month =="April")],y=rainfall["rainfall-mm"]).set_title("Rainfall(mm) in April from year 2000 to 2016")

Rainfall(mm) in May from year 2000 to 2016

In [ ]:
plt.figure(figsize=(10,6))
sns.barplot(x=rainfall["year"].loc[(rainfall.year >=2000)].loc[(rainfall.month =="May")],y=rainfall["rainfall-mm"]).set_title("Rainfall(mm) in May from year 2000 to 2016")

Rainfall(mm) in June from year 2000 to 2016

In [ ]:
plt.figure(figsize=(10,6))
sns.barplot(x=rainfall["year"].loc[(rainfall.year >=2000)].loc[(rainfall.month =="June")],y=rainfall["rainfall-mm"]).set_title("Rainfall(mm) in June from year 2000 to 2016")

Rainfall(mm) in July from year 2000 to 2016

In [ ]:
plt.figure(figsize=(10,6))
sns.barplot(x=rainfall["year"].loc[(rainfall.year >=2000)].loc[(rainfall.month =="July")],y=rainfall["rainfall-mm"]).set_title("Rainfall(mm) in July from year 2000 to 2016")

Rainfall(mm) in August from year 2000 to 2016

In [ ]:
plt.figure(figsize=(10,6))
sns.barplot(x=rainfall["year"].loc[(rainfall.year >=2000)].loc[(rainfall.month =="August")],y=rainfall["rainfall-mm"]).set_title("Rainfall(mm) in August from year 2000 to 2016")

Rainfall(mm) in September from year 2000 to 2016

In [ ]:
plt.figure(figsize=(10,6))
sns.barplot(x=rainfall["year"].loc[(rainfall.year >=2000)].loc[(rainfall.month =="September")],y=rainfall["rainfall-mm"]).set_title("Rainfall(mm) in September from year 2000 to 2016")

Rainfall(mm) in October from year 2000 to 2016

In [ ]:
plt.figure(figsize=(10,6))
sns.barplot(x=rainfall["year"].loc[(rainfall.year >=2000)].loc[(rainfall.month =="October")],y=rainfall["rainfall-mm"]).set_title("Rainfall(mm) in October from year 2000 to 2016")

Rainfall(mm) in November from year 2000 to 2016

In [ ]:
plt.figure(figsize=(10,6))
sns.barplot(x=rainfall["year"].loc[(rainfall.year >=2000)].loc[(rainfall.month =="November")],y=rainfall["rainfall-mm"]).set_title("Rainfall(mm) in November from year 2000 to 2016")

Rainfall(mm) in December from year 2000 to 2016

In [ ]:
plt.figure(figsize=(10,6))
sns.barplot(x=rainfall["year"].loc[(rainfall.year >=2000)].loc[(rainfall.month =="December")],y=rainfall["rainfall-mm"]).set_title("Rainfall(mm) in December from year 2000 to 2016")

In [ ]:
px.scatter(rainfall.loc[(rainfall.year >=2000)], x="year", y="rainfall-mm", animation_frame="year", animation_group="month",
           size="rainfall-mm", color="month", hover_name="month",title=' Rain fall-(mm) in each month from 2000 to 2016',
           log_x=True, size_max=100, range_x=[1998,2018], range_y=[0,200])

In [ ]:
px.bar(rainfall.loc[(rainfall.year >=2000)], x="year", y="rainfall-mm", animation_frame="year", animation_group="month",
            color="month", hover_name="month",title=' Rain fall-(mm) in each month from 2000 to 2016',
           log_x=True, range_x=[1998,2018], range_y=[0,400])