In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns  # visualization tool
from subprocess import check_output
print(check_output(["ls", "../input"]).decode("utf8"))

In [ ]:
data = pd.read_csv('../input/master.csv')
data.head()

In [ ]:
# This code line get all columns of into dataset
data.columns

In [ ]:
# It shows that this csv document occurs 27820 items and 12 columns
data.shape

In [ ]:
# info gives data type like dataframe
data.info()

In [ ]:
print(data['country'].value_counts(dropna = False))

In [ ]:
data.describe()

In [ ]:
#Melt 
melted = pd.melt(frame=data,id_vars = 'country', value_vars = ['population','age'])
melted

In [ ]:
#Concatenating Data and Data Types
data['population'] = data['population'].astype('float')
data.info()

In [ ]:
data.rename(columns = {'HDI for year':'HDI_for_year'},inplace=True)
data["HDI_for_year"].value_counts(dropna = False)

In [ ]:
data["HDI_for_year"].dropna(inplace=True)
assert data["HDI_for_year"].notnull().all()