In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
train = pd.read_csv('../input/introductiontopandas/titanic_train.csv')

In [ ]:
train.head()

In [ ]:
sns.heatmap(train.isnull(),yticklabels=False,cbar=False,cmap='viridis')

In [ ]:
#Purple is good and yello is null

In [ ]:
sns.set_style('whitegrid')

In [ ]:
#Who survived vs. didn't...use count plot

In [ ]:
sns.countplot(x='Survived',data=train)

In [ ]:
#Remember 1 signifies they survived

In [ ]:
#Adding Gender

In [ ]:
sns.countplot(x='Survived',hue='Sex',data=train,palette='RdBu_r')

In [ ]:
sns.countplot(x='Survived',hue='Pclass',data=train)

In [ ]:
sns.distplot(train['Age'].dropna(),kde=False,bins=30)

In [ ]:
#Easy way to drop nulls above

In [ ]:
train['Age'].plot.hist(bins=35)

In [ ]:
train.info()

In [ ]:
sns.countplot(x='SibSp',data=train)

In [ ]:
#Number of siblings or spouses on board - No spouses or children most common

In [ ]:
#Next highest is couples

In [ ]:
train['Fare'].hist(bins=40,figsize=(10,4))

In [ ]:
#How much paying...cheaper fares

In [ ]:
#

In [ ]:
#

In [ ]:
#Part 2 - Logistic Regression

In [ ]:
#Above lots of nulls in the purple/yellow diagram focused on nulls.

In [ ]:
plt.figure(figsize=(10,7))
sns.boxplot(x='Pclass',y='Age',data=train)

In [ ]:
#Class of individuals.....looking at Age of each classes

In [ ]:
#So first class and second class passengers were older

In [ ]:
#Taking care of nulls putting in averages for blanks else using age

In [ ]:
def impute_age(cols):
    Age = cols[0]
    Pclass = cols[1]
    
    if pd.isnull(Age):
        
        if Pclass == 1:
            return 37
        elif Pclass == 2:
            return 29
        else:
            return 24
    else:
        return Age

In [ ]:
train['Age'] = train[['Age','Pclass']].apply(impute_age,axis=1)

In [ ]:
sns.heatmap(train.isnull(),yticklabels=False,cbar=False)

In [ ]:
sns.heatmap(train.isnull(),yticklabels=False,cbar=False,cmap='viridis')

In [ ]:
train.columns

In [ ]:
train.dropna(inplace=True)

In [ ]:
#Taking out more NAs and missing values

In [ ]:
#Machine learning can't take male or female so making new column 1/0

In [ ]:
#Dummies looks at column and gets dummy values

In [ ]:
pd.get_dummies(train['Sex'])

In [ ]:
#Problem with this.....Multi Collinearity....Predicting if not female male

In [ ]:
#One column predicts other. Feed both then predicts other.

In [ ]:
#This will drop the first column brining back only one.

In [ ]:
sex = pd.get_dummies(train['Sex'],drop_first=True)

In [ ]:
embark = pd.get_dummies(train['Embarked'],drop_first=True)

In [ ]:
embark.head()

In [ ]:
train = pd.concat([train,sex,embark],axis=1)

In [ ]:
#Axis = 1 adds as new column

In [ ]:
train.head(2)

In [ ]:
#New columns are indicator or dummy columns meaning we don't need others

In [ ]:
train.drop('PassengerId',axis=1,inplace=True)

In [ ]:
train.head()