In [ ]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
sb.set()

data = pd.read_csv("../input/../input/titanicdataset-traincsv/train.csv")
# data

# 1
print("the whole passenegers are- "+str(len(data.values)))

In [ ]:
# 2
count = data["Sex"].value_counts()
count.plot(kind="pie")
print("the males were more than females")

In [ ]:
# first way
sb.countplot(x="Survived" ,hue="Sex",data=data)
# females were survived more than males
plt.show()

# second way
sb.countplot(x="Sex",hue="Survived",data=data)
# men were died more than 400 people
# females were died below the 250 people
plt.show()

In [ ]:
sb.countplot(x="Survived",hue="Pclass",data=data)
# the pclass3 people were died more than other classes ticket

In [ ]:
plt.hist(data["Age"],bins="auto")
# most of the passengers's age range were between 18-30 yearsold

In [ ]:
pclass_count = data["Pclass"].value_counts()
pclass_count.plot(kind="bar")
# as you see most of the passengers were pclass3
# pclass2 were lowest percentage

In [ ]:
# we want to know about the range of the passengers's age 
# we seperate the ages via the Survived item
death_age = []
survived_age = []
d = [(x,death_age.append(y)) for x,y in zip(data["Survived"],data["Age"]) if x==0]
s = [(x,survived_age.append(y)) for x,y in zip(data["Survived"],data["Age"]) if x==1]


# plotting deathplot and survivedplot via the ages
plt.figure(figsize=(7,4),dpi=100)
plt.subplot(1,2,1)

plt.title("death".capitalize())
plt.xticks(range(0,70,10))
plt.hist(death_age,bins=40)

plt.subplot(1,2,2)
plt.hist(survived_age,bins=40)

plt.title("survived".capitalize())
plt.xticks(range(0,70,10))
plt.show()

print("the most passengers's age that died were 18-30 somehow")
print("the most passengers's age that survived were 22-35 somehow")

In [ ]:
counter_death = list(map(int,input("between what numbers do you want to count for dead people: ").split(",")))
x = 0
for i in death_age:
    if counter_death[0]<= i <=counter_death[1]:
        x += 1
print(x) # 18-30 years old : 191 people died


print(len(death_age)) # 549
# between 0-90 years old the count is 424 , we have nan element in the Age item in data
# in addition to them the whole count is 549 which 424 is the right answer