In [ ]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
titanic=pd.read_csv("../input/titanic_train.csv")

In [ ]:
titanic.head(10)

In [ ]:
del titanic["Name"] #bcz name variable isnt important thats why we remove this

In [ ]:
del titanic["PassengerId"] #same pid also del

In [ ]:
titanic.describe(include="all")

In [ ]:
titanic.info()

# missing value
"age" have nan value,
"cabin" have,
"embarked"have also

In [ ]:
titanic.columns

In [ ]:
plt.figure(figsize=(9,9))
titanic.boxplot(["Age","Parch","Fare"])

# outlier
"age" ,"parch", "fare" have many outlier

In [ ]:
titanic.head()

### variable identifiction 
  survived dependent variable 
  and remaining all are independent

## categorical variable
1 sex 

2 ticket (alpha_numeric variable)

3 cabin (alpha_numeric variable)

4 embarked

5 survived (numeric type)

6 pclass (numeric type)

# numeric/qualitative variable
 
 continuous :>
 
 1 fare
 
 2 age
 
 discrete :>
 
 1 sib sp
 
 2 parch

# univariate analyis

In [ ]:
titanic.columns

In [ ]:
titanic.nunique()  #show unique value in a every coloumn

In [ ]:
sns.distplot(titanic["Survived"])

In [ ]:
titanic.boxplot(column="Survived")

In [ ]:
# age have nan value

In [ ]:
titanic.hist(column="Age")

age varible showing like +ve skewed so thats why miss value fill by median (and many outlier in age variable)

In [ ]:
titanic.boxplot(column="Fare") #oputlier

###  age positve skewed

In [ ]:
titanic.hist(column="Fare")  #positive skewed

### such that type of people is more which have 0-100 fare amount

In [ ]:
pd.crosstab(titanic["Survived"],columns="count").plot(kind="bar") #survived count 0=549 more 1=342 less

### survived count means dead=549 , live=342

In [ ]:
titanic["Survived"].value_counts()

In [ ]:
titanic["Pclass"].value_counts()   #group of people is more in 3 pclass

In [ ]:
titanic["Sex"].value_counts()    # male > female

In [ ]:
titanic["SibSp"].value_counts()  # alone is more in sibsp

In [ ]:
titanic["Parch"].value_counts() #alone is more in parch

In [ ]:
titanic["Embarked"].value_counts() # people quantity s>c>q in Embarked

### plz chk
#survived count means dead=549 , live=342

#group of people is more in 3 pclass

@ male > female

#alone is more in sibsp

#alone is more in parch

#people quantity s>c>q in Embarked

# biavariate analyis

In [ ]:
plt.scatter(titanic["Age"],titanic["Fare"])   #no relation

In [ ]:
plt.scatter(titanic["Fare"],titanic["Age"]) #no relation 0-100 fare count high

In [ ]:
c=titanic.groupby(["Sex","Embarked"],axis=0)
c.size()                                                # sex and embarked relation

In [ ]:
c=titanic.groupby(["Sex","Survived"],axis=0)
c.size()                                                # survived ratio of gender [female survived more as compare to male]

In [ ]:
c=titanic.groupby(["Pclass","Survived"],axis=0)
c.size()                                                # survived ratio is high in Pclass 1 and less in pclass 3

In [ ]:
c=titanic.groupby(["Embarked","Survived"],axis=0)
c.size()      

#print("percentage c :", 93/75+93*100) 
#print("percentage q :", 30/47+30*100) 
#print("percentage s :", 217/427+217*100)                # survived and embarked relation

In [ ]:
c=(93/168)*100
q=30/77*100
s=217/644*100
print("survived percentage by embarked \n")
print("percentage c :", c) 
print("percentage q :", q) 
print("percentage s :", s)               #survived percentage by embarked c>q>s @c on top

In [ ]:
c=titanic.groupby(["Embarked","Sex"],axis=0)
c.size()                                                # sex and embarked relation

### importnt insights 

#survived ratio of gender [female survived more as compare to male]

#survived ratio is high in Pclass 1 and less in pclass 3

#survived percentage by embarked c>q>s @c on top

In [ ]:
crr=titanic.corr()

In [ ]:
sns.heatmap(crr,annot=True,cmap="RdBu_r")

In [ ]:
titanic.head()

In [ ]:
f=sns.FacetGrid(titanic,col="Survived")   # near 30 age group is more dead and live also more near by 30 age group
f.map(plt.hist, "Age")

In [ ]:
f=sns.FacetGrid(titanic,col="Pclass")
f.map(plt.hist, "Age")

In [ ]:
del titanic["Pclass"]

In [ ]:
t=pd.read_csv("titanic_train.csv")

In [ ]:
p=t["Pclass"]

In [ ]:
t2=pd.concat([titanic,p],axis=1)

In [ ]:
titanic.insert(loc=2,column="Pcl",value=p)

In [ ]:
titanic.head()

In [ ]:
#sns.pairplot(titanic)  not found good info from pairplot

In [ ]:
s=sns.FacetGrid(titanic,col="SibSp")    #live and dead ratio is high in sibsp alone(0)
s=s.map(plt.hist, "Survived")                         #but sibsp(1) live ratio is high as compare to dead

In [ ]:
s=sns.FacetGrid(titanic,col="Parch")    #live and dead ratio is high at the time of parch  is  alone(0)
s=s.map(plt.hist, "Survived")                         #but parch (1) live ratio is high as compare to dead

### sibsp & parch info

#live and dead ratio is high in sibsp alone(0)     #but sibsp(1) live ratio is high as compare to dead

 #live and dead ratio is high at the time of parch  is  alone(0)      #but parch (1) live ratio is high as compare to dead

In [ ]:
s=sns.FacetGrid(titanic,col="Survived",row="Sex")    #gender survived ratio
s=s.map(plt.hist, "Age")

In [ ]:
s=sns.FacetGrid(titanic,col="Embarked")    #gender survived ratio
s=s.map(plt.hist, "Fare")

# missing value treatment

(19% value nan value)fill nan value age with med. bcz age like a +ve skewed and some uppr  outlier also

In [ ]:
titanic["Age"]=titanic["Age"].fillna(titanic["Age"].median())   #age fill with med.

###  age miss value fill with med.

In [ ]:
titanic.info()

### cabin have too much missing value(77%above) so thats why i want to remove this variable

`and cabin dtype is categorical

In [ ]:
del titanic["Cabin"]

In [ ]:
titanic.head()

### fill nan value of embarked with mode

In [ ]:
titanic["Embarked"]=titanic["Embarked"].fillna(titanic["Embarked"].mode()[0])

In [ ]:
titanic.isnull().sum()

## outlier treat

In [ ]:
titanic.describe()

In [ ]:
iqr_age=titanic["Age"].quantile(0.75)-titanic["Age"].quantile(.25)

In [ ]:
uppr_age=titanic["Age"].quantile(0.75)+1.5*iqr_age

In [ ]:
lower_age=titanic["Age"].quantile(0.25)-1.5*iqr_age

In [ ]:
uppr_age

In [ ]:
lower_age

In [ ]:
upproutlier_age=titanic[(titanic["Age"]>uppr_age)]

In [ ]:
loweroutlier_age=titanic[(titanic["Age"]<lower_age)]

In [ ]:
upproutlier_age.head()  # these are natural outlier  so we can not remove this type of outlier

In [ ]:
loweroutlier_age.head() # these are also natural outlier

# data have no outlier bcz age can be big and small and in all  rst outlier variable same process implement

## all outlier are natural outlier so thats why we cannot treat

### create dummy variable for sex and embarked

### i think " ticket " also not imprtnt variable so we can remove this

In [ ]:
del titanic["Ticket"]

In [ ]:
cate=titanic.dtypes==np.object

In [ ]:
obj=titanic.columns[cate]

In [ ]:
obj

In [ ]:
dummy_dt=pd.DataFrame()

In [ ]:
for i in obj:
    dummy=pd.get_dummies(titanic[i],drop_first=True)
    dummy_dt=pd.concat([dummy_dt,dummy],axis=1)

In [ ]:
dummy_dt

In [ ]:
titanic2=pd.concat([titanic,dummy_dt],axis=1)

In [ ]:
titanic2

In [ ]:
del titanic2["Sex"]

In [ ]:
del titanic2["Embarked"]

In [ ]:
titanic2

In [ ]:
titanic2.info()

# one more method for quick eda please check

In [ ]:
from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
import pandas_profiling

In [ ]:
pandas_profiling.ProfileReport(titanic)