In [36]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['train_and_test2.csv']

In [40]:
data=pd.read_csv('../input/train_and_test2.csv')

In [41]:
data.columns=['Passengerid', 'Age', 'Fare', 'Sex', 'sibsp', 'zero', 'zero.1',
       'zero.2', 'zero.3', 'zero.4', 'zero.5', 'zero.6', 'Parch', 'zero.7',
       'zero.8', 'zero.9', 'zero.10', 'zero.11', 'zero.12', 'zero.13',
       'zero.14', 'Pclass', 'zero.15', 'zero.16', 'Embarked', 'zero.17',
       'zero.18', '2urvived']
data.drop(['Passengerid','zero', 'zero.1',
       'zero.2', 'zero.3', 'zero.4', 'zero.5', 'zero.6','zero.7',
       'zero.8', 'zero.9', 'zero.10', 'zero.11', 'zero.12', 'zero.13',
       'zero.14','zero.15', 'zero.16', 'zero.17',
       'zero.18'],axis=1,inplace=True)

In [42]:
data.columns=['age','fare','sex','sibsb','parch','pclass','embarked','survived']

In [43]:
data.dropna(inplace=True)
data.fillna('0.0')

       age      fare  sex  sibsb  parch  pclass  embarked  survived
0     22.0    7.2500    0      1      0       3       2.0         0
1     38.0   71.2833    1      1      0       1       0.0         1
2     26.0    7.9250    1      0      0       3       2.0         1
3     35.0   53.1000    1      1      0       1       2.0         1
4     35.0    8.0500    0      0      0       3       2.0         0
5     28.0    8.4583    0      0      0       3       1.0         0
6     54.0   51.8625    0      0      0       1       2.0         0
7      2.0   21.0750    0      3      1       3       2.0         0
8     27.0   11.1333    1      0      2       3       2.0         1
9     14.0   30.0708    1      1      0       2       0.0         1
10     4.0   16.7000    1      1      1       3       2.0         1
11    58.0   26.5500    1      0      0       1       2.0         1
12    20.0    8.0500    0      0      0       3       2.0         0
13    39.0   31.2750    0      1      5       3       2.0         0
14    14.0    7.8542    1      0      0       3       2.0         0
15    55.0   16.0000    1      0      0       2       2.0         1
16     2.0   29.1250    0      4      1       3       1.0         0
17    28.0   13.0000    0      0      0       2       2.0         1
18    31.0   18.0000    1      1      0       3       2.0         0
19    28.0    7.2250    1      0      0       3       0.0         1
20    35.0   26.0000    0      0      0       2       2.0         0
21    34.0   13.0000    0      0      0       2       2.0         1
22    15.0    8.0292    1      0      0       3       1.0         1
23    28.0   35.5000    0      0      0       1       2.0         1
24     8.0   21.0750    1      3      1       3       2.0         0
25    38.0   31.3875    1      1      5       3       2.0         1
26    28.0    7.2250    0      0      0       3       0.0         0
27    19.0  263.0000    0      3      2       1       2.0         0
28    28.0    7.8792    1      0      0       3       1.0         1
29    28.0    7.8958    0      0      0       3       2.0         0
...    ...       ...  ...    ...    ...     ...       ...       ...
1279  21.0    7.7500    0      0      0       3       1.0         0
1280   6.0   21.0750    0      3      1       3       2.0         0
1281  23.0   93.5000    0      0      0       1       2.0         0
1282  51.0   39.4000    1      0      1       1       2.0         0
1283  13.0   20.2500    0      0      2       3       2.0         0
1284  47.0   10.5000    0      0      0       2       2.0         0
1285  29.0   22.0250    0      3      1       3       2.0         0
1286  18.0   60.0000    1      1      0       1       2.0         0
1287  24.0    7.2500    0      0      0       3       1.0         0
1288  48.0   79.2000    1      1      1       1       0.0         0
1289  22.0    7.7750    0      0      0       3       2.0         0
1290  31.0    7.7333    0      0      0       3       1.0         0
1291  30.0  164.8667    1      0      0       1       2.0         0
1292  38.0   21.0000    0      1      0       2       2.0         0
1293  22.0   59.4000    1      0      1       1       0.0         0
1294  17.0   47.1000    0      0      0       1       2.0         0
1295  43.0   27.7208    0      1      0       1       0.0         0
1296  20.0   13.8625    0      0      0       2       0.0         0
1297  23.0   10.5000    0      1      0       2       2.0         0
1298  50.0  211.5000    0      1      1       1       0.0         0
1299  28.0    7.7208    1      0      0       3       1.0         0
1300   3.0   13.7750    1      1      1       3       2.0         0
1301  28.0    7.7500    1      0      0       3       1.0         0
1302  37.0   90.0000    1      1      0       1       1.0         0
1303  28.0    7.7750    1      0      0       3       2.0         0
1304  28.0    8.0500    0      0      0       3       2.0         0
1305  39.0  108.9000    1      0      0       1       0.0         0
1306  38.5    7.2500    0      0      0       3       2.0         0
1307  28.0    8.0500    0      0      0       3       2.0         0
1308  28.0   22.3583    0      1      1       3       0.0         0

[1307 rows x 8 columns]

In [44]:
data.isnull().sum()

age         0
fare        0
sex         0
sibsb       0
parch       0
pclass      0
embarked    0
survived    0
dtype: int64

In [45]:
data.head()

    age     fare  sex  sibsb  parch  pclass  embarked  survived
0  22.0   7.2500    0      1      0       3       2.0         0
1  38.0  71.2833    1      1      0       1       0.0         1
2  26.0   7.9250    1      0      0       3       2.0         1
3  35.0  53.1000    1      1      0       1       2.0         1
4  35.0   8.0500    0      0      0       3       2.0         0

In [47]:
y=data.survived
x=data.drop(['survived'],axis=1)

In [48]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [49]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)
print("test accuracy {}".format(lr.score(x_test,y_test)))

test accuracy 0.7900763358778626

/opt/conda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)