In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
df=pd.read_csv("/kaggle/input/titanic/train.csv")

In [ ]:
df

In [ ]:
UVS=df['Survived'].unique()

Q1.count number of unique values in "Survived" coulmn.

In [ ]:
UVS

In [ ]:
Male=df['Sex'].value_counts()

Q.2 count the number of male and female

In [ ]:
Male

In [ ]:
Female=df['Sex'].value_counts()

In [ ]:
Female

In [ ]:
last5_row=df.iloc[883:891]

Q3. Show the last 8 rows of the dataset

In [ ]:
last5_row

In [ ]:
df

In [ ]:
Age1= df["Age"]

In [ ]:
Age1

In [ ]:
max_value = Age1.max()

In [ ]:
max_value

In [ ]:
Age1

In [ ]:
df2=df[df['Age']>30].value_counts()

Q4. Count the number of people who have age greater than 30

In [ ]:
df2

In [ ]:
Age1=df[df['Age']>30]

In [ ]:
Age1

In [ ]:
df.info()

In [ ]:
df.iloc[:,10:21]

Q.Show the number of columns from 10-20