 # **Introduction**
 
 
 In this notebook  , I'll provide a brief introduction to the dataset I've selected for analysis
 
 This data set contains information
about 10,000 movies collected from
The Movie Database (TMDb),
including user ratings and revenue.

[www.kaggle.com/tmdb/tmdb-movie-metadata](http://)


● Certain columns, like ‘cast’ and ‘genres’, contain multiple values separated by pipe (|) characters.

● There are some odd characters in the ‘cast’ column

●The final two columns ending with adj show the budget and revenue of the associated movie in terms of 2010 dollars, accounting for inflation over time.
 


Here's some of questions which  i asked based on Dataset

 
1. What is the average runtime of all movies?
2. Which are the successfull genres?
3. Which movie had the highest and lowest budget?
3. What is the average budget of the movie?

In [ ]:
#import libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import csv

In [ ]:
#read our data using pandas 
data =  pd.read_csv("../input/tmdb-movie-metadata/tmdb_5000_movies.csv")
#showing head of our dataset
data.head()

# Wrangling the data


Data wrangling is the process of gathering, selecting, and transforming data to answer an analytical question.

In [ ]:
#detailed information about dataset
data.info()

In [ ]:
#lenght of our data
print(len(data))

In [ ]:
#describe our data
data.describe()

In [ ]:
#columns names
columns = data.columns
#print(columns)

# Cleaning our data

first detect which columns is not important for me to delete it from our original data

In [ ]:
#deleted columns 
deleted_columns = [ 'id', 'popularity', 'homepage', 'keywords', 'tagline', 'overview', 'production_companies', 'vote_average']
#drop it from our data
data.drop(deleted_columns,axis = 1 ,inplace = True)

In [ ]:
data.info()

In [ ]:
data.head()

In [ ]:
#removing nan object  or  0 
columns = ['budget', 'revenue']
data[columns] = data[columns].replace(0, np.NaN)
data.dropna(subset = columns, inplace = True)
rows, col = data.shape
print(rows,col)

# Exploratory Data Analysis¶


We will now compute statistics and create visualizations with the goal of addressing the research questions that we posed in the Introduction section.

# **Q1** : 1. What is the average runtime of all movies?

In [ ]:
# Average runtime of movies
data['runtime'].mean()

In [ ]:
#plot relation between runtime and budget
plt.title("Relation between Runtime and N.of movies")
plt.xlabel("runtime of movies ")
plt.ylabel("number of movies ")
plt.hist(data["runtime"],bins= 30,color="y" )
plt.show()

In [ ]:
#plot relation between runtime and budget
plt.title("Relation Between Runtime and Budget")
plt.xlabel("runtime")
plt.ylabel("budget ")
plt.scatter(data["runtime"],data["budget"], alpha=0.3,color = "g")
plt.show()

# **Q2** : 2. Which are the successfull genres?

In [ ]:
#showing types of our movies 
print(data.iloc[:,1].values)

In [ ]:
count = pd.Series(data['genres'].str.cat(sep = '|').split('|')).value_counts(ascending = False)
count

In [ ]:
# Initialize the plot
diagram = count[:10].plot.bar(fontsize = 6)
# Set a title
diagram.set(title = 'Top Genres')
# x-label and y-label
diagram.set_xlabel('Type of genres')
diagram.set_ylabel('Number of Movies')
# Show the plot
plt.show()

Darma is highest number of movies and it is successful genres

# **Q3**  : 3. Which movie had the highest and lowest budget?

In [ ]:
# highest budget
x = data.loc[data['budget'].idxmax()]
print(x)
print("======================================")
print(x["budget"])
print("======================================")
print(x["title"])

In [ ]:
#Lowest budget 
y=data.loc[data['budget'].idxmin()]
print(y)
print("======================================")
print(y ["budget"])
print("======================================")
print(y["title"])

# **Q4:**  What is the average budget of the movie?

In [ ]:
#mean of our budget data
budget_mean = data.iloc[:,0].mean()
print(budget_mean)

In [ ]:
#plot relation between budget and revenue   
revenue = data.iloc [:,6].values
budget =  data.iloc[:,0].values 
plt.title("Relation between Budget and Revenue ")
plt.xlabel("revenue")
plt.ylabel("budget")
plt.scatter(revenue,budget , color = "r" )