In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt 
import seaborn as sns
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

In [ ]:
bitcoin_data =pd.read_csv("../input/bitstampUSD_1-min_data_2012-01-01_to_2018-11-11.csv")

In [ ]:
bitcoin_data.info() #data information

In [ ]:
bitcoin_data.describe() #numeric value

In [ ]:
bitcoin_data.columns

In [ ]:
bitcoin_data.head() #default first 5

In [ ]:
bitcoin_data.tail()

In [ ]:
bitcoin_data.corr()

In [ ]:
#correlation map 
f,ax = plt.subplots(figsize=(10,10))
sns.heatmap(bitcoin_data.corr(),annot=True,linewidths=4,fmt=".1f",ax=ax)
plt.show()

In [ ]:
bitcoin_data.isnull

In [ ]:
#line plot
bitcoin_data.Low.plot(kind="line",color='r',label="low",linewidth=1.5,alpha=0.5,grid=True,linestyle=":")
bitcoin_data.High.plot(kind="line",color="b",label="high",linewidth=1,alpha=0.5,grid=True,linestyle="-")
plt.legend(loc = "upper right")
plt.xlabel("x axis")
plt.ylabel("y axis")
plt.title("line plot")
plt.show()

In [ ]:
#scatter
# x= low, y=high
bitcoin_data.plot(kind="scatter",x="Low",y="High",alpha=0.8,color="r")
plt.xlabel("low")
plt.ylabel("high")
plt.show()

In [ ]:
# Histogram
# bins = number of bar in figure
#data.Speed.plot(kind = 'hist',bins = 50,figsize = (12,12))
bitcoin_data.Close.plot(kind = "hist",bins = 10,orientation="horizontal",figsize=(10,10)) #horizantal hist
plt.show()
bitcoin_data.Close.plot(kind="hist",bins=16,figsize=(10,10))
plt.show()

In [ ]:
#clf clean plot 
bitcoin_data.High.plot(kind="hist",bins = 40)
plt.clf() 
#we cannot plot

In [ ]:

series =bitcoin_data["High"] #data["High"] = series
print(type(series))
data_frame = bitcoin_data[["High"]] #data[["High"]] = data frame
print(type(data_frame))

In [ ]:
x =bitcoin_data["High"]>300000
print(x)

In [ ]:
bitcoin_data[np.logical_and(bitcoin_data["Open"]>290000 ,bitcoin_data["Close"]<300000)]

In [ ]:
lis=[1,2,3,4,5]
for i in lis:
     print('i is :',i)
        
print('')   
# Enumerate index and value of list
# index : value = 0:1, 1:2, 2:3, 3:4, 4:5
for index,value in enumerate(lis):
    print(index," :",value)
print('') 
# We can use for loop to achive key and value of dictionary. We learnt key and value at dictionary part.
dicto={'Turkey':'Ankara','spain':'madrid','canada':'toronto'}
for key,value in dicto.items():
        print(key,":",value)
print("")      
# For pandas we can achieve index and value
for index,value in bitcoin_data[['High']][0:1].iterrows():  
    print(key,":",value)

In [ ]:
#tuble: sequence of immutable python objects.
#cant modify values
#tuple uses paranthesis like tuple = (1,2,3)
#unpack tuple into several variables like a,b,c = tuple

def tuple_x():
    """ return defined t tuble"""
    t =(1,2,3)
    return t 
a,b,c= tuple_x()
print(a,b,c)

In [ ]:
#Scope
#What we need to know about scope:
# global: defined main body in script
# local: defined in a function
#* built in scope: names in predefined built in scope module such as print, len
x =2 
def f():
    x =3
    return x
print(x) #x is global
print(f()) #x is local

In [ ]:
# What if there is no local scope
x=4
def f ():
    y=2*x  #x is not local spoce 
    return y 
print(f())   # it uses global scope x
# First local scopesearched, then global scope searched, if two of them cannot be found lastly built in scope searched.

In [ ]:
# How can we learn what is built in scope
import builtins
dir(builtins)

In [ ]:
#nested function: inside to funtion 
def squared():
    """return square of value """
    def add():
        """ return add to  2  local value"""
        x=2
        z=4
        y=x+z
        return y 
    return add()**2
print(squared())

<a id="19"></a><br>
### DEFAULT and FLEXIBLE ARGUMENTS
*  default argument def f(a,b=1) b=1 default argument
* flexible argument def f(*args) """  *args can be one or more """
* another flexible argument def f(**kwargs) """ **kwargs is dictionary"""

In [ ]:
#default argment
def f(a,b=2,c=3):
    y = a + b + c
    return y 

print(f(5))
    # what if we want to change default arguments
print(f(5,4,6))

In [ ]:
#flexible argument *args
def f(*args) :
    for i in args :
        print(i)
f(1)
print("")
f(1,23,5)

#flexible argument **kwargs
def f(**kwargs):
    """return key,value on dictionary"""
    for index,value in kwargs.items():
        print(index,":",value)
f(country = "spain",capital ="madrid",population = 1478522)

In [ ]:
#lambda funtion :faster function
square = lambda x :x**2
print(square(5))
total=lambda x,y,z : x+y+z
print(total(1,2,3))

In [ ]:
# anonymous function : it like lambda but can be more then one argument
number=[1,2,3,4]
y =map(lambda x :x**3,number)
print(list(y))

ITERATORS

    iterable is an object that can return an iterator
    iterable: an object with an associated iter() method
    example: list, strings and dictionaries
    iterator: produces next value with next() method

In [ ]:
#iteration
name="rihanna"
it =iter(name)
print(next(it)) #first /next iteration
print(*it) #remaning iteration

In [ ]:
#zip():zip list
list1=[1,2,3,4]
list2=[7,8,9,6]
z=zip(list1,list2) 
print(z)
z_list=list(z) #convert z to list(z_list)
print(z_list)

In [ ]:
un_zip =zip(*z_list)
ulist1,ulist2=list(un_zip) #return to unzip yo tuble
print(ulist1)
print(ulist2)
print(type(ulist1))

In [ ]:
#list comperhension:collapse for loops for building lists into a single line 
#ex: num1 = [1,2,3] and we want to make it num2 = [2,3,4]. This can be done with for loop. 
#However it is unnecessarily long. We can make it one line code that is list comprehension
num1=[1,2,3]
num2=[ i+1  for i in num1]
print(num2)

#[i + 1 for i in num1 ]: list of comprehension
#i +1: list comprehension syntax
#for i in num1: for loop syntax
#i: iterator
#num1: iterable object

In [ ]:
# Conditionals on iterable
num1=[7,5,6]
num2 = [i**2 if i==5  else i-7 if i==7 else i+1 for i in num1]
print (num2)
nu=[9,10,4]
nu2 =[  i+5 if i<5 else i+1 if i<10  else i  for i in nu]
print(nu2)

In [ ]:
# lets classify bitcoin  whether they have high or low speed. Our threshold is average speed
threshold=sum(bitcoin_data.Open)/len(bitcoin_data.Open)
bitcoin_data["Open_Level"] = [" high" if i >threshold else "low" for i in bitcoin_data.Open]
bitcoin_data.loc[:10,["Open_Level","Open"]]  #we will learn loc more detailed later

<a id="18"></a>Cleaning Data  <br>
<br>DIAGNOSE DATA for CLEANING
<br>we need to diagnose and clean data before exploring
<br>why need to  cleaning :missing data,diffrent  language,upper-lower case or space between word
<br>We will use head, tail, columns, shape and info methods to diagnose data

In [ ]:
data=pd.read_csv("../input/bitstampUSD_1-min_data_2012-01-01_to_2018-11-11.csv")

In [ ]:
data.head() #first 5 rows

In [ ]:
data.tail() #last 5 rows

In [ ]:
data.columns

In [ ]:
data.shape #shape gives number of rows and columns in a tuple

In [ ]:
data.info

<a id="18"></a> <br>
### EXPLORATORY DATA ANALYSIS
value_counts(): Frequency counts
<br>outliers: the value that is considerably higher or lower from rest of the data
* Lets say value at 75% is Q3 and value at 25% is Q1. 
* Outlier are smaller than Q1 - 1.5(Q3-Q1) and bigger than Q3 + 1.5(Q3-Q1). (Q3-Q1) = IQR
<br>We will use describe() method. Describe method includes:
* count: number of entries
* mean: average of entries
* std: standart deviation
* min: minimum entry
* 25%: first quantile
* 50%: median or second quantile
* 75%: third quantile
* max: maximum entry

<br> What is quantile?

* 1,4,5,6,8,9,11,12,13,14,15,16,17
* The median is the number that is in **middle** of the sequence. In this case it would be 11.

* The lower quartile is the median in between the smallest number and the median i.e. in between 1 and 11, which is 6.
* The upper quartile, you find the median between the median and the largest number i.e. between 11 and 17, which will be 14 according to the question above.

In [ ]:
print(data.Open.value_counts(dropna=True))

In [ ]:
data.describe()

<a id="19"></a> <br>
### VISUAL EXPLORATORY DATA ANALYSIS
* Box plots: visualize basic statistics like outliers, min/max or quantiles

In [ ]:
data.boxplot(column="Open",by="High")

<a id="19"></a><br>
### TIDY DATA
* We tidy data with melt(). Describing melt is confusing. Therefore lets make example to understand it.

In [ ]:
data_new =data.head()
data_new

In [ ]:
# lets melt
# id_vars = what we do not wish to melt
# value_vars = what we want to melt
melted=pd.melt(frame=data_new,id_vars="Close",value_vars=["High","Low"])
melted

<a id="19"></a><br>
### PIVOTING DATA
* Reverse of melting.

In [ ]:
# Index is name
# I want to make that columns are variable
# Finally values in columns are value
melted.pivot(index='Close',columns= 'variable',values= 'value')

<a id="19"></a><br>
### CONCATENATING DATA
* We can concatenate two dataframe

In [ ]:
#firstl create 2 frame 
data1=data.head()
data2=data.tail()
cont_data_row=pd.concat([data1,data2],axis=0,ignore_index=True) #axis=0 add datadrame in  rows
cont_data_row

In [ ]:
data1=data["High"].head()
data2=data["Low"].head()
cont_data_col=pd.concat([data1,data2],axis=1,ignore_index=True)
cont_data_col

<a id="19"></a><br>
### DATA TYPES
<br>There are 5 basic data types: object(string),booleab, integer, float and categorical.
<br>We can make conversion data types like from str to categorical or from int to float
<br>Why is category important:
*    make dataframe smaller in memory
 *   can be utilized for anlaysis especially for sklear(we will learn later)

In [ ]:
data.dtypes

In [ ]:
# lets convert int to categorical and  float.
data['Timestamp']=data['Timestamp'].astype("category")
data["Volume_(BTC)"]=data["Volume_(BTC)"].astype("int")

In [ ]:
data.dtypes
#as you can Timestamp convert int to categorry
#Volume_BTc convert from float to int

<a id="19"></a><br>
### MISSING DATA and TESTING WITH ASSERT
<br>If we encounter with missing data, what we can do:
*     leave as is
*     drop them with dropna()
*     fill missing value with fillna()
*     fill missing values with test statistics like mean
*     Assert statement: check that you can turn on or turn off when you are done with your testing of the program

In [ ]:
data.info()

In [ ]:
data["Timestamp"].value_counts(dropna=False)

In [ ]:
data1=data
data1["Open"].dropna(inplace=True) # inplace = True means we do not assign it to new variable. Changes automatically assigned to data

In [ ]:
# Lets check with assert statement
# Assert statement:
assert 1==1 # return nothing because it is true

In [ ]:
# In order to run all code, we need to make this line comment
#assert 1==2 # return error because it is false

In [ ]:
assert data['Open'].notnull().all() #returns nothingg becasue we drop non value

In [ ]:
data['Open'].fillna('empty',inplace=True)

In [ ]:
assert data['Open'].notnull().all() #returns nothing beacuse we do not not have nan values

In [ ]:


# # With assert statement we can check a lot of thing. For example
# assert data.columns[1] == 'Open'
# assert data.Open.dtypes == np.int

<a id="20"></a><br>
# PANDAS
### REVİEW of PANDAS
<br>As you notice, I do not give all idea in a same time. Although, we learn some basics of pandas, we will go deeper in pandas.
*     single column = series
*     NaN = not a number
*     dataframe.values = numpy

### BUILDING DATA FRAMES FROM SCRATCH
*   We can build data frames from csv as we did earlier.
*   Also we can build dataframe from dictionaries
   *   zip() method: This function returns a list of tuples, where the i-th tuple contains the i-th element from each of the argument sequences or iterables.
*    Adding new column
*   Broadcasting: Create new column and assign a value to entire column

In [ ]:
#data frame from dictionary
country=["spain","france"]
population=["12","15"]
list_label=["country","population"]
list_col=[country,population]
zipped=list(zip(list_label,list_col))
data_dict=dict(zipped)
df = pd.DataFrame(data_dict)
df

In [ ]:
#add news columns
df["capital"]=["madrid","paris"]
df

In [ ]:
#broadcasting
df["incame"]=0 #broadcast entire colunmn
df

<a id="19"></a><br>
### VISUAL EXPLORATORY DATA ANALYSIS
*    Plot
*     Subplot
*     Histogram:
*         bins: number of bins
*         range(tuble): min and max values of bins
*         normed(boolean): normalize or not
*         cumulative(boolean): compute cumulative distribution

In [ ]:
#ploting all data
data1=data.loc[1:,["Open","Low","High"]]
data1.plot()
#it is confused

In [ ]:
#subplot
data1.plot(subplots=True)
plt.show()

In [ ]:
#scater
data1.plot(kind="scatter",x="Low",y="High")
plt.show()

In [ ]:
#hist
data1.plot(kind="hist",y="Low",bins=60,range=(2500,3000000),normed= True)

In [ ]:
# histogram subplot with non cumulative and cumulative
fig,axes=plt.subplots(nrows=2,ncols=1)
data1.plot(kind = "hist", y="Low",bins=50 ,range=(25000,3000000),normed=True, ax=axes[0])
data1.plot(kind ="hist",y="Low",bins=50, range=(25000,3000000),normed=True,ax=axes[0],cumulative=True)
plt.savefig("graph.png")
plt.show()

<a id="19"></a><br>
### STATISTICAL EXPLORATORY DATA ANALYSIS
<br>I already explained it at previous parts. However lets look at one more time.
*  count: number of entries
* mean: average of entries
*  std: standart deviation
*  min: minimum entry
* 25%: first quantile
*  50%: median or second quantile
*  75%: third quantile
*  max: maximum entry

In [ ]:
data.describe()

<a id="17"></a><br>
### INDEXING PANDAS TIME SERIES
*   datetime = object
*    parse_dates(boolean): Transform date to ISO 8601 (yyyy-mm-dd hh:mm:ss ) format

In [ ]:
time_list=["2018-02-10","2018-03-04"]
print(type(time_list)) #let see string
# however we want it to be datetime object
datetime_object=pd.to_datetime(time_list)
print(type(datetime_object))

In [ ]:
# close warning
import warnings
warnings.filterwarnings("ignore")

# In order to practice lets take head of bitcoin data and add it a time list
data2=data.head()
date_list =["2018-01-16","2018-02-19","2018-03-09","2018-04-17","2018-09-19"]
datetime_object=pd.to_datetime(date_list)
data2["date"]=datetime_object
# lets make date as index
data2=data2.set_index("date")
data2

In [ ]:
#now we can select according to our index
print(data2.loc["2018-02-19"])
print(data2.loc["2018-01-01":"2018-06-01"])

<a id="16"></a><br>
### RESAMPLING PANDAS TIME SERIES
*    Resampling: statistical method over different time intervals
*       Needs string to specify frequency like "M" = month or "A" = year
*     Downsampling: reduce date time rows to slower frequency like from daily to weekly
*     Upsampling: increase date time rows to faster frequency like from daily to hourly
*     Interpolate: Interpolate values according to different methods like ‘linear’, ‘time’ or index’
*        https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.interpolate.html

In [ ]:
data2.resample("A").mean() #We will use data2 that we create at previous part

In [ ]:
# Lets resample with month
data2.resample("M").mean()

In [ ]:
# In real life (data is real. Not created from us like data2) we can solve this problem with interpolate
# We can interpolete from first value
data2.resample("M").first().interpolate("linear")

In [ ]:
# Or we can interpolate with mean()
data2.resample("M").mean().interpolate("linear")

<a id="19"></a><br>
# MANIPULATING DATA FRAMES WITH PANDAS

### INDEXING DATA FRAMES
*    Indexing using square brackets
*     Using column attribute and row label
*     Using loc accessor
*     Selecting only some columns

In [ ]:
 #data =pd.read_csv("../input/bitflyerJPY_1-min_data_2017-07-04_to_2018-06-27.csv"
#data=data.set_index("#")
#data.head()

In [ ]:
#indexing using square brackets
data["Open"][1]

In [ ]:
# using column attribute and row label
data.Open[1]

In [ ]:
# using loc accessor
data.loc[1,["Open"]]

In [ ]:
data[["Open","Close"]]

<a id="19"></a><br>
### SLICING DATA FRAME
*    Difference between selecting columns
*         Series and data frames
*     Slicing and indexing series
*     Reverse slicing
*     From something to end

In [ ]:
# Difference between selecting columns: series and dataframes
print(type(data["Open"])) #series
print(type(data[["Open"]])) #dataframes

In [ ]:
# Slicing and indexing series
data.loc[1:10,"Open":"Close"]  #10 and "Close" are inclusive

In [ ]:
# Reverse slicing 
data.loc[10:1:-1,"Open":"Close"] #

In [ ]:
# From something to end
data.loc[1:10,"Low":]

<a id="19"></a><br>
### FILTERING DATA FRAMES
* Creating boolean series Combining filters Filtering column based others

In [ ]:
#creating booelan series
boolen =data.Open >300000
data[boolen]

In [ ]:
#combining filters
first_filter =data.Open<1500000
seconde_filte=data.Close>300000
data[first_filter & seconde_filte]

In [ ]:
# Filtering column based others
data.Open[data.Low<3000000]

<a id="20"></a><br>
### TRANSFORMING DATA
*    Plain python functions
*     Lambda function: to apply arbitrary python function to every element
*     Defining column using other columns

In [ ]:
#plain function
def div(n):
    return n/2
data.Timestamp.apply(div)

In [ ]:
# Or we can use lambda function
data.Timestamp.apply(lambda x : x/2)

In [ ]:
# Defining column using other columns
data["total_difference"]= data.Close -data.Open
data.head()

<a id ="19"></a><br>
### INDEX OBJECTS AND LABELED DATA
* index: sequence of label

In [ ]:
# our index name is this:a
#data.index.name="#"
print(data.index.name)
# lets change it
data.index.name = "index_name"
data

In [ ]:
# Overwrite index
# if we want to modify index we need to change all of them.
data.head()
# first copy of our data to data4 then change index 
data4 = data.copy()
# lets make index start from 100. It is not remarkable change but it is just example
#data4.index = range(100,150,3)
data4.head()

In [ ]:
# We can make one of the column as index. I actually did it at the beginning of manipulating data 
# data= data.set_index("#")
# also you can use 
# data.index = data["#"]

<a id ="19"></a><br>
### HIERARCHICAL INDEXING
*    Setting indexing

In [ ]:
#lets read dara frame one more time to start from beginning
data =pd.read_csv("../input/bitstampUSD_1-min_data_2012-01-01_to_2018-11-11.csv")
data.head()

In [ ]:
# Setting index : type 1 is outer type 2 is inner index
data1=data.set_index(["Open","Close"])
data1.head(100)
#data1.loc["Low","High"] # howw to use indexes

<a id="20"></a><br>
## PIVOTING DATA FRAMES
*    pivoting: reshape tool

In [ ]:
dic = {"treament":["A","A","B","B"],"gender":["F","M","F","M"],"response":[12,30,45,68],"age":[20,49,18,69]}
df = pd.DataFrame(dic)
df

In [ ]:
#pivoting
df.pivot(index="treament",columns= "gender",values="age"),

<a id="30"></a><br>
### STACKING and UNSTACKING DATAFRAME
* deal with multi label indexes
* level: position of unstacked index
* swaplevel: change inner and outer level index position

In [ ]:
df1=df.set_index(["treament","gender"])
df1

In [ ]:
# lets unstack it
#level determines indexes
df1.unstack(level=0)

In [ ]:
df1.unstack(level=1)

In [ ]:
# change inner and outer level index position
df1.swaplevel(0,1)
df1

<a id="20"></a><br>
### MELTING DATA FRAMES
*   Reverse of pivoting

In [ ]:
df

In [ ]:
#df.pivot(index="treament",columns="gender",values="age")
pd.melt(df,id_vars="treament",value_vars=["age","response"])

<a id="42"></a> <br>
### CATEGORICALS AND GROUPBY

In [ ]:
#we will use df
df

In [ ]:
# according to treatment take means of other features
df.groupby("treament").mean()   
# there are other methods like sum, std,max or min

In [ ]:
# we can only choose one of the feature
df.groupby("treament").age.max()

In [ ]:
# Or we can choose multiple features
df.groupby("treament")[["age","response"]].min()

In [ ]:
df.info()
# as you can see gender is object
# However if we use groupby, we can convert it categorical data. 
# Because categorical data uses less memory, speed up operations like groupby
df["gender"] = df["gender"].astype("category")
df["treament"] = df["treament"].astype("category")
df["response"]= df["response"].astype("float")
df.info()