In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

### Importing required libraries

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

### Reading data into a dataframe

In [ ]:
df_twlo = pd.read_csv('../input/twilio-stock-price-twlo20162021/TWLO_stock.csv')

In [ ]:
df_twlo.head()

### Reading stock data
- date -> Date of trading 
- open -> opening price for single stock in USD for the given day
- high -> highest price for single stock in USD for the given day
- close -> closing value for single stock in USD for the given day
- volume -> total stocks (count/NAV)

In [ ]:
df_twlo.columns

### Renaming the columns for better readibility

In [ ]:
df_twlo_renamed = df_twlo.rename(columns = {'1. open':'open', '2. high':'high', '3. low':'low','4. close':'close','5. volume':'volume'}, inplace = False)

In [ ]:
df_twlo_renamed.head()

### Checking the data type for the columns

In [ ]:
df_twlo_renamed.dtypes

### Checking shape of the dataset (row, col)

In [ ]:
df_twlo.shape

### Checking null values
- No null values found

In [ ]:
df_twlo_renamed.isnull().sum()/df_twlo_renamed.shape[0]*100

### Checking the statistical params

In [ ]:
df_twlo_renamed.describe()

### Converting Date from object to datetime

In [ ]:
df_twlo_renamed['date'] = pd.to_datetime(df_twlo_renamed['date'], utc=True)

In [ ]:
df_twlo_renamed.dtypes

In [ ]:
df_twlo_renamed.tail()

In [ ]:
sns.lineplot(x=df_twlo_renamed.date, y=df_twlo_renamed.close)
plt.show()

``` Insight 01 - stock price spiked post pandemic hit (around 2020)```

In [ ]:
names = ['open', 'close', 'high', 'low']
fig = plt.figure(figsize=(14,22))

a = 2  # number of rows
b = 4 # number of columns
c = 1  # initialize plot counter

for i in names:
    plt.subplot(a, b, c)
    plt.title('{} displot'.format(i))
    plt.xlabel(i)
    sns.distplot(df_twlo_renamed[i])
    c = c + 1
    
    plt.subplot(a,b,c)
    plt.title('{} boxplot'.format(i))
    plt.xlabel(i)
    plt.boxplot(x=df_twlo_renamed[i])
    c = c + 1
plt.show()