## Uber Drive - Solved
Instructions:

For all questions in which the dataframe is used without dropping na, row number-1155 should be included.
For Q6 :- Output should be boolean only.
For Q9 :- Outcome will contain only numerical column.
For Q11 :- You need to print the unique destination place names in this and not the count.
For Q15,16 :- Popular: It is the place that is visited the most.
For Q17 :- Print the most frequent route taken by Uber drivers after dropping null values (Route= combination of START & END points present in the Data set). *Note: Only the top most value is expected
For Q19 :- You have to plot total/sum miles per purpose.
For Q21 :- You can make a countplot or barplot.
For Q22 :- Out of the category of trips, you need to find percentage wise how many are business and how many are personal on the basis of miles per category.
For all questions after 10th, Please only use the data specified in the note given just below the question
You need to add answers in the same file i.e. PDS_UberDriveProject_Questions.ipynb' and rename that file as 'Name_Date.ipynb'.You can mention the date on which you will be uploading/submitting the file.For e.g. if you plan to submit your assignment on 31-March, you can rename the file as 'STUDENTNAME_31-Mar-2020'

This was performed as part of an assignment.
Hope it helps some one to practice the same.
Give these simple questions a try then look for the answers.
You can find the dataset here https://www.kaggle.com/prasan7/uber-drive-dataset

Import the dataset and Load the dataset. Load the necessary libraries.

In [ ]:
#loading libraries & the dataset

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
uber_data = pd.read_csv('../input/uber-drive-dataset/uberdrive.csv')

Q1. Show the last 10 records of the dataset. (2 point)

In [ ]:
# Showing last ten records for the dataset

uber_data.tail(10)

Q2. Show the first 10 records of the dataset. (2 points)

In [ ]:
# showing first ten records of the dataset

uber_data.head(10)

Q3. Show the dimension of the dataset. (2 points)

In [ ]:
# Dimensions

uber_data.shape

Q4. Show the size of the dataset. (2 points)

In [ ]:
#Size

uber_data.size

Q5. Print the information about all the variables of the data set.

In [ ]:
#Information about all the variables

uber_data.info()

Q6. Check for missing values. (2 points)

In [ ]:
# Checking for Missing Values in the original dataset(Outplut in boolean only)

uber_data.isna()

# True indicates there are missing values in the data

Q7. How many missing values are present? (2 points)

In [ ]:
# Sum of those missing values in the original dataset

uber_data.isna().sum()

Q8. Get the initial data (name it 'df') with dropping the NA values.

In [ ]:
# Dropping the missing values and naming the dataset as 'df'

df = uber_data.dropna()

Q9. Get the summary of the original data (before dropping the 'na' values).

In [ ]:
# Summary of original data "uber_data"

uber_data.describe()

Q10. Check the information of the new dataframe.

In [ ]:
#Information of the new database "df"

df.info()

Q11. Get the unique start destinations.
Note: This question is based on the dataframe with no 'na' values in the 'START' variable.

In [ ]:
# Unique values in the Start column for the data with no missing values 'df'

df['START*'].unique()

Q12. What is the total number of unique start destinations?
Note: This question is based on the dataframe with no 'na' values in the 'START' variable.

In [ ]:
# Sum of unique values in the Start column for the data with no missing values 'df'

df['START*'].nunique()

Q13. Print the total number of unique stop destinations.
Note: This question is based on the dataframe with no 'na' values in the 'STOP' variable.

In [ ]:
# Printing total number of unique stop destinations for the data with no missing values 'df'

print(df['STOP*'].nunique())

Q14. Print all the Uber trips that has the starting point of San Francisco. 
Note: Use the original dataframe without dropping the 'na' values.

In [ ]:
# Printing all the trips that is started from the point of San Francisco for the original data 'uber_data'.

print(uber_data[uber_data['START*'] == "San Francisco"])

Q15. What is the most popular starting point for the Uber drivers? 
Note: This question is based on the dataframe with no 'na' values in the 'START' variable.

In [ ]:
#Most popular starting point for the data with no missing values 'df'.

df['START*'].value_counts().nlargest(n=1)

Q16. What is the most popular dropping point for the Uber drivers? 
Note: This question is based on the dataframe with no 'na' values in the 'STOP' variable.

In [ ]:
#Most popular dropping point for the data with no missing values 'df'

df['STOP*'].value_counts().nlargest(n=1)

Q17. List the most frequent route taken by Uber drivers. 
Note: This question is based on the dataframe with no 'na' values.

In [ ]:
# Listing the top ten frequent routes taken by the Uber drivers for the data with no missing values 'df'

df.groupby(['START*','STOP*']).size().sort_values(ascending=False).head(1)

# Cary to Morrisville is the top most frequent route taken by the Uber drivers.

Q18. Print all types of purposes for the trip in an array.
Note: This question is based on the dataframe with no 'na' values in the 'PURPOSE' variable.

In [ ]:
#Printing all types of purposes for the trip and its miles in an array for the dataset with no missing values 'df'

print(np.array(df['PURPOSE*'].dropna().unique()))
df['MILES*'].groupby(df['PURPOSE*']).sum().sort_values(ascending = False)

# Significant trips are for meetings and customer visit.

Q19. Plot a bar graph of Purposes vs Distance.
Note: This question is based on the original dataframe.

In [ ]:
# Barplot for Purposes vs Distance for the original dataset "uber_data".

df1 = uber_data.groupby('PURPOSE*')['MILES*'].sum().sort_values(ascending=False).head(10) 
df1
df1= df1.reset_index() # resetting the index
df1
df1.columns = ['PURPOSE*' ,'Total_Miles']
df1
%matplotlib inline
sns.barplot(data= df1 , x= 'PURPOSE*' , y ='Total_Miles').set_title('Purpose vs Distance')
plt.xticks(rotation=90)

Q20. Print a dataframe of Purposes and the distance travelled for that particular Purpose.
Note: This question is based on the original dataframe.

In [ ]:
# Printing a dataframe for the pupose of the trips and their respective total distance from the original database 'uber_data'.

purpose_dist = uber_data.groupby('PURPOSE*').sum()['MILES*'].sort_values(ascending = False)
print(purpose_dist)

Q21. Plot number of trips vs Category of trips. 
Note: This question is based on the original dataframe.

In [ ]:
# Plotting number of trips by category from original database 'uber_data'

ax = sns.countplot(x = uber_data['CATEGORY*'], data=uber_data, hue='CATEGORY*', palette="Set3")

# More trips are made for business pupose than the personal purpose.

Q22. What is proportion of trips that is Business and what is the proportion of trips that is Personal? 
Note: The proportion calculation is with respect to the 'miles' variable.
Note: This question is based on the original dataframe.

In [ ]:
# Proportion of trips between business & personal purpose for the original database 'uber_data'.

categorries_prop = uber_data.groupby('CATEGORY*').agg({'MILES*':'sum'})
categorries_prop
categorries_prop.apply(lambda x: x/x.sum()*100).rename(columns = {'MILES':'% of Miles'})

### Thank you !