### Univariate Analyis Assignment

The following assignment tests your analytical ability to solve problems that are limited to one variable in a dataset. Answers to these questions will be provided upon request in the comments section. Please upvote and comment if you find this useful.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data_df = pd.read_csv('../input/titanic/titanic1.csv')

In [ ]:
data_df.head()

In [ ]:
data_df.shape

In [ ]:
data_df.dtypes

# Solve the following Questions

#### 1) Change/Replace the values of Survived Column from 1 and 0 to 'Survived' and 'Not Survived'  
#### (Solved for you guys to get going through the exercise)

In [ ]:
# Here we will use .replace which we discussed in class topic "Data Preprocessing"

In [ ]:
# Validate that the replace command's output is generated as intended (Hint: Use the unique function)

## Univariate Analysis

#### 2) Calculate in percent how many of the total survived?

In [ ]:
#Hint: use value_counts

#### 3) Plot a bar chart of the percentages of people 'Survived' and 'Not Survived'?

#### 4) Calculate in percent the distribution of male and female in the data?

#### 5) Plot a bar chart of the percentages of Male and Female in the given data?

### We can observe a column namely "Pclass" which denotes different travelling Class that we usually have trains and aeroplanes. Lets see how many unique classes we have in our data:

### As shown above, there are three unique classes (standards) in which the passengers are travelling i.e 1st ,2nd and 3rd class. Please note that although these are denoted as numbers in the data, they are termed as Categorical Data since these are the travelling class categories 1st Class being the Highest and most expensive('Fare').
#### 6) On the basis of discussion in the class, can you answer which type of Categorical Data is this?

#Write your answer as a comment

Firsly as we know that this is categorical data now we need to find out that wether it is ordinal or normal as we can analyze in the above question which is clearly showing that this colum showing the class(standard) of each person 1st class people are very rich people and 2nd class people are middle class level people and 3rd class level people are kind of poor people. so on this understanding we can clearly classify this as ordinal categorial data

#### 7) Calculate the distrinution of "number" of people travelling in different classes(Pclass) i.e how many people were travelling in 1st, 2nd and 3rd class? (HINT: You may use value_counts() for it)

#### 8) Plot a bar chart showing the distrinution of "number" of people travelling in different classes(Pclass) i.e plot of how many people were travelling in 1st, 2nd and 3rd class?