In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/kaggle/input/upwork-1/management.csv')

In [ ]:
df

In [ ]:
df = df.drop_duplicates(['recno'])

In [ ]:
df

In [ ]:
df['rate_in_usd'] = df['hourlyRate'].str.replace('{','').str.replace('}', '').str.split('\'amount\':').str[1]

In [ ]:
df

In [ ]:
#Most common job titles in dataset
df['title'].value_counts()[0:20].plot(kind='bar')

In [ ]:
#Find value counts for rates ($/hr) in listings with 'logo' in title
df[df['title'].str.lower().str.contains('logo')]['rate_in_usd'].value_counts()

In [ ]:
#Common rates in dataset
df['rate_in_usd'].value_counts()[0:20].plot(kind='bar')

In [ ]:
#Change type
df['rate_in_usd'] = df['rate_in_usd'].astype(float)

In [ ]:
#Narrow down by rates $30/hr and less
df1 = df[df['rate_in_usd'] <= 30]

In [ ]:
#Check for employees that...
#1. have 'law' in their title/desc
#2. charge less than $30/hr
df1[df1['title'].str.lower().str.contains('law')]