In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
dft = pd.read_csv('../input/titanic-train/train.csv')
dft

Task: Create a multi-indexed dataframe

Indexes:

level_0 = Sex
level_1 = Embarked
Columns:

level_0 = Sex
level_1 = Survived
Values: Random

Result:

In [ ]:
dftc = dft.copy()
dftc.info()

In [ ]:
index1 = [dftc.Sex.unique(), dftc.Embarked.unique()]
indexes = pd.MultiIndex.from_product(index1, names=["Sex", "Embarked"])
indexes

In [ ]:
column1 = [dftc.Pclass.unique(), dftc.Survived.unique()]
columns = pd.MultiIndex.from_product(column1, names=["Pclass", "Survived"])
columns

In [ ]:
dftc1 = pd.DataFrame(np.random.randint(9,size=(8,6)), index=indexes, columns=columns)
dftc1

2. Pivot:
Data: https://www.kaggle.com/c/titanic

Task: Create pivot table by using pivot

Index: Name

Column: Ticket

Values: Age

In [ ]:
dftc2 = dftc.iloc[:10].pivot(index='Name',columns='Ticket',values='Age')
dftc2

3. Stack & Unstack:
Data: Task 1

Task: Manipulate the table you obtained in the 1st task with the stack and unstack methods

In [ ]:
dftc3 = dftc1.stack([0,1]).unstack([0,3])
dftc3

4. Melt:
Data: https://www.kaggle.com/c/titanic

Task: Create the table below using melt method

Id_vars: 'Name' and 'Embarked'

Value_vars: 'Sex' and 'Age'

In [ ]:
dftc4 = dftc.melt(id_vars=['Name','Embarked'], value_vars =['Sex', 'Age'], var_name='variable', value_name='value').iloc[:10]
dftc4

5. Pivot Table:
Data: https://www.kaggle.com/c/titanic

Task: Create the following pivot tables using the pivot_table method

Index:

A) 'Embarked'

B) 'Embarked', 'Sex', 'Pclass'

C) 'Embarked', 'Sex', 'Pclass'

Values: 'Fare' and 'Age'

aggfunc:

A) 'Fare': mean, 'Age': median

B) 'Fare': mean, 'Age': median

C) 'Fare': mean and np.sum, 'Age': np.median and np.std

In [ ]:
#A#
pd.pivot_table(dftc, values=['Fare','Age'], index="Embarked",aggfunc={'Fare':[np.mean,np.sum], 'Age' : [np.median,np.std]})

In [ ]:
#B#

pd.pivot_table(dftc, values=['Fare','Age'], 
               index=['Embarked', 'Sex', 'Pclass'],
               aggfunc={'Fare':np.mean, 'Age' : np.median})

In [ ]:
#C#

pd.pivot_table(dftc, values=['Fare','Age'], 
               index=['Embarked', 'Sex', 'Pclass'],
               aggfunc={'Fare':np.mean, 'Age' : np.median})