Import

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

Read

In [ ]:
df = pd.read_csv('/kaggle/input/life-expectancy-who/Life Expectancy Data.csv')
df

Convert year to year

In [ ]:
import datetime

df.Year = pd.to_datetime(df.Year,format = '%Y')
df.Year

Analyse

In [ ]:
df.info()

Country

In [ ]:

country = df['Country'].to_list()

# using naive method to remove duplicates from list  
list_country = [] 
for i in country: 
    if i not in list_country: 
        list_country.append(i) 

list_country

In [ ]:
print(len(list_country))

Heatmap

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

corrmat = df.corr()
f, ax = plt.subplots(figsize=(12, 9))
sns.heatmap(corrmat, vmax=.8, square=True)

Countries

In [ ]:

country = "United Kingdom of Great Britain and Northern Ireland"

include_uk = df[df['Country'].values == country]
exclude_uk = df[df['Country'].values != country]
uk_life = include_uk
uk_life

In [ ]:
country = "United States of America"

include_us = df[df['Country'].values == country]
exclude_us = df[df['Country'].values != country]
us_life = include_us
us_life

In [ ]:
plt.plot(uk_life.Year, uk_life['Life expectancy '])
plt.plot(us_life.Year, us_life['Life expectancy '])
plt.legend(['UK', 'US'])
plt.xlabel('Year')
plt.ylabel('Life Expectancy')
plt.title('Life EXpectancy in UK and US')
plt.show()

In [ ]:
plt.plot(uk_life.Year, uk_life['Adult Mortality'])
plt.plot(us_life.Year, us_life['Adult Mortality'])
plt.legend(['UK', 'US'])
plt.xlabel('Year')
plt.ylabel('Adult Mortality')
plt.title('Adult Mortality in UK and US')
plt.show()

In [ ]:
plt.plot(uk_life.Year, uk_life['infant deaths'])
plt.plot(us_life.Year, us_life['infant deaths'])
plt.legend(['UK', 'US'])
plt.xlabel('Year')
plt.ylabel('Infant Deaths')
plt.title('Infant Deaths in the UK and US')
plt.show()

In [ ]:
plt.plot(uk_life.Year, uk_life['under-five deaths '])
plt.plot(us_life.Year, us_life['under-five deaths '])
plt.legend(['UK', 'US'])
plt.xlabel('Year')
plt.ylabel('under-five deaths')
plt.title('under-five deaths in the UK and US')
plt.show()

In [ ]:
plt.plot(uk_life.Year, uk_life['Alcohol'])
plt.plot(us_life.Year, us_life['Alcohol'])
plt.legend(['UK', 'US'])
plt.xlabel('Year')
plt.ylabel('Alcohol')
plt.title('Alcohol in the UK and US')
plt.show()

In [ ]:
plt.plot(uk_life.Year, uk_life['Measles '])
plt.plot(us_life.Year, us_life['Measles '])
plt.legend(['UK', 'US'])
plt.xlabel('Year')
plt.ylabel('Measles')
plt.title('Measles in the UK and US')
plt.show()

In [ ]:
plt.plot(uk_life.Year, uk_life[' BMI '])
plt.plot(us_life.Year, us_life[' BMI '])
plt.legend(['UK', 'US'])
plt.xlabel('Year')
plt.ylabel('BMI')
plt.title('BMI in the UK and US')
plt.show()

In [ ]:
plt.plot(uk_life.Year, uk_life['Polio'])
plt.plot(us_life.Year, us_life['Polio'])
plt.legend(['UK', 'US'])
plt.xlabel('Year')
plt.ylabel('Polio')
plt.title('Polio in the UK and US')
plt.show()

In [ ]:
plt.plot(uk_life.Year, uk_life['Diphtheria '])
plt.plot(us_life.Year, us_life['Diphtheria '])
plt.legend(['UK', 'US'])
plt.xlabel('Year')
plt.ylabel('Diptheria')
plt.title('Diptheria in the UK and US')
plt.show()

In [ ]:
plt.plot(uk_life.Year, uk_life[' HIV/AIDS'])
plt.plot(us_life.Year, us_life[' HIV/AIDS'])
plt.legend(['UK', 'US'])
plt.xlabel('Year')
plt.ylabel('HIV/AIDS')
plt.title('HIV/AIDS in the UK and US')
plt.show()