In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

First of all we must read the data we have.

In [ ]:
data = pd.read_csv('../input/2015ddd/2015d.csv')

In [ ]:
data.info()

We can see the informations in data with data.info(). It shows us entries,columns,types of columns and whether they are non-null or not.

In [ ]:
data.head(20)

data.head() shows us the first 5(default) rows of the datas.It is important because we should take a look to data before working on data deeply.

In [ ]:
data.tail()

In [ ]:
data.columns

To see the columns easily use data.columns.

In [ ]:
data.corr()

data.corr() is essential to see the correlations beetween columns.Also we use data.corr() to map the correlations.

In [ ]:
f,ax = plt.subplots(figsize = (15,15))
sns.heatmap(data.corr(), annot = True, linewidth = 0.5, fmt='.2f', ax=ax)
plt.show()

Personally I like correlation map because it looks verys elegant :).And of course it helps us to see correlation easily.

Now it is time to see behaviours of features on graphs.

In [ ]:
data.Economy.plot(kind = 'line', color = 'g', label = 'Economy', linewidth = 1, alpha = 1, grid = True, linestyle= ':')
data.Health.plot(kind = 'line', color = 'b', label = 'Health', linewidth = 1, alpha = 1, grid = True, linestyle = '-.')
plt.xlabel('x axis')
plt.ylabel('y axis')
plt.legend()
plt.title('Line plot')
plt.show()

Line plot is good for observe two columns behaviour together.

In [ ]:
data.plot(kind = 'scatter', x = 'Happiness_Score', y = 'Economy', color = 'b', alpha = 0.5)
plt.xlabel('Happiness Score')
plt.ylabel('Economy')
plt.title('Happiness Score - Economy Scatter Plot ')
plt.show()

Scatter plot is brilliant way to see correlations or comparing two features.

In [ ]:
plt.bar(data.Country[145:157], data.Happiness_Score[145:157], width =  0.5, color= 'r', alpha = 0.7)
plt.show()

**--------------------------------------------------------------------------------------------------------------------------------------------------------------**

In [ ]:
def tuple_ex():
    t = (5,6,'a')
    return t    #return defined tuple -t- .
x,y,z = tuple_ex()
print(x,y,z)

**SCOPE**

In [ ]:
x = 5
def f():
    x = 3
    y = x * 2
    return y
print(x)
print(f())

* x = 5 is the global that defined main body in script
* x = 3 is a local that defined in a function
If there is no local scope, function will use the global scope

**------------------------**

In [ ]:
def f(a, b = 1, c = 2):
    y = a + b + c
    return y
print(f(1,2,3))

* b and c are default arguments but a is a flexible arguments that we can assign.

In [ ]:
def f(*args):
    for i in args:
        print(i)
f(1)
f(1,2,3,4,'as',67)

def f(**kwargs):
    for key , value in kwargs.items():
        print(key," ",value)
        
f(country = 'spain', capital = 'madrid' , population = 123421)

*args can be anything.    **kwargs is a dictionary version of *args.

We can use **lambda** to write function in a line.

In [ ]:
addition = lambda x,a,b : x+a+b
addition(1,9,3)
square = lambda x : x**2
square(7)

map(func,list) means, apply the function whole list.

In [ ]:
number_list = [1,2,3]
y = map(lambda x : x**2 , number_list)
print(list(y))

In [ ]:
name = "abdullah"
k = iter(name)
print(next(k))
print(*k)

k  = iterable
We iterate the object(iterable) with iterator.

We can zip list with zip().

In [ ]:
list1 = [1,2,3,4]
list2 = [5,6,'a',8]
z = zip(list1,list2)
print(z)
z_list = list(z)
type(z_list)
print(z_list)

Also we can unzip the lists that we zipped before.

In [ ]:
un_zip = zip(*z_list)
un_list1 , un_list2 = list(un_zip)
print(un_list1)
print(un_list2)
print(type(un_list2))

List comprehension is creating a list using for loops in a single line.

In [ ]:
num1 = [1,2,3]
num2 = [i+1 for i in num1]
print(num2)

In [ ]:
num1 = [5,10,15]
num2 = [i-5 if i < 7 else i**2 if i == 10 else i+5 for i in num1]
print(num2)

In [ ]:
#  <6low        >6 high

In [ ]:
data["Happiness_level"] = ["high" if i > 6 else "low" for i in data.Happiness_Score]
data.loc[:10 , ["Country","Happiness_level", "Happiness_Score"]]

**CLEANING DATA**

In [ ]:
data.head()

In [ ]:
data.tail() #last 5

In [ ]:
data.columns

In [ ]:
data.shape

In [ ]:
data.info()

In [ ]:
print(data['Region'].value_counts(dropna = False)) #count non-null variables too.

We can see repetitions of entries by using value_counts().

In [ ]:
data.describe() #ignore null entries

Box plots : visualize basic statistics like outliers,min/max or quantiles

In [ ]:
data.boxplot(column = 'Economy', by = 'Happiness_level')
plt.show()

* Black line at top is the max value.
* Blue line at top is the secont quartile (%75)
* Green line is median (%50)
* Blue line at bottom is first quartile (%25)
* Black line at bottom is min value.
* **Black circle is the outlier !!**

**Tidy Data:**
We tidy data with melt().

In [ ]:
data_new = data.head()
data_new

* frame = source
* id_vars = unchanging variable
* value_vars = variables and their values.

In [ ]:
melted = pd.melt(frame = data_new, id_vars = 'Country',value_vars =['Happiness_Rank','Happiness_Score'])
melted

**Pivoting Data:**Reverse of melting

In [ ]:
melted.pivot(index = 'Country',columns = 'variable',values = 'value')

**Concatenating Data**

First concatenate datas in rows. (Means axis = 0)

In [ ]:
data1 = data.head()
data2 = data.tail()
conc_data_row = pd.concat([data1,data2],axis = 0,ignore_index = False) # axis = 0 add in row
conc_data_row

In [ ]:
data0 = data['Country'].head()
data1 = data['Happiness_Score'].head()
data2 = data['Economy'].head()
conc_data_col = pd.concat([data0,data1,data2],axis = 1)
conc_data_col

If you do axis = 1 it will concat datas with columns

**DATA TYPES**

In [ ]:
data.dtypes

Changing the data types may be important some times.And for this purpose we have astype().

In [ ]:
data['Country'] = data['Country'].astype('category')
data['Happiness_Rank'] = data['Happiness_Rank'].astype('float')

In [ ]:
data.dtypes

**Missing Datas**
You can do:
* -leave as it
* -drop them with dropna()
* -fill missing value with fillna()
* -fill missing values with test statistics like mean

In [ ]:
data.info()

We do not have null entry.All of the entries are non-null.

We also see this with using value_counts(dropna = False) -means do not drop null entries.-

In [ ]:
data["Region"].value_counts(dropna = False)

In this data we don't have null entries.But in order to learn what we do with null entries I'd like to share with you dropna().

To drop null entries we use dropna().

In [ ]:
data["Region"].dropna(inplace = True) #inplace = True means do not assign new variable.

We check this code with assert.If the sentences that we write next to assert is true then it will return nothing.

In [ ]:
assert data["Region"].notnull().all()

So it returns nothing, means in the all 'Region' column we do not have null entries, all of the entries are notnull.

------**PANDAS FOUNDATİON**------

* Building Data Frames From Scratch
* Despite the building data frames from csv we can also build data frames from dictionaries via using zip() method.
zip() method returns a list of tuples.

In [ ]:
#data frame creating from dictionary
mountains = ["Rocky","Everest"]
altitude = ["4401","8848"]
list_label = ["Mountain","Altitude"]
list_col = [mountains,altitude]
zipped = list(zip(list_label,list_col))
data_dict = dict(zipped)
df = pd.DataFrame(data_dict)
df

As you can see it takes time to create dataframes from dictionary.

In [ ]:
df["Location"] = ["Nort America","Himalayas"]
df

Adding new features to the data frame is the same as we did before.

In [ ]:
df["broadcasting"] = 0
df

What we mean broadcasting is adding new column to the data frame and give whole entries a value.

**VISUAL EXPLORATORY DATA ANALYSIS**

Let's remind ourselves basic plotting techniques.

In [ ]:
#plotting all data
data1 = data.loc[:,["Happiness_Score","Economy","Health"]]
data1.plot()
plt.show()

Using subplots we can separate the features.

In [ ]:
#subplots
data1.plot(subplots = True)
plt.show()

In [ ]:
#Scatter plot
data.plot(kind = "scatter",x = "Economy",y = "Happiness_Score")
plt.show()

In [ ]:
#Histogram plot
data1.plot(kind = "hist",y = "Happiness_Score",bins = 50,range = (0,10),normed = True)
plt.show()

In [ ]:
fig,axes = plt.subplots(nrows = 2,ncols = 1)
data1.plot(kind = "hist",y = "Happiness_Score",bins = 50,range = (0,10),normed = True, ax = axes[0])
data1.plot(kind = "hist",y = "Happiness_Score",bins = 50,range = (0,10),normed = True, ax = axes[1]
          ,cumulative = True)
plt.show()

**INDEXING PANDAS TIME SERIES**

datatime is an object.

In [ ]:
time_list = ["1981-04-17","1981-03-12"]
print(type(time_list[1]))
datetime_object = pd.to_datetime(time_list)
print(type(datetime_object))

Now, let's create a datelist then change it's type to datetime (like ı said it is an object) and add it to our dataframe as an index.

In [ ]:
data2 = data.head()
date_list = ["1992-01-10","1992-02-10","1992-03-10","1993-03-15","1993-03-16"]
datetime_object = pd.to_datetime(date_list) #changing type, str to datetime
data2["date"] = datetime_object             #adding to dataframe
data2 = data2.set_index("date")             # as an index !
data2

We can search a specific data with respect to date.

In [ ]:
print(data2.loc["1993-03-16"])

In [ ]:
print(data2.loc["1992-03-10":"1993-03-16"])

**RESAMPLING PANDAS TIME SERIES**

* Now we can resample the dataframe. 
* "A" means with respect to YEAR,
* "M" means with respect to MONTH

Resampling by YEAR ("A") with mean.

In [ ]:
data2.resample("A").mean()

In [ ]:
data2.resample("M").mean()

Resampling by Month ("M") with mean.

To fill NaN entries we can interpolate linearly.

In [ ]:
data2.resample("M").first().interpolate("linear")

Also we can interpolate linearly with having same means.

In [ ]:
data2.resample("M").mean().interpolate("linear")

**MANIPULATİNG DATA FRAMES with PANDAS******

INDEXING

In [ ]:
data = data.set_index("Happiness_Rank")  #indexing with happiness_rank
data.head()

To find specific element we have several ways.

In [ ]:
data["Happiness_Score"][1]     #using square brackets

In [ ]:
data.Happiness_Score[1]       #using column attribute and row label

In [ ]:
data.loc[1,["Happiness_Score"]]  #using loc

In [ ]:
data[["Happiness_Score","Economy"]]      #selecting only precise columns

SLICING DATA FRAME

We may want to learn features beetween 2 selected columns.For this purpose we use slicing.

In [ ]:
data.loc[1:10,"Region":"Family"]    # ROWS --->  1 TO 10
                                    # COLUMNS -> Region to Family

In [ ]:
data.loc[10:1:-1,"Region":"Family"]    #reverse slicing

In [ ]:
data.loc[1:10,"Economy":]

FILTERING DATA FRAMES

Filtering means getting datas for defined interval by creating boolean series.

This code gives us the entries that only have Happiness Score higher than 6.

In [ ]:
boolean = data.Happiness_Score > 6
data[boolean]

We can also use more than one filter.

In [ ]:
filt1 = data.Happiness_Score > 6
filt2 = data.Economy > 1.25
data[filt1 & filt2]

This code will give us the Regions which only has Happiness Score greater than 6.8

In [ ]:
data.Region[data.Happiness_Score > 6.8]

TRANSFORMING DATA

We may want to have different kind of our data's values.

In [ ]:
def div(m):
    y = m/2
    return y
data.Happiness_Score.apply(div)

But we learnt shorter way to write function before.

In [ ]:
data.Happiness_Score.apply(lambda m:m/2)

We can define a new column by using other columns in the dataframe.

In [ ]:
data["new_column"] = data.Happiness_Score - data.Standard_Error
data.head()

INDEX OBJECTS AND LABELED DATA

In [ ]:
#We can learn our index name :
print(data.index.name)

It is also possible to change the name of index.

In [ ]:
data.index.name = "index_name"
data.head()

We can modify the index.

In [ ]:
data3 = data.copy()
data3.index = range(100,258,1)
data3.head()

HIERARCHICAL INDEXING

Region : outer index and Happiness_level: inner index

In [ ]:
data3 = data.set_index(["Region","Happiness_level"])
data3.head(150)

PIVOTING DATA FRAMES

In [ ]:
dic = {"chemical" : ["X","Y","X","Y"],"reactivity" : ["low","high","low","high"],"price" : [34,14,56,78],
       "config" : [3,7,7,3] }
df = pd.DataFrame(dic)
df

In [ ]:
#pivoting
df.pivot(index = "chemical",columns = "config",values = "price")

STACKING AND UNSTACKING DATAFRAME

In [ ]:
df1 = df.set_index(["chemical","config"])    
df1

We can easily unstack the df1

In [ ]:
df1.unstack(level = 0)  #level : position of unstacked index

In [ ]:
df1.unstack(level = 1)

We are able to change inner and outer level index positions.

In [ ]:
df2 = df1.swaplevel(0,1)
df2

MELTING

In [ ]:
df

In [ ]:
pd.melt(frame = df,id_vars = "chemical",value_vars = ["reactivity","price"])

CATEGORICALS AND GROUPBY

In [ ]:
df

We can group the features according to any feature that we want

In [ ]:
df.groupby("chemical").mean()

In [ ]:
df.groupby("chemical").max()

In [ ]:
df.groupby("chemical").price.max()

In [ ]:
df.groupby("chemical")[["price","reactivity"]].min()