In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [ ]:
#Reading the csv file
unv_df=pd.read_csv("/kaggle/input/world-university-rankings/cwurData.csv")

In [ ]:
#displaying the top 5 data
unv_df.head(5)

In [ ]:
#Calculate the no of rows and columns
unv_df.shape

In [ ]:
unv_df.dtypes

From the above it is clear that the institution and country are categorical data. Rest of the data are numeric with data type as integer and float respectively.

In [ ]:
#Dataframe information
unv_df.info()

In [ ]:
#Check for the missing values 

unv_df.isna().any()

In [ ]:
#Calculating the no of missing values for broad_impact column
unv_df['broad_impact'].isna().sum()

There are 200 missing values in the broad_impact column.Broad_impact values are not available for year 2014 and 2015. Also the mean and median are equal which means the data is normally distributed.

In [ ]:
unv_df.nunique()

In [ ]:
unv_df["year"].value_counts()


**All the rankings are based from the year 2012-2015. We will divide our data into four parts for each year respectively.**

In [ ]:
# Reading columns
df1 = unv_df[['country' ,'institution','national_rank' , 'year']]
df1.head(10)

In [ ]:
#Read specific rows
df1.iloc[1:4]

In [ ]:
#Filter data
df1.loc[df1['country']== 'USA']

In [ ]:
#Sort Data Frame
display('Sorted Data Frame', df1.sort_values(['country'], ascending=True).head(5))

In [ ]:
#Sort Data Frame in descending order
display('Sorted Data Frame', df1.sort_values(['country'], ascending=False).head(5))

In [ ]:
#Sort Data Frame - Ascending on "Country" & descending on "national rank"
display('Sorted Data Frame', df1.sort_values(['country', 'national_rank'], ascending=[True,False]))

In [ ]:
#Iterating through the dataset
for index , row in df1.iterrows():
    if (row['country'] == 'United Kingdom' ):
        display(row[['country', 'institution']])

In [ ]:
#Unique Values
unv_df['country'].drop_duplicates(keep='first').head(10)

In [ ]:
# Countries with universities 
countries = unv_df['country'].unique()
type(countries) , countries

In [ ]:
#Check for the missing values 

unv_df.isna().any()

In [ ]:
#Calculating the no of missing values for broad_impact column
unv_df['broad_impact'].isna().sum()

In [ ]:
# Mean of all Columns
unv_df.mean()

In [ ]:
# Max value per column
unv_df.max()

In [ ]:
# Min value per column
unv_df.min()

In [ ]:
# Median
unv_df.median()

In [ ]:
unv_df.std() #Standard Deviation

In [ ]:
unv_df.var() #Variance

In [ ]:
#Lower Quartile / First Quartile
unv_df.quantile(0.25)

In [ ]:
#Second Quartile / Median
unv_df.quantile(0.50)

In [ ]:
# Upper Quartile
unv_df.quantile(0.75)

In [ ]:
#IQR (Interquartile Range)
unv_df.quantile(0.75) - unv_df.quantile(0.25)

In [ ]:
# SUM of column values
unv_df.sum()

In [ ]:
# GENERATES DESCRIPTIVE STATS
unv_df.describe()

In [ ]:
#Return unbiased skew
# https://www.youtube.com/watch?v=HnMGKsupF8Q
unv_df.skew()

In [ ]:
# Return unbiased kurtosis using Fisherâ€™s definition of kurtosis
# https://www.youtube.com/watch?v=HnMGKsupF8Q
unv_df.kurt()

In [ ]:
#Correlation
unv_df.corr()

In [ ]:
#Covariance
unv_df.cov()

In [ ]:
# Hormonic Mean
import statistics as st
st.harmonic_mean(unv_df['alumni_employment'])

In [ ]:
# low median of the data with EVEN length
st.median_low(unv_df['alumni_employment'])

In [ ]:
# High median of the data with EVEN length
st.median_high(unv_df['alumni_employment'])

In [ ]:
# Mode of Dataset
st.mode(unv_df['publications'])

In [ ]:
# Sample Variance
st.variance(unv_df['alumni_employment'])

In [ ]:
#Population Variance
st.pvariance(unv_df['alumni_employment'])

In [ ]:
#Sample Standard Deviation
st.stdev(unv_df['alumni_employment'])

In [ ]:
#Population Standard Deviation
st.pstdev(unv_df['alumni_employment'])

In [ ]:
# Finding MAX value in Columns
unv_df.apply(max)

In [ ]:
# Finding minimum value in Columns
unv_df.apply(min)

In [ ]:
#Sum of Column Values
unv_df.apply(np.sum)

In [ ]:
# Using Lambda function in Dataframes
unv_df.apply(lambda x: min(x))

In [ ]:
for key,value in unv_df.iteritems():
    print(key,value)

In [ ]:
for key,value in unv_df.iterrows():
    print(key,value)

In [ ]:
unv_df.groupby(['year']).mean().head(10)

In [ ]:
unv_df.groupby(['year']).mean().sort_values("quality_of_faculty",ascending=False).head(10)

In [ ]:
unv_df.sum()

In [ ]:
unv_df.groupby(['year']).sum().head()

In [ ]:
unv_df.count()

In [ ]:
unv_df['count1'] = 0
unv_df.groupby(['year']).count()['count1']

In [ ]:
unv_df['count1'] = 0
unv_df.groupby(['year','country']).count()['count1']

In [ ]:
# Pivot table with SUM aggregation
pd.pivot_table(unv_df , index= ['year' , 'quality_of_faculty'] , aggfunc='sum')

In [ ]:
# Pivot table with MEAN aggregation
pd.pivot_table(unv_df , index= ['year' , 'quality_of_faculty'] , aggfunc='mean')

In [ ]:
new_unv_df=unv_df.set_index(['year', 'quality_of_faculty'])
new_unv_df

In [ ]:
new_unv_df.index

In [ ]:
new_unv_df.loc[2015]

In [ ]:
new_unv_df=unv_df.set_index(['year', 'quality_of_faculty','country'])
new_unv_df

In [ ]:
# Swaping the columns in Hierarchical index
new_unv_df = new_unv_df.swaplevel('year', 'quality_of_faculty')
new_unv_df

In [ ]:
pd.crosstab(unv_df['year'] , unv_df.score , margins=True)

In [ ]:
# 2 way cross table
pd.crosstab(unv_df.score,unv_df['year'] , margins=True)

**1. Analysis of the data for year 2012**

In [ ]:
unv_df_2012=unv_df.loc[unv_df['year'] == 2012]
unv_df_2012.head(10)

In [ ]:
#Shape of the data

unv_df_2012.shape

In [ ]:
#Missing values in the columns

unv_df_2012.isna().any()

In [ ]:
#Count the missing values in the broad_impact data set

unv_df_2012.isna().sum()

In [ ]:
#Drop the broad_impact column as the entire data is missing for all the rows 

unv_df_2012.drop("broad_impact",axis=1,inplace=True)

The above shown warning can be removed by the following code :-

        unv_df_2012_new = unv_df_2012.drop('Item', axis=1).
        
 But I am ignoring it to avoid so many names for the same set of the data

In [ ]:
#List of countries in the dataset

unv_df_2012["country"].unique()

In [ ]:
unv_df_2012.describe().T

In [ ]:
sns.pairplot(unv_df_2012)

**Observations**

1. World Rank is from 1 to 100 for all the universities.
2. Most of the universities are top or second best universities respectively from there country.
3. Most of the univesities rank higher in terms of quality of education,alumni employemnt,quality of         faculity,publication,influence,citations and patents (rank=101). Here Mean>Median. the graph is right skewed.
4. The world Rank and the national rank is directly proportional to each other . As the national rank rises , the world rank rises too.But in some of the cases the national rank is less but the world rank is much more.
5. The world rank and the quality of education is evenly distributed for most of the data. The universities with rank 101 in terms of quality of education has world rank between 25 to 100.
6. The world rank and the alumni employment is evenly distributed for most of the data. The universities with rank 101 in terms of alumni employment has world rank between  15 to 100.
7. The world rank and the quality of faculty is evenly distributed for most of the data. The universities with rank 101 in terms of quality of faculty has world rank ranges between 30 to 100.
8. The world rank and the publications is evenly distributed for most of the data. The universities with rank 101 in terms of publications doesn't have world rank in top 20.
9. The word rank and the influence is evenly distributed for most of the data.The universities with rank 101 in terms of influence doesn't have world rank in top 40.
10. The world rank and the citations  is evenly distributed for most of the data. The universities with rank 101 in terms of citations doesn't have world rank in top 20.
11. The world rank and the patents is evenly distributed for most of the data. The universities with rank 101 in terms of patents doesn't have the world rank in top 5.
12. The world rank and the score is indirectly proportional to each other. The universities with low score have comparatively higher rank.

In [ ]:
# Correlation with heat map
import matplotlib.pyplot as plt
import seaborn as sns
corr =unv_df_2012.corr()
sns.set_context("notebook", font_scale=1.0, rc={"lines.linewidth": 2.5})
plt.figure(figsize=(13,7))
# create a mask so we only see the correlation values once
mask = np.zeros_like(corr)
mask[np.triu_indices_from(mask, 1)] = True
a = sns.heatmap(corr,mask=mask, annot=True, fmt='.2f')
rotx = a.set_xticklabels(a.get_xticklabels(), rotation=90)
roty = a.set_yticklabels(a.get_yticklabels(), rotation=30)

**Observation**

1. World rank and Score are highly corelated to each other.
2. Publications and quality of education is least corelated to each other.

In [ ]:
#Top ten universities in terms of world rank 

unv_df_2012_new= unv_df_2012.head(10)
plt.scatter(unv_df_2012_new.country,unv_df_2012_new.institution)
plt.xlabel('countries')
plt.ylabel('universities')
plt.title('rank')
plt.show()

In [ ]:
#Top ten universities of the USA as per the national rankings

unv_df_2012_USA=unv_df_2012.loc[unv_df_2012['country']=="USA"]

unv_df_2012_USA.sort_values('national_rank')
print(unv_df_2012_USA["institution"].head(10))

In [ ]:
# University of USA world ranking 
plt.hist(unv_df_2012_USA.world_rank,bins=2) #histogram
plt.title('Universities of USA')
plt.xlabel("rank of institutions")
plt.show()

**Most of the US universities are ranked between 1 to 50. **

In [ ]:
#Alumni employed by the top ten universities  

plt.figure(figsize=(25,7)) # this creates a figure 20 inch wide, 7 inch high
sns.barplot(unv_df_2012_new['institution'], unv_df_2012_new['alumni_employment'])

In [ ]:
#Impact of score to the 
plt.figure(figsize=(25,7)) # this creates a figure 20 inch wide, 7 inch high
sns.barplot(unv_df_2012_new['institution'], unv_df_2012_new['score'])