In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
print(os.listdir("../input"))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

Here is the link for the pandas help document.

https://pandas.pydata.org/pandas-docs/stable/index.html

# 1. Data Structure- Series
Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.

In [ ]:
#creat a series by passing in a list of values
fruit=['apple','peach','pear']
pd.Series(fruit)

In [ ]:
numbers=[1,2,3]
pd.Series(numbers)

In [ ]:
#Create series from dicts.
student_score={'a':'physics', 'b':'math','c':'English'}
s=pd.Series(student_score)
s

In [ ]:
s.index

In [ ]:
s=pd.Series(['physics','math','English'], index=['a','b','c'])
s

### Slicing

In [ ]:
s[['a','b']]

In [ ]:
s[[0,1]]

# 2. Data structure- Dataframe
DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object.

In [ ]:
# Create dataframe from series
record1=pd.Series({'name':'a','class':'physics','score':85})
record2=pd.Series({'name':'b','class':'chemistry','score':82})
record3=pd.Series({'name':'c','class':'biology','score':90})
df=pd.DataFrame([record1,record2,record3],index=['school1','school2','school3'])
df.head()

In [ ]:
#Create dataframe from dictionary
students=[{'name':'a','class':'physics','score':85},
          {'name':'b','class':'chemistry','score':82},
          {'name':'c','class':'biology','score':90}]
    
df=pd.DataFrame(students,index=['school1','school2','school1'])
df.head()

### Subsetting Rows

In [ ]:
#extract data based on row and column labels using the .loc. 
df.loc['school2']

In [ ]:
#select data based on multipul axes using .loc. It takes two parameters, the row index and the column names.
df.loc['school1','name']

In [ ]:
df.loc[:,['name','score']]

### Subsetting columns

In [ ]:
df[['name','class']]
#df['name','class'] #wrong example

In [ ]:
#drop row data
df.drop('school1')

In [ ]:
df

In [ ]:
#drop columns
copy_df=df.copy()
copy_df.drop('name',inplace=True, axis=1)
copy_df

In [ ]:
del copy_df['class']
copy_df

In [ ]:
#adding a new column
df['classranking']=None
df

# 3. How does index work in pandas

In [ ]:
df = pd.read_csv('../input/amazon-top-50-bestselling-books-2009-2019/bestsellers with categories.csv')
df.head()

In [ ]:
df.index

In [ ]:
df1=df.set_index('Year')
df1.head()

In [ ]:
df2=df1.reset_index()
df2.head()

In [ ]:
df1.loc[2016,'Name']

In [ ]:
df1.loc[[2016,2011],['Name','Author']]

Subsetting by row/column number.

The most common ways to subset rows are the ways we've previously discussed: using a Boolean condition or by index labels. However, it is also occasionally useful to pass row numbers. This is done using .iloc[], and like .loc[], it can take two arguments to let you subset by rows and columns.

In [ ]:
df.head()

In [ ]:
df.iloc[1,2]

In [ ]:
df.iloc[:,[1,3]]

# 4. How does pandas handle missing values

In [ ]:
dfc=pd.read_csv('../input/my-dataset/credit_test.csv')
dfc.head(10)

In [ ]:
dfc.isnull().head(10)

In [ ]:
dfc.isnull().sum()

In [ ]:
dfc.dropna().head(10)

In [ ]:
dfc.head(10)

In [ ]:
#inplace attribute causes pandas to fill the values and modifies the dataframe instead of returning a copy of the dataframe
dfc.fillna(0,inplace=True)
dfc.head(10)

In [ ]:
dfc=pd.read_csv('../input/my-dataset/credit_test.csv')
dfc.head(10)

In [ ]:
dfc1=dfc.fillna(method='ffill')
dfc1.head(10)

In [ ]:
dfc2=dfc.fillna(method='bfill')
dfc2.head(10)

# 5. Merging Dataframe

In [ ]:
staff_df=pd.DataFrame([{'name':'Kelly','roll':'Director'},
                      {'name':'Sally','roll':'HR'},
                      {'name':'James','roll':'Manager'}])
staff_df=staff_df.set_index('name')
student_df=pd.DataFrame([{'name':'James','school':'Business'},
                      {'name':'Mike','school':'Law'},
                      {'name':'Sally','school':'Engineering'}])
student_df=student_df.set_index('name')
print(staff_df)
print(student_df)

### 1) using index to merge dataframe

In [ ]:
pd.merge(staff_df,student_df, how='outer',left_index=True,right_index=True)

In [ ]:
pd.merge(staff_df,student_df, how='inner',left_index=True,right_index=True)

In [ ]:
#get a list of all staff 
pd.merge(staff_df,student_df, how='left',left_index=True,right_index=True)

In [ ]:
#get a list of all students
pd.merge(staff_df,student_df, how='right',left_index=True,right_index=True)

### 2) using columns to merge dataframe

In [ ]:
staff_df=staff_df.reset_index()
student_df=student_df.reset_index()

pd.merge(staff_df,student_df, how='right',on='name')

In [ ]:
staff_df=pd.DataFrame([{'name':'Kelly','roll':'Director','location':'NY'},
                      {'name':'Sally','roll':'HR','location':'TX'},
                      {'name':'James','roll':'Manager','location':'FL'}])

student_df=pd.DataFrame([{'name':'James','school':'Business','location':'1024 Avenue'},
                      {'name':'Mike','school':'Law','location':'2733 Heart street'},
                      {'name':'Sally','school':'Engineering','location':'512 wilson'}])

pd.merge(staff_df,student_df, how='right',on='name')
#The merge function append _x and _y to help differentiate the columns with same column name

In [ ]:
staff_df=pd.DataFrame([{'first name':'Kelly','last name':'Des','roll':'Director','location':'NY'},
                      {'first name':'Sally','last name':'Br','roll':'HR','location':'TX'},
                      {'first name':'James','last name':'Wilde','roll':'Manager','location':'FL'}])

student_df=pd.DataFrame([{'first name':'James','last name':'Ham','school':'Business','location':'1024 Avenue'},
                      {'first name':'Mike','last name':'Smith','school':'Law','location':'2733 Heart street'},
                      {'first name':'Sally','last name':'Br','school':'Engineering','location':'512 wilson'}])

pd.merge(staff_df,student_df, how='inner',on=['first name','last name'])

## merge dataframe vertically

In [ ]:
pd.concat([staff_df,student_df], join ='outer')

In [ ]:
pd.concat([staff_df,student_df], join ='inner')

In [ ]:
pd.concat([staff_df,student_df], keys=['staff','student'])

# 6. Group by Function

In [ ]:
df = pd.read_csv('../input/amazon-top-50-bestselling-books-2009-2019/bestsellers with categories.csv')
df.head()

In [ ]:
df.groupby('Year').agg(np.average)

In [ ]:
df.groupby('Year').agg({'User Rating':np.average})

In [ ]:
df.groupby('Year')['User Rating'].agg(np.average)

In [ ]:
df.groupby('Year').agg({'Price':(np.average, np.sum)})

In [ ]:
df.groupby(['Year','User Rating']).agg({'Price':(np.average, np.sum)})