**UYARI!!! 
BURADAKİ ÖRNEKLER BANA DEĞİL, https://www.kaggle.com/kanncaa1/data-sciencetutorial-for-beginners KERNELİNİN SAHBİ DATAI'A AİTTİR. BEN ÜZERİNE NOTLAR,KARIŞIK KISIMLARI AÇIKLAYICI İFADELER,HATIRLATICI KODLAR VE BAZI KISIMLARDA AYRICA KODLAR ALDIM.**

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd# data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [ ]:
data=pd.read_csv("/kaggle/input/pokemon-challenge/pokemon.csv")

In [ ]:
data

In [ ]:
data.info()

In [ ]:
data.describe()

In [ ]:
data.columns

In [ ]:
data.corr()
#orantı tablosu verir.

correlation map
eğer 2 feature arasında correlation 1 yada 1'e yakın ise bunlar birbiri ile doğru orantılıdır(positive correlation). eğer 0 çıkarsa orantı yoktur,alakasızdır. eğer -1 yada -1'e yakın çıkarsa ters orantılıdır.

In [ ]:
f,ax=plt.subplots(figsize=(18,18))
sns.heatmap(data.corr(),annot=True,linewidths=.5,fmt=".1f",ax=ax)
plt.show()

2.satırda seaborn library'sini kullnıcaz(sns). heatmap yaparak şekilli tablo elde ederiz. içinde data.corr() diyerek yukarıdaki orantı tablosunu ekleriz. annot=True diyerek tablodaki karelerin içindeki sayıları elde ederiz. linewidths=.5 demek kareler arasındaki çizginin kalınlığı 0.5 olsun demektir. fmt=".1f" demek de virgülden sonra  basamak yazdırsın demektir. 1. satırda ise, subplots içinde figsize=(18,18) diyerek tablonun boyutunun 18x18 boyutunda olmasını söylüyoruz. eğer mesela 13x13 deseydik daha küçük bir tablo verirdi. eğer bu satırı hiç demeseydik çok küçük bir tablo verirdi. 
eğer bu 2 satırdan sonra plt.show() demezsek < ... > içinde bir yazı verir. plt.show() diyince bu yazı kaybolur.
f)figure,ax=axes(eksenler)

In [ ]:
data.head(10)

**LINE PLOT**

In [ ]:
#line plot
data.Speed.plot(kind="line",color="g",label="Speed",linewidth=1,alpha=0.5,grid=True,linestyle=":")
data.Defense.plot(color="r",label="Defense",linewidth=1,alpha=0.5,grid=True,linestyle="-.")
plt.legend(loc="upper right")
plt.xlabel("x axis",color="white")
plt.ylabel("y axis",color="white")
plt.title("Line plot",color="white")
plt.show()

bunu eski öğrendiğimiz line plot yöntemi ile de çizebiliriz. farklı yöntemleri öğrenmek için bu da güzel. data adlı dataframe'imizin speed column'ını aldık ve plot ettiricez. önce içine türünü giriyoruz.(kine,scatter,histogram vs...) sonra rengi giriyoruz. Renk için, rengin kısaltması girilebilir. line'ların kalınlıklarını linewidth ile gireriz. grid ,le karelere böleriz. ikisine de grid girmeliyiz, birine girmez isek hiç grid oluşturmaz.en son linestyle(ls) ile çizginin türünü seçeriz. çizgi türleri 4 türdür: ":", "-.", "-", "--"  
Defense için de bunları girdik ancak türümüzü ilkinde line olarak girdiğimiz için şimdi tekrar girmeye gerek yok, girilebilir de girilmeyebilir de. 
Daha sonra plt.legend() dedik ve içine labellerimizi grafiğin neresine yazmasını istediğimizi girdik(upper right,lower left,center, center right...)
xlabel ve ylabel ile eksenlere yazmasını istediklerimizi yazdık,başlığı girdik ve show ettik.

In [ ]:
#scatter plot
data.plot(kind="scatter",x="Attack",y="Defense",alpha=.5,color="r",grid=True,figsize=(10,10))
plt.xlabel("Attack",color="w")
plt.ylabel("Defense",color="w")
plt.title("Attack Defense Scatter Plot",color="w")

plt.show() demediğimiz için üstte bir yazı çıktı.
Bu grafiği önceden öğrendiğimiz şu şekilde de çizdirebiliriz. Sonuç aynısı olur.

In [ ]:
plt.scatter(data.Attack,data.Defense,alpha=.5,color="r")
plt.grid(True)
plt.show()

In [ ]:
#histogram
# bins = number of bar in figure
data.Speed.plot(kind="hist",bins=50, figsize=(12,12))
plt.show()

In [ ]:
# clf() = cleans it up again you can start a fresh
data.Speed.plot(kind = 'hist',bins = 50)
plt.clf()
# We cannot see plot due to clf()

eğer bir figure çizdirdikten sonra onu silmek istersek plt.clf() yazarız.

In [ ]:
#dictioanry
dictionary={"spain":"madrid","usa":"vegas"}
dictionary.keys()

In [ ]:
print(dictionary.keys())

In [ ]:
dictionary.keys()

In [ ]:

print(dictionary.keys())

* Keys have to be immutable(değiştirilemez.) objects like string, boolean, float, integer or tubles.
* List is not immutable.
* Keys are unique.
* Values are mutable(değiştirilebilir).

In [ ]:
dictionary["spain"]="barcelona"
print(dictionary)

In [ ]:
dictionary["france"]="paris"
dictionary

In [ ]:
del dictionary["spain"]
dictionary

In [ ]:
print("france"in dictionary)

In [ ]:
dictionary.clear()
dictionary

1. clear() metodu ==> dictionary'nin içini boşaltır.
2. del metodu dictionary'yi tamamen siler.

> CSV: comma - separated values

In [ ]:
data=pd.read_csv("/kaggle/input/pokemon-challenge/pokemon.csv")

In [ ]:
series=data["Defense"]  # data['Defense'] = series
print(type(series))
data_frame=data[["Defense"]] # data[['Defense']] = data frame
print(type(data_frame))

* data['Defense'] = series  (tek boyutlu matris,yani vector)
* data[['Defense']] = data frame
* "Farklarına dikkat et!!!"

* Before continue with pandas, we need to learn logic, control flow and filtering.
* Comparison operator: ==, <, >, <=
* Boolean operators: and, or ,not
* Filtering pandas

In [ ]:
# Comparison operator
print(3 > 2)
print(3!=2)
# Boolean operators
print(True and False)
print(True or False)

In [ ]:
# 1 - Filtering Pandas data frame
x=data["Defense"]>200
data[x]

In [ ]:
# 2 - Filtering pandas with logical_and
data[np.logical_and(data["Defense"]>200,data["Attack"]>100)]

In [ ]:
# This is also same with previous code line. Therefore we can also use '&' for filtering.
data[(data["Defense"]>200)&(data["Attack"]>100)]

# WHILE and FOR LOOPS

In [ ]:
# Stay in loop if condition( i is not equal 5) is true
i=0
while i!=5:
    print("i is:",i)
    i+=1
print(i,' is equal to 5')

In [ ]:
# Stay in loop if condition( i is not equal 5) is true
list1=[3,8,12,40,-5]
for i in list1:
    print('i is: ',i)
print('')

In [ ]:
# Enumerate index and value of list
# index : value = 0:1, 1:2, 2:3, 3:4, 4:5
for index,value in enumerate(list1):
    print(index,":",value)
print('')
#for'dan sonra ilk yazılan index,daha sonra yazılan value içindir.

In [ ]:
# For dictionaries
# We can use for loop to achive key and value of dictionary. We learnt key and value at dictionary part
dictionary = {'spain':'madrid','france':'paris'}
for key,value in dictionary.items():
    print(key," : ",value)
print('')
#for'dan sonra ilk yazılan key,daha sonra yazılan value içindir.

In [ ]:
# For pandas we can achieve index and value
for index,value in data[["Attack"]][0:1].iterrows():
    print(index," : ",value)

* List,pandas ve dictionary lerde for while looplar #index/key ve #value bulmak için kullanılır.
* listelerde index bulmak için *enumerate*;
* dictionary lerde key ve value bulmak için *dictionary.items()*;
* pandas ta index ve value bulmak için *data[["..."][0:1].iterrows()* kullanılır.

# Python Data Science Tool Box
USER DEFINED FUNCTION AND SCOPE

In [ ]:
#USER DEFINED FUNCTION
# example of what we learn above
def tuple_ex():
    """return defined t tuple"""
    t=(1,2,3)
    return t
a,b,c=tuple_ex()
print("a:",a,"\nb:",b,"\nc:",c)

In [ ]:
#SCOPE
x=2 #global x
def f():
    x=5  #local x
    return x
print(x) #global değeri döndürür.
print(f()) #tanımlanan fonksiyondaki local x'i döndürür.

In [ ]:
#eğer local scope olmazsa;
x=2
def f():
    y=x*2  # there is no local scope x
    return y
print(f())   # it uses global scope x

> First local scopesearched, then global scope searched, if two of them cannot be found lastly built in scope searched.
> foksiyona bakılırken önce *local scope'a*, sonra *global scope'a* bakılır. eğer ikisi de yoksa en son *built in scope'a* bakılır.

In [ ]:
# How can we learn what is built in scope
import builtins
dir(builtins)

In [ ]:
#nested function
#iç içe fonksiyon
def square():
    """return square of value"""
    def add():
        """add two local variable"""
        x=2
        y=3
        z=x+y
        return z
    return add()**2
print(square())

In [ ]:
# default arguments
#önceden tanımladığımız fonksiyonlar
def f(a,b=1,c=2):
    y=a+b+c
    return y
# eğer fonksiyonu döndürürken içine sadece 1 değer
# yazarsam onun a olduğunu anlar,zaten b ve c tanmlı
# ama eğer  değer girersem a,b ve c için o değerleri alır.
# sırayla alır,mesela a ve b için değer girip de c için 
# girmezsem c için default değeri alır,b ve a için 
# tanımlanan değeri alır.

In [ ]:
f(5)

In [ ]:
f(5,6)

In [ ]:
f(5,6,7)

In [ ]:
f(5,c=7)

In [ ]:
# flexible arguments *args
def f(*args):
    for i in args:
        print(i)
f(1)
f("")
f(1,2,3,4)

In [ ]:
def f(*args):
    a=0
    for i in args:
     a+=i
    return a
f(1,2)

In [ ]:
f(1,2,3,4,5,6,7,8,9)

In [ ]:
# flexible arguments **kwargs that is dictionary
def f(**kwargs):
    """print key and value of dictionary"""
    for key,value in kwargs.items():
# If you do not understand this part turn for loop part and look at dictionary in for loop
        print("key:",key,"value:",value)
f(country = 'spain', capital = 'madrid', population = 123456)

In [ ]:
#LAMBDA FUNCTION
square=lambda x: x**2
print(square(3))

In [ ]:
total=lambda a,b,c:a+b+c
print(total(3,-6,1))

In [ ]:
#ANONYMOUS FUNCTİON
number_list=[1,2,3]
y=map(lambda x:x**2,number_list)
print(list(y))

> ****Yani,lambda function ile 1 argument alabilirken,map ile list şeklinde birden fazla argument alabilir.****

In [ ]:
name="marcelo"
it=iter(name)
print(next(it)) # print next iteration

In [ ]:
print(*it) # print remaining iteration

In [ ]:
#zip(): zip lists
#iki listeyi zip etmek(birleştirmek)
list1=[1,2,3,4]
list2=[5,6,7,8]
z=zip(list1,list2)
print(z)
z_list=list(z)
print(z_list)

In [ ]:
#zip şeklindeki bir listeyi unzip ediyoruz. ==> zip(* ... )ile
un_zip=zip(*z_list)
unlist1,unlist2=list(un_zip) #burada list yada tuple diyebiliriz.
print(unlist1)               #ikisinde de tuple yapar.
print(unlist2)
print(type(unlist2))

In [ ]:
#unzip yapınca bunları tuple yaptı, istersek liste yapabiliriz.
print(list(unlist1))
print(type(list(unlist1)))

In [ ]:
#list comprehension
num1=[1,2,3]
num2=[i+1 for i in num1]
print(num2)

* [i + 1 for i in num1 ]: list of comprehension
* i +1: list comprehension syntax
* for i in num1: for loop syntax
* i: iterator
* num1: iterable object

In [ ]:
# Conditionals on iterable
num1 = [5,10,15]
num2=[i**2 if i==10 else i-5 if i<7 else i+5 for i in num1]
num2

In [ ]:
# lets return pokemon csv and make one more list comprehension example
# lets classify pokemons whether they have high or low speed. Our threshold is average speed.
data=pd.read_csv("/kaggle/input/pokemon-challenge/pokemon.csv")
threshold = sum(data.Speed)/len(data.Speed)
data["speed_level"] = ["high" if i > threshold else "low" for i in data.Speed]
data.loc[:10,["speed_level","Speed"]] # we will learn loc more detailed later

# DIAGNOSE DATA for CLEANING
We need to diagnose and clean data before exploring.
Unclean data:

Column name inconsistency like upper-lower case letter or space between words
missing data
different language

We will use head, tail, columns, shape and info methods to diagnose data

# EXPLORATORY DATA ANALYSIS
value_counts(): Frequency counts
outliers: the value that is considerably higher or lower from rest of the data

Lets say value at 75% is Q3 and value at 25% is Q1.
Outlier are smaller than Q1 - 1.5(Q3-Q1) and bigger than Q3 + 1.5(Q3-Q1). (Q3-Q1) = IQR
We will use describe() method. Describe method includes:
count: number of entries
mean: average of entries
std: standart deviation
min: minimum entry
25%: first quantile
50%: median or second quantile
75%: third quantile
max: maximum entry

What is quantile?

1,4,5,6,8,9,11,12,13,14,15,16,17
The median is the number that is in middle of the sequence. In this case it would be 11.

The lower quartile is the median in between the smallest number and the median i.e. in between 1 and 11, which is 6.

The upper quartile, you find the median between the median and the largest number i.e. between 11 and 17, which will be 14 according to the question above.

In [ ]:
#value_counts
print(data["Type 1"].value_counts(dropna=False)) # if there are nan values that also be counted
# As it can be seen below there are 112 water pokemon or 70 grass pokemon

In [ ]:
data.describe()

In [ ]:
data

# VISUAL EXPLORATORY DATA ANALYSIS
* Box plots: visualize basic statistics like outliers, min/max or quantiles

In [ ]:
data.boxplot(column="Attack",by="Legendary",figsize=(10,10))

> Attack'ları legendary olup olmamasına göre boxplot ettirdik. legendary'nin true ve false olmasına göre boxplot'lar çizdi.

* aşağıdaki çizgiler *min*
* yukarıdaki çizgiler *max*
* ortadaki kutu içindeki çizgi *median*
* kutunun üst kısmı *Q3*
* kutunun alt kısmı *Q1*
* bunların dışındaki yuvarlaklar *outlier*'lar

* For example: compare attack of pokemons that are legendary  or not
* Black line at top is max
* Blue line at top is 75%
* Red line is median (50%)
* Blue line at bottom is 25%
* Black line at bottom is min
* There are no outliers

In [ ]:
#TIDY DATA
# Firstly I create new data from pokemons data to explain melt nore easily.
data_new = data.head()    # I only take 5 rows into new data
data_new

In [ ]:
# lets melt
# id_vars = what we do not wish to melt
# value_vars = what we want to melt
melted=pd.melt(frame=data_new,id_vars="Name",value_vars=["Attack","Defense"])
melted

In [ ]:
#PIVOTING DATA
#Reverse of melting.

* Index is name
* I want to make that columns are variable
* Finally values in columns are value

### melted.pivot(index="Name",columns="variable",values="value")

In [ ]:
#CONCATENATING DATA
data1 = data.head()
data2= data.tail()
concat_data_row=pd.concat([data1,data2],axis=0,ignore_index=True)
concat_data_row

* pandas library'de olduğu için pd.concat alıyoruz. 
* axis=0 diyerek rowları alt alta birleştirdik.
* ignore_index=True diyerek solda yeni bir index column'ı oluşturuyoruz.
* eğer bunu demezsek indexleri eski indexleri alır. mesela 9 değil de 799 alır.

In [ ]:
# ignore_index=True demezsek;
data1 = data.head()
data2= data.tail()
concat_data_row=pd.concat([data1,data2],axis=0)
concat_data_row

In [ ]:
data["Type 1"]=data["Type 1"].astype("category")
data["Speed"]=data["Speed"].astype("float")

In [ ]:
data.dtypes

In [ ]:
#MISSING DATA and TESTING WITH ASSERT
data.info()
#type2 de 386 tane NaN varmış.

In [ ]:
data["Type 2"].value_counts(dropna =False)
#dropna false diyerek nan ları da yazdırmasını söyledik.

In [ ]:
# Lets drop nan values
data1=data.copy()
data1["Type 2"].dropna(inplace = True)
#inplace=True diyerek çıkardığın bu değerleri
#data1 içine kaydet demektir. Güncel hali
#data1 içine kaydetmiş olduk.
#PEKİ ÇALIŞTI MI?

* Bunun çalışıp çalışmadığını assert metodu ile kontrol edebiliriz.
* eğer assert bir şey döndürmezse bu doğru olduğunu gösterir.
* yanlış ise hata verir.

In [ ]:
# Assert statement:
assert 1==1 # return nothing because it is true

In [ ]:
# assert 1==2 # return error because it is false
#eğer bunu döndürürsek hata verir çünkü yanlış.

In [ ]:
assert  data1['Type 2'].notnull().all() # returns nothing because we drop nan values
#mesela bunu data için yapsak hata verirdi çünkü nan lar duruyor.

In [ ]:
data1["Type 2"].fillna("empty",inplace=True)
#boş yerleri "empty" yazısı ile doldurduk

In [ ]:
assert data1['Type 2'].notnull().all()  # returns nothing because we do not have nan values

In [ ]:
assert data1.columns[1]=="Name"
#1. column Name mi diye kontrol ediyoruz. bir şey döndürmüyor,demek ki doğru.

In [ ]:
assert data.Speed.dtypes == np.float

* With assert statement we can check a lot of thing. 
* For example; assert data.columns[1] == 'Name'
* assert data.Speed.dtypes == np.int

# REVİEW of PANDAS
* single column = series
* NaN = not a number
* dataframe.values = numpy

In [ ]:
# data frames from dictionary
country=["Turkey","France","USA"]
population=["80","70","300"]
capital=["Ankara","Paris","Washington DC"]
list_label=["country","population","capital"]
list_col=[country,population,capital]
zipped=list(zip(list_label,list_col))
data_dict=dict(zipped)
df=pd.DataFrame(data_dict)
df

In [ ]:
data_dict

In [ ]:
# Add new columns
df["EU"]=["False","True","False"]
df

In [ ]:
# Broadcasting
df["income"] = 0 #Broadcasting entire column
df

Broadcasting ile column akleme aynı şeydir, ikisinde de column eklenir ancak normal column eklerken herbir rowdaki data için ayrı bir data eklenir. broadcasting te ise tüm column'a aynı değer eklenir.

In [ ]:
#VISUAL EXPLORATORY DATA ANALYSIS
# Plotting all data 
data2=data.loc[:,["Attack","Defense","Speed"]]
data2.plot()
# it is confusing

In [ ]:
#subpolts
data2.plot(subplots=True)
plt.show()

In [ ]:
# scatter plot  
data2.plot(kind="scatter",x="Attack",y="Defense")
plt.show()

In [ ]:
# hist plot 
data2.plot(kind="hist")
#başka hibir şey girmezsek;

In [ ]:
# hist plot  
data2.plot(kind="hist",y = "Defense",bins = 50,range=(0,250),normed = True)

In [ ]:
# hist plot  
data2.plot(kind="hist",y = "Defense",bins = 50,range=(0,250))
#normed=True yazmazsak;

In [ ]:
# hist plot  
data2.plot(kind="hist",y = "Defense",bins = 50)
#range vermzesek;

In [ ]:
# hist plot  
data2.plot(kind="hist",y = "Defense",bins = 50,range=(0,1000))
#farklı bir range daha verelim;

In [ ]:
# histogram subplot with non cumulative and cumulative
fig,axes=plt.subplots(nrows=2,ncols=1)
data2.plot(kind="hist",y="Defense",bins=50,range=(0,250),normed=True,ax=axes[0]) #non-cumulative
data1.plot(kind = "hist",y = "Defense",bins = 50,range= (0,250),normed = True,ax = axes[1],cumulative=True) #cumulative
plt.savefig('graph.png')
plt

In [ ]:
# histogram subplot with non cumulative and cumulative
fig,axes=plt.subplots(nrows=4,ncols=1)
data2.plot(kind="hist",y="Defense",bins=50,range=(0,250),normed=True,ax=axes[0]) #non-cumulative
data1.plot(kind = "hist",y = "Defense",bins = 50,range= (0,250),normed = True,ax = axes[1],cumulative=True) #cumulative
plt.savefig('graph.png')
plt

In [ ]:
data2.plot(kind="hist",y="Defense",bins=50,range=(0,250),normed=True,ax=axes[0]) #non-cumulative
data1.plot(kind = "hist",y = "Defense",bins = 50,range= (0,250),normed = True,ax = axes[1],cumulative=True) #cumulative
plt.savefig('graph.png')
plt
#ilk satırı yazmazsak

In [ ]:
fig,at=plt.subplots(nrows=2,ncols=1)
data2.plot(kind="hist",y="Defense",bins=50,range=(0,250),normed=True,ax=at[0]) #non-cumulative
data1.plot(kind = "hist",y = "Defense",bins = 50,range= (0,250),normed = True,ax = at[1],cumulative=True) #cumulative
plt.savefig('graph.png')
plt
#burada axes yazanların hepsine ax ta yazazbiliriz, at da. ne yazdığımı zönemli değil. bir şey değişmez.

In [ ]:
fig,at=plt.subplots(nrows=2,ncols=1)
data2.plot(kind="hist",y="Defense",bins=50,range=(0,250),normed=True,ax=at[0]) #non-cumulative
data1.plot(kind = "hist",y = "Defense",bins = 50,range= (0,250),normed = True,ax = at[1],cumulative=True) #cumulative
plt
# plt.savefig('graph.png') yazmasak da olur.

In [ ]:
fig,axes=plt.subplots(nrows=2,ncols=1)
#data2.plot(kind="hist",y="Defense",bins=50,range=(0,250),normed=True,ax=axes[0]) #non-cumulative
data1.plot(kind = "hist",y = "Defense",bins = 50,range= (0,250),normed = True,ax = axes[1],cumulative=True) #cumulative
plt.savefig('graph.png')
plt

# INDEXING PANDAS TIME SERIES

In [ ]:
time_list=["1997-03-11","1997-10-22"]
print(type(time_list))
print(type(time_list[1]))
#biz string oluşturmuş olduk ama 
#biz datatime object istiyoruz.

In [ ]:
datatime_object=pd.to_datetime(time_list)
print(type(datatime_object))

In [ ]:
# close warning
import warnings
warnings.filterwarnings("ignore")
#yukardaki 3 satırın ne olduğu önemli değil, hata vermemesi için yazdık.
# In order to practice lets take head of pokemon data and add it a time list
data3=data.head()
data_list=["1991-01-10","1992-02-10","1992-03-10","1993-03-15","1993-03-16"]
datatime_object=pd.to_datetime(data_list)
data3["date"]=datatime_object
data3

date'i ayrı bir column olarak oluşturduk. şimdi de bu column'ı index sütunu yapalım:

In [ ]:
data3=data3.set_index("date")
data3
#index sütunumuz date'lerden oluşuyor.

In [ ]:
# Now we can select according to our date index
print(data3.loc["1993-03-16"])

In [ ]:
print(data3.loc["1992-03-10":"1993-03-16"])

# RESAMPLING PANDAS TIME SERIES

* M diyerek ay'a,A diyerek yıla göre resample yapabiliriz.
* resample=yeniden örneklendirmek

In [ ]:
data3.resample("A").mean()
#yılları mean'e göre resample ediyoruz.

1991'de tek veri olduğu için aynı ama diğer yıllarda mean'ini alıp yazıyor.

In [ ]:
data3.resample("M").mean()
#şimdi de ayları mean'e göre resample ediyoruz.

1993 3. ayında 2 veri var.bunların mean'ini alıyor,kalanlarda tek veri olanları aynen alıyor.
Değer olmayan aylarda NaN yazıyor.

In [ ]:
#data3.resample("M").first().interpolate("linear")
#sürekli hata veriyor,sorunu çözemedim.

In [ ]:
data3.resample("M").mean().interpolate("linear")

# MANIPULATING DATA FRAMES WITH PANDAS

### INDEXING DATA FRAMES

In [ ]:
#1st
# read data
data=pd.read_csv("/kaggle/input/pokemon-challenge/pokemon.csv")
data.head()

In [ ]:
#2nd
#index changing
data=data.set_index("#")
data.head()

In [ ]:
#3rd
# indexing using square brackets
data["Sp. Atk"][1]

In [ ]:
data.HP[1]

In [ ]:
data["HP"][1]

In [ ]:
data.loc[1,["HP"]]

In [ ]:
#4th
# Selecting only some columns
data[["HP","Attack"]]

# SLICING DATA FRAME

In [ ]:
#1st
# Difference between selecting columns: series and dataframes
print(type(data["HP"]))   # series
print(type(data[["HP"]])) # data frames

In [ ]:
#2nd
# Slicing and indexing series
data.loc[1:10,"HP":"Defense"]

In [ ]:
data.loc[1:10,["HP","Defense"]]

In [ ]:
#3rd
# Reverse slicing 
data.loc[10:1:-1,"HP":"Defense"]

In [ ]:
#4th
# From something to end
data.loc[1:10,"Speed":]
#Speed'den son column'a kadar tamamını aldık.

# FILTERING DATA FRAMES

In [ ]:
#1st
# Creating boolean series
boolean=data.HP>200
data[boolean]

In [ ]:
boolean=data.HP>200
print(boolean)

In [ ]:
boolean=data.HP>200
boolean

In [ ]:
#2nd
# Combining filters
first_filter = data.HP > 150
second_filter = data.Speed > 35
data[first_filter & second_filter]

In [ ]:
#3rd
# Filtering column based others
data.HP[data.Speed<15]

Burada, Speed'in <15 oluğu row'ları aldık.ama bu filtrelemeden sonra speed in değil hp nin bu filtredeki değerlerini yazdırdık.

# TRANSFORMING DATA

In [ ]:
#1st
# def ile func tanımlayarak;
# Plain python functions
def div(n):
    return n/2
data.HP.apply(div)

In [ ]:
#2nd
# apply lambda ile
# Or we can use lambda function
data.HP.apply(lambda n : n/2 )

In [ ]:
#3rd
# Defining column using other columns
data["Total_Power"]=data.Attack + data.Defense
data.head()

In [ ]:
data.Total_Power.head()

# INDEX OBJECTS AND LABELED DATA

In [ ]:
#1)Index'in ismini öğrenme:
print(data.index.name)

In [ ]:
#2)İndex'in ismini değiştirme
data.index.name="index_name"
data.head()

In [ ]:
#3)
# Overwrite index
# if we want to modify index we need to change all of them.
data.head()
# first copy of our data to data4 then change index 
data4 = data.copy()
# lets make index start from 100. It is not remarkable change but it is just example
data4.index=range(100,1700,2)
data4.head()

> index i 0 dan değil de 100 den başlattık ve 2şer 2şer artmasını söyledik. toplam 800 verimiz olduğu ve 2şer artacağı için 100+800.2=1700'ü de son olarak aldık.

* We can make one of the column as index. I actually did it at the beginning of manipulating data frames with pandas section
* It was like this
* data= data.set_index("#")
* also you can use 
* data.index = data["#"]

# HIERARCHICAL INDEXING

In [ ]:
data=pd.read_csv("/kaggle/input/pokemon-challenge/pokemon.csv")
data.head()

In [ ]:
#2 index column'ı oluşturma
# Setting index : type 1 is outer type 2 is inner index
data1=data.set_index(["Type 1","Type 2"])
data1.head(20)

# PIVOTING DATA FRAMES

In [ ]:
dic = {"treatment":["A","A","B","B"],"gender":["F","M","F","M"],"response":[10,45,5,9],"age":[15,4,72,65]}
df = pd.DataFrame(dic)
df

In [ ]:
# pivoting
df.pivot(index="treatment",columns = "gender",values="response")

# STACKING and UNSTACKING DATAFRAME

In [ ]:
df1=df.set_index(["treatment","gender"])
df1

In [ ]:
# lets unstack it
df1.unstack(level=0)
#2 index column ı var. biz 0. index column ını siliyoruz.

In [ ]:
df1.unstack(level=1)
#şimdi de 1. index column ını siliyoruz.

In [ ]:
#,ndex column'larının yerini değiştirelim.
# change inner and outer level index position
df2=df1.swaplevel(0,1)
df2

# MELTING DATA FRAMES

In [ ]:
df

In [ ]:
#df.pivot(index="treatment",columns="gender",values="response")
pd.melt(df,id_vars="treatment",value_vars=["age","response"])
# biz bir şey girmediğimiz sürece variable ve value columnları otomatik olarak gelir.

# CATEGORICALS AND GROUPBY

In [ ]:
# We will use df
df

In [ ]:
df.groupby("treatment").mean()  # mean is aggregation / reduction method
# there are other methods like sum, std,max or min

In [ ]:
# we can only choose one of the feature
df.groupby("treatment").age.max()

In [ ]:
df.groupby("treatment").max()

In [ ]:
df.groupby("treatment")[["age","response"]].min()

In [ ]:
df.groupby("treatment").min()