In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

**Hi Kagglers**,
> 
> Happy to see you back !
> 
> > **For Data Analysis**, 
> > > Selecting specific values of a pandas DataFrame or Series to work on is the first step.
> 
> > > **Data Scientists** use these basic yet effective ways of indexing and slicing DataFrame almost daily.
> 
> If there is any point in the notebook, you need better explanation about, Please let me know in comments.

Happy to help !

Lets start by reading a csv file.

In [ ]:
import pandas as pd

In [ ]:
student=pd.read_csv("../input/student-grade-prediction/student-mat.csv")

In [ ]:
student

**Acessing a particular column in DataFrame:**
1. df.columnname
2. df["columnname"]

In [ ]:
student.school

In [ ]:
student["Mjob"]

For selecting a column,
**The indexing operator [] has a advantage that it can handle column names with reserved characters in them (e.g. if here we had a  "school name"column), student.school name wouldn't work. why?
Because of the space in the column name**

Reaching a specific value in pandas is super easy. Just use indexing operator once more to specify the position

In [ ]:
student['Fjob'][3]

**Index-based selection**
selecting data based on its numerical position in the data.
**iloc** follows this approach.

To select the first row of data in a DataFrame, use the below way.

In [ ]:
student.iloc[0]

Both loc and iloc are row-first, column-second. To get a column with iloc, we can do the following:

In [ ]:
student.iloc[:,0]

The : operator, means "everything". When combined with other selectors, however, it can be used to indicate a range of values. For example, to select the school column from just the first, second, and third row, we would do:-

In [ ]:
student.iloc[:3,0]

Or, to select just the second and third entries, we would do:

In [ ]:
student.iloc[1:3,0]

It's also possible to pass a list  of both rows and columns we need:-

In [ ]:
student.iloc[[0,1,2,3,4,5,6,7,8,21,13,12],[0,2,4]]

Negative numbers can be used in selection.
This will start counting forwards from the end of the values.
So for example here are the last five elements of the dataset. we will have option of using
df.tail(5) or df.iloc[-5:]

In [ ]:
student.iloc[-5] #the 5th last row data

In [ ]:
student.iloc[-5:] #data of last 5 rows

**Label-based selection**

**loc** follows this approach.
For example, to get the first entry in student, we would now do the following:

In [ ]:
student.loc[0,'school']

**iloc** is conceptually simpler than loc because it ignores the dataset's indices. When we use iloc we treat the dataset like a big matrix (a list of lists), one that we have to index into by position. 
**loc**, uses the information in the indices to do its work. Since dataset usually has meaningful indices, it's usually easier to do things using loc instead. 

For example, here's one operation that's much easier using loc

In [ ]:
student.loc[:,['school','age','Mjob','Fjob']]

**Manipulating the index**
Label-based selection derives its power from the labels in the index.
The set_index() method can be used to do the job

In [ ]:
student.set_index("school")

**Conditional selection**

In [ ]:
student.loc[(student.school=="MS") & (student.Mjob=="other") & (student.age>=19)]

Pandas comes with a few built-in conditional selectors.

The first is **isin**. 
isin is lets you select data whose value "is in" a list of values. 
For example, here's how we can use it to select students whose mother works in service sector or is a teacher.

In [ ]:
student.loc[student.Mjob.isin (["services","teacher"])]

In [ ]:
student.loc[(student.Fjob.isin(["health","at_home"])) & (student.Mjob.isin(["teacher"]))]

**Assigning data** to new column
        1. create new column
        2.Add values to that column
        
Say, 
 here we wanna add character of student

In [ ]:
student["character"]="Good"
student

Observe, 
 A column named character is added at the end of the DataFrame.

Select the character column from student and assign the result to the variable personality

In [ ]:
student['personality']=student.character
student

Create a variable df containing the school and famsize columns of the first 100 records.

In [ ]:
df=student.loc[0:99,["school","famsize"]]
df

# the other ways to do same are listed below as comments.



#cols = ["school","famsize"]
#df = school.loc[:99, cols]


#or

#cols_idx = [0, 4] # school is at index 0 and famsize at index 4

#df = reviews.iloc[:100, cols_idx]"""