In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dfreal = pd.read_csv("/kaggle/input/suicides-in-india/Suicides in India 2001-2012.csv")
dfreal['State'].unique()

# notice that there are states and ut's and also total count of states,ut's and total of both
#'Total (All India)', 'Total (States)', 'Total (Uts)'

In [ ]:
dfreal.head(3)

In [ ]:
# Getting rid of Totals of states and ut's...
               #as they will be added again while grouping states and thus give the wrong count.
df = dfreal[dfreal['State']!='Total (All India)']    
df = df[dfreal['State']!= 'Total (States)']        
df = df[dfreal['State']!= 'Total (Uts)']
df = df[dfreal['Age_group']!= '0-100+']       # similarly for age group of 0-100+

In [ ]:
df['State'].unique()

In [ ]:
df['Age_group'].unique()

In [ ]:
df.info()

In [ ]:
plt.figure(figsize=(10,5))
sns.heatmap(df.isnull(),cmap='coolwarm')        #No null data

In [ ]:
bygen = pd.DataFrame(df.groupby('Gender')['Total'].sum())
bygen = bygen.reset_index()                               # grouping by Gender
bygen

In [ ]:
bygen.sum()                           # Total suicide count is 4336148 (men and women)

In [ ]:
sns.barplot(x='Gender', y='Total', data=bygen )

In [ ]:
bystate = pd.DataFrame(df['Total'].groupby(df['State']).sum())  
bystate = bystate.reset_index().sort_values('Total',ascending =False)  # Grouping by State
bystate

In [ ]:
bystate['Total'].sum()  # total suicide count is 4336148(total states count) to keep track that our code is right

In [ ]:
plt.figure(figsize=(12,4))
sns.barplot(x='State',y='Total', data=bystate)
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

In [ ]:
byage = pd.DataFrame(df.groupby('Age_group')['Total'].sum())
byage = byage.reset_index()               # Grouping by Age_group
byage                                     # No 0-100+ age group as we removed it earlier.

In [ ]:
sns.barplot(x='Age_group', y='Total' ,data=byage)  # People of younger age are the most afected.

In [ ]:
x = pd.DataFrame(df.groupby(['Age_group','Gender'])['Total'].sum())
plt.figure(figsize=(10,4))
sns.set_style('darkgrid')                                    
sns.lineplot(x='Age_group', y='Total' ,data=x, hue = 'Gender')

 # VERY CLEAR THAT IT'S NOT EASY BEING A MAN

In [ ]:
 df['Type_code'].unique()

In [ ]:
cause = df[df['Type_code']=='Causes'].sort_values(by='Total',ascending = False)

In [ ]:
plt.figure(figsize=(12,8))
sns.barplot(x='Type',y='Total',hue='Gender',data=cause, palette=['C1','C0'])
plt.xticks(rotation=90)
plt.title('Causes vs suicides \n \n')
plt.tight_layout()
plt.show()

In [ ]:
profession = df[df['Type_code']=='Professional_Profile'].sort_values(by='Total',ascending = False)

In [ ]:
plt.figure(figsize=(12,7))
hue_order = ['Male','Female']
sns.barplot(x='Type',y='Total',hue='Gender',hue_order=hue_order ,data=profession, palette=['C1','C0'])
plt.xticks(rotation=90)
plt.title('Profession_profile vs suicides \n \n')
plt.xlabel('Profession')
plt.ylabel('Total suicides')
plt.tight_layout()
plt.show()

In [ ]:
byyear = pd.DataFrame(df.groupby(['Year','Gender'])['Total'].sum())
byyear = byyear.reset_index()                                         # Grouping by Year
byyear

In [ ]:
plt.figure(figsize=(12,5))
sns.lineplot(x='Year', y='Total', data=byyear, lw=2, marker="*", markersize=10, color ='r')
plt.title('Suicides - year_wise')
plt.xlabel('\n \n  Year')
plt.ylabel('Total Suicides')
plt.tight_layout()
plt.show()

In [ ]:
bystate.head()

In [ ]:
# Checking the situation in Andhra Pradesh

ap = df[df['State']=='Andhra Pradesh']
ap_c = ap[ap['Type_code']=='Causes']
ap_c = pd.DataFrame(ap.groupby('Type')['Total'].sum()).reset_index().sort_values(by = 'Total',ascending=False)

ap_p = ap[ap['Type_code']=='Professional_Profile']
ap_P = pd.DataFrame(ap_p.groupby('Type')['Total'].sum()).reset_index().sort_values(by = 'Total',ascending=False)

In [ ]:
plt.figure(figsize=(12,5))
plt.tight_layout()
sns.barplot(x='Type',y='Total',data=ap_p)
plt.title('SUICIDES VS PROFESSION')
plt.tight_layout()
plt.xticks(rotation=90)
plt.show()

In [ ]:
plt.figure(figsize=(12,6))
plt.tight_layout()
sns.barplot(x='Type',y='Total',data=ap_c)
plt.title('SUICIDES VS CAUSES ')
plt.tight_layout()
plt.xticks(rotation=90)
plt.show()

# **CONCLUSION** #


* **Most of the Suicide victims in India are Men.**
* **The Age groups of 15-29 and 30-44 were the most vulnerable to most suicides.**
* **Most men suffer fom stress related issues as suicides due to family problems, insanity/mental issues and drug addiction are higher among them.**
* **Most women face family problems and dowry issues as suicides are mostly seen among married women who are housewives.**
* **The states of (Maharashtra, West Bengal, Tamil Nadu, Andhra Pradesh and Karnataka) had the most suicide deaths.(SOUTH STATES)**
* **In the state of AP, suicides are higher among Farmers and houswives**