
<h1 style="font-size:50px;" ><center>  Space Missions ðŸš€ </center></h1>

<img src="https://specials-images.forbesimg.com/imageserve/5e3192b5f133f400076b0339/960x0.jpg?fit=scale" width="800" height="500" align="center"/>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objs as go
import plotly.figure_factory as ff
import plotly.express as px
from iso3166 import countries

In [ ]:
data = pd.read_csv('../input/all-space-missions-from-1957/Space_Corrected.csv')
data = data.drop(['Unnamed: 0','Unnamed: 0.1'],axis=1)
data.head()

In [ ]:
data[' Rocket'] = data[' Rocket'].str.replace(' ', '')
data[' Rocket'] = data[' Rocket'].str.replace(',', '')
data[' Rocket'] = data[' Rocket'].fillna(0)
data[' Rocket'] = data[' Rocket'].astype(float)

In [ ]:
data.columns

# Mission Status

In [ ]:
plt.figure(figsize=(8,6))
plt.title('Mission Status')
sns.countplot(data = data, x = 'Status Mission')

# Rocket Status

In [ ]:
plt.figure(figsize=(8,6))
sns.countplot(data = data, x = 'Status Rocket')

In [ ]:
topcompany = data.groupby(['Company Name'])[' Rocket'].sum()
topcompany = topcompany.to_frame().reset_index()
topcompany.columns = ['Company Name','Spent Money']
topcompany = topcompany[topcompany['Spent Money']!=0]

# Company spending money in millions

In [ ]:
plt.figure(figsize=(10,8))
sns.barplot(data = topcompany, y ='Company Name',x = 'Spent Money')

In [ ]:
data['date'] = pd.to_datetime(data['Datum'])
data['year'] = data['date'].apply(lambda datetime: datetime.year)
data['month'] = data['date'].apply(lambda datetime: datetime.month)
data['weekday'] = data['date'].apply(lambda datetime: datetime.weekday())

In [ ]:
plt.figure(figsize=(12,5))
sns.countplot(data['year'])
plt.xticks(rotation=90)

In [ ]:
data['country'] = data['Location'].str.split(', ').str[-1]
data.loc[data['country'] == 'Russia', 'country'] = 'Russian Federation'
data.loc[data['country'] == 'New Mexico', 'country'] = 'Mexico'

In [ ]:
!pip install iso3166

In [ ]:
from iso3166 import countries

country_dict = {}

for c in countries:
    country_dict[c.name] = c.alpha3

data['alpha3'] = data['country']
data = data.replace({"alpha3": country_dict})
data.loc[data['country'] == "North Korea", 'alpha3'] = "PRK"
data.loc[data['country'] == "South Korea", 'alpha3'] = "KOR"

In [ ]:
geomap = data.groupby(['country', 'alpha3'])['Status Mission'].count().reset_index()

Geo Map Credits : [isaienkov](https://www.kaggle.com/isaienkov)

# Geo Map

In [ ]:
continent = ['Asia','Europe','Africa','Americas','Oceania']
fig = px.scatter_geo(geomap, locations="alpha3",
                     hover_name="country",
                     size="Status Mission",
                     projection="natural earth", 
                     width=800, 
                     height=600, 
                     title='Number of missions country-wise')
fig.show()

# Country with the most successful missions

In [ ]:
susmiss = data[data['Status Mission']=='Success']
susmiss = susmiss['country'].value_counts().reset_index()
susmiss.columns = ['Country','Number of successful missions']

In [ ]:
plt.figure(figsize=(7,8))
sns.barplot(data= susmiss, y = 'Country', x= 'Number of successful missions')

# Countries with the most failed missions

In [ ]:
failmiss = data[data['Status Mission']!='Success']
failmiss = failmiss['country'].value_counts().reset_index()
failmiss.columns = ['Country','Number of failed missions']

In [ ]:
plt.figure(figsize=(7,8))
sns.barplot(data= failmiss, y = 'Country', x= 'Number of failed missions')

# Space Company with the most successful missions

In [ ]:
suscomp = data[data['Status Mission']=='Success']
suscomp = suscomp['Company Name'].value_counts().reset_index()
suscomp.columns = ['Company Name','Number of successful missions']

In [ ]:
plt.figure(figsize=(10,14))
sns.barplot(data= suscomp, y = 'Company Name', x= 'Number of successful missions')

# Space Company with the most failed missions

In [ ]:
failcomp = data[data['Status Mission']!='Success']
failcomp = failcomp['Company Name'].value_counts().reset_index()
failcomp.columns = ['Company Name','Number of failed missions']

In [ ]:
plt.figure(figsize=(10,14))
sns.barplot(data= failcomp, y = 'Company Name', x= 'Number of failed missions')

<span style='color:Red'><center> If you find this notebook useful then please treat me with an upvote :).  </span>