In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# > ****EDA ON STUDENTS-PERFORMANCE DATASET:
Introduction:
In this notebook, I have done the Exploratory Data Analysis of the STUDENTS-PERFORMANCE dataset. ********

In [ ]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# **Preliminary Data Processing:
To start off, we read in our dataset and generate a simple preview and statistics of our data.

Loading Data:

In [ ]:
df=pd.read_csv("/kaggle/input/students-performance-in-exams/StudentsPerformance.csv")
df

The output shows that we have around 1000 entries with 7 columns in our dataset.

# **Understanding the Data:

In [ ]:
df.head()

The output shows the first 4 rows of our dataset.

In [ ]:
df.tail()

The output shows the first 5 rows of our dataset.

In [ ]:
df.shape

we have 1000 records with 8 columns

In [ ]:
df.columns

The output shows the names of the columns in our dataset

In [ ]:
df.dtypes.value_counts()

5 of the columns are objects while the other 3 are categorical which is seen by dtpes function.

In [ ]:
df.describe(include="all")

This method generates a high-level summary of the attributes over each column of the dataset. More probably, it provides the statistical insights of the dataset.

In [ ]:
df.info()

Here is the more information of our dataset chosen. We can see that all the columns of our dataset are free from null values.

In [ ]:
df.duplicated().sum()

From this output, it is clear that we don't have any duplicates in our dataset.

In [ ]:
df["gender"].value_counts()

Here, we observed that our dataset is not balanced to the mark as there are two different gender of which female is the most occurring gender.

In [ ]:
df.lunch.unique()

So, we are having two different lunch in our dataset.

In [ ]:
df.isnull().sum()

Here,we get the missing values in each column present in our dataset.

In [ ]:
df.dropna(inplace=True)
df.head()

From this,we are getting the dataset by removing all the inconsistency present in it.

In [ ]:
df.iloc[:10,:3]

In [ ]:
df.loc[:,["race/ethnicity","parental level of education"]]

# Visualization:


> COUNT PLOT

In [ ]:
plt.title('NO of femal')
plot=sns.countplot(x="gender",data=df)

From this visualization,we can observe that our dataset is not balanced as we don't have equal number of count of the femal. We can also observe that we have more number of female in the data.

> # SCATTER PLOT

In [ ]:
plot=sns.scatterplot(x='math score',y='reading score',hue="gender",data=df)

From the above visualization, we can tell that the female has smaller reading score but higher math score.

In [ ]:
fig, axs = plt.subplots(figsize = (6,6))
plot=sns.stripplot(x="gender",y="reading score",hue="writing score",data=df);

From the above visualization,we observed that the male  has higher readingscore when compared to female  of our dataset.

# BOX PLOT

In [ ]:
fig, axs = plt.subplots(figsize = (8,6))
plot=sns.boxplot(x="gender",y="math score",data=df)

here we can obger the male and female mathe score almost equal.

# Correlation Between Variables

In [ ]:
fig = plt.figure(figsize = (15,9))
sns.heatmap(df.corr(), cmap='Reds', annot = True);

# HIST PLOT

In [ ]:
df.hist(edgecolor='black',bins = 25, figsize= (12,6))
plt.show()

Here,we can visualize the distribution of mathe score, and reading score of our dataset.

# PAIR PLOT

In [ ]:
sns.pairplot(data = df,hue="gender", height=3)

pairplot is showing the bivariate relation between each pair of features. From the pairplot, we'll see that the Gento reading score is separataed from the other one across all  combinations


# JOINT PLOT

In [ ]:
sns.jointplot(x="reading score", y="math score", data=df,height=5)
plt.show()

We can also use the seaborn library to make a similar plot. A seaborn jointplot shows bivariate scatterplots and univariate histograms in the same figure.

# VIOLIN PLOT

In [ ]:
sns.violinplot(x="gender", y="math score", data=df, size=6)
plt.show()

Here,we can observe that bothfemale and male have almost equal range of math scores.

CONCLUSION:
*The dataset is not balanced i.e. equal records are not present for all three species.
*We have two numerical columns while two categorical columns.
*I think that bothe male and female genders have equal no of scores in mathes
*