**Content:**
1. [Introduction to Python:](#1)
    1. [Matplotlib](#2)
    1. [Dictionaries ](#3)
    1. [Pandas](#4)
    1. [Logic, control flow and filtering](#5)
    1. [Loop data structures](#6)
1. [Python Data Science Toolbox:](#7)
    1. [User defined function](#8)
    1. [Scope](#9)
    1. [Nested function](#10)
    1. [Default and flexible arguments](#11)
    1. [Lambda function](#12)
    1. [Anonymous function](#13)
    1. [Iterators](#14)
    1. [List comprehension](#15)
1. [Cleaning Data](#16)
    1. [Diagnose data for cleaning](#17)
    1. [Exploratory data analysis](#18)
    1. [Visual exploratory data analysis](#19)
    1. [Tidy data](#20)
    1. [Pivoting data](#21)
    1. [Concatenating data](#22)
    1. [Data types](#23)
    
1. [Pandas Foundation](#25)
    1. [Review of pandas](#26)
    1. [Building data frames from scratch](#27)
    1. [Visual exploratory data analysis](#28)
    1. [Statistical explatory data analysis](#29)
    1. [Indexing pandas time series](#30)
    1. [Resampling pandas time series](#31)
    
1. [Manipulating Data Frames with Pandas](#32)
    1. [Indexing data frames](#33)
    1. [Slicing data frames](#34)
    1. [Filtering data frames](#35)
    1. [Transforming data frames](#36)
    1. [Index objects and labeled data](#37)
    1. [Hierarchical indexing](#38)
    1. [Pivoting data frames](#39)
    1. [Stacking and unstacking data frames](#40)
    1. [Melting data frames](#41)
    1. [Categoricals and groupby](#42)

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

In [ ]:
data_2015=pd.read_csv('../input/2015.csv')
data_2016=pd.read_csv('../input/2016.csv')
data_2017=pd.read_csv('../input/2017.csv')

In [ ]:
data_2015.info()
print("****************************************")
data_2016.info()
print("****************************************")
data_2017.info()

In [ ]:
data_2015.corr()

In [ ]:
data_2016.corr()

In [ ]:
data_2017.corr()

In [ ]:
#correlation map
f,ax = plt.subplots(figsize=(18, 18))
sns.heatmap(data_2015.corr(), annot=True, linewidths=.5, fmt= '.3f',ax=ax)
plt.show()

In [ ]:
data_2015.head(3)

In [ ]:
data_2016.head(3)

In [ ]:
data_2017.head(3)

In [ ]:
data_2015.columns

In [ ]:
data_2016.columns

In [ ]:
data_2017.columns

In [ ]:
data_2015.columns=[each.split()[0]+"_"+each.split()[1] if(len(each.split())>1) else each for each in data_2015.columns]
data_2016.columns=[each.split()[0]+"_"+each.split()[1] if(len(each.split())>1) else each for each in data_2016.columns]
data_2015.rename(columns = {"Economy_(GDP": "Economy","Health_(Life": "Health","Trust_(Government": "Trust"},inplace = True)
data_2016.rename(columns = {"Economy_(GDP": "Economy","Health_(Life": "Health","Trust_(Government": "Trust"},inplace = True)
data_2015.columns

In [ ]:
data_2017.columns=[each.replace(".","_") for each in data_2017.columns]
data_2017.columns

<a id="1"></a> <br>
# 1. INTRODUCTION TO PYTHON

<a id="2"></a> <br>
### MATPLOTLIB

In [ ]:
### Line Plot
data_2015.Happiness_Score.plot(kind='line',color='y', label='Happiness Score 2015',linewidth=1.5,alpha=0.9,grid=True,linestyle='--')
data_2016.Happiness_Score.plot(kind='line',color='b', label='Happiness Score 2016',linewidth=1.5,alpha=0.9,grid=True,linestyle='--')
data_2017.Happiness_Score.plot(kind='line',color='g', label='Happiness Score 2017',linewidth=1.5,alpha=0.9,grid=True,linestyle='--')
plt.legend(loc='upper right')
plt.xlabel('Rank')
plt.ylabel('Score')
plt.title('Happiness Score Line Plot')
plt.show()

In [ ]:
# Scatter Plot 
# x = Economy, y = Happiness Score
data_2015.plot(kind='scatter', x='Economy', y='Happiness_Score',alpha = 0.5,color = 'orange')
data_2016.plot(kind='scatter', x='Economy', y='Happiness_Score',alpha = 0.5,color = 'black')
data_2017.plot(kind='scatter', x='Economy__GDP_per_Capita_', y='Happiness_Score',alpha = 0.5,color = 'purple')
plt.xlabel('Economy')              # label = name of label
plt.ylabel('Happiness Score')
plt.title('Economy Happiness Scatter Plot')            # title = title of plot
plt.show()

In [ ]:
# Histogram
# bins = number of bar in figure
data_2015.Happiness_Score.plot(kind = 'hist',bins = 10,figsize = (10,10))
plt.show()

<a id="3"></a> <br>
### DICTIONARY

In [ ]:
#create dictionary and look its keys and values
dictionary={'Name':'Murat', 'Height':'180','Weight':'70'}
print(dictionary.keys())
print(dictionary.values())

In [ ]:
dictionary['Name']="Ahmet"        #update existing entry
print(dictionary)
dictionary['Country']="Turkey"    # add new entry
print(dictionary)
del dictionary['Weight']          #remove 'Weight'
print(dictionary)
print('Height' in dictionary)     #check include or not
dictionary.clear()                #remove all 
print(dictionary)

<a id="4"></a> <br>
### PANDAS

In [ ]:
data=pd.read_csv('../input/2015.csv')

In [ ]:
series=data['Country']           #data['Country'] = series
print(type(series))
data_frame=data[['Country']]     #data[['Country']] = data frame
print(type(data_frame))

<a id="5"></a> <br>
Before continue with pandas,   we need to learn **logic, control flow** and **filtering.**
<br>Comparison operator:  ==, <, >, <=
<br>Boolean operators: and, or ,not
<br> Filtering pandas

In [ ]:
# Comparison operator
print(3 > 2)
print(3!=2)
# Boolean operators
print(True and False)
print(True or False)

In [ ]:
# 1- Filtering Pandas data frame 
meanHappiness_Score2015=data_2015.Happiness_Score.mean()
meanHappiness_Score2016=data_2016.Happiness_Score.mean()
meanHappiness_Score2017=data_2017.Happiness_Score.mean()

x=data_2015['Happiness_Score']>meanHappiness_Score2015*1.33
data_2015[x]

In [ ]:
# 2- Filtering pandas with logical
data_2016[(data_2016['Happiness_Score']>meanHappiness_Score2016) & (data_2016.Economy.mean()>data_2016['Economy'])]
### or
#data_2016[np.logical_and(data_2016['Happiness_Score']>meanHappiness_Score2016), (data_2016.Economy.mean()>data_2016['Economy'])]

<a id="6"></a> <br>
### WHILE and FOR LOOPS
We will learn most basic while and for loops

In [ ]:
# Stay in loop if condition( i is not equal 5) is true
i = 0
while i != 5 :
    print('i is: ',i)
    i +=1 
print(i,' is equal to 5')

In [ ]:
# Stay in loop if condition( i is not equal 5) is true
lis = [1,2,3,4,5]
for i in lis:
    print('i is: ',i)
print('')

# Enumerate index and value of list
# index : value = 0:1, 1:2, 2:3, 3:4, 4:5
for index, value in enumerate(lis):
    print(index," : ",value)
print('')   

# For dictionaries
# We can use for loop to achive key and value of dictionary. We learnt key and value at dictionary part.
dictionary = {'spain':'madrid','france':'paris'}
for key,value in dictionary.items():
    print(key," : ",value)
print('')

# For pandas we can achieve index and value
for index,value in data[['Country']][0:1].iterrows():
    print(index," : ",value)

<a id="7"></a> <br>
# 2. PYTHON DATA SCIENCE TOOLBOX

<a id="8"></a> <br>
### USER DEFINED FUNCTION

What we need to know about functions:
* docstrings: documentation for functions. Example:
<br>for f():
    <br>"""This is docstring for documentation of function f"""
* tuble: sequence of immutable python objects. 
<br>cant modify values
<br>tuble uses paranthesis like tuble = (1,2,3)
<br>unpack tuble into several variables like a,b,c = tuble

In [ ]:
# example of what we learn above
def tuble_ex():
    """ return defined t tuble"""
    t = (1,2,3)
    return t
a,b,c = tuble_ex()
print(a,b,c)

<a id="9"></a> <br>
### SCOPE
What we need to know about scope:
* global: defined main body in script
* local: defined in a function
* built in scope: names in predefined built in scope module such as print, len
<br><br>Lets make some basic examples

In [ ]:
# guess print what
x = 2
def f():
    x = 3
    return x
print(x)      # x = 2 global scope
print(f())    # x = 3 local scope

In [ ]:
# What if there is no local scope
x = 5
def f():
    y = 2*x        # there is no local scope x
    return y
print(f())         # it uses global scope x
# First local scopesearched, then global scope searched, if two of them cannot be found lastly built in scope searched.

<a id="10"></a> <br>
### NESTED FUNCTION
* function inside function.
* There is a LEGB rule that is search local scope, enclosing function, global and built in scopes, respectively.

In [ ]:
#nested function
def ort():
    """ return square of value """
    def topla():
        """ add two local variable """
        vize = 20
        final = 80
        topl = vize + final
        return topl
    return topla()/2
print(ort())

<a id="11"></a> <br>
### DEFAULT and FLEXIBLE ARGUMENTS
* Default argument example:
<br> def f(a, b=1):
        """ b = 1 is default argument"""
* Flexible argument example:
<br> def f(*args):
       """ *args can be one or more"""
<br>def f(** kwargs)
       """ **kwargs is a dictionary"""
       
<br><br> lets write some code to practice

In [ ]:
# default arguments
def f(a, b = 1, c = 2):
    y = a + b + c
    return y
print(f(5))
# what if we want to change default arguments
print(f(5,4,3))

In [ ]:
# flexible arguments *args
def f(*args):
    for i in args:
        print(i)
f(1)
print("")
f(1,2,3,"murat","ali")


# flexible arguments **kwargs that is dictionary
def f(**kwargs):
    """ print key and value of dictionary"""
    for key, value in kwargs.items():               # If you do not understand this part turn for loop part and look at dictionary in for loop
        print(key, " ", value)
f(country = 'spain', capital = 'madrid', population = 123456)

<a id="12"></a> <br>
### LAMBDA FUNCTION
Faster way of writing function

In [ ]:
# lambda function
square = lambda x: x**2     # where x is name of argument
print(square(4))

#long way
def Square(x):
    return x**2
print(Square(5))

In [ ]:
tot = lambda x,y,z: x+y+z   # where x,y,z are names of arguments
print(tot(1,2,3))

#long way

def Tot(x,y,z):
    return x+y+z
print(Tot(1,5,9))

<a id="13"></a> <br>
### ANONYMOUS FUNCTİON
Like lambda function but it can take more than one arguments.
* map(func,seq) : applies a function to all the items in a list

In [ ]:
number_list = [1,2,3]
y = map(lambda x:x**2,number_list)
print(list(y))

<a id="14"></a> <br>
### ITERATORS
* iterable is an object that can return an iterator
* iterable: an object with an associated iter() method
<br> example: list, strings and dictionaries
* iterator: produces next value with next() method

In [ ]:
# iteration example
name = "murat"
it = iter(name)
print(next(it))    # print next iteration
print(next(it))
print(*it)         # print remaining iteration

#population=985614
#it2=iter(population)
#print(next(it2))
#print(*it2)

#'int' object is not iterable

<a id="15"></a> <br>
### LIST COMPREHENSİON
**One of the most important topic of this kernel**
<br>We use list comprehension for data analysis often. 
<br> list comprehension: collapse for loops for building lists into a single line
<br>Ex: num1 = [1,2,3] and we want to make it num2 = [2,3,4]. This can be done with for loop. However it is  unnecessarily long. We can make it one line code that is list comprehension.

In [ ]:
# Example of list comprehension
num1 = [1,2,3]
num2 = [i**2 for i in num1 ]
print(num2)

In [ ]:
# Conditionals on iterable
num1 = [5,10,15]
num2 = [i**2 if i == 10 else i-5 if i < 7 else i+5 for i in num1]
print(num2)

In [ ]:
threshold=sum(data_2015.Happiness_Score)/len(data_2015.Happiness_Score)
data_2015["Happiness_Level"]=["high" if i > threshold else "low" for i in data_2015.Happiness_Score]
data_2015.loc[:5,["Happiness_Level","Happiness_Score"]]

<a id="16"></a> <br>
# 3.CLEANING DATA

In [ ]:
data=pd.read_csv('../input/2015.csv')
data.head()

In [ ]:
data.tail()

In [ ]:
data.columns

In [ ]:
data.shape

In [ ]:
data.info()

<a id="18"></a> <br>
### EXPLORATORY DATA ANALYSIS

In [ ]:
print(data['Region'].value_counts(dropna =False))  # if there are nan values that also be counted

In [ ]:
data.describe()

<a id="19"></a> <br>
### VISUAL EXPLORATORY DATA ANALYSIS
* Box plots: visualize basic statistics like outliers, min/max or quantiles

In [ ]:
# Black line at top is max
# Blue line at top is 75%
# Red line is median (50%)
# Blue line at bottom is 25%
# Black line at bottom is min
# There are no outliers
data.boxplot(column='Happiness Score',by = 'Region',rot=90, fontsize=8)

<a id="20"></a> <br>
### TIDY DATA
We tidy data with melt().
Describing melt is confusing. Therefore lets make example to understand it.

In [ ]:
data_new=data.head()
data_new

In [ ]:
# lets melt
# id_vars = what we do not wish to melt
# value_vars = what we want to melt
melted=pd.melt(frame=data_new,id_vars='Country',value_vars=['Happiness Score','Freedom'])
melted

<a id="21"></a> <br>
### PIVOTING DATA
Reverse of melting.

In [ ]:
# Index is name
# I want to make that columns are variable
# Finally values in columns are value
melted.pivot(index = 'Country', columns = 'variable',values='value')

<a id="22"></a> <br>
### CONCATENATING DATA
We can concatenate two dataframe

In [ ]:
 # Firstly lets create 2 data frame
data1=data.head()
data2=data.tail()
conc_data_row=pd.concat([data1,data2],axis=0,ignore_index=True)  # axis = 0 : adds dataframes in row
conc_data_row

In [ ]:
data11=data['Generosity'].head()
data22=data['Freedom'].head()
conc_data_col=pd.concat([data11,data22],axis=1)
conc_data_col

<a id="23"></a> <br>
### DATA TYPES
There are 5 basic data types: object(string),booleab,  integer, float and categorical.
<br> We can make conversion data types like from str to categorical or from int to float
<br> Why is category important: 
* make dataframe smaller in memory 
* can be utilized for anlaysis especially for sklear(we will learn later)

In [ ]:
data.dtypes

In [ ]:
data['Happiness Rank']=data['Happiness Rank'].astype('float')
data['Region']=data['Region'].astype('category')

In [ ]:
data.dtypes

<a id="25"></a> <br>
# 4. PANDAS FOUNDATION

<a id="26"></a> <br>
### REVİEW of PANDAS
As you notice, I do not give all idea in a same time. Although, we learn some basics of pandas, we will go deeper in pandas.
* single column = series
* NaN = not a number
* dataframe.values = numpy

<a id="27"></a> <br>
### BUILDING DATA FRAMES FROM SCRATCH
* We can build data frames from csv as we did earlier.
* Also we can build dataframe from dictionaries
    * zip() method: This function returns a list of tuples, where the i-th tuple contains the i-th element from each of the argument sequences or iterables.
* Adding new column
* Broadcasting: Create new column and assign a value to entire column

In [ ]:
#data frames from dictionary
name=["murat","volkan","sedat"]
province=["kocaeli","erzurum","ankara"]
list_label=["name","province"]
list_col=[name,province]
zipped=list(zip(list_label,list_col))
data_dict=dict(zipped)
df=pd.DataFrame(data_dict)
df

In [ ]:
#add new columns
df["age"]=[21,28,32]
df

In [ ]:
#broadcasting
df["height"]=180
df

<a id="28"></a> <br>
### VISUAL EXPLORATORY DATA ANALYSIS
* Plot
* Subplot
* Histogram:
    * bins: number of bins
    * range(tuble): min and max values of bins
    * normed(boolean): normalize or not
    * cumulative(boolean): compute cumulative distribution

In [ ]:
# Plotting all data 
data1=data.loc[:,["Family","Freedom","Generosity"]]
data1.plot()
# it is confusing

In [ ]:
#subplots
data1.plot(subplots=True)
plt.show()

In [ ]:
#scatter plot
data1.plot(kind="scatter",x="Freedom",y="Generosity")
plt.show()

In [ ]:
#hist plot
data1.plot(kind="hist",y="Freedom",bins=50,range=(0,1),normed=True)
plt.show()

In [ ]:
#histogram subplot with non cumulative and cumulative
fig,axes=plt.subplots(nrows=2,ncols=1)
data1.plot(kind="hist",y="Freedom",bins=50,range=(0,1),ax=axes[0])
data1.plot(kind="hist",y="Freedom",bins=50,range=(0,0.8),ax=axes[1],cumulative = True)
plt.savefig('graph.png')
plt

<a id="29"></a> <br>
### STATISTICAL EXPLORATORY DATA ANALYSIS
I already explained it at previous parts. However lets look at one more time.
* count: number of entries
* mean: average of entries
* std: standart deviation
* min: minimum entry
* 25%: first quantile
* 50%: median or second quantile
* 75%: third quantile
* max: maximum entry

In [ ]:
data.describe()

In [ ]:
data.Region.unique()

In [ ]:
data.Region.value_counts()

<a id="30"></a> <br>
### INDEXING PANDAS TIME SERIES
* datetime = object
* parse_dates(boolean): Transform date to ISO 8601 (yyyy-mm-dd hh:mm:ss ) format

In [ ]:
time_list=["1997-08-12","2019-01-21"]
print(type(time_list[1])) # As you can see date is string
# however we want it to be datetime object
datetime_object=pd.to_datetime(time_list)
print(type(datetime_object))

In [ ]:
### close warning
import warnings
warnings.filterwarnings("ignore")
data2=data.head()
date_list=["1997-01-02","1997-08-12","1997-07-19","2008-07-12","2012-10-23"]
datetime_object=pd.to_datetime(date_list)
data2["date"]=datetime_object
# lets make date as index
data2=data2.set_index("date")
data2

In [ ]:
# now we can select according to our date index
print(data2.loc["1997-01-02"])
print(data2.loc["1997-01-01":"2010-05-23"])

<a id="31"></a> <br>
### RESAMPLING PANDAS TIME SERIES
* Resampling: statistical method over different time intervals
    * Needs string to specify frequency like "M" = month or "A" = year
* Downsampling: reduce date time rows to slower frequency like from daily to weekly
* Upsampling: increase date time rows to faster frequency like from daily to hourly
* Interpolate: Interpolate values according to different methods like ‘linear’, ‘time’ or index’ 
    * https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.interpolate.html

In [ ]:
# we will use data2 that we create at previous part
data2.resample("A").mean()

In [ ]:
# lets resample with month
data2.resample("M").mean()

In [ ]:
# In real life (data is real. Not created from us like data2) we can solve this problem with interpolate
# We can interpolete from first value
data2.resample("M").first().interpolate("linear")

In [ ]:
data2.resample("M").mean().interpolate("linear")

<a id="32"></a> <br>
# MANIPULATING DATA FRAMES WITH PANDAS

<a id="33"></a> <br>
### INDEXING DATA FRAMES
* Indexing using square brackets
* Using column attribute and row label
* Using loc accessor
* Selecting only some columns

In [ ]:
data_t=pd.read_csv('../input/2015.csv')
data_t=data_t.set_index("Happiness Rank")
data_t.head()

In [ ]:
#indexing using square brackets
data_t["Family"][4]

In [ ]:
# using columns attribute and row label
data_t.Family[4]

In [ ]:
#using loc accessor
data_t.loc[1,["Family"]]

In [ ]:
# selecting only some columns
data_t[["Family","Freedom"]]

<a id="34"></a> <br>
### SLICING DATA FRAME
* Difference between selecting columns
    * Series and data frames
* Slicing and indexing series
* Reverse slicing 
* From something to end

In [ ]:
# difference between selecting columns: series and dataframes
print(type(data_t["Family"])) #series
print(type(data_t[["Family"]])) #data frames

In [ ]:
# slicing and indexing series
data.loc[1:9,"Happiness Rank":"Family"]

In [ ]:
#reverse slicing
data.loc[10:1:-1,"Happiness Rank":"Family"]

In [ ]:
data.loc[1:10,"Standard Error":]

<a id="35"></a> <br>
### FILTERING DATA FRAMES
Creating boolean series
Combining filters
Filtering column based others

In [ ]:
boolean=data.Family>1.31
data[boolean]

In [ ]:
#combining filters
first_filter=data.Family>1.31
second_filter=data.Freedom>0.64
data[first_filter&second_filter]

In [ ]:
#filtering column based others
data.Region[data.Generosity<0.1]

<a id="36"></a> <br>
### TRANSFORMING DATA
* Plain python functions
* Lambda function: to apply arbitrary python function to every element
* Defining column using other columns

In [ ]:
# plain python functions
def div(n):
    return n*10
data.Generosity.apply(div)

In [ ]:
# or we can use lambda function
data.Generosity.apply(lambda n:n*10)

In [ ]:
data["my_rank"]=data.Freedom+data.Family+data.Generosity
data=data.set_index("my_rank")
data.head()

<a id="37"></a> <br>
### INDEX OBJECTS AND LABELED DATA
index: sequence of label

In [ ]:
#our index name is this:
print(data.index.name)
#lets change it
data.index.name="index_name"
data.head()

In [ ]:
#overwrite index
#if we want to modify index we need to change all of them
data.head()
#first copy of our data to data3 then change index
data3=data.copy()
# lets make index start from 100. it is not remarkable change but it is just example
data3.index=range(100,258,1)
data3.head()

<a id="38"></a> <br>
### HIERARCHICAL INDEXING
* Setting indexing

In [ ]:
data4=pd.read_csv('../input/2015.csv')
data4.head()

In [ ]:
data5=data4.set_index(["Region","Family"])
data5.head(30)

<a id="39"></a> <br>
### PIVOTING DATA FRAMES
* pivoting: reshape tool

In [ ]:
dic={"lesson":["Math","Math","Phy","Phy"],"gender":["F","M","F","M"],"vize":["55","40","70","40"],"final":["60","70","60","80"]}
df=pd.DataFrame(dic)
df

In [ ]:
#pivoting
df.pivot(index="lesson",columns="gender",values="final")

<a id="40"></a> <br>
### STACKING and UNSTACKING DATAFRAME
* deal with multi label indexes
* level: position of unstacked index
* swaplevel: change inner and outer level index position

In [ ]:
df1=df.set_index(["lesson","gender"])
df1
#lets unstack it

In [ ]:
#level determines indexes
df1.unstack(level=0)

In [ ]:
df1.unstack(level=1)

In [ ]:
#change inner and outer level index position
df2=df1.swaplevel(0,1)
df2

<a id="41"></a> <br>
### MELTING DATA FRAMES
* Reverse of pivoting

In [ ]:
df

In [ ]:
#df.pivot(index="lesson",columns="gender",values="final")
pd.melt(df,id_vars="lesson",value_vars=["vize","final"])

<a id="42"></a> <br>
### CATEGORICALS AND GROUPBY

In [ ]:
dic={"lesson":["Math","Math","Phy","Phy"],"gender":["F","M","F","M"],"vize":[55,40,70,40],"final":[60,70,60,80]}
df3=pd.DataFrame(dic)
df3

In [ ]:
df3.groupby("lesson").mean()

In [ ]:
df3.groupby("lesson").vize.max()

In [ ]:
df3.groupby("lesson")[["vize","final"]].min()

In [ ]:
df3.info()

In [ ]:
WestEU=data_2015[data_2015.Region=="Western Europe"]
mean_WestEU=WestEU.Happiness_Score.mean()
NorthA=data_2015[data_2015.Region=="North America"]
mean_NorthA=NorthA.Happiness_Score.mean()
Aust=data_2015[data_2015.Region=="Australia and New Zealand"]
mean_Aust=Aust.Happiness_Score.mean()
MiddAfrica=data_2015[data_2015.Region=="Middle East and Northern Africa"]
mean_MiddAfrica=MiddAfrica.Happiness_Score.mean()
Latin=data_2015[data_2015.Region=="Latin America and Caribbean"]
mean_Latin=Latin.Happiness_Score.mean()
Asia=data_2015[data_2015.Region=="Southeastern Asia"]
mean_Asia=Asia.Happiness_Score.mean()
EastEU=data_2015[data_2015.Region=="Central and Eastern Europe"]
mean_EastEU=EastEU.Happiness_Score.mean()
EastAsia=data_2015[data_2015.Region=="Eastern Asia"]
mean_EastAsia=EastAsia.Happiness_Score.mean()
SubAf=data_2015[data_2015.Region=="Sub-Saharan Africa"]
mean_SubAf=SubAf.Happiness_Score.mean()
SouthAsia=data_2015[data_2015.Region=="Southern Asia"]
mean_SouthAsia=SouthAsia.Happiness_Score.mean()

In [ ]:
dictionary={"Region":["Western Europe","North America","Australia and New Zealand",
                      "Middle East and Northern Africa","Latin America and Caribbean",
                      "Southeastern Asia","Central and Eastern Europe","Eastern Asia","Sub-Saharan Africa","Southern Asia"],
            "Mean":[mean_WestEU,mean_NorthA,mean_Aust,mean_MiddAfrica,mean_Latin,mean_Asia,mean_EastEU,mean_EastAsia,mean_SubAf,mean_SouthAsia]}
dataframe1=pd.DataFrame(dictionary)
dataframe1

In [ ]:
plt.barh(dataframe1.Region,dataframe1.Mean)
plt.show()

# CONCLUSION
Thank you for your votes and comments