# **Playing With Covid-19 Data**

In this Notebook we will go throught some pandas command in a very easy and simple way, i hope this to be helpfull for beginner user.

Project: Covid-19 In Italy</br>
Date: August-2021 | Last Update: 4.8.2021</br>
By: Ali H.R.</br>
Target Audience: Beginners</br>
Codes: Python, pandas, bumpy, matplotlib </br>

More Python Codes and projects in my website..
</br>**Website: AHRADWANI.COM**

In [ ]:
"""
Project: Covid-19 In Italy
Date: August-2021
By: Ali H.R.

Summary:
    The Gola of this Project to use some Pandas & Python Command to Test 
    my knowledge.   
    
    Data-Set: Covid-19 Italy Dateset
    Data-Set Link: ../input/covid19-in-italy/covid19_italy_province.csv

"""
# Setup part MUST 
import pandas as pd
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [ ]:
# file name and path
file_1= "../input/covid19-in-italy/covid19_italy_province.csv"

# load the data
the_data = pd.read_csv(file_1)

In [ ]:
# show first 5 records 
the_data.head(20)

In [ ]:
# Explor the data:

# Number of columns and Rows in the data-set
print('\n',the_data.shape)

# let's get all column names in the data-set 
print("\n",the_data.columns)

In [ ]:
# check the data type for each column in the data-frame 
the_data.dtypes

We can see that Date column is object, next we will convert it to a DateTime.

In [ ]:
# check the data type of the date column
# Date is object not date, so we will convert it to date 
# To do so, we will create new coulmn, name it as 'p_date' and copy all the
# date in 'Date' to the new coulmn then convert it to Date dtype.



# Copy first 10 charecters from Date column to p_date column 
the_data["p_date"] = the_data['Date'].apply(lambda x: x[0:10]) 


# convert p_date dtype to date.
the_data['p_date'] = pd.to_datetime(the_data['p_date'])

In [ ]:
# check the dtype for the p_date
print(the_data['p_date'].dtypes)

# **lost Data: Here we will check how much lost data we have in the data-set**</br>

**Check for NaN under an entire DataFrame (True: There is NaN values)** 
</br>the_data.isnull().values.any() 

**print each column with the numer of NaN value**
</br>the_data.isnull().sum(axis = 0)

**Check for NaN under a single DataFrame Column: (True: There is NaN values)**
</br>the_data['Column Name'].isnull().values.any()

**Count the NaN under a single DataFrame column:** 
</br>the_data['Column Name'].isnull().sum()

**get the percent of missing data in each column**
</br>the_data.isnull().sum() * 100 / len(the_data) 

**get the percent of missing data in a column**
</br>the_data['Column Name'].isnull().sum() * 100 / len(the_data)


> Change the ['Column Name'] to what ever column in your data-set.

In [ ]:
# lost Data: Here we will check how much lost data we have in the data-set

# Check for NaN under an entire DataFrame (True: There is NaN values) 
the_data.isnull().values.any() 

# print each column with the numer of NaN value
the_data.isnull().sum(axis = 0)

# Check for NaN under a single DataFrame Column: (True: There is NaN values)
#the_data['Column Name'].isnull().values.any()

# Count the NaN under a single DataFrame column: 
#the_data['Column Name'].isnull().sum()

# get the percent of missing data in each column
#the_data.isnull().sum() * 100 / len(the_data) 

# get the percent of missing data in a column
#the_data['Column Name'].isnull().sum() * 100 / len(the_data)

From the code above, we can see that the Column 
</br>ProvinceAbbreviation has 9779 NaN Values.
</br>Latitude has 9492 NaN Values.
<br>Longitude has 9492 NaN Values.</br>

Now, we can take a desetion of How we will solve the problem of missing data in the columns.