### Previous days

* [Day 1: Handling missing values](https://www.kaggle.com/rtatman/data-cleaning-challenge-handling-missing-values)
* [Day 2: Scaling and normalization](https://www.kaggle.com/rtatman/data-cleaning-challenge-scale-and-normalize-data)
___
Welcome to day 3 of the 5-Day Data Challenge! Today, we're going to work with dates. To get started, click the blue "Fork Notebook" button in the upper, right hand corner. This will create a private copy of this notebook that you can edit and play with. Once you're finished with the exercises, you can choose to make your notebook public to share with others. :)

> **Your turn!** As we work through this notebook, you'll see some notebook cells (a block of either code or text) that has "Your Turn!" written in it. These are exercises for you to do to help cement your understanding of the concepts we're talking about. Once you've written the code to answer a specific question, you can run the code by clicking inside the cell (box with code in it) with the code you want to run and then hit CTRL + ENTER (CMD + ENTER on a Mac). You can also click in a cell and then click on the right "play" arrow to the left of the code. If you want to run all the code in your notebook, you can use the double, "fast forward" arrows at the bottom of the notebook editor.

Here's what we're going to do today:

* [Get our environment set up](#Get-our-environment-set-up)
* [Check the data type of our date column](#Check-the-data-type-of-our-date-column)
* [Convert our date columns to datetime](#Convert-our-date-columns-to-datetime)
* [Select just the day of the month from our column](#Select-just-the-day-of-the-month-from-our-column)
* [Plot the day of the month to check the date parsing](#Plot-the-day-of-the-month-to-the-date-parsing)

Let's get started!

# Get our environment set up
________

The first thing we'll need to do is load in the libraries and datasets we'll be using. For today, we'll be working with two datasets: one containing information on earthquakes that occured between 1965 and 2016, and another that contains information on landslides that occured between 2007 and 2016.

> **Important!** Make sure you run this cell yourself or the rest of your code won't work!

In [221]:
# modules we'll use
import pandas as pd
import numpy as np
import seaborn as sns
import datetime

# read in our data
earthquakes = pd.read_csv("../input/earthquake-database/database.csv")
landslides = pd.read_csv("../input/landslide-events/catalog.csv")
volcanos = pd.read_csv("../input/volcanic-eruptions/database.csv")

# set seed for reproducibility
np.random.seed(0)

Now we're ready to look at some dates! (If you like, you can take this opportunity to take a look at some of the data.)

# Check the data type of our date column
___

For this part of the challenge, I'll be working with the `date` column from the `landslides` dataframe. The very first thing I'm going to do is take a peek at the first few rows to make sure it actually looks like it contains dates.

In [79]:
# print the first few rows of the date column
print(landslides['date'].head())

Yep, those are dates! But just because I, a human, can tell that these are dates doesn't mean that Python knows that they're dates. Notice that the at the bottom of the output of `head()`, you can see that it says that the data type of this  column is "object". 

> Pandas uses the "object" dtype for storing various types of data types, but most often when you see a column with the dtype "object" it will have strings in it. 

If you check the pandas dtype documentation [here](http://pandas.pydata.org/pandas-docs/stable/basics.html#dtypes), you'll notice that there's also a specific `datetime64` dtypes. Because the dtype of our column is `object` rather than `datetime64`, we can tell that Python doesn't know that this column contains dates.

We can also look at just the dtype of your column without printing the first few rows if we like:

In [80]:
# check the data type of our date column
landslides['date'].dtype

You may have to check the [numpy documentation](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.dtype.kind.html#numpy.dtype.kind) to match the letter code to the dtype of the object. "O" is the code for "object", so we can see that these two methods give us the same information.

In [81]:
# Your turn! Check the data type of the Date column in the earthquakes dataframe
# (note the capital 'D' in date!)
earthquakes.Date.dtype

In [82]:
earthquakes.Date.head(15)

In [83]:
earthquakes.shape

In [84]:
earthquakes.info()

In [85]:
earthquakes.tail()

# Convert our date columns to datetime
___

Now that we know that our date column isn't being recognized as a date, it's time to convert it so that it *is* recognized as a date. This is called "parsing dates" because we're taking in a string and identifying its component parts.

We can pandas what the format of our dates are with a guide called as ["strftime directive", which you can find more information on at this link](http://strftime.org/). The basic idea is that you need to point out which parts of the date are where and what punctuation is between them. There are [lots of possible parts of a date](http://strftime.org/), but the most common are `%d` for day, `%m` for month, `%y` for a two-digit year and `%Y` for a four digit year.

Some examples:

 * 1/17/07 has the format "%m/%d/%y"
 * 17-1-2007 has the format "%d-%m-%Y"
 
 Looking back up at the head of the `date` column in the landslides dataset, we can see that it's in the format "month/day/two-digit year", so we can use the same syntax as the first example to parse in our dates:

In [86]:
# create a new column, date_parsed, with the parsed dates
landslides['date_parsed'] = pd.to_datetime(landslides['date'], format = "%m/%d/%y")

Now when I check the first few rows of the new column, I can see that the dtype is `datetime64`. I can also see that my dates have been slightly rearranged so that they fit the default order datetime objects (year-month-day).

In [87]:
# print the first few rows
landslides['date_parsed'].head()

Now that our dates are parsed correctly, we can interact with them in useful ways.

There seems to be a date that is formatted differently... '1975-02-23T02:58:41.000Z'

In [88]:
other_format = earthquakes.Date.str.findall('.*T.*Z')
wrong_dates = other_format[other_format.apply(len) > 0].apply(lambda x: x[0])
wrong_dates

In [89]:
converted_dates = pd.to_datetime(wrong_dates)
converted_dates

In [90]:
converted_dates[3378].day

In [91]:
converted_dates = converted_dates.apply(lambda x: '{}/{}/{}'.format(x.month, x.day, x.year))
converted_dates

In [92]:
earthquakes.Date.update(converted_dates)

In [93]:
earthquakes.Date.head()

In [95]:
other_format = earthquakes.Date.str.findall('.*T.*Z')
(other_format.apply(len) > 0).sum()

In [96]:
# Your turn! Create a new column, date_parsed, in the earthquakes
# dataset that has correctly parsed dates in it. (Don't forget to 
# double-check that the dtype is correct!)
earthquakes['date_parsed'] = pd.to_datetime(earthquakes['Date'], format='%m/%d/%Y')

In [97]:
print(earthquakes.date_parsed.dtype)
earthquakes.date_parsed.head()

# Select just the day of the month from our column
___

"Ok, Rachael," you may be saying at this point, "This messing around with data types is fine, I guess, but what's the *point*?" To answer your question, let's try to get information on the day of the month that a landslide occured on from the original "date" column, which has an "object" dtype:

In [98]:
# try to get the day of the month from the date column
day_of_month_landslides = landslides['date'].dt.day

We got an error! The important part to look at here is the part at the very end that says `AttributeError: Can only use .dt accessor with datetimelike values`. We're getting this error because the dt.day() function doesn't know how to deal with a column with the dtype "object". Even though our dataframe has dates in it, because they haven't been parsed we can't interact with them in a useful way.

Luckily, we have a column that we parsed earlier , and that lets us get the day of the month out no problem:

In [99]:
# get the day of the month from the date_parsed column
day_of_month_landslides = landslides['date_parsed'].dt.day

In [100]:
# Your turn! get the day of the month from the date_parsed column
day_of_month_earthquakes = earthquakes.date_parsed.dt.day
day_of_month_earthquakes.head()

# Plot the day of the month to check the date parsing
___

One of the biggest dangers in parsing dates is mixing up the months and days. The to_datetime() function does have very helpful error messages, but it doesn't hurt to double-check that the days of the month we've extracted make sense. 

To do this, let's plot a histogram of the days of the month. We expect it to have values between 1 and 31 and, since there's no reason to suppose the landslides are more common on some days of the month than others, a relatively even distribution. (With a dip on 31 because not all months have 31 days.) Let's see if that's the case:

In [101]:
# remove na's
day_of_month_landslides = day_of_month_landslides.dropna()

# plot the day of the month
sns.distplot(day_of_month_landslides, kde=False, bins=31)

Yep, it looks like we did parse our dates correctly & this graph makes good sense to me. Why don't you take a turn checking the dates you parsed earlier?

In [104]:
# Your turn! Plot the days of the month from your
# earthquake dataset and make sure they make sense.
sns.distplot(earthquakes.date_parsed.dt.day, bins=31)

Looks good to me.

And that's it for today! If you have any questions, be sure to post them in the comments below or [on the forums](https://www.kaggle.com/questions-and-answers). 

Remember that your notebook is private by default, and in order to share it with other people or ask for help with it, you'll need to make it public. First, you'll need to save a version of your notebook that shows your current work by hitting the "Commit & Run" button. (Your work is saved automatically, but versioning your work lets you go back and look at what it was like at the point you saved it. It also lets you share a nice compiled notebook instead of just the raw code.) Then, once your notebook is finished running, you can go to the Settings tab in the panel to the left (you may have to expand it by hitting the [<] button next to the "Commit & Run" button) and setting the "Visibility" dropdown to "Public".

# More practice!
___

If you're interested in graphing time series, [check out this Learn tutorial](https://www.kaggle.com/residentmario/time-series-plotting-optional).

You can also look into passing columns that you know have dates in them to the `parse_dates` argument in `read_csv`. (The documention [is here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html).) Do note that this method can be very slow, but depending on your needs it may sometimes be handy to use.

For an extra challenge, you can try try parsing the column `Last Known Eruption` from the `volcanos` dataframe. This column contains a mixture of text ("Unknown") and years both before the common era (BCE, also known as BC) and in the common era (CE, also known as AD).

In [222]:
volcanos['Last Known Eruption'].sample(5)

In [223]:
v_dates = volcanos['Last Known Eruption']
print(v_dates.shape)
n_total = v_dates.shape[0]

In [224]:
common_era = v_dates.str.findall('\d+ CE').apply(len) > 0
n_ce = common_era.sum()
n_ce

In [225]:
before_common_era = v_dates.str.findall('\d+ BCE').apply(len) > 0
n_bce = before_common_era.sum()
n_bce

In [226]:
print(n_total)
print(n_ce + n_bce)

In [227]:
dates_ce = v_dates[common_era]
dates_bce = v_dates[before_common_era]
dates_other = v_dates[~common_era]
dates_other = dates_other[~before_common_era]

In [228]:
print(dates_ce.head())
print(dates_bce.head())
dates_other.head()

In [229]:
(dates_other == 'Unknown').sum() / dates_other.shape[0]

So, there are no unexpected values. Every value is CE, BCE or Unknown

In [230]:
dates_ce = dates_ce.apply(lambda x: pd.Period(year=int(x.split(' ')[0]), freq='Y'))
print(dates_ce.dtype)
dates_ce.head()

In [231]:
dates_ce.dt.year.head()  # Even if the dtype is "object" this is a Period object (could be used as PeriodIndex if required)

In [232]:
dates_bce = dates_bce.apply(lambda x: pd.Period(year=-int(x.split(' ')[0]), freq='Y'))
print(dates_bce.dtype)
dates_bce.head()

Let's see if the years are computed correctly, when adding days, for example

In [233]:
from pandas.tseries.offsets import YearEnd

In [234]:
dates_bce[5]

In [235]:
dates_bce[5] + YearEnd(105)

Looks good to me

In [236]:
dates_other = dates_other.apply(lambda x: pd.NaT)
dates_other.head()

In [237]:
new_dates = pd.concat([dates_ce, dates_bce, dates_other])
print(new_dates.isnull().sum())
print(len(dates_other))

In [238]:
volcanos['Last Known Eruption'] = new_dates

In [239]:
volcanos.head()

In [250]:
new_dates.value_counts().head(10)

In [251]:
new_dates

In [249]:
new_dates.dt.year

In [241]:
sns.distplot(new_dates.dt.year)

In [242]:
pd.NaT.year

In [243]:
dates_other.head()

In [252]:
dates_other.dt.year.head()

## For some reason, the NaTs, when stored in a Period return year "-1", but when stored as a regular Series they return NaN, as expected.

I will not go further into the cleanup, but clearly the peak of the distribution close to zero is due to the missing data. The rest of the distribution is natural (more volcanoes are known to have erupted in recent times, as more data was recorded and is available from those times)