In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

import warnings 
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('/kaggle/input/cardiogoodfitness/CardioGoodFitness.csv')
df.head()

The market research team at AdRight is assigned the task to identify the profile of the typical customer for each treadmill product offered by CardioGood Fitness. The market research team decides to investigate whether there are differences across the product lines with respect to customer characteristics. 

The team decides to collect data on individuals who purchased a treadmill at a CardioGoodFitness retail store during the prior three months. The data are stored in the CardioGoodFitness.csv file. 

The team identifies the following customer variables to study: product purchased, TM195, TM498, or TM798; gender; age, in years;education, in years; relationship status, single or partnered; annual household income ($); 

average number of times the customer plans to use the treadmill each week; 
average number of miles the customer expects to walk/run each week; and self-rated fitness on an 1-to-5 scale, where 1 is poor shape and 5 is excellent shape. Perform descriptive analytics to create a customer profile for each CardioGood Fitness treadmill product line.

In [ ]:
# let's understand the data set 
print(f'Shape of the dataset is {df.shape}')
print(f'\nlets see the datatypes in the dataset\n{df.dtypes}')

**Obeservation** 
- We have 180 rows in the dataset and 9 columns 
- the datatypes for the columns are Object and Integer

In [ ]:
# let's see the info of the dataset 
df.info()

In [ ]:
# describe the data 
df.describe(include='all').T

**Observation** 

> Numerical Variables 

1.  Age variable has 180 values where its range is (18-50), median is at 26 and mean is 28.78, Data is spread with 6 STD
2. Education 180 values with range of 12 to 21, it has mean and median with 0.5 units of difference 
3. Usage has 180 values with range 2 to 7, it has mean and median of 3.45 and 3.0 respect.
4. Fitness has 180 values with range of 1 to 5 and mean of 3.31 and median 3
5. Income : has 180 non null values iwht mean of 53719.577778 units and range is between 29k to 104k
6. Miles: has 180 non null values with mean of 103.19 and range is 21.0 to 360.0

> Categorical Variables 

1. Product has 180 non null values,3 unique with top value is of TM195 with frequency of 80 
2. Gender has 180 non null values with 2 unique  with top value is Male with 104 freq
3. Marital Status has 180 non null values with 2 unique values| Partnered is most column has 107 freq

# Explore dataset more to gain insight 

## Univariate Analysis 

#### (Categorical)

In [ ]:
# Product 
# setting bagground of seaborn 
sns.set()

#proudct 
fig, ax = plt.subplots(1, 3, figsize=(15, 6))
sns.countplot(df['Product'], capsize=0.2, ax=ax[0])
ax[0].bar_label(ax[0].containers[0], fmt='Count:\n%.2f', label_type='center')
plt.title("Product", size=20)

#gender 
sns.countplot(df['Gender'], capsize=0.2, ax=ax[1])
ax[1].bar_label(ax[1].containers[0], fmt='Count:\n%.2f', label_type='center')
plt.title("Gender", size=20)

#MaritalStatus 
sns.countplot(df['MaritalStatus'], capsize=0.2, ax=ax[2])
ax[2].bar_label(ax[2].containers[0], fmt='Count:\n%.2f', label_type='center')
ax[0].set_title("Product", size=20)
ax[1].set_title("Gender", size=20)
ax[2].set_title("MaritalStatus", size=20)

plt.show()

**Observation**
- For Product we have Three categories: 
                                    - TM195 with 80 values 
                                    - TM498 with 60 values
                                    - TM798 with 40 values
 > TM195 is dominating, most of the users prefer this product, we investigate more about the price of this product.                                       

- For Gender, we have two categories here
                                    - Male with 104 values 
                                    - Female with 76 values 
 > Male are dominating the dataset 
 
- MaritalStatus have two categories with Single and Partnered. 
                                    - single are 73 values
                                    - partnered are 107 values
  > Partenred are more than sigle for this dataset

## Univariate Analysis 

#### (Numerical)

In [ ]:
in_df = df.select_dtypes('int')

In [ ]:
fig, ax = plt.subplots(2,3, figsize=(16, 8))
ax = ax.flatten()
for i in range(6):
    mean = in_df.iloc[:,i].mean()
    median = np.median(in_df.iloc[:,i])
    sns.kdeplot(in_df.iloc[:,i].values, ax=ax[i], shade=True)
    ax[i].axvline(mean, color='g', linestyle='--', label='mean')
    ax[i].axvline(median, color='b', linestyle='--', label='median')
    ax[i].set_title(in_df.columns[i])
    ax[i].legend()
fig.tight_layout(pad=2.0)

**Observation** 

1. Age:
        - we can see the age is right skewed. 
        - age is ranging from 18 to 50.
        - from figure it is clear the median is at 26 around and mean is near 29, so there must be outlier(or maybe not)i.e. there must be value which is so large that it pulling whole graph to it self and it is skewed. 
 
2. Education : 
        - Not highly skewed. 
        - ranging from 12-22 
        - mean is higher than median looks like slightly left skewed but not much( not need to deal or pay attention)
3. All other 4 are not showing much of difference, range is already mentioned and some graphs shows little modes near but no need to worry since we are just exploring the data here.

In [ ]:
# correlation between variables 
sns.pairplot(df)
plt.title('Pairplot', size=22)

**Observation** 

1. Age and income has kind of linear relationship.
2. Income and miles also share the linear relationship
3. As miles is increasing ussage increase(which is obvious)
4. Fitness increases as mile increases 
5. Age and miles also has linear relationship but as it increases the values has variations in it. 
6. Ussage and income : those having less income has high ussage.

In [ ]:
# let's check for outleirs using box plot 
fig, ax = plt.subplots(2,3, figsize=(16, 8))
ax = ax.flatten()
for i in range(6):
    mean = in_df.iloc[:,i].mean()
    median = np.median(in_df.iloc[:,i])
    sns.boxplot(in_df.iloc[:,i].values, ax=ax[i])
    ax[i].set_title(in_df.columns[i], size=19)

fig.tight_layout(pad=2.0)

**Observation** 

1. Age: it has 2-3 values which exceed the IQR and our boxplots are considering them as outlier. 
2. Education : it has two values while others are ranging 12 to 18 
3. Fitness has one outlier which doesnot have fitness value(must be me ;p) 
4. Income : as expected income has lot of outliers in it. income generally most of people has same in a organization & few has great fancy incomes. 
5. Miles : has outliers too, means few people really push **themself**.

In [ ]:
# corr matrix 
fig, ax = plt.subplots(1,1, figsize=(16, 8))

corr = df.corr()

sns.heatmap(corr, annot=True)
plt.show()

In [ ]:
# Bi/multi variate data analysis 
# let's see the relationship between numerical variables  
# using scatter plot 
# relation of age with all variables keeping product as heu


> created a function which will print all the relationship in the dataset with categorical variables but I am not using it to print because it is taking so much space where I can't write my observations


`
for cat in df.select_dtypes('object').columns:
    for col in in_df.columns:
        fig, ax = plt.subplots(2,3, figsize=(16, 8))
        ax = ax.flatten()
        for i in range(6):
                sns.scatterplot(data=df, x=col, y=df.columns[i],hue=cat,  ax=ax[i])
        plt.show()
        print("\n\n\n")
`

> here I am going to check relationship with only those who are showing more than .5 value in corr matrix

In [ ]:
# fitness with miles with all the cat columns 
fig, ax = plt.subplots(1 ,3 , figsize=(16, 5))
ax = ax.flatten()
i=0
for cat in df.select_dtypes('object').columns: 
    sns.scatterplot(data=df, x='Fitness', y='Miles', hue=cat, ax=ax[i])
    ax[i].set_title(f'Fitness vs Miles hue : {cat}', size=16)
    i = i+1
plt.show()

**Observations** 

1. With 0.79 of correlation between fitness and miles, we can clearly see that the data is linearly increasing, 
2. So we can say here that once people start getting fit there Run per miles increases. 
3. That means High miles value has better fitness but there are exception as we can see the data has lot of variations at the fitness : 5. 
4. we can see there is a trend after fitness level 4 we can the people are using TM798 and which is quiet clear here but Most of the are using TM498 
5. More Males are Fitness freak, 1,2 are mostly female level but after that Male values are increasing. but female values are not decreasing, but the densitiy is decreasing for females since Males are increasing 
6. Partnered are more fitness freaks

In [ ]:
# usage with miles with all the cat columns 
fig, ax = plt.subplots(1 ,3 , figsize=(16, 5))
ax = ax.flatten()
i=0
for cat in df.select_dtypes('object').columns: 
    sns.scatterplot(data=df, x='Usage', y='Miles', hue=cat, ax=ax[i])
    ax[i].set_title(f'Usage vs Miles hue : {cat}', size=16)
    i = i+1
plt.show()

**Observations** 

1. Since the corr are +ve all the values are incrementing only
2. we can see most of the people usage is TM798 tredmill but with ussage of 2 &3 TM498 is more. 
3. Gender is not biased both of them has same usage just male are having outlier values of Miles
4. Marital status, since in our Partnereds are more we can see more usage and Miles have parterened, ( I think competitions help us to do incredible work)

In [ ]:
# Income with Education with all the cat columns 
fig, ax = plt.subplots(1 ,3 , figsize=(16, 5))
ax = ax.flatten()
i=0
for cat in df.select_dtypes('object').columns: 
    sns.scatterplot(data=df, x='Income', y='Education', hue=cat, ax=ax[i])
    ax[i].set_title(f'Income vs Education hue : {cat}', size=16)
    i = i+1
plt.show()

In [ ]:
# Fitness with Usage with all the cat columns 
fig, ax = plt.subplots(1 ,3 , figsize=(16, 5))
ax = ax.flatten()
i=0
for cat in df.select_dtypes('object').columns: 
    sns.scatterplot(data=df, x='Fitness', y='Usage', hue=cat, ax=ax[i])
    ax[i].set_title(f'Fitness vs Usage hue : {cat}', size=16)
    i = i+1
plt.show()

**Observtions** 

1. Clearly in first image we can see the clusters with Products. 
2. Yes fitness 3-5 are TM798 and Gender and Maritalstatus has above observations

In [ ]:
# Income with Age with all the cat columns 
fig, ax = plt.subplots(1 ,3 , figsize=(16, 5))
ax = ax.flatten()
i=0
for cat in df.select_dtypes('object').columns: 
    sns.scatterplot(data=df, x='Income', y='Age', hue=cat, ax=ax[i])
    ax[i].set_title(f'Income vs Age hue : {cat}', size=16)
    i = i+1
plt.show()

1. Income increases as Age increase is clearly vissible 
2. Those who has higher income & lower age are prefering TM798 ( I really think treadmill 798 is awesome among all) 
3.  Looks like male at lower age earns more and females are more in age of 20-35 with income 40000-60000
4. Single and partenered are not different here

In [ ]:
Miles_group = df.groupby('Product').mean().reset_index()
Miles_group

In [ ]:
fig, ax = plt.subplots(2, 3, figsize=(16,12))
ax =ax.flatten()
for i in range(6):
    sns.barplot(x=Miles_group.Product, y=Miles_group.iloc[:, i+1].values, ax=ax[i], palette="plasma")
    ax[i].bar_label(ax[i].containers[0], fmt='Mean:\n%.2f', label_type='center')
    ax[i].set_title(Miles_group.columns[i+1], size=20)
plt.show()

In [ ]:
Gender_group = df.groupby('Gender').mean().reset_index()
Gender_group
fig, ax = plt.subplots(2, 3, figsize=(16,12))
ax =ax.flatten()
for i in range(6):
    sns.barplot(x=Gender_group.Gender, y=Gender_group.iloc[:, i+1].values, ax=ax[i], palette="plasma")
    ax[i].bar_label(ax[i].containers[0], fmt='Mean:\n%.2f', label_type='center')
    ax[i].set_title(Gender_group.columns[i+1], size=20)
plt.show()

In [ ]:
MaritalStatus_group = df.groupby('MaritalStatus').mean().reset_index()
MaritalStatus_group
fig, ax = plt.subplots(2, 3, figsize=(16,12))
ax =ax.flatten()
for i in range(6):
    sns.barplot(x=MaritalStatus_group.MaritalStatus, y=MaritalStatus_group.iloc[:, i+1].values, ax=ax[i], palette="plasma")
    ax[i].bar_label(ax[i].containers[0], fmt='Mean:\n%.2f', label_type='center')
    ax[i].set_title(MaritalStatus_group.columns[i+1], size=20)
plt.show()