In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

In [ ]:
database=pd.read_csv("../input/2017.csv") #database variable

In [ ]:
print(database.info())

In [ ]:
# "." replace "_" because accessing the fields will cause problems with dot
#example: Happiness.Rank raplace Happiness_Rank
database.columns=[i.replace(".","_") for i in database.columns] #tüm alan isimlerine nokta yerine _ ile değiştirdim kodlamadayken problem olmasından kaynaklı
database.columns

 **Most Happy 5 Countries**

This method indicates data up to numeric value written in parentheses.

*Example using*: dataFrame.head(numaric_valuable)

In [ ]:
database.head(5) # en mutlu ilk 5 ülke

****

**Comparison Of Freedom and Generosity By Happiness Rank**

Line Plot: Used the library of matplotlib.

X axis= Happiness Rank

Y axis= Comparison of freedom and generosity

Result: We cannot say there is generosity in very freedom

In [ ]:

database.Generosity.plot(kind='line',color='blue',label='Generosity',linewidth=2,grid=True,linestyle='-')
database.Freedom.plot(color='red',label='Freedom',linewidth=2,grid=True,linestyle=':')
plt.legend(loc='upper right')
plt.xlabel('Happiness Rank')
plt.ylabel('Freedom and Generosity')
plt.title('Freedom vs Generosity')
plt.show()

**Comparison  of Health Life Expectancy and Happiness Rank**

Scatter Plot: Used the library of matplotlib.

X Axis: Happiness Rank 

Y Axis: 
    1.  The most health expectancy value = 1.0
    2. Lowest health expectancy value = 0.0
Result: We can say healthy life expectancy in happy countries is high and vice versa

In [ ]:

database.plot(kind="scatter",x="Happiness_Rank",y="Health__Life_Expectancy_", color="green")
plt.xlabel("Happiness Rank")
plt.ylabel("Health Life Expectancy")
plt.title("Happiness Rank vs Health Life Expectancy")
plt.show()

In [ ]:
# with score of comparison
database.plot(kind="scatter",x="Happiness_Score",y="Health__Life_Expectancy_", color="green")
plt.xlabel("Happiness Score")
plt.ylabel("Health Life Expectancy")
plt.title("Happiness Score vs Health Life Expectancy")
plt.show()

**Cross country comparison and The most happy country with the most unhappy country comparison**

In [ ]:
#norway and turkey match
norwayTurkey=database[(database["Country"]=="Norway") | (database["Country"]=="Turkey")]
norwayTurkey

In [ ]:

#The most happy country with the most unhappy country comparison
minRank=max(database["Happiness_Rank"]) # Lowest happy country
maxRank=min(database["Happiness_Rank"]) # the most happy country
print("Un Happy: ",minRank)
print("Happy: ",maxRank)
hpCountries=database[(database["Happiness_Rank"]==minRank) | (database["Happiness_Rank"]==maxRank)]
hpCountries

**PYTHON DATA SCIENCE TOOLBOX**

In [ ]:
#Tuple example
def tuple_example():
    values=database[(database["Happiness_Rank"]>=1) & (database["Happiness_Rank"]<3)]
    return values["Country"]
a,b=tuple_example() # two values, a=Norway, b=Denmark
print(a,b)

In [ ]:
#Scope Example
name="global scope"
def scopeFunc():
    name="Local Scope"
    return name
print(name) #global scope #main code block
print(scopeFunc()) # local scope in method

In [ ]:
#Python built in scope examples: print, len, int,str etc.
import builtins
dir(builtins)

In [ ]:
#Nested Functions

#Example: name and surname combining method and printer method
#Nested Method Starting.
def printerFunc(name,surname): #External method
    def comibinedNames(name,surname):#internal method
        return name+" "+surname
    print(name,surname)
#Nested Method Finished.
name="Hakan"
surname="Yusufoglu"
printerFunc(name,surname)

In [ ]:
#Default Arguments(parameter)
#Example mean method
def averageFunc(score1,score2,score3=48): #score3= Default value so default argumen
    sumValues=score1+score2+score3
    return sumValues/3
print(averageFunc(10,10)) #score3 value=48 because default argumen=48
#and
print(averageFunc(10,10,10)) #score3 value=10 because changed with 10

In [ ]:
#Flexible Arguments
#Example many value print

def sumFunc(*values):
    for i in values:
        print(i)
sumFunc(10) #1 parameter
print("")
sumFunc(20,30)#two parameter etc (many parameter)

In [ ]:
#Lamda Functions
#Briefly faster function
#Example mean method

avarage=lambda score1,score2,score3=48: (score1+score2+score3)/3 #up: normal method
print(avarage(10,10))
print(avarage(10,10,10))

**LIST COMPREHENSİON**
We use list comprehension for data analysis often.

In [ ]:
#Example: Happiness Score mean
def meanFunction_2():
    sumValuable=0
    counter=0
    meanValuable=0
    for i in database["Happiness_Score"]:
        counter+=1
        sumValuable+=i
    meanValuable=sumValuable/counter
    return meanValuable
print(meanFunction_2())

In [ ]:
database.head(10)
meanScore=sum(database["Happiness_Score"])/len(database["Happiness_Score"])
#Example happy or unhappy countries with dataframe(World Happiness Report)
database["Happy_Status"]=["Happy" if i>meanScore else "UnHappy" for i in database.Happiness_Score]
database.loc[60:75,["Country","Happiness_Score","Happy_Status"]]

**Cleaning Data**

Column regulation for missing data, irregular data etc.

In [ ]:
print(database.shape)
#155 rows, 13 columns
print(type(database.shape))
#return tuple

**EXPLORATORY DATA ANALYSIS**
Learning with examples

In [ ]:
animalExample={"Mammals":("human","lion","dogg"),"invertebrate":"spider"}
print(animalExample["Mammals"])
dataframe_1=pd.DataFrame.from_dict(animalExample) #
invert_1=dataframe_1["invertebrate"].value_counts(dropna=False)
mammals_1=dataframe_1["Mammals"].value_counts(dropna=False)
print(mammals_1) 
print(invert_1)
print(dataframe_1)

In [ ]:

database.describe()

**VISUAL EXPLORATORY DATA ANALYSIS**

*  Black line at top is max
*  Blue line at top is 75%
*  Green line is median (50%)
*  Blue line at bottom is 25%
*  Black line at bottom is min
*  There are no outliers

In [ ]:
    database.boxplot(column="Happiness_Score",by="Happy_Status",grid=True)
    #Result: Happy Countries= 7,80 between 5,30 values
    #UnHappy Countries= 2,30 between 5,20 values

**TIDY DATA**
Grouping data melting...

In [ ]:
groupingMelt=pd.melt(frame=database.head(),id_vars="Country",value_vars=["Happiness_Rank","Happiness_Score","Happy_Status"])
groupingMelt
#variable= column name
#value=data in column

#Pivot Table

groupingMelt.pivot(index="Country",columns="variable",values="value")

**CONCATENATING DATA**

In [ ]:
column_2=database["Country"].head()
column_3=database["Happy_Status"].head()
colms=pd.concat([column_2,column_3],axis=1) # accept as axis=1 column axis=0 row 
colms

**MISSING DATA and TESTING WITH ASSERT**

In [ ]:
#Does it exist nan country value or Is there repetitive data?
database["Country"].value_counts(dropna=True) #Dropna Does it exist nan?

In [ ]:
assert 1==1
database.head()

**PANDAS FOUNDATION**

In [ ]:
tables=database.loc[:,["Freedom","Generosity"]]
tables.plot(subplots=True)
plt.show()

In [ ]:
tables.plot(kind="hist",y="Generosity",bins=50, range=(0,1),normed=True)

**MANIPULATING DATA FRAMES WITH PANDAS**

In [ ]:
#İndexing data 

newDataFrame=pd.read_csv("../input/2017.csv")
newDataFrame=newDataFrame.set_index("Happiness.Rank")
newDataFrame["Country"][1] #[1] happiness rank so new index

**TRANSFORMING DATA**

In [ ]:

def multiply(values):
    return values*5
database.Generosity.apply(multiply)

**PIVOTING DATA FRAMES**

In [ ]:
library={"books":["Great Expectations","Chess","Oliver Twist"],"page_no":[335,80,552],"author":["Charles_Dickens","Stefan_Zweig","Charles_Dickens"]}
dataframe_1=pd.DataFrame(library)
dataframe_1

In [ ]:
#pivot table
dataframe_1.pivot(index="books",columns="author",values="page_no")

In [ ]:
#group by using mean page no
dataframe_1.groupby("author").mean() #so Charles Dickens page number average=443.5 
#Stefan Zweig page number average=80 because one entity

In [ ]:
#max page number by author
dataframe_1.groupby("author").max()

In [ ]:
#min page number by author
dataframe_1.groupby("author").min()

In [ ]:
dataframe_1.describe()

In [ ]:
dataframe_1.info()

One Step: I'am learning Data Science step one
Target: Learn artificial intelligence
Thank you everybody.