(under editing.....)

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

In [ ]:
df = pd.read_csv("../input/Mall_Customers.csv")

In [ ]:
df.columns

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.columns = ["ID","Gender" ,"Age","Income","Score"]

In [ ]:
plt.hist(df.Age)

In [ ]:
df.boxplot()

In [ ]:
df["Income"]

In [ ]:
df.head()

In [ ]:
df["Gender"].value_counts()

In [ ]:
df["Gender"] = df.Gender.map({"Male":1,"Female":0})

In [ ]:
sns.barplot(x = "Gender", y = "Score", data = df)

In [ ]:
sorted(list(df.Age.unique()))

I would like to categorise Age with 5yrs as frequency

In [ ]:
def group_age(age):
    if age <= 30:
        return "<= 30"
    elif age <= 40:
        return "31-40"
    elif age<= 50:
        return "41-50"
    elif age<= 60:
        return "51-60"
    else:
        return "61-70"

In [ ]:
df["Age"]= df.Age.apply(group_age)

In [ ]:
df

In [ ]:
sns.barplot(x = 'Age', y = "Score", hue = "Gender", data  = df,)

In [ ]:
df.Age.unique()

In [ ]:
sns.barplot(x = "Age",y="Income",hue = "Gender", data = df, order = ['<= 30', '31-40', '41-50','51-60','61-70'])

In [ ]:
plt.scatter(x = "Income", y = "Score", data = df)

In [ ]:
plt.scatter(x = "Income", y = "Score", data = df[df.Gender == 1])

In [ ]:
plt.scatter(x = "Income", y = "Score", data = df[df.Gender == 0])

In [ ]:
plt.scatter(x = "Age", y = "Score", data = df[df.Gender == 0])

In [ ]:
plt.scatter(x = "Age", y = "Score", data = df[df.Gender == 1])

In [ ]:
df.groupby(["Gender","Age"]).mean()

Insights : 
1. Upto Age- 50, Average Income for male is higher than female, after that average income for female is higher compared to that of male.
2. Average Spending score of male is less than that of female across all age groups.