In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
data=pd.read_csv("/kaggle/input/weather-dataset-rattle-package/weatherAUS.csv")

In [ ]:
#We are looking at the first 10 data of our data
data.head(10)

In [ ]:
#We are getting some information about the data
data.info()

In [ ]:
#We are seeing correlations
data.corr()

In [ ]:
#We are seeing correlations on the heatmap.
f,ax=plt.subplots(figsize=(10,10))
sns.heatmap(data.corr(),linewidths=0.5,annot=True,fmt=".2f")
#linewidths:width of line
#(annot=True):we can see the number in the box
#fmt:number of decimal places

In [ ]:
#We can see the name of columns
data.columns

In [ ]:
#Line Plot
data.Temp9am.plot(kind="line",color="g",label="Temp9am",linewidth=1,alpha=0.5,grid=True,linestyle=":")
data.Temp3pm.plot(kind="line",color="r",label="Temp3pm",linewidth=1,alpha=0.3,grid=True,linestyle="-.")
plt.legend("upper right")   #legend:puts label into plot       #alpha=line of transparency
plt.xlabel("x axis")        #label :name of label
plt.ylabel("y label")
plt.title("Line Plot")      #title :title of plot
plt.show()

In [ ]:
#Scatter Plot
data.plot(kind="scatter",x="Temp9am",y="Temp3pm",alpha=0.1,color="r")
plt.xlabel("Temp9am")    #label:name of label
plt.ylabel("Temp3pm")
plt.title("Temp9am and Temp3pm Scatter Plot")    #title:name of title
plt.show()

In [ ]:
#Histogram
data.Temp9am.plot(kind="hist",bins=50)   #bins:number of bars

In [ ]:
#We are seeing the dates that Temp9am>30 and Temp3am>40
df=data[(data["Temp9am"]>30) & (data["Temp3pm"]>40)]

In [ ]:
#We are seeing the max,min,mean values
[data.Temp9am.max(), data.Temp9am.min(), data.Temp9am.mean()]

In [ ]:
#The informations of Temp9am for 2009
data.loc[31:395,["Date","Temp9am"]]

In [ ]:
#The highest and lowest temperature for 2009
data.loc[31:395,["Temp9am"]].max(),data.loc[31:395,["Temp9am"]].min()

In [ ]:
#User Defined Function
def denklem():
    a=[1,2,3,4,5,6]
    return a
a,b,c,d,e,f=denklem()
print(a,b,c,d,e,f)

In [ ]:
#Scope
x=5
def fonk():
    x=2
    return x+5
print(x)         #Local scope
print(fonk())    #Global scope

In [ ]:
x=5
def fonk():
    y=x*2
    return y
print(fonk())  #There is no local scope

In [ ]:
import builtins  #We can not say len=5. Because "len" has a duty for python. So it is usefull for that situations.
dir (builtins)

In [ ]:
#Nested:Function in functin
def f1():
    print("Hello from outer")
    def f2():
        print("Hello from inner")
    f2()
f1()

In [ ]:
#Default Argument Example
def student(firstname, lastname ="Umdu"):
     print(firstname, lastname)
student("Kadir")

In [ ]:
#Flexible argument
def sum_(*numbers):
    result=0
    for i in numbers:
        result+=i
    return result
sum_(10,20,30)

In [ ]:
#Lambda Function
a=lambda x:x**3
a(3)

In [ ]:
#Anonymous Function
liste=["Ali","Veli","Fatma"]
x=map(lambda y:y*2,liste)
print(list(x))

In [ ]:
liste=["Mavi","Yeşil","Kırmızı"]
my_it=iter(liste)
print(next(my_it))
print(next(my_it))
print(next(my_it))

In [ ]:
#zip example
data1=data.Temp9am.head()
data2=data.Temp3pm.head()
zipped=zip(data1,data2)
z_list=list(zipped)
print(z_list)
#we have to transform "zipped" to list that seeing the variable

In [ ]:
#unzip example
un_zip=zip(*z_list)
un_data1,un_data2=list(un_zip)
print(un_data1)
print(un_data2)

In [ ]:
#List Comprehension
#example of list comprehension
num1=[1,2,3,4,5]
num2=[i*3 if i>3 else i*2 if x==3 else i*1 for i in num1]
print(num2)

In [ ]:
data.shape  #gives number of raws and columns

In [ ]:
#We can see some information with "describe()" like min,ma,mean...
data[["Temp9am","Temp3pm"]].describe()

In [ ]:
#We can see informations of "describe" as a plot like this
data.boxplot(column="Temp9am")
plt.show()

In [ ]:
#We are creating a new data.
data_new=data[["Date","Temp9am","Temp3pm"]].head(10)
data_new

In [ ]:
#We can use "melt" for seeing better
melted=pd.melt(data_new,id_vars=["Date"],value_vars=["Temp9am","Temp3pm"]) #value_vars=variable
melted

In [ ]:
#We can transform the "melted" to "new_data" again.
melted.pivot(index="Date",columns="variable",values="value")

In [ ]:
#We are making an example for concatenate
data1=data.head()
data2=data.tail()
conc_data_row=pd.concat([data1,data2],axis=0,ignore_index=True)   #axis=0 : vertical merger
conc_data_row                                                     #ignore_index=True : assign a new index

In [ ]:
#Concatenate example again.
#It is not a good example I know :)
conc_data_col=pd.concat([data1,data2],axis=1)  #axis=1 : horizontal merger
conc_data_col

In [ ]:
data["Temp9am"].value_counts(dropna=False)

In [ ]:
#We dropped the Nan
data["Temp9am"].dropna(inplace=True)  #inplace=True : save data without NaN's

In [ ]:
#We control what we did with assert.
#If "assert" gives an error. You can not do what you want
assert data["Temp9am"].head().notnull().all()

In [ ]:
#We put "empty" in place of NaN
data["Temp9am"].head().fillna("empty",inplace=True)

In [ ]:
#DataFrames from dictionary
name=["Deniz","Kadir","Sude"]
age=[28,24,14]
list_label=["name","age"]
list_col=[name,age]
zipped=list(zip(list_label,list_col))   #zip : zipped 
data_dict=dict(zipped)               
df=pd.DataFrame(data_dict)
df

In [ ]:
#we can add a new column "salary"
df["salary"]=[8000,1000,600]
df

In [ ]:
#Histogram Plot
data["Temp3pm"].plot(kind="hist",bins=50,range=(0,50))  #range(0,50): from zero to fifty(numbers on x axis)

In [ ]:
data["Temp3pm"].plot(kind="hist",bins=50,range=(0,50),cumulative=True)  #cumulative=True: bars add up in order

In [ ]:
print(data.loc[2008-12-4])  #We can see information for choosing date

In [ ]:
#We also have date(datetime). So We do not create "time_list" again. We just transform the series of data to list.
datetime=data.loc[:366,"Date"]
time_list=list(datetime)

In [ ]:
#We transform our "time_list" to datetime from list
datetime_object=pd.to_datetime(time_list)
print(type(datetime_object))
datetime_object

In [ ]:
#We can see the information of 367 day for "Temp3pm"
df=data.loc[0:366,["Date","Temp3pm"]]
df

In [ ]:
df["date"]=datetime_object  #we added a new column
df=df.set_index("date")     #set_index : we named the new column
df

In [ ]:
#We dropped the "Date". Because "date" and "Date" have different types.
df=df.drop("Date",axis=1)  
df

In [ ]:
#We can see "mean" for different years
df.resample("A").mean()  #"A" : for years

In [ ]:
#We can see "mean" for different months
df.resample("M").mean()  #"M" : for months

In [ ]:
#We can add a new column to "df" from our "data"
Humidity=data.loc[0:366,"Humidity3pm"]
list(Humidity)      #We have to convert to list
df["Humidity3pm"]=list(Humidity)
df

In [ ]:
df.Temp3pm[df.Humidity3pm>50]

In [ ]:
#We can use lamda function like this
df.Humidity3pm.apply(lambda x:x*2)

In [ ]:
#Our index name this:
print(df.index.name)

In [ ]:
#Lets change it
df.index.name="Date"
df