In [ ]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
import chardet

In [ ]:
df = pd.read_csv("../input/spacex-missions/database.csv")
df.head()

In [ ]:
with open("../input/spacex-missions/database.csv", 'rb') as rawdata:
    result = chardet.detect(rawdata.read(10000))

# check what the character encoding might be
print(result)

# Rename columns

In [ ]:
#remove space in  columns
columns = df.columns 
col = [i.replace(' ', '_') for i in columns]
df.columns = col

# Missing Value

In [ ]:
# get the number of missing data points per column
missing_values_count = df.isnull().sum()
total_cells = np.product(df.shape)
total_missing = missing_values_count.sum()
total_cells,total_missing

In [ ]:
total_cells = np.product(df.shape)
total_missing = missing_values_count.sum()

In [ ]:
df.fillna(0)



# Datetime

In [ ]:
df["Launch_Date"] = pd.to_datetime( df["Launch_Date"])
df.info()

# **Categorical_data**

In [ ]:
#select categorical data
objet_columns = df.select_dtypes(include=[object])
colonne = objet_columns.columns
colonne

In [ ]:
def convert_categorical_to_int(col,df) :
    for i in col:
# list unique value for each column
        tab  = df[i].unique()
#     transform to dataframe
        data = pd.DataFrame(tab)
#      add primary key for each dataframe
        data[i+'_int'] = range(len(data))
#     rename the first column
        data = data.rename(columns={0: i})
#     lookup in df to get the primary key
        result = pd.merge(df, data, on=i)
        df = result
    return result

df = convert_categorical_to_int(colonne,objet_columns) 
df.info()

In [ ]:
# drop all the categorical data
objet_columns = df.select_dtypes(include=[object])
df = df.drop(columns=objet_columns)

In [ ]:
df.head()

#  Correlation

In [ ]:
plt.subplots(figsize = (10 , 10))
sns.heatmap(df.corr(),annot=True,cmap = 'cool')