In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Load Dataset

In [ ]:
df = pd.read_csv('../input/coursera-course-dataset/coursea_data.csv')
df.head()

# Data Pre-processing

In [ ]:
df.info()

In [ ]:
# change course_students_enrolled values like: 53k into 53,000

df['course_students_enrolled'] = df['course_students_enrolled'].str.replace('k', '*1000')
df['course_students_enrolled'] = df['course_students_enrolled'].str.replace('m', '*1000000')
df['course_students_enrolled'] = df['course_students_enrolled'].map(lambda x: eval(x))
df['course_students_enrolled']

In [ ]:
df.describe()

In [ ]:
print("There are {} Rows and {} Columns in the dataset".format(df.shape[0], df.shape[1]))

In [ ]:
# Check Null Values

df.isna().sum()

In [ ]:
df.columns

In [ ]:
df.index

# Start Analyzing

# How many type of courses available in Coursera

In [ ]:
ax = df['course_Certificate_type'].value_counts().plot(kind='bar', figsize=(16,12), color='dodgerblue')
ax.set_alpha(0.5)
ax.set_title('course_certificate_type')
ax.set_ylabel('Count')

totals = []

# find the values and append to list
for i in ax.patches:
    totals.append(i.get_height())

# set individual bar lables using above list
total = sum(totals)

# set individual bar lables using above list
for i in ax.patches:
    # get_x pulls left or right; get_height pushes up or down
    ax.text(i.get_x(), i.get_height()+.5, \
            str(round((i.get_height()/total)*100, 2))+'%', fontsize=15,
                color='dimgrey')

As we see that maximum courses are available on single courses then some specialization courses and very few Professional certificate courses are avilable

# Course Difficulty

In [ ]:
ax = df['course_difficulty'].value_counts().plot(kind='bar', figsize=(16,12),
                                                color="#F65F3A")
ax.set_alpha(0.8)
ax.set_title("Course Difficulty Type");
ax.set_ylabel('Count',fontsize=17);
totals = []

# find the values and append to list
for i in ax.patches:
    totals.append(i.get_height())

# set individual bar lables using above list
total = sum(totals)

# set individual bar lables using above list
for i in ax.patches:
    # get_x pulls left or right; get_height pushes up or down
    ax.text(i.get_x(), i.get_height()+.5, \
            str(round((i.get_height()/total)*100, 2))+'%', fontsize=15,
                color='dimgrey')

# Top 10 Organizations Course wise in Coursera

In [ ]:
abc = df.groupby(['course_organization'])['course_organization'].count().to_dict()
abc = pd.DataFrame({'course_organization': list(abc.keys()), 'Count': list(abc.values())})
abc = abc.sort_values(by=['Count'], ascending=False)
abc = abc.head(10)
abc

In [ ]:
plt.bar(abc['course_organization'], abc['Count'])
plt.show()

# Top 10 Courses on Coursera

In [ ]:
top_10_courses = df.loc[:,['course_title', 'course_students_enrolled']]
top_10_courses = top_10_courses.sort_values(by=['course_students_enrolled'], ascending=False)
top_10_courses = top_10_courses.head(10)
top_10_courses

In [ ]:
fig = plt.figure(figsize=(16, 12))
ax = fig.add_axes([0,0,1,1])
ax.bar(top_10_courses['course_title'], top_10_courses['course_students_enrolled'], color="#85DA62")
plt.show()

# Top 10 Organizations enrolled_students wise in Coursera

In [ ]:
seo = df.loc[:, ['course_organization','course_students_enrolled']]
seo = pd.DataFrame(seo.groupby(['course_organization'])['course_students_enrolled'].sum())
seo = seo.sort_values(by=['course_students_enrolled'], ascending=False)
seo = seo.head(10)
seo

In [ ]:
df.groupby('course_rating')['course_students_enrolled'].count().plot(kind='bar', grid=True,
    figsize=(16, 12)).set_ylabel('Enrolled')

In [ ]:
cor = df.corr()
cor

In [ ]:
sns.heatmap(cor, annot=True)

This heatmap show that there is a high correlation between course_rating and course_student_enroolment. Its mean if the course_rating is high then definately student enroll those course

In [ ]:
sns.displot(df.course_rating, kde=True)

# Which organization has the highest course rating?

In [ ]:
oc = round(df.groupby(['course_organization'])['course_rating'].mean()).to_dict()
oc

In [ ]:
oc = pd.DataFrame({'course_organization': list(oc.keys()), 'course_rating': list(oc.values())})
res = oc[oc['course_rating'] >=4.9]
res