**  LOGISTIC REGRESSION TO  PREDICT HEART DISEASE.**

 **Introduction**
 
World Health Organization has estimated 12 million deaths occur worldwide, every year due to Heart diseases. Half the deaths in the United States and other developed countries are due to cardio vascular diseases. The early prognosis of cardiovascular diseases can aid in making decisions on lifestyle changes in high risk patients and in turn reduce the complications. This research intends to pinpoint the most relevant/risk factors of heart disease as well as predict the overall risk using logistic regression.

** # Supress Warnings**

In [25]:


import warnings
warnings.filterwarnings('ignore')

**import libraries**

In [26]:

import pandas as pd
import numpy as np
import statsmodels.api as sm
import scipy.stats as st
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import matplotlib.mlab as mlab

#Importing the dataset and dropping the unwanted columns 
heart_df=pd.read_csv("../input/framingham.csv")
heart_df.drop(['education'],axis=1,inplace=True)
heart_df.head()

   male  age  currentSmoker     ...      heartRate  glucose  TenYearCHD
0     1   39              0     ...           80.0     77.0           0
1     0   46              0     ...           95.0     76.0           0
2     1   48              1     ...           75.0     70.0           0
3     0   61              1     ...           65.0    103.0           1
4     0   46              1     ...           85.0     85.0           0

[5 rows x 15 columns]

Data Preparation
Source:
The dataset is publically available on the Kaggle website, and it is from an ongoing ongoing cardiovascular study on residents of the town of Framingham, Massachusetts. The classification goal is to predict whether the patient has 10-year risk of future coronary heart disease (CHD).The dataset provides the patients’ information. It includes over 4,000 records and 15 attributes

In [27]:
#Renaming the column name
heart_df.rename(columns={'male':'Sex_male'},inplace=True)

heart_df.head()

   Sex_male  age  currentSmoker     ...      heartRate  glucose  TenYearCHD
0         1   39              0     ...           80.0     77.0           0
1         0   46              0     ...           95.0     76.0           0
2         1   48              1     ...           75.0     70.0           0
3         0   61              1     ...           65.0    103.0           1
4         0   46              1     ...           85.0     85.0           0

[5 rows x 15 columns]

Missing values

In [28]:
# Checking the missing values 
heart_df.isnull().sum()

Sex_male             0
age                  0
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

Exploratory Analysis

In [29]:
#Counting the missing values and dropping them
count=0
for i in heart_df.isnull().sum(axis=1):
    if i>0:
        count=count+1
print('Total number of rows with missing values is ', count)
print('since it is only',round((count/len(heart_df.index))*100), 'percent of the entire dataset the rows with missing values are excluded.')

heart_df.dropna(axis=0,inplace=True)

heart_df.describe()

Total number of rows with missing values is  489
since it is only 12 percent of the entire dataset the rows with missing values are excluded.

          Sex_male          age     ...           glucose   TenYearCHD
count  3749.000000  3749.000000     ...       3749.000000  3749.000000
mean      0.445185    49.578821     ...         81.883169     0.152574
std       0.497053     8.569322     ...         23.888039     0.359624
min       0.000000    32.000000     ...         40.000000     0.000000
25%       0.000000    42.000000     ...         71.000000     0.000000
50%       0.000000    49.000000     ...         78.000000     0.000000
75%       1.000000    56.000000     ...         87.000000     0.000000
max       1.000000    70.000000     ...        394.000000     1.000000

[8 rows x 15 columns]

**again checking null values**

In [30]:
heart_df.isnull().sum()

Sex_male           0
age                0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [32]:
#Adding a constant
from statsmodels.tools import add_constant as add_constant
heart_df_constant = add_constant(heart_df)
heart_df_constant.head()

   const  Sex_male  age     ...      heartRate  glucose  TenYearCHD
0    1.0         1   39     ...           80.0     77.0           0
1    1.0         0   46     ...           95.0     76.0           0
2    1.0         1   48     ...           75.0     70.0           0
3    1.0         0   61     ...           65.0    103.0           1
4    1.0         0   46     ...           85.0     85.0           0

[5 rows x 16 columns]

**Logistic Regression**

Logistic regression is a type of regression analysis in statistics used for prediction of outcome of a categorical dependent variable from a set of predictor or independent variables. In logistic regression the dependent variable is always binary. Logistic regression is mainly used to for prediction and also calculating the probability of success.

**Chi-square Test**

● A Chi-square Test (also written 𝜒2) is used to determine the probability of an observed frequency of events given an expected frequency

**Chi-square Test**

● The chi-square formula considers the sum of square distances between observed values O and expected values E, divided by each expected value:
𝜒2 = ((𝑂 − 𝐸)e2)/E

In [7]:


st.chisqprob = lambda chisq, df: st.chi2.sf(chisq, df)
cols=heart_df_constant.columns[:-1]
model=sm.Logit(heart_df.TenYearCHD,heart_df_constant[cols])
result=model.fit()
result.summary()

Optimization terminated successfully.
         Current function value: 0.377199
         Iterations 7

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:             TenYearCHD   No. Observations:                 3749
Model:                          Logit   Df Residuals:                     3734
Method:                           MLE   Df Model:                           14
Date:                Fri, 07 Jun 2019   Pseudo R-squ.:                  0.1169
Time:                        06:21:21   Log-Likelihood:                -1414.1
converged:                       True   LL-Null:                       -1601.4
                                        LLR p-value:                 2.922e-71
===================================================================================
                      coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              -8.6463      0.687    -12.577      0.000      -9.994      -7.299
Sex_male            0.5740      0.107      5.343      0.000       0.363       0.785
age                 0.0640      0.007      9.787      0.000       0.051       0.077
currentSmoker       0.0732      0.155      0.473      0.636      -0.230       0.376
cigsPerDay          0.0184      0.006      3.003      0.003       0.006       0.030
BPMeds              0.1446      0.232      0.622      0.534      -0.311       0.600
prevalentStroke     0.7191      0.489      1.471      0.141      -0.239       1.677
prevalentHyp        0.2146      0.136      1.574      0.116      -0.053       0.482
diabetes            0.0025      0.312      0.008      0.994      -0.609       0.614
totChol             0.0022      0.001      2.074      0.038       0.000       0.004
sysBP               0.0153      0.004      4.080      0.000       0.008       0.023
diaBP              -0.0039      0.006     -0.619      0.536      -0.016       0.009
BMI                 0.0103      0.013      0.820      0.412      -0.014       0.035
heartRate          -0.0023      0.004     -0.550      0.583      -0.010       0.006
glucose             0.0076      0.002      3.408      0.001       0.003       0.012
===================================================================================
"""

**#Feature Selection: Backward elemination (P-value approach)
#Takes in the dataframe, the dependent variable and a list of column names, 
#runs the regression repeatedly eleminating feature with the highest
#P-value above alpha one at a time and returns the regression summary 
#with all p-values below alpha
**

In [8]:

def back_feature_elem (data_frame,dep_var,col_list):
    while len(col_list)>0 :
        model=sm.Logit(dep_var,data_frame[col_list])
        result=model.fit(disp=0)
        largest_pvalue=round(result.pvalues,3).nlargest(1)
        if largest_pvalue[0]<(0.05):
            return result
            break
        else:
            col_list=col_list.drop(largest_pvalue.index)

result=back_feature_elem(heart_df_constant,heart_df.TenYearCHD,cols)

Logistic regression equation
P=e(β0+β1X1/1+eβ0+β1X1)
 
When all features plugged in:

logit(p)=log(p/(1−p))=β0+β1∗Sexmale+β2∗age+β3∗cigsPerDay+β4∗totChol+β5∗sysBP+β6∗glucose

In [33]:
#Interpreting the results: Odds Ratio, Confidence Intervals and Pvalues

params = np.exp(result.params)
conf = np.exp(result.conf_int())
conf['OR'] = params
pvalue=round(result.pvalues,3)
conf['pvalue']=pvalue
conf.columns = ['CI 95%(2.5%)', 'CI 95%(97.5%)', 'Odds Ratio','pvalue']
print ((conf))

            CI 95%(2.5%)  CI 95%(97.5%)  Odds Ratio  pvalue
const           0.000044       0.000274    0.000109   0.000
Sex_male        1.454877       2.198166    1.788313   0.000
age             1.054409       1.080897    1.067571   0.000
cigsPerDay      1.011730       1.028128    1.019896   0.000
totChol         1.000150       1.004386    1.002266   0.036
sysBP           1.013299       1.021791    1.017536   0.000
glucose         1.004343       1.010895    1.007614   0.000

**#Splitting data to train and test split**

In [35]:

import sklearn
new_features=heart_df[['age','Sex_male','cigsPerDay','totChol','sysBP','glucose','TenYearCHD']]
x=new_features.iloc[:,:-1]
y=new_features.iloc[:,-1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=5)

from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logreg.fit(x_train,y_train)
y_pred=logreg.predict(x_test)

**#Confusion matrix**

In [36]:

from sklearn import metrics
confusion_matrix = metrics.confusion_matrix(y_test,y_pred)
print(confusion_matrix)

[[646   1]
 [ 99   4]]

**#Model accuracy**

In [37]:

sklearn.metrics.accuracy_score(y_test,y_pred)

0.8666666666666667