# Sales Data analysis

## Introduction 
<p> This notebook is for Sales Simulation training where we ganna do some sustomer analytics.
 Originally the Data used in this notebook was Written by María Carina Roldán, Pentaho Community Member, BI consultant (Assert Solutions), Argentina.
 This Data is licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License. <p>

## Data Preparation
so the first we do is loading the data to our notebook and then we start pocessing , filtering and sorting it.

In [ ]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print("libraries installed succeffuly")

In [ ]:
#loding the dataset 
sales_data = pd.read_csv("../input/sample-sales-data/sales_data_sample.csv")
sales_data.head() # printing the head of the data

In [ ]:
sales_data.shape # getting the shape of the data 
sales_data.info() # data info
sales_data.describe() #numeric column statistic

In [ ]:
sales_data.duplicated( keep='first').sum() #checking if there are dublicates 
sales_data.isna().sum() #finding missing values

we have four columns with missing values we can replace,remove them or we can just ignore them since the four columns are not ( yet crucial to our analysis )

In [ ]:
#checking how many unique value we have in each columns 
for col in sales_data.columns:
    print(f'Number of {col} unique values: {sales_data[col].nunique()}')

In [ ]:
sales_data['ORDERDATE'] = pd.to_datetime(sales_data['ORDERDATE']) #ORDERDATE to pandas datetime format
# let's sort the data by order data
sales_data.sort_values(by = ['ORDERDATE'], inplace = True) 
sales_data.set_index('ORDERDATE', inplace = True) #Indexing by the ORDERDATE

In [ ]:
sales_data.head()

### Data Analysis

Now we can start our analysis to get some insghitsfrom the dataset.

In [ ]:
top_country = sales_data.groupby(['COUNTRY']).sum().sort_values('SALES', ascending = False).head(10) 
top_country = top_country[['SALES']].round(3) 
top_country.reset_index(inplace = True) 
top_country.head()

In [ ]:
ax = top_country.plot.barh(x='COUNTRY', y='SALES',figsize=(8,6), color= "darkblue",rot=0)

the 3 top sales come from USA , Spain and france
<p> now we want to look at the top cities by sales

In [ ]:
top_city_sales = sales_data.groupby(['CITY']).sum().sort_values('SALES', ascending = False).head(10)
top_city_sales = top_city_sales[['SALES']].round(3) 
top_city_sales.reset_index(inplace = True) 
ax = top_city_sales.plot.barh(x='CITY', y='SALES',figsize=(8,6), color= "darkblue",rot=0)

looks like Madrid , San Rafael , NYC are the top 3 cities by sales

In [ ]:
top_customer = sales_data.groupby(['CUSTOMERNAME']).sum().sort_values('SALES', ascending = False).head(10) 
top_customer = top_customer[['SALES']].round(3) 
top_customer.reset_index(inplace = True) 
top_customer.head()

In [ ]:

ax = top_customer.plot.barh(x='CUSTOMERNAME', y='SALES',figsize=(8,6),color= "darkblue",rot=0)

The three top customers are Euro shopping Channel , mini Gifts Distributors ltd and australian collectors,co.
<p> now we want to know what are the top PRODUCT by revenue

In [ ]:
top_product_revenues = sales_data.groupby(['PRODUCTLINE']).sum().sort_values('SALES', ascending = False)
top_product_revenues = top_product_revenues[['SALES']] 
top_product_revenues.head()

In [ ]:
ax = top_product_revenues.plot.bar(figsize=(10,5),color= "blue",rot=0)

As we can see the top product revenues are Classic cars , Vintage Cars , Motorcycles and Trucks 
<p> let's review now the sales over the three years

In [ ]:
year_sales = sales_data.groupby(['YEAR_ID']).sum().sort_values('SALES', ascending = False)
top_year_sales = year_sales[['SALES']] 
top_year_sales.plot.bar()

2005 has the most sales in the data set 2003 second and 2005 is third
<p> let's now check the top monthes with sales

In [ ]:
month_sales = sales_data.groupby(['MONTH_ID']).sum().sort_values('SALES', ascending = False)
month_sales = month_sales[['SALES']] 
month_sales.plot.bar()

October , november and may has the most revenues from sales

## Summary

the dataset is a collection of observations from 2005 with 2003 and 2004 includded.
    
* we found that USA , Spain and France are the top contries ordred by sum of sales
* madrid , San rafael and NYC are the top three cities ordred by sum of sales 
* the three most productline are Classic cars , Vintage cars and Motorcycles.
* year 2004 has the most revenues compared to the two other  years where November and October has the highest sum of sales

**IF YOU FIND THIS USEFUL PLEASE UPVOTE**