This article will cover all the essential that a programmer, data scientist, or machine learning engineer should know about Pandas library, it is like briefly described cheat sheet. Some people may ask why from A to Y, not from A to Z, simply because no one could be aware of everything in the world, so I am just putting my experience with Pandas here in that article.

During this article I am gonna use "New York City Current Job Postings" dataset from Kaggle. So, let's startâ€¦.
but first we need to import the library:

In [ ]:
import pandas as pd

Reading datasets can be done by:

In [ ]:
loc = "../input/nyc-jobs.csv"
df = pd.read_csv(loc)
#df = pd.read_excel(loc)     # if the dataset is excel

Have a look on the data, check the head (first n rows of the data -default first 5 rows-) and the tail of it (last n rows of the data-default last 5 rows-), additionaly let's have a summary about the types of headers (columns).

In [ ]:
df.head()    # Get the first 5 rows

In [ ]:
df.tail(5)

In [ ]:
df.info()    # Get a summary of the attributes (Columns) data types and the number of non-null values for each column

In [ ]:
df.describe()      # Get a numerical summary for the whole dataset

Get some information about the rows and columns. For example, rows number, columns number and columns names

In [ ]:
print(df.shape)  # print both rows number and column number
print(df.shape[0])  # row number
print(df.shape[1])  # col number
print(df.columns)   # Columns names

# you can put columns names into a list by following: 

Col_List = df.columns.tolist()
print(Col_List)

If you don't like the column name and you want to rename it:

In [ ]:
df.rename(columns = {'Job ID':'JobID'})

Getting unique values in a certain column and put them into a list

In [ ]:
df['Posting Type'].unique().tolist()

Now, if you want to check how many times each value within this column was repeated (number of counts)

In [ ]:
import collections
CounterDic = collections.Counter(list(df['Posting Type']))
print(CounterDic)

Or you can do it like that as well:

In [ ]:
df.Agency.value_counts()

If you wanna split them into names and number of unique values

In [ ]:
X = list(CounterDic.keys())        # or you can write it like that also: df.Agency.value_counts()    # .keys().tolist()
Y = list(CounterDic.values())
print(X)
print(Y)

To plot number of counts for the unique values in a certain column into a graph:

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
chart = sns.countplot(df['Posting Type'],label="Counts")  # plot the number of repetition for each data within this header/Col.
chart.set_xticklabels(chart.get_xticklabels(), rotation=45)    # to write the x label 
plt.ylabel('Number of counts')

Accessing a certain data locations:

In [ ]:
df.iloc[:,0]   # first col
df.iloc[1,0]   # accessing a certain cell

Dropping data, there are different cases that you will need to drop a data:
1. drop a whole column
2. Drop a whole row
3. Drop a certain row that contain a certain data.
4. Drop the NaN values

In [ ]:
df = df.drop(['Recruitment Contact'],axis=1)   # Dropping column, should write axis=1 as it indicates to dropping column.

In [ ]:
# df = df.drop[1]   # dropping row with index 1

In [ ]:
df = df[df.Level != 'M3']    # if the column contain a data cell named .... drop that row from the dataset
# instead of M3 it could be anyting, like NaN also

Replace values by another, for example if you have "NaN" and you wanna replace it by 0 or 'None'

In [ ]:
import numpy as np
df['Hours'] = df['Hours/Shift']
df['Hours/Shift'].drop
df.Hours = df.Hours.replace(np.nan,0)
print(df.head())

Replace a value by 1 and the cell that has no value by 0 and put them into a new column called ""

In [ ]:
df['WorkLocation'] = df['Work Location 1']
df['Work Location 1'].drop

This part if you want to repace empty cells (NULL values) by a certain value and the non-empty values by another value. What we do here, is that we check the values in "WorkLocation", the NOT NULL values are replaced by '1' and the NULL values are replaced by '0' and we save these new form of the column in a new column named as 'NewWorkLocation'

In [ ]:
df.loc[(df.WorkLocation.notnull()),'NewWorkLocation']=1 
df.loc[(df.WorkLocation.isnull()),'NewWorkLocation']=0
print(df.WorkLocation)
print(df.NewWorkLocation)

If you have a list and wanna convert it to dataframe and save it as csv

In [ ]:
Xdf = pd.DataFrame(X)     # Remember that X is a list that contain the keys of 'Agency' column
print(Xdf)
df.head(10).to_csv('X head.csv') # here you write the directory

***** Numerical Analysis ***** 

In this part we will do some numerical annalysis on the dataset. For example, get the mean value for a certain column....

In [ ]:
df['Salary Range From'].mean()